// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mini_app.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptTelegramPolicies = `-- name: AcceptTelegramPolicies :exec
UPDATE accounts SET terms_version=$2,privacy_version=$3,policy_accepted_at=$4 WHERE id=$1
`

type AcceptTelegramPoliciesParams struct {
	ID               uuid.UUID
	TermsVersion     pgtype.Text
	PrivacyVersion   pgtype.Text
	PolicyAcceptedAt pgtype.Timestamptz
}

func (q *Queries) AcceptTelegramPolicies(ctx context.Context, arg AcceptTelegramPoliciesParams) error {
	_, err := q.db.Exec(ctx, acceptTelegramPolicies,
		arg.ID,
		arg.TermsVersion,
		arg.PrivacyVersion,
		arg.PolicyAcceptedAt,
	)
	return err
}

const addTelegramSession = `-- name: AddTelegramSession :exec
INSERT INTO sessions(id_hash,account_id,csrf_token,created_at,last_seen,absolute_expires_at,auth_source,telegram_id)
VALUES($1,$2,$3,$4,$5,$6,'telegram',$7)
`

type AddTelegramSessionParams struct {
	IDHash            []byte
	AccountID         uuid.UUID
	CsrfToken         string
	CreatedAt         pgtype.Timestamptz
	LastSeen          pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	TelegramID        pgtype.Int8
}

func (q *Queries) AddTelegramSession(ctx context.Context, arg AddTelegramSessionParams) error {
	_, err := q.db.Exec(ctx, addTelegramSession,
		arg.IDHash,
		arg.AccountID,
		arg.CsrfToken,
		arg.CreatedAt,
		arg.LastSeen,
		arg.AbsoluteExpiresAt,
		arg.TelegramID,
	)
	return err
}

const deleteTelegramSession = `-- name: DeleteTelegramSession :execrows
DELETE FROM sessions WHERE id_hash=$1 AND auth_source='telegram'
`

func (q *Queries) DeleteTelegramSession(ctx context.Context, idHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTelegramSession, idHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const preserveTelegramStartParam = `-- name: PreserveTelegramStartParam :exec
UPDATE accounts SET telegram_start_param=$2 WHERE id=$1 AND telegram_start_param IS NULL
`

type PreserveTelegramStartParamParams struct {
	ID                 uuid.UUID
	TelegramStartParam pgtype.Text
}

func (q *Queries) PreserveTelegramStartParam(ctx context.Context, arg PreserveTelegramStartParamParams) error {
	_, err := q.db.Exec(ctx, preserveTelegramStartParam, arg.ID, arg.TelegramStartParam)
	return err
}
