// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                           uuid.UUID
	EmailKey                     pgtype.Text
	Locale                       string
	PasswordHash                 pgtype.Text
	VerifiedAt                   pgtype.Timestamptz
	Restricted                   bool
	VpnID                        uuid.UUID
	SubID                        string
	PanelKey                     string
	TermsVersion                 pgtype.Text
	PrivacyVersion               pgtype.Text
	TelegramID                   pgtype.Int8
	LegacyUserID                 pgtype.Int8
	AssignedPanelID              pgtype.Text
	HadSubscription              bool
	CredentialVersion            int64
	VpnBanned                    bool
	Kind                         string
	DisplayName                  pgtype.Text
	CreatedAt                    pgtype.Timestamptz
	RestrictionChangedAt         pgtype.Timestamptz
	RestrictionOperatorAccountID *uuid.UUID
	AccessProfile                pgtype.Text
	PolicyAcceptedAt             pgtype.Timestamptz
	TelegramStartParam           pgtype.Text
}

type CredentialChallenge struct {
	ID                uuid.UUID
	Purpose           string
	AccountID         *uuid.UUID
	ChangeID          *uuid.UUID
	OriginalEmail     string
	TargetEmail       string
	CredentialVersion int64
	TokenHash         []byte
	CodeHash          []byte
	CreatedAt         pgtype.Timestamptz
	TokenExpiresAt    pgtype.Timestamptz
	CodeExpiresAt     pgtype.Timestamptz
	FailedGuesses     int32
	ConfirmedAt       pgtype.Timestamptz
	UsedAt            pgtype.Timestamptz
	Revoked           bool
}

type IdempotencyRecord struct {
	Principal string
	Operation string
	Key       uuid.UUID
	BodyHash  []byte
	Result    []byte
	CreatedAt pgtype.Timestamptz
}

type LegacyApprovalEvent struct {
	SourceID   int64
	AccountID  uuid.UUID
	TargetTgID int64
	CreatedAt  pgtype.Timestamptz
	Action     string
	ActorType  pgtype.Text
	ActorID    pgtype.Int8
	ActorName  pgtype.Text
	Source     pgtype.Text
}

type LegacyApprovalSnapshot struct {
	AccountID          uuid.UUID
	SourceLegacyUserID int64
	SourceTgID         int64
	Status             string
	RequestedAt        pgtype.Timestamptz
	DecidedAt          pgtype.Timestamptz
	DecidedBy          pgtype.Int8
}

type RegistrationChallenge struct {
	ID             uuid.UUID
	EmailKey       string
	Locale         string
	TermsVersion   string
	PrivacyVersion string
	TokenHash      []byte
	CodeHash       []byte
	CreatedAt      pgtype.Timestamptz
	TokenExpiresAt pgtype.Timestamptz
	CodeExpiresAt  pgtype.Timestamptz
	FailedGuesses  int32
	Revoked        bool
}

type Session struct {
	IDHash            []byte
	AccountID         uuid.UUID
	CsrfToken         string
	CreatedAt         pgtype.Timestamptz
	LastSeen          pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	AuthSource        string
	TelegramID        pgtype.Int8
}
