// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: referrals.sql

package store

import (
	"context"
)

const referralInviter = `-- name: ReferralInviter :one
SELECT id, email_key, locale, password_hash, verified_at, restricted, vpn_id, sub_id, panel_key, terms_version, privacy_version, telegram_id, legacy_user_id, assigned_panel_id, had_subscription, credential_version, vpn_banned, kind, display_name, created_at, restriction_changed_at, restriction_operator_account_id, access_profile, policy_accepted_at, telegram_start_param, original_kind, telegram_login_disabled, registration_source_code FROM accounts WHERE id=COALESCE(
 (SELECT id FROM accounts WHERE telegram_id=$1::bigint),
 (SELECT account_id FROM telegram_identity_reservations WHERE telegram_id=$1::bigint)
)
`

// One snapshot keeps the owner visible while a retired identity is re-linked.
func (q *Queries) ReferralInviter(ctx context.Context, telegramID int64) (Account, error) {
	row := q.db.QueryRow(ctx, referralInviter, telegramID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.EmailKey,
		&i.Locale,
		&i.PasswordHash,
		&i.VerifiedAt,
		&i.Restricted,
		&i.VpnID,
		&i.SubID,
		&i.PanelKey,
		&i.TermsVersion,
		&i.PrivacyVersion,
		&i.TelegramID,
		&i.LegacyUserID,
		&i.AssignedPanelID,
		&i.HadSubscription,
		&i.CredentialVersion,
		&i.VpnBanned,
		&i.Kind,
		&i.DisplayName,
		&i.CreatedAt,
		&i.RestrictionChangedAt,
		&i.RestrictionOperatorAccountID,
		&i.AccessProfile,
		&i.PolicyAcceptedAt,
		&i.TelegramStartParam,
		&i.OriginalKind,
		&i.TelegramLoginDisabled,
		&i.RegistrationSourceCode,
	)
	return i, err
}
