// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const accountByEmail = `-- name: AccountByEmail :one
SELECT id, email_key, locale, password_hash, verified_at, restricted, vpn_id, sub_id, panel_key, terms_version, privacy_version, telegram_id, legacy_user_id, assigned_panel_id, had_subscription, credential_version, vpn_banned, kind, display_name, created_at, restriction_changed_at, restriction_operator_account_id, access_profile, policy_accepted_at, telegram_start_param FROM accounts WHERE email_key = $1::text
`

func (q *Queries) AccountByEmail(ctx context.Context, emailKey string) (Account, error) {
	row := q.db.QueryRow(ctx, accountByEmail, emailKey)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.EmailKey,
		&i.Locale,
		&i.PasswordHash,
		&i.VerifiedAt,
		&i.Restricted,
		&i.VpnID,
		&i.SubID,
		&i.PanelKey,
		&i.TermsVersion,
		&i.PrivacyVersion,
		&i.TelegramID,
		&i.LegacyUserID,
		&i.AssignedPanelID,
		&i.HadSubscription,
		&i.CredentialVersion,
		&i.VpnBanned,
		&i.Kind,
		&i.DisplayName,
		&i.CreatedAt,
		&i.RestrictionChangedAt,
		&i.RestrictionOperatorAccountID,
		&i.AccessProfile,
		&i.PolicyAcceptedAt,
		&i.TelegramStartParam,
	)
	return i, err
}

const accountByID = `-- name: AccountByID :one
SELECT id, email_key, locale, password_hash, verified_at, restricted, vpn_id, sub_id, panel_key, terms_version, privacy_version, telegram_id, legacy_user_id, assigned_panel_id, had_subscription, credential_version, vpn_banned, kind, display_name, created_at, restriction_changed_at, restriction_operator_account_id, access_profile, policy_accepted_at, telegram_start_param FROM accounts WHERE id = $1
`

func (q *Queries) AccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, accountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.EmailKey,
		&i.Locale,
		&i.PasswordHash,
		&i.VerifiedAt,
		&i.Restricted,
		&i.VpnID,
		&i.SubID,
		&i.PanelKey,
		&i.TermsVersion,
		&i.PrivacyVersion,
		&i.TelegramID,
		&i.LegacyUserID,
		&i.AssignedPanelID,
		&i.HadSubscription,
		&i.CredentialVersion,
		&i.VpnBanned,
		&i.Kind,
		&i.DisplayName,
		&i.CreatedAt,
		&i.RestrictionChangedAt,
		&i.RestrictionOperatorAccountID,
		&i.AccessProfile,
		&i.PolicyAcceptedAt,
		&i.TelegramStartParam,
	)
	return i, err
}

const addAccount = `-- name: AddAccount :exec
INSERT INTO accounts(id,email_key,locale,password_hash,verified_at,vpn_id,sub_id,panel_key,terms_version,privacy_version,access_profile)
VALUES($1::uuid,$2::text,$3::text,
 $4::text,$5::timestamptz,
 $6::uuid,$7::text,$8::text,
 $9::text,$10::text,'regular')
`

type AddAccountParams struct {
	ID             uuid.UUID
	EmailKey       string
	Locale         string
	PasswordHash   string
	VerifiedAt     pgtype.Timestamptz
	VpnID          uuid.UUID
	SubID          string
	PanelKey       string
	TermsVersion   string
	PrivacyVersion string
}

func (q *Queries) AddAccount(ctx context.Context, arg AddAccountParams) error {
	_, err := q.db.Exec(ctx, addAccount,
		arg.ID,
		arg.EmailKey,
		arg.Locale,
		arg.PasswordHash,
		arg.VerifiedAt,
		arg.VpnID,
		arg.SubID,
		arg.PanelKey,
		arg.TermsVersion,
		arg.PrivacyVersion,
	)
	return err
}

const addChallenge = `-- name: AddChallenge :exec
INSERT INTO registration_challenges(id,email_key,locale,terms_version,privacy_version,token_hash,code_hash,created_at,token_expires_at,code_expires_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
`

type AddChallengeParams struct {
	ID             uuid.UUID
	EmailKey       string
	Locale         string
	TermsVersion   string
	PrivacyVersion string
	TokenHash      []byte
	CodeHash       []byte
	CreatedAt      pgtype.Timestamptz
	TokenExpiresAt pgtype.Timestamptz
	CodeExpiresAt  pgtype.Timestamptz
}

func (q *Queries) AddChallenge(ctx context.Context, arg AddChallengeParams) error {
	_, err := q.db.Exec(ctx, addChallenge,
		arg.ID,
		arg.EmailKey,
		arg.Locale,
		arg.TermsVersion,
		arg.PrivacyVersion,
		arg.TokenHash,
		arg.CodeHash,
		arg.CreatedAt,
		arg.TokenExpiresAt,
		arg.CodeExpiresAt,
	)
	return err
}

const challengeByID = `-- name: ChallengeByID :one
SELECT id, email_key, locale, terms_version, privacy_version, token_hash, code_hash, created_at, token_expires_at, code_expires_at, failed_guesses, revoked FROM registration_challenges WHERE id = $1 FOR UPDATE
`

func (q *Queries) ChallengeByID(ctx context.Context, id uuid.UUID) (RegistrationChallenge, error) {
	row := q.db.QueryRow(ctx, challengeByID, id)
	var i RegistrationChallenge
	err := row.Scan(
		&i.ID,
		&i.EmailKey,
		&i.Locale,
		&i.TermsVersion,
		&i.PrivacyVersion,
		&i.TokenHash,
		&i.CodeHash,
		&i.CreatedAt,
		&i.TokenExpiresAt,
		&i.CodeExpiresAt,
		&i.FailedGuesses,
		&i.Revoked,
	)
	return i, err
}

const challengeByToken = `-- name: ChallengeByToken :one
SELECT id, email_key, locale, terms_version, privacy_version, token_hash, code_hash, created_at, token_expires_at, code_expires_at, failed_guesses, revoked FROM registration_challenges WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) ChallengeByToken(ctx context.Context, tokenHash []byte) (RegistrationChallenge, error) {
	row := q.db.QueryRow(ctx, challengeByToken, tokenHash)
	var i RegistrationChallenge
	err := row.Scan(
		&i.ID,
		&i.EmailKey,
		&i.Locale,
		&i.TermsVersion,
		&i.PrivacyVersion,
		&i.TokenHash,
		&i.CodeHash,
		&i.CreatedAt,
		&i.TokenExpiresAt,
		&i.CodeExpiresAt,
		&i.FailedGuesses,
		&i.Revoked,
	)
	return i, err
}

const challengeEmailByID = `-- name: ChallengeEmailByID :one
SELECT email_key FROM registration_challenges WHERE id=$1
`

func (q *Queries) ChallengeEmailByID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, challengeEmailByID, id)
	var email_key string
	err := row.Scan(&email_key)
	return email_key, err
}

const challengeEmailByToken = `-- name: ChallengeEmailByToken :one
SELECT email_key FROM registration_challenges WHERE token_hash=$1
`

func (q *Queries) ChallengeEmailByToken(ctx context.Context, tokenHash []byte) (string, error) {
	row := q.db.QueryRow(ctx, challengeEmailByToken, tokenHash)
	var email_key string
	err := row.Scan(&email_key)
	return email_key, err
}

const consumeChallenge = `-- name: ConsumeChallenge :exec
UPDATE registration_challenges SET revoked=true WHERE id=$1
`

func (q *Queries) ConsumeChallenge(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeChallenge, id)
	return err
}

const failChallenge = `-- name: FailChallenge :exec
UPDATE registration_challenges SET failed_guesses = LEAST(failed_guesses+1,5) WHERE id=$1
`

func (q *Queries) FailChallenge(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, failChallenge, id)
	return err
}

const lockRegistrationEmail = `-- name: LockRegistrationEmail :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) LockRegistrationEmail(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, lockRegistrationEmail, dollar_1)
	return err
}

const revokeChallenges = `-- name: RevokeChallenges :exec
UPDATE registration_challenges SET revoked = true WHERE email_key = $1 AND NOT revoked
`

func (q *Queries) RevokeChallenges(ctx context.Context, emailKey string) error {
	_, err := q.db.Exec(ctx, revokeChallenges, emailKey)
	return err
}
