// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addSession = `-- name: AddSession :exec
INSERT INTO sessions(id_hash,account_id,csrf_token,created_at,last_seen,absolute_expires_at) VALUES($1,$2,$3,$4,$5,$6)
`

type AddSessionParams struct {
	IDHash            []byte
	AccountID         uuid.UUID
	CsrfToken         string
	CreatedAt         pgtype.Timestamptz
	LastSeen          pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
}

func (q *Queries) AddSession(ctx context.Context, arg AddSessionParams) error {
	_, err := q.db.Exec(ctx, addSession,
		arg.IDHash,
		arg.AccountID,
		arg.CsrfToken,
		arg.CreatedAt,
		arg.LastSeen,
		arg.AbsoluteExpiresAt,
	)
	return err
}

const authenticateSession = `-- name: AuthenticateSession :one
UPDATE sessions SET last_seen=GREATEST(last_seen,$1::timestamptz)
WHERE id_hash=$2 AND absolute_expires_at>$1::timestamptz AND last_seen>$1::timestamptz-INTERVAL '7 days'
RETURNING id_hash, account_id, csrf_token, created_at, last_seen, absolute_expires_at, auth_source, telegram_id
`

type AuthenticateSessionParams struct {
	Now    pgtype.Timestamptz
	IDHash []byte
}

func (q *Queries) AuthenticateSession(ctx context.Context, arg AuthenticateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, authenticateSession, arg.Now, arg.IDHash)
	var i Session
	err := row.Scan(
		&i.IDHash,
		&i.AccountID,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.LastSeen,
		&i.AbsoluteExpiresAt,
		&i.AuthSource,
		&i.TelegramID,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id_hash=$1
`

func (q *Queries) DeleteSession(ctx context.Context, idHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, idHash)
	return err
}

const hasOtherSessions = `-- name: HasOtherSessions :one
SELECT EXISTS(SELECT 1 FROM sessions WHERE account_id=$1 AND id_hash<>$2 AND absolute_expires_at>$3::timestamptz AND last_seen>$3::timestamptz-INTERVAL '7 days')
`

type HasOtherSessionsParams struct {
	AccountID uuid.UUID
	IDHash    []byte
	Now       pgtype.Timestamptz
}

func (q *Queries) HasOtherSessions(ctx context.Context, arg HasOtherSessionsParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasOtherSessions, arg.AccountID, arg.IDHash, arg.Now)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lookupLiveSession = `-- name: LookupLiveSession :one
SELECT id_hash, account_id, csrf_token, created_at, last_seen, absolute_expires_at, auth_source, telegram_id FROM sessions WHERE id_hash=$1 AND absolute_expires_at>$2::timestamptz AND last_seen>$2::timestamptz-INTERVAL '7 days'
`

type LookupLiveSessionParams struct {
	IDHash []byte
	Now    pgtype.Timestamptz
}

func (q *Queries) LookupLiveSession(ctx context.Context, arg LookupLiveSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, lookupLiveSession, arg.IDHash, arg.Now)
	var i Session
	err := row.Scan(
		&i.IDHash,
		&i.AccountID,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.LastSeen,
		&i.AbsoluteExpiresAt,
		&i.AuthSource,
		&i.TelegramID,
	)
	return i, err
}
