// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shared.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addAudit = `-- name: AddAudit :exec
INSERT INTO audit_events(id,created_at,action,account_id,request_id,operation_id,operator_tg_id,reason) VALUES($1,$2,$3,$4,$5,$6,$7,$8)
`

type AddAuditParams struct {
	ID           uuid.UUID
	CreatedAt    pgtype.Timestamptz
	Action       string
	AccountID    uuid.UUID
	RequestID    *uuid.UUID
	OperationID  *uuid.UUID
	OperatorTgID pgtype.Int8
	Reason       pgtype.Text
}

func (q *Queries) AddAudit(ctx context.Context, arg AddAuditParams) error {
	_, err := q.db.Exec(ctx, addAudit,
		arg.ID,
		arg.CreatedAt,
		arg.Action,
		arg.AccountID,
		arg.RequestID,
		arg.OperationID,
		arg.OperatorTgID,
		arg.Reason,
	)
	return err
}

const lockAccount = `-- name: LockAccount :one
SELECT id, email_key, locale, password_hash, verified_at, restricted, vpn_id, sub_id, panel_key, terms_version, privacy_version, telegram_id, legacy_user_id, assigned_panel_id, had_subscription, credential_version, vpn_banned, kind, display_name, created_at, restriction_changed_at, restriction_operator_account_id, access_profile FROM accounts WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, lockAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.EmailKey,
		&i.Locale,
		&i.PasswordHash,
		&i.VerifiedAt,
		&i.Restricted,
		&i.VpnID,
		&i.SubID,
		&i.PanelKey,
		&i.TermsVersion,
		&i.PrivacyVersion,
		&i.TelegramID,
		&i.LegacyUserID,
		&i.AssignedPanelID,
		&i.HadSubscription,
		&i.CredentialVersion,
		&i.VpnBanned,
		&i.Kind,
		&i.DisplayName,
		&i.CreatedAt,
		&i.RestrictionChangedAt,
		&i.RestrictionOperatorAccountID,
		&i.AccessProfile,
	)
	return i, err
}
