// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access_operations.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const accessApplied = `-- name: AccessApplied :execrows
UPDATE access_operations SET status='applied',lease_hash=NULL,lease_expires_at=NULL,review_reason=NULL,completed_steps=completed_steps||'["readback_confirmed"]'::jsonb,updated_at=$3
WHERE id=$1 AND lease_hash=$2 AND status='provisioning' AND lease_expires_at>clock_timestamp()
`

type AccessAppliedParams struct {
	ID        uuid.UUID
	LeaseHash []byte
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) AccessApplied(ctx context.Context, arg AccessAppliedParams) (int64, error) {
	result, err := q.db.Exec(ctx, accessApplied, arg.ID, arg.LeaseHash, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const accessNeedsReview = `-- name: AccessNeedsReview :execrows
UPDATE access_operations SET status='needs_review',lease_hash=NULL,lease_expires_at=NULL,review_reason=$3,updated_at=$4
WHERE id=$1 AND lease_hash=$2 AND status='provisioning'
`

type AccessNeedsReviewParams struct {
	ID           uuid.UUID
	LeaseHash    []byte
	ReviewReason pgtype.Text
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) AccessNeedsReview(ctx context.Context, arg AccessNeedsReviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, accessNeedsReview,
		arg.ID,
		arg.LeaseHash,
		arg.ReviewReason,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const accessOperationByID = `-- name: AccessOperationByID :one
SELECT id, account_id, operator_account_id, kind, status, reason, plan_id, plan_revision, period_days, desired, target, completed_steps, review_reason, write_started, reset_started, reset_acknowledged, attempts, lease_hash, lease_expires_at, created_at, updated_at, sequence, execution_actor_id, monthly_period, purchase_order_id FROM access_operations WHERE id=$1
`

func (q *Queries) AccessOperationByID(ctx context.Context, id uuid.UUID) (AccessOperation, error) {
	row := q.db.QueryRow(ctx, accessOperationByID, id)
	var i AccessOperation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OperatorAccountID,
		&i.Kind,
		&i.Status,
		&i.Reason,
		&i.PlanID,
		&i.PlanRevision,
		&i.PeriodDays,
		&i.Desired,
		&i.Target,
		&i.CompletedSteps,
		&i.ReviewReason,
		&i.WriteStarted,
		&i.ResetStarted,
		&i.ResetAcknowledged,
		&i.Attempts,
		&i.LeaseHash,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Sequence,
		&i.ExecutionActorID,
		&i.MonthlyPeriod,
		&i.PurchaseOrderID,
	)
	return i, err
}

const accessOperationForAccount = `-- name: AccessOperationForAccount :one
SELECT id, account_id, operator_account_id, kind, status, reason, plan_id, plan_revision, period_days, desired, target, completed_steps, review_reason, write_started, reset_started, reset_acknowledged, attempts, lease_hash, lease_expires_at, created_at, updated_at, sequence, execution_actor_id, monthly_period, purchase_order_id FROM access_operations WHERE id=$1 AND account_id=$2
`

type AccessOperationForAccountParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) AccessOperationForAccount(ctx context.Context, arg AccessOperationForAccountParams) (AccessOperation, error) {
	row := q.db.QueryRow(ctx, accessOperationForAccount, arg.ID, arg.AccountID)
	var i AccessOperation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OperatorAccountID,
		&i.Kind,
		&i.Status,
		&i.Reason,
		&i.PlanID,
		&i.PlanRevision,
		&i.PeriodDays,
		&i.Desired,
		&i.Target,
		&i.CompletedSteps,
		&i.ReviewReason,
		&i.WriteStarted,
		&i.ResetStarted,
		&i.ResetAcknowledged,
		&i.Attempts,
		&i.LeaseHash,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Sequence,
		&i.ExecutionActorID,
		&i.MonthlyPeriod,
		&i.PurchaseOrderID,
	)
	return i, err
}

const accessRetry = `-- name: AccessRetry :execrows
UPDATE access_operations SET status='pending',lease_hash=NULL,lease_expires_at=NULL,updated_at=$3 WHERE id=$1 AND lease_hash=$2 AND status='provisioning'
`

type AccessRetryParams struct {
	ID        uuid.UUID
	LeaseHash []byte
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) AccessRetry(ctx context.Context, arg AccessRetryParams) (int64, error) {
	result, err := q.db.Exec(ctx, accessRetry, arg.ID, arg.LeaseHash, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const appendAccessStep = `-- name: AppendAccessStep :execrows
UPDATE access_operations SET completed_steps=CASE WHEN completed_steps ? $1::text THEN completed_steps ELSE completed_steps||jsonb_build_array($1::text) END,updated_at=$2::timestamptz
WHERE id=$3::uuid AND lease_hash=$4::bytea AND status='provisioning' AND lease_expires_at>clock_timestamp()
`

type AppendAccessStepParams struct {
	Step      string
	UpdatedAt pgtype.Timestamptz
	ID        uuid.UUID
	LeaseHash []byte
}

func (q *Queries) AppendAccessStep(ctx context.Context, arg AppendAccessStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, appendAccessStep,
		arg.Step,
		arg.UpdatedAt,
		arg.ID,
		arg.LeaseHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const currentAccessPlanID = `-- name: CurrentAccessPlanID :one
SELECT plan_id FROM access_operations WHERE account_id=$1 AND status='applied'
 AND (kind IN ('purchase','assign_plan','starter_trial')
      OR (kind='set_profile' AND (plan_id IS NOT NULL OR desired->>'reset_traffic'='true')))
 ORDER BY sequence DESC LIMIT 1
`

func (q *Queries) CurrentAccessPlanID(ctx context.Context, accountID uuid.UUID) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, currentAccessPlanID, accountID)
	var plan_id *uuid.UUID
	err := row.Scan(&plan_id)
	return plan_id, err
}

const insertAccessOperation = `-- name: InsertAccessOperation :exec
INSERT INTO access_operations(id,account_id,operator_account_id,execution_actor_id,kind,status,reason,plan_id,plan_revision,period_days,desired,target,completed_steps,monthly_period,purchase_order_id,created_at,updated_at)
VALUES($1,$2,$3,$3,$4,'pending',$5,$6,$7,$8,$9,$10,'["prepared"]'::jsonb,$12::text,$13::uuid,$11,$11)
`

type InsertAccessOperationParams struct {
	ID                uuid.UUID
	AccountID         uuid.UUID
	OperatorAccountID *uuid.UUID
	Kind              string
	Reason            string
	PlanID            *uuid.UUID
	PlanRevision      pgtype.Int8
	PeriodDays        pgtype.Int8
	Desired           []byte
	Target            []byte
	CreatedAt         pgtype.Timestamptz
	MonthlyPeriod     pgtype.Text
	PurchaseOrderID   *uuid.UUID
}

func (q *Queries) InsertAccessOperation(ctx context.Context, arg InsertAccessOperationParams) error {
	_, err := q.db.Exec(ctx, insertAccessOperation,
		arg.ID,
		arg.AccountID,
		arg.OperatorAccountID,
		arg.Kind,
		arg.Reason,
		arg.PlanID,
		arg.PlanRevision,
		arg.PeriodDays,
		arg.Desired,
		arg.Target,
		arg.CreatedAt,
		arg.MonthlyPeriod,
		arg.PurchaseOrderID,
	)
	return err
}

const latestAccessOperation = `-- name: LatestAccessOperation :one
SELECT id, account_id, operator_account_id, kind, status, reason, plan_id, plan_revision, period_days, desired, target, completed_steps, review_reason, write_started, reset_started, reset_acknowledged, attempts, lease_hash, lease_expires_at, created_at, updated_at, sequence, execution_actor_id, monthly_period, purchase_order_id FROM access_operations WHERE account_id=$1 AND status<>'skipped' ORDER BY sequence DESC LIMIT 1
`

func (q *Queries) LatestAccessOperation(ctx context.Context, accountID uuid.UUID) (AccessOperation, error) {
	row := q.db.QueryRow(ctx, latestAccessOperation, accountID)
	var i AccessOperation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OperatorAccountID,
		&i.Kind,
		&i.Status,
		&i.Reason,
		&i.PlanID,
		&i.PlanRevision,
		&i.PeriodDays,
		&i.Desired,
		&i.Target,
		&i.CompletedSteps,
		&i.ReviewReason,
		&i.WriteStarted,
		&i.ResetStarted,
		&i.ResetAcknowledged,
		&i.Attempts,
		&i.LeaseHash,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Sequence,
		&i.ExecutionActorID,
		&i.MonthlyPeriod,
		&i.PurchaseOrderID,
	)
	return i, err
}

const latestAppliedAccess = `-- name: LatestAppliedAccess :one
SELECT id, account_id, operator_account_id, kind, status, reason, plan_id, plan_revision, period_days, desired, target, completed_steps, review_reason, write_started, reset_started, reset_acknowledged, attempts, lease_hash, lease_expires_at, created_at, updated_at, sequence, execution_actor_id, monthly_period, purchase_order_id FROM access_operations WHERE account_id=$1 AND status='applied' ORDER BY updated_at DESC,sequence DESC LIMIT 1
`

func (q *Queries) LatestAppliedAccess(ctx context.Context, accountID uuid.UUID) (AccessOperation, error) {
	row := q.db.QueryRow(ctx, latestAppliedAccess, accountID)
	var i AccessOperation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OperatorAccountID,
		&i.Kind,
		&i.Status,
		&i.Reason,
		&i.PlanID,
		&i.PlanRevision,
		&i.PeriodDays,
		&i.Desired,
		&i.Target,
		&i.CompletedSteps,
		&i.ReviewReason,
		&i.WriteStarted,
		&i.ResetStarted,
		&i.ResetAcknowledged,
		&i.Attempts,
		&i.LeaseHash,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Sequence,
		&i.ExecutionActorID,
		&i.MonthlyPeriod,
		&i.PurchaseOrderID,
	)
	return i, err
}

const leaseAccessOperation = `-- name: LeaseAccessOperation :one
UPDATE access_operations SET status='provisioning',attempts=attempts+1,lease_hash=$2,lease_expires_at=clock_timestamp()+interval '3 minutes',updated_at=$3
WHERE id=$1 AND status IN ('pending','provisioning') RETURNING id, account_id, operator_account_id, kind, status, reason, plan_id, plan_revision, period_days, desired, target, completed_steps, review_reason, write_started, reset_started, reset_acknowledged, attempts, lease_hash, lease_expires_at, created_at, updated_at, sequence, execution_actor_id, monthly_period, purchase_order_id
`

type LeaseAccessOperationParams struct {
	ID        uuid.UUID
	LeaseHash []byte
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) LeaseAccessOperation(ctx context.Context, arg LeaseAccessOperationParams) (AccessOperation, error) {
	row := q.db.QueryRow(ctx, leaseAccessOperation, arg.ID, arg.LeaseHash, arg.UpdatedAt)
	var i AccessOperation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OperatorAccountID,
		&i.Kind,
		&i.Status,
		&i.Reason,
		&i.PlanID,
		&i.PlanRevision,
		&i.PeriodDays,
		&i.Desired,
		&i.Target,
		&i.CompletedSteps,
		&i.ReviewReason,
		&i.WriteStarted,
		&i.ResetStarted,
		&i.ResetAcknowledged,
		&i.Attempts,
		&i.LeaseHash,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Sequence,
		&i.ExecutionActorID,
		&i.MonthlyPeriod,
		&i.PurchaseOrderID,
	)
	return i, err
}

const markAccessReset = `-- name: MarkAccessReset :execrows
UPDATE access_operations SET reset_started=true,reset_acknowledged=false,completed_steps=completed_steps||'["reset_started"]'::jsonb,updated_at=$3 WHERE id=$1 AND lease_hash=$2 AND status='provisioning' AND lease_expires_at>clock_timestamp()
`

type MarkAccessResetParams struct {
	ID        uuid.UUID
	LeaseHash []byte
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) MarkAccessReset(ctx context.Context, arg MarkAccessResetParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAccessReset, arg.ID, arg.LeaseHash, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markAccessWrite = `-- name: MarkAccessWrite :execrows
UPDATE access_operations SET write_started=true,updated_at=$3 WHERE id=$1 AND lease_hash=$2 AND status='provisioning' AND lease_expires_at>clock_timestamp()
`

type MarkAccessWriteParams struct {
	ID        uuid.UUID
	LeaseHash []byte
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) MarkAccessWrite(ctx context.Context, arg MarkAccessWriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAccessWrite, arg.ID, arg.LeaseHash, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueAccess = `-- name: RequeueAccess :execrows
UPDATE access_operations SET status='pending',attempts=0,reset_acknowledged=$2,execution_actor_id=CASE WHEN kind='purchase' THEN NULL ELSE $4::uuid END,review_reason=NULL,updated_at=$3 WHERE id=$1 AND status='needs_review'
`

type RequeueAccessParams struct {
	ID                uuid.UUID
	ResetAcknowledged bool
	UpdatedAt         pgtype.Timestamptz
	ExecutionActorID  uuid.UUID
}

func (q *Queries) RequeueAccess(ctx context.Context, arg RequeueAccessParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueAccess,
		arg.ID,
		arg.ResetAcknowledged,
		arg.UpdatedAt,
		arg.ExecutionActorID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unresolvedAccessExists = `-- name: UnresolvedAccessExists :one
SELECT EXISTS(SELECT 1 FROM access_operations WHERE account_id=$1 AND status IN ('pending','provisioning','needs_review'))
`

func (q *Queries) UnresolvedAccessExists(ctx context.Context, accountID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, unresolvedAccessExists, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const unresolvedTrialExists = `-- name: UnresolvedTrialExists :one
SELECT EXISTS(SELECT 1 FROM trial_operations WHERE account_id=$1 AND status IN ('pending','provisioning','needs_review'))
`

func (q *Queries) UnresolvedTrialExists(ctx context.Context, accountID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, unresolvedTrialExists, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
