// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessOperation struct {
	ID                uuid.UUID
	AccountID         uuid.UUID
	OperatorAccountID *uuid.UUID
	Kind              string
	Status            string
	Reason            string
	PlanID            *uuid.UUID
	PlanRevision      pgtype.Int8
	PeriodDays        pgtype.Int8
	Desired           []byte
	Target            []byte
	CompletedSteps    []byte
	ReviewReason      pgtype.Text
	WriteStarted      bool
	ResetStarted      bool
	ResetAcknowledged bool
	Attempts          int32
	LeaseHash         []byte
	LeaseExpiresAt    pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	Sequence          int64
	ExecutionActorID  *uuid.UUID
	MonthlyPeriod     pgtype.Text
	PurchaseOrderID   *uuid.UUID
}

type TrialOperation struct {
	ID               uuid.UUID
	AccountID        uuid.UUID
	RequestID        uuid.UUID
	Status           string
	TrialEnabled     bool
	PeriodDays       int64
	TrafficGb        int64
	Devices          int64
	PanelID          string
	CreatedAt        pgtype.Timestamptz
	FirstStartedAt   pgtype.Timestamptz
	Target           []byte
	WriteStarted     bool
	Attempts         int32
	LeaseHash        []byte
	LeaseExpiresAt   pgtype.Timestamptz
	WorkerPid        pgtype.Int4
	TrafficUsedBytes pgtype.Int8
	ObservedAt       pgtype.Timestamptz
	TrafficUpBytes   pgtype.Int8
	TrafficDownBytes pgtype.Int8
	ProfileSnapshot  []byte
}
