// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: servers.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const lockServerPool = `-- name: LockServerPool :exec
SELECT pg_advisory_xact_lock(hashtextextended('vpn-server-pool',0))
`

func (q *Queries) LockServerPool(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockServerPool)
	return err
}

const observePoolServer = `-- name: ObservePoolServer :exec
UPDATE vpn_servers SET online=$1,observed_at=$2,
 subscription_base_url=CASE WHEN subscription_base_url='' THEN $3::text ELSE subscription_base_url END
WHERE id=$4 AND revision=$5 AND NOT retired
 AND (observed_at IS NULL OR observed_at<$2)
`

type ObservePoolServerParams struct {
	Online     bool
	ObservedAt pgtype.Timestamptz
	Base       string
	ID         string
	Revision   int64
}

func (q *Queries) ObservePoolServer(ctx context.Context, arg ObservePoolServerParams) error {
	_, err := q.db.Exec(ctx, observePoolServer,
		arg.Online,
		arg.ObservedAt,
		arg.Base,
		arg.ID,
		arg.Revision,
	)
	return err
}

const poolServers = `-- name: PoolServers :many
SELECT s.id, s.name, s.host, s.max_clients, s.subscription_base_url, s.online, s.observed_at, s.revision, s.retired, (SELECT count(*) FROM vpn_server_reservations r WHERE r.server_id=s.id) AS reserved_clients
FROM vpn_servers s ORDER BY s.id
`

type PoolServersRow struct {
	ID                  string
	Name                string
	Host                string
	MaxClients          pgtype.Int8
	SubscriptionBaseUrl string
	Online              bool
	ObservedAt          pgtype.Timestamptz
	Revision            int64
	Retired             bool
	ReservedClients     int64
}

func (q *Queries) PoolServers(ctx context.Context) ([]PoolServersRow, error) {
	rows, err := q.db.Query(ctx, poolServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PoolServersRow
	for rows.Next() {
		var i PoolServersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.MaxClients,
			&i.SubscriptionBaseUrl,
			&i.Online,
			&i.ObservedAt,
			&i.Revision,
			&i.Retired,
			&i.ReservedClients,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerPoolServer = `-- name: RegisterPoolServer :one
INSERT INTO vpn_servers(id,name,host,max_clients) VALUES($1,$2,$3,$4)
ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,max_clients=EXCLUDED.max_clients,
 revision=vpn_servers.revision+1
WHERE vpn_servers.host=EXCLUDED.host AND NOT vpn_servers.retired
RETURNING id, name, host, max_clients, subscription_base_url, online, observed_at, revision, retired
`

type RegisterPoolServerParams struct {
	ID         string
	Name       string
	Host       string
	MaxClients pgtype.Int8
}

func (q *Queries) RegisterPoolServer(ctx context.Context, arg RegisterPoolServerParams) (VpnServer, error) {
	row := q.db.QueryRow(ctx, registerPoolServer,
		arg.ID,
		arg.Name,
		arg.Host,
		arg.MaxClients,
	)
	var i VpnServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.MaxClients,
		&i.SubscriptionBaseUrl,
		&i.Online,
		&i.ObservedAt,
		&i.Revision,
		&i.Retired,
	)
	return i, err
}

const seedPrimaryServer = `-- name: SeedPrimaryServer :exec
INSERT INTO vpn_servers(id,name,host,subscription_base_url) VALUES($1,$2,$3,$4)
ON CONFLICT DO NOTHING
`

type SeedPrimaryServerParams struct {
	ID                  string
	Name                string
	Host                string
	SubscriptionBaseUrl string
}

func (q *Queries) SeedPrimaryServer(ctx context.Context, arg SeedPrimaryServerParams) error {
	_, err := q.db.Exec(ctx, seedPrimaryServer,
		arg.ID,
		arg.Name,
		arg.Host,
		arg.SubscriptionBaseUrl,
	)
	return err
}
