// Package wire provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package wire

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AccountLocale.
const (
	AccountLocaleEn AccountLocale = "en"
	AccountLocaleRu AccountLocale = "ru"
)

// Valid indicates whether the value is a known member of the AccountLocale enum.
func (e AccountLocale) Valid() bool {
	switch e {
	case AccountLocaleEn:
		return true
	case AccountLocaleRu:
		return true
	default:
		return false
	}
}

// Defines values for AccountTelegramLinked.
const (
	False AccountTelegramLinked = false
)

// Valid indicates whether the value is a known member of the AccountTelegramLinked enum.
func (e AccountTelegramLinked) Valid() bool {
	switch e {
	case False:
		return true
	default:
		return false
	}
}

// Defines values for ClaimInputLimit.
const (
	N1 ClaimInputLimit = 1
)

// Valid indicates whether the value is a known member of the ClaimInputLimit enum.
func (e ClaimInputLimit) Valid() bool {
	switch e {
	case N1:
		return true
	default:
		return false
	}
}

// Defines values for DecisionInputDecision.
const (
	Approve DecisionInputDecision = "approve"
	Reject  DecisionInputDecision = "reject"
)

// Valid indicates whether the value is a known member of the DecisionInputDecision enum.
func (e DecisionInputDecision) Valid() bool {
	switch e {
	case Approve:
		return true
	case Reject:
		return true
	default:
		return false
	}
}

// Defines values for DecisionResultDeliveryState.
const (
	DecisionResultDeliveryStateFailed  DecisionResultDeliveryState = "failed"
	DecisionResultDeliveryStatePending DecisionResultDeliveryState = "pending"
	DecisionResultDeliveryStateSent    DecisionResultDeliveryState = "sent"
)

// Valid indicates whether the value is a known member of the DecisionResultDeliveryState enum.
func (e DecisionResultDeliveryState) Valid() bool {
	switch e {
	case DecisionResultDeliveryStateFailed:
		return true
	case DecisionResultDeliveryStatePending:
		return true
	case DecisionResultDeliveryStateSent:
		return true
	default:
		return false
	}
}

// Defines values for ErrorBodyCode.
const (
	ACCOUNTRESTRICTED            ErrorBodyCode = "ACCOUNT_RESTRICTED"
	EMAILVERIFICATIONREQUIRED    ErrorBodyCode = "EMAIL_VERIFICATION_REQUIRED"
	IDEMPOTENCYCONFLICT          ErrorBodyCode = "IDEMPOTENCY_CONFLICT"
	INVALIDCREDENTIALS           ErrorBodyCode = "INVALID_CREDENTIALS"
	INVALIDINPUT                 ErrorBodyCode = "INVALID_INPUT"
	OPERATIONNOTREADY            ErrorBodyCode = "OPERATION_NOT_READY"
	RATELIMITED                  ErrorBodyCode = "RATE_LIMITED"
	REQUESTSTATECONFLICT         ErrorBodyCode = "REQUEST_STATE_CONFLICT"
	SERVICEUNAVAILABLE           ErrorBodyCode = "SERVICE_UNAVAILABLE"
	TRIALALREADYUSED             ErrorBodyCode = "TRIAL_ALREADY_USED"
	TRIALDISABLED                ErrorBodyCode = "TRIAL_DISABLED"
	TRIALRECONSIDERATIONREQUIRED ErrorBodyCode = "TRIAL_RECONSIDERATION_REQUIRED"
)

// Valid indicates whether the value is a known member of the ErrorBodyCode enum.
func (e ErrorBodyCode) Valid() bool {
	switch e {
	case ACCOUNTRESTRICTED:
		return true
	case EMAILVERIFICATIONREQUIRED:
		return true
	case IDEMPOTENCYCONFLICT:
		return true
	case INVALIDCREDENTIALS:
		return true
	case INVALIDINPUT:
		return true
	case OPERATIONNOTREADY:
		return true
	case RATELIMITED:
		return true
	case REQUESTSTATECONFLICT:
		return true
	case SERVICEUNAVAILABLE:
		return true
	case TRIALALREADYUSED:
		return true
	case TRIALDISABLED:
		return true
	case TRIALRECONSIDERATIONREQUIRED:
		return true
	default:
		return false
	}
}

// Defines values for ErrorBodyCurrentRequestStatus.
const (
	ErrorBodyCurrentRequestStatusApproved ErrorBodyCurrentRequestStatus = "approved"
	ErrorBodyCurrentRequestStatusPending  ErrorBodyCurrentRequestStatus = "pending"
	ErrorBodyCurrentRequestStatusRejected ErrorBodyCurrentRequestStatus = "rejected"
)

// Valid indicates whether the value is a known member of the ErrorBodyCurrentRequestStatus enum.
func (e ErrorBodyCurrentRequestStatus) Valid() bool {
	switch e {
	case ErrorBodyCurrentRequestStatusApproved:
		return true
	case ErrorBodyCurrentRequestStatusPending:
		return true
	case ErrorBodyCurrentRequestStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for PasswordResetInputLocale.
const (
	PasswordResetInputLocaleEn PasswordResetInputLocale = "en"
	PasswordResetInputLocaleRu PasswordResetInputLocale = "ru"
)

// Valid indicates whether the value is a known member of the PasswordResetInputLocale enum.
func (e PasswordResetInputLocale) Valid() bool {
	switch e {
	case PasswordResetInputLocaleEn:
		return true
	case PasswordResetInputLocaleRu:
		return true
	default:
		return false
	}
}

// Defines values for ReconcileResultStatus.
const (
	ReconcileResultStatusApplied      ReconcileResultStatus = "applied"
	ReconcileResultStatusNeedsReview  ReconcileResultStatus = "needs_review"
	ReconcileResultStatusPending      ReconcileResultStatus = "pending"
	ReconcileResultStatusProvisioning ReconcileResultStatus = "provisioning"
)

// Valid indicates whether the value is a known member of the ReconcileResultStatus enum.
func (e ReconcileResultStatus) Valid() bool {
	switch e {
	case ReconcileResultStatusApplied:
		return true
	case ReconcileResultStatusNeedsReview:
		return true
	case ReconcileResultStatusPending:
		return true
	case ReconcileResultStatusProvisioning:
		return true
	default:
		return false
	}
}

// Defines values for RegisterInputLocale.
const (
	RegisterInputLocaleEn RegisterInputLocale = "en"
	RegisterInputLocaleRu RegisterInputLocale = "ru"
)

// Valid indicates whether the value is a known member of the RegisterInputLocale enum.
func (e RegisterInputLocale) Valid() bool {
	switch e {
	case RegisterInputLocaleEn:
		return true
	case RegisterInputLocaleRu:
		return true
	default:
		return false
	}
}

// Defines values for SubscriptionAccessProfile.
const (
	SubscriptionAccessProfileBanned    SubscriptionAccessProfile = "banned"
	SubscriptionAccessProfileEuru      SubscriptionAccessProfile = "euru"
	SubscriptionAccessProfileRegular   SubscriptionAccessProfile = "regular"
	SubscriptionAccessProfileUnknown   SubscriptionAccessProfile = "unknown"
	SubscriptionAccessProfileUnlimited SubscriptionAccessProfile = "unlimited"
)

// Valid indicates whether the value is a known member of the SubscriptionAccessProfile enum.
func (e SubscriptionAccessProfile) Valid() bool {
	switch e {
	case SubscriptionAccessProfileBanned:
		return true
	case SubscriptionAccessProfileEuru:
		return true
	case SubscriptionAccessProfileRegular:
		return true
	case SubscriptionAccessProfileUnknown:
		return true
	case SubscriptionAccessProfileUnlimited:
		return true
	default:
		return false
	}
}

// Defines values for SubscriptionPanelError.
const (
	IdentityMismatch  SubscriptionPanelError = "identity_mismatch"
	InvalidTraffic    SubscriptionPanelError = "invalid_traffic"
	LessThannil       SubscriptionPanelError = "<nil>"
	Unavailable       SubscriptionPanelError = "unavailable"
	UnknownMembership SubscriptionPanelError = "unknown_membership"
)

// Valid indicates whether the value is a known member of the SubscriptionPanelError enum.
func (e SubscriptionPanelError) Valid() bool {
	switch e {
	case IdentityMismatch:
		return true
	case InvalidTraffic:
		return true
	case LessThannil:
		return true
	case Unavailable:
		return true
	case UnknownMembership:
		return true
	default:
		return false
	}
}

// Defines values for SubscriptionStatus.
const (
	SubscriptionStatusActive       SubscriptionStatus = "active"
	SubscriptionStatusBanned       SubscriptionStatus = "banned"
	SubscriptionStatusDisabled     SubscriptionStatus = "disabled"
	SubscriptionStatusExhausted    SubscriptionStatus = "exhausted"
	SubscriptionStatusExpired      SubscriptionStatus = "expired"
	SubscriptionStatusNeedsReview  SubscriptionStatus = "needs_review"
	SubscriptionStatusNone         SubscriptionStatus = "none"
	SubscriptionStatusProvisioning SubscriptionStatus = "provisioning"
)

// Valid indicates whether the value is a known member of the SubscriptionStatus enum.
func (e SubscriptionStatus) Valid() bool {
	switch e {
	case SubscriptionStatusActive:
		return true
	case SubscriptionStatusBanned:
		return true
	case SubscriptionStatusDisabled:
		return true
	case SubscriptionStatusExhausted:
		return true
	case SubscriptionStatusExpired:
		return true
	case SubscriptionStatusNeedsReview:
		return true
	case SubscriptionStatusNone:
		return true
	case SubscriptionStatusProvisioning:
		return true
	default:
		return false
	}
}

// Defines values for SupportConversationStatus.
const (
	SupportConversationStatusClosed SupportConversationStatus = "closed"
	SupportConversationStatusOpen   SupportConversationStatus = "open"
)

// Valid indicates whether the value is a known member of the SupportConversationStatus enum.
func (e SupportConversationStatus) Valid() bool {
	switch e {
	case SupportConversationStatusClosed:
		return true
	case SupportConversationStatusOpen:
		return true
	default:
		return false
	}
}

// Defines values for SupportMessageDelivery.
const (
	Delivered SupportMessageDelivery = "delivered"
	Stored    SupportMessageDelivery = "stored"
)

// Valid indicates whether the value is a known member of the SupportMessageDelivery enum.
func (e SupportMessageDelivery) Valid() bool {
	switch e {
	case Delivered:
		return true
	case Stored:
		return true
	default:
		return false
	}
}

// Defines values for SupportMessageSender.
const (
	Customer SupportMessageSender = "customer"
	Operator SupportMessageSender = "operator"
)

// Valid indicates whether the value is a known member of the SupportMessageSender enum.
func (e SupportMessageSender) Valid() bool {
	switch e {
	case Customer:
		return true
	case Operator:
		return true
	default:
		return false
	}
}

// Defines values for SupportStateInputStatus.
const (
	SupportStateInputStatusClosed SupportStateInputStatus = "closed"
	SupportStateInputStatusOpen   SupportStateInputStatus = "open"
)

// Valid indicates whether the value is a known member of the SupportStateInputStatus enum.
func (e SupportStateInputStatus) Valid() bool {
	switch e {
	case SupportStateInputStatusClosed:
		return true
	case SupportStateInputStatusOpen:
		return true
	default:
		return false
	}
}

// Defines values for TelegramFailedCode.
const (
	EditFailed      TelegramFailedCode = "edit_failed"
	Forbidden       TelegramFailedCode = "forbidden"
	InvalidResponse TelegramFailedCode = "invalid_response"
	Network         TelegramFailedCode = "network"
	Timeout         TelegramFailedCode = "timeout"
)

// Valid indicates whether the value is a known member of the TelegramFailedCode enum.
func (e TelegramFailedCode) Valid() bool {
	switch e {
	case EditFailed:
		return true
	case Forbidden:
		return true
	case InvalidResponse:
		return true
	case Network:
		return true
	case Timeout:
		return true
	default:
		return false
	}
}

// Defines values for TelegramFailedKind.
const (
	DeliveryFailed TelegramFailedKind = "delivery_failed"
)

// Valid indicates whether the value is a known member of the TelegramFailedKind enum.
func (e TelegramFailedKind) Valid() bool {
	switch e {
	case DeliveryFailed:
		return true
	default:
		return false
	}
}

// Defines values for TelegramJobKind.
const (
	ApprovalCard     TelegramJobKind = "approval_card"
	ProvisionApplied TelegramJobKind = "provision_applied"
	ProvisionReview  TelegramJobKind = "provision_review"
	RequestDecided   TelegramJobKind = "request_decided"
)

// Valid indicates whether the value is a known member of the TelegramJobKind enum.
func (e TelegramJobKind) Valid() bool {
	switch e {
	case ApprovalCard:
		return true
	case ProvisionApplied:
		return true
	case ProvisionReview:
		return true
	case RequestDecided:
		return true
	default:
		return false
	}
}

// Defines values for TelegramPayloadStatus.
const (
	TelegramPayloadStatusActive       TelegramPayloadStatus = "active"
	TelegramPayloadStatusApproved     TelegramPayloadStatus = "approved"
	TelegramPayloadStatusExpired      TelegramPayloadStatus = "expired"
	TelegramPayloadStatusNeedsReview  TelegramPayloadStatus = "needs_review"
	TelegramPayloadStatusPending      TelegramPayloadStatus = "pending"
	TelegramPayloadStatusProvisioning TelegramPayloadStatus = "provisioning"
	TelegramPayloadStatusRejected     TelegramPayloadStatus = "rejected"
)

// Valid indicates whether the value is a known member of the TelegramPayloadStatus enum.
func (e TelegramPayloadStatus) Valid() bool {
	switch e {
	case TelegramPayloadStatusActive:
		return true
	case TelegramPayloadStatusApproved:
		return true
	case TelegramPayloadStatusExpired:
		return true
	case TelegramPayloadStatusNeedsReview:
		return true
	case TelegramPayloadStatusPending:
		return true
	case TelegramPayloadStatusProvisioning:
		return true
	case TelegramPayloadStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for TelegramSentKind.
const (
	TelegramSentKindSent TelegramSentKind = "sent"
)

// Valid indicates whether the value is a known member of the TelegramSentKind enum.
func (e TelegramSentKind) Valid() bool {
	switch e {
	case TelegramSentKindSent:
		return true
	default:
		return false
	}
}

// Defines values for TrialRequestStatus.
const (
	TrialRequestStatusApproved TrialRequestStatus = "approved"
	TrialRequestStatusPending  TrialRequestStatus = "pending"
	TrialRequestStatusRejected TrialRequestStatus = "rejected"
)

// Valid indicates whether the value is a known member of the TrialRequestStatus enum.
func (e TrialRequestStatus) Valid() bool {
	switch e {
	case TrialRequestStatusApproved:
		return true
	case TrialRequestStatusPending:
		return true
	case TrialRequestStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for VerifyResultVerified.
const (
	True VerifyResultVerified = true
)

// Valid indicates whether the value is a known member of the VerifyResultVerified enum.
func (e VerifyResultVerified) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// APIError defines model for APIError.
type APIError struct {
	Error ErrorBody `json:"error"`
}

// Account defines model for Account.
type Account struct {
	AccountId      openapi_types.UUID    `json:"account_id"`
	Email          openapi_types.Email   `json:"email"`
	EmailVerified  bool                  `json:"email_verified"`
	Locale         AccountLocale         `json:"locale"`
	TelegramLinked AccountTelegramLinked `json:"telegram_linked"`
}

// AccountLocale defines model for Account.Locale.
type AccountLocale string

// AccountTelegramLinked defines model for Account.TelegramLinked.
type AccountTelegramLinked bool

// AccountResult defines model for AccountResult.
type AccountResult struct {
	Account      Account      `json:"account"`
	Capabilities Capabilities `json:"capabilities"`
	CsrfToken    string       `json:"csrf_token"`
}

// AccountSecurity defines model for AccountSecurity.
type AccountSecurity struct {
	Email              openapi_types.Email `json:"email"`
	HasOtherSessions   bool                `json:"has_other_sessions"`
	PendingEmailChange *PendingEmailChange `json:"pending_email_change"`
}

// Capabilities defines model for Capabilities.
type Capabilities struct {
	TrialAvailable bool `json:"trial_available"`
}

// ClaimInput defines model for ClaimInput.
type ClaimInput struct {
	Limit ClaimInputLimit `json:"limit"`
}

// ClaimInputLimit defines model for ClaimInput.Limit.
type ClaimInputLimit int

// ClaimResult defines model for ClaimResult.
type ClaimResult struct {
	Jobs []TelegramJob `json:"jobs"`
}

// CompleteResult defines model for CompleteResult.
type CompleteResult = map[string]interface{}

// CurrentPasswordInput defines model for CurrentPasswordInput.
type CurrentPasswordInput struct {
	CurrentPassword string `json:"current_password"`
}

// CurrentTrialRequest defines model for CurrentTrialRequest.
type CurrentTrialRequest struct {
	Request *TrialRequest `json:"request"`
}

// DecisionInput defines model for DecisionInput.
type DecisionInput struct {
	CallbackQueryId string                `json:"callback_query_id"`
	Decision        DecisionInputDecision `json:"decision"`
	OperatorTgId    int64                 `json:"operator_tg_id"`
	Reason          *string               `json:"reason,omitempty"`
}

// DecisionInputDecision defines model for DecisionInput.Decision.
type DecisionInputDecision string

// DecisionResult defines model for DecisionResult.
type DecisionResult struct {
	Card          TelegramPayload             `json:"card"`
	DeliveryState DecisionResultDeliveryState `json:"delivery_state"`
	OperationId   *openapi_types.UUID         `json:"operation_id"`
	Request       TrialRequest                `json:"request"`
}

// DecisionResultDeliveryState defines model for DecisionResult.DeliveryState.
type DecisionResultDeliveryState string

// EmailChangeAccepted defines model for EmailChangeAccepted.
type EmailChangeAccepted struct {
	ChangeId    openapi_types.UUID `json:"change_id"`
	ExpiresAt   time.Time          `json:"expires_at"`
	ResendAfter int                `json:"resend_after"`
}

// EmailChangeConfirmInput defines model for EmailChangeConfirmInput.
type EmailChangeConfirmInput struct {
	ChallengeId *openapi_types.UUID `json:"challenge_id,omitempty"`
	Code        *string             `json:"code,omitempty"`
	Token       *string             `json:"token,omitempty"`
	union       json.RawMessage
}

// EmailChangeConfirmInput0 defines model for EmailChangeConfirmInput.0.
type EmailChangeConfirmInput0 = interface{}

// EmailChangeConfirmInput1 defines model for EmailChangeConfirmInput.1.
type EmailChangeConfirmInput1 = interface{}

// EmailChangeInput defines model for EmailChangeInput.
type EmailChangeInput struct {
	CurrentPassword string              `json:"current_password"`
	NewEmail        openapi_types.Email `json:"new_email"`
}

// EmailChangeResult defines model for EmailChangeResult.
type EmailChangeResult struct {
	Completed bool `json:"completed"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Code                 ErrorBodyCode                  `json:"code"`
	CurrentRequestStatus *ErrorBodyCurrentRequestStatus `json:"current_request_status,omitempty"`
	Message              string                         `json:"message"`
	OperationId          *openapi_types.UUID            `json:"operation_id,omitempty"`
	RequestId            openapi_types.UUID             `json:"request_id"`
}

// ErrorBodyCode defines model for ErrorBody.Code.
type ErrorBodyCode string

// ErrorBodyCurrentRequestStatus defines model for ErrorBody.CurrentRequestStatus.
type ErrorBodyCurrentRequestStatus string

// LoginInput defines model for LoginInput.
type LoginInput struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResult defines model for LoginResult.
type LoginResult struct {
	Account   Account `json:"account"`
	CsrfToken string  `json:"csrf_token"`
}

// PasswordChangeInput defines model for PasswordChangeInput.
type PasswordChangeInput struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// PasswordResetAccepted defines model for PasswordResetAccepted.
type PasswordResetAccepted struct {
	ChallengeId openapi_types.UUID `json:"challenge_id"`
	ResendAfter int64              `json:"resend_after"`
}

// PasswordResetCompleteInput defines model for PasswordResetCompleteInput.
type PasswordResetCompleteInput struct {
	ChallengeId *openapi_types.UUID `json:"challenge_id,omitempty"`
	Code        *string             `json:"code,omitempty"`
	NewPassword string              `json:"new_password"`
	Token       *string             `json:"token,omitempty"`
	union       json.RawMessage
}

// PasswordResetCompleteInput0 defines model for PasswordResetCompleteInput.0.
type PasswordResetCompleteInput0 = interface{}

// PasswordResetCompleteInput1 defines model for PasswordResetCompleteInput.1.
type PasswordResetCompleteInput1 = interface{}

// PasswordResetInput defines model for PasswordResetInput.
type PasswordResetInput struct {
	Email  openapi_types.Email      `json:"email"`
	Locale PasswordResetInputLocale `json:"locale"`
}

// PasswordResetInputLocale defines model for PasswordResetInput.Locale.
type PasswordResetInputLocale string

// PendingEmailChange defines model for PendingEmailChange.
type PendingEmailChange struct {
	CurrentEmailConfirmed bool                `json:"current_email_confirmed"`
	ExpiresAt             time.Time           `json:"expires_at"`
	NewEmail              openapi_types.Email `json:"new_email"`
	NewEmailConfirmed     bool                `json:"new_email_confirmed"`
}

// ReconcileInput defines model for ReconcileInput.
type ReconcileInput struct {
	OperatorTgId int64  `json:"operator_tg_id"`
	Reason       string `json:"reason"`
}

// ReconcileResult defines model for ReconcileResult.
type ReconcileResult struct {
	OperationId openapi_types.UUID    `json:"operation_id"`
	Status      ReconcileResultStatus `json:"status"`
}

// ReconcileResultStatus defines model for ReconcileResult.Status.
type ReconcileResultStatus string

// ReconsiderInput defines model for ReconsiderInput.
type ReconsiderInput struct {
	OperatorTgId int64  `json:"operator_tg_id"`
	Reason       string `json:"reason"`
}

// RegisterInput defines model for RegisterInput.
type RegisterInput struct {
	AcceptedPrivacyVersion string              `json:"accepted_privacy_version"`
	AcceptedTermsVersion   string              `json:"accepted_terms_version"`
	Email                  openapi_types.Email `json:"email"`
	Locale                 RegisterInputLocale `json:"locale"`
}

// RegisterInputLocale defines model for RegisterInput.Locale.
type RegisterInputLocale string

// RegistrationAccepted defines model for RegistrationAccepted.
type RegistrationAccepted struct {
	ChallengeId openapi_types.UUID `json:"challenge_id"`
	ResendAfter int64              `json:"resend_after"`
}

// ResendAccepted defines model for ResendAccepted.
type ResendAccepted struct {
	ResendAfter int64 `json:"resend_after"`
}

// ResendInput defines model for ResendInput.
type ResendInput struct {
	Email openapi_types.Email `json:"email"`
}

// SessionContext defines model for SessionContext.
type SessionContext struct {
	CsrfToken string `json:"csrf_token"`
}

// Subscription defines model for Subscription.
type Subscription struct {
	AccessProfile         *SubscriptionAccessProfile `json:"access_profile,omitempty"`
	ConnectionAvailable   *bool                      `json:"connection_available,omitempty"`
	DataStale             bool                       `json:"data_stale"`
	Devices               int64                      `json:"devices"`
	ExpiresAt             *time.Time                 `json:"expires_at"`
	ObservedAt            *time.Time                 `json:"observed_at"`
	PanelError            *SubscriptionPanelError    `json:"panel_error,omitempty"`
	Status                SubscriptionStatus         `json:"status"`
	TrafficDownloadBytes  *int64                     `json:"traffic_download_bytes,omitempty"`
	TrafficLimitBytes     int64                      `json:"traffic_limit_bytes"`
	TrafficRemainingBytes *int64                     `json:"traffic_remaining_bytes,omitempty"`
	TrafficUploadBytes    *int64                     `json:"traffic_upload_bytes,omitempty"`
	TrafficUsedBytes      *int64                     `json:"traffic_used_bytes"`
	UnlimitedDevices      *bool                      `json:"unlimited_devices,omitempty"`
	UnlimitedTraffic      *bool                      `json:"unlimited_traffic,omitempty"`
}

// SubscriptionAccessProfile defines model for Subscription.AccessProfile.
type SubscriptionAccessProfile string

// SubscriptionPanelError defines model for Subscription.PanelError.
type SubscriptionPanelError string

// SubscriptionStatus defines model for Subscription.Status.
type SubscriptionStatus string

// SubscriptionKey defines model for SubscriptionKey.
type SubscriptionKey struct {
	SubscriptionUrl string `json:"subscription_url"`
}

// SupportAttachment defines model for SupportAttachment.
type SupportAttachment struct {
	Name      string `json:"name"`
	SizeBytes int64  `json:"size_bytes"`
}

// SupportBanInput defines model for SupportBanInput.
type SupportBanInput struct {
	Banned bool   `json:"banned"`
	Reason string `json:"reason"`
}

// SupportConversation defines model for SupportConversation.
type SupportConversation struct {
	CreatedAt                time.Time                 `json:"created_at"`
	CustomerReceivedSequence int64                     `json:"customer_received_sequence"`
	Id                       openapi_types.UUID        `json:"id"`
	OperatorReceivedSequence int64                     `json:"operator_received_sequence"`
	Status                   SupportConversationStatus `json:"status"`
	SupportBanned            bool                      `json:"support_banned"`
	UpdatedAt                time.Time                 `json:"updated_at"`
}

// SupportConversationStatus defines model for SupportConversation.Status.
type SupportConversationStatus string

// SupportHistoryInput defines model for SupportHistoryInput.
type SupportHistoryInput struct {
	BeforeSequence int64 `json:"before_sequence"`
}

// SupportMessage defines model for SupportMessage.
type SupportMessage struct {
	Attachment *SupportAttachment     `json:"attachment"`
	CreatedAt  time.Time              `json:"created_at"`
	Delivery   SupportMessageDelivery `json:"delivery"`
	Id         openapi_types.UUID     `json:"id"`
	Sender     SupportMessageSender   `json:"sender"`
	Sequence   int64                  `json:"sequence"`
	Text       string                 `json:"text"`
}

// SupportMessageDelivery defines model for SupportMessage.Delivery.
type SupportMessageDelivery string

// SupportMessageSender defines model for SupportMessage.Sender.
type SupportMessageSender string

// SupportMessageInput defines model for SupportMessageInput.
type SupportMessageInput struct {
	Text string `json:"text"`
}

// SupportMultipartInput defines model for SupportMultipartInput.
type SupportMultipartInput struct {
	File *openapi_types.File `json:"file,omitempty"`
	Text string              `json:"text"`
}

// SupportReadInput defines model for SupportReadInput.
type SupportReadInput struct {
	Sequence int64 `json:"sequence"`
}

// SupportResult defines model for SupportResult.
type SupportResult struct {
	Conversation   *SupportConversation `json:"conversation"`
	HasMore        bool                 `json:"has_more"`
	Messages       []SupportMessage     `json:"messages"`
	OldestSequence *int64               `json:"oldest_sequence"`
}

// SupportStateInput defines model for SupportStateInput.
type SupportStateInput struct {
	Status SupportStateInputStatus `json:"status"`
}

// SupportStateInputStatus defines model for SupportStateInput.Status.
type SupportStateInputStatus string

// TelegramFailed defines model for TelegramFailed.
type TelegramFailed struct {
	Code TelegramFailedCode `json:"code"`
	Kind TelegramFailedKind `json:"kind"`
}

// TelegramFailedCode defines model for TelegramFailed.Code.
type TelegramFailedCode string

// TelegramFailedKind defines model for TelegramFailed.Kind.
type TelegramFailedKind string

// TelegramJob defines model for TelegramJob.
type TelegramJob struct {
	ChatId         int64              `json:"chat_id"`
	JobId          openapi_types.UUID `json:"job_id"`
	Kind           TelegramJobKind    `json:"kind"`
	LeaseExpiresAt time.Time          `json:"lease_expires_at"`
	LeaseToken     string             `json:"lease_token"`
	Payload        TelegramPayload    `json:"payload"`
}

// TelegramJobKind defines model for TelegramJob.Kind.
type TelegramJobKind string

// TelegramPayload defines model for TelegramPayload.
type TelegramPayload struct {
	Comment         string                `json:"comment"`
	CreatedAt       time.Time             `json:"created_at"`
	Email           openapi_types.Email   `json:"email"`
	OperationId     *openapi_types.UUID   `json:"operation_id"`
	RequestId       openapi_types.UUID    `json:"request_id"`
	Status          TelegramPayloadStatus `json:"status"`
	TargetMessageId *int64                `json:"target_message_id"`
}

// TelegramPayloadStatus defines model for TelegramPayload.Status.
type TelegramPayloadStatus string

// TelegramResult defines model for TelegramResult.
type TelegramResult struct {
	union json.RawMessage
}

// TelegramResultInput defines model for TelegramResultInput.
type TelegramResultInput struct {
	LeaseToken string         `json:"lease_token"`
	Result     TelegramResult `json:"result"`
}

// TelegramSent defines model for TelegramSent.
type TelegramSent struct {
	ChatId    int64            `json:"chat_id"`
	Kind      TelegramSentKind `json:"kind"`
	MessageId int64            `json:"message_id"`
}

// TelegramSentKind defines model for TelegramSent.Kind.
type TelegramSentKind string

// TrialRequest defines model for TrialRequest.
type TrialRequest struct {
	CreatedAt         time.Time           `json:"created_at"`
	DecidedAt         *time.Time          `json:"decided_at"`
	OperationId       *openapi_types.UUID `json:"operation_id"`
	PreviousRequestId *openapi_types.UUID `json:"previous_request_id"`
	RequestId         openapi_types.UUID  `json:"request_id"`
	Status            TrialRequestStatus  `json:"status"`
}

// TrialRequestStatus defines model for TrialRequest.Status.
type TrialRequestStatus string

// TrialRequestInput defines model for TrialRequestInput.
type TrialRequestInput struct {
	Comment *string `json:"comment,omitempty"`
}

// VerifyInput defines model for VerifyInput.
type VerifyInput struct {
	ChallengeId *openapi_types.UUID `json:"challenge_id,omitempty"`
	Code        *string             `json:"code,omitempty"`
	NewPassword string              `json:"new_password"`
	Token       *string             `json:"token,omitempty"`
	union       json.RawMessage
}

// VerifyInput0 defines model for VerifyInput.0.
type VerifyInput0 = interface{}

// VerifyInput1 defines model for VerifyInput.1.
type VerifyInput1 = interface{}

// VerifyResult defines model for VerifyResult.
type VerifyResult struct {
	Verified VerifyResultVerified `json:"verified"`
}

// VerifyResultVerified defines model for VerifyResult.Verified.
type VerifyResultVerified bool

// ConfirmEmailChangeParams defines parameters for ConfirmEmailChange.
type ConfirmEmailChangeParams struct {
	Origin string `json:"Origin"`
}

// LoginAccountParams defines parameters for LoginAccount.
type LoginAccountParams struct {
	Origin string `json:"Origin"`
}

// LogoutAccountParams defines parameters for LogoutAccount.
type LogoutAccountParams struct {
	Origin     string  `json:"Origin"`
	XCSRFToken *string `json:"X-CSRF-Token,omitempty"`
}

// RequestPasswordResetParams defines parameters for RequestPasswordReset.
type RequestPasswordResetParams struct {
	Origin string `json:"Origin"`
}

// CompletePasswordResetParams defines parameters for CompletePasswordReset.
type CompletePasswordResetParams struct {
	Origin string `json:"Origin"`
}

// RegisterAccountParams defines parameters for RegisterAccount.
type RegisterAccountParams struct {
	Origin string `json:"Origin"`
}

// ResendVerificationParams defines parameters for ResendVerification.
type ResendVerificationParams struct {
	Origin string `json:"Origin"`
}

// VerifyEmailParams defines parameters for VerifyEmail.
type VerifyEmailParams struct {
	Origin string `json:"Origin"`
}

// RequestEmailChangeParams defines parameters for RequestEmailChange.
type RequestEmailChangeParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// CancelEmailChangeParams defines parameters for CancelEmailChange.
type CancelEmailChangeParams struct {
	Origin     string  `json:"Origin"`
	XCSRFToken *string `json:"X-CSRF-Token,omitempty"`
}

// ChangePasswordParams defines parameters for ChangePassword.
type ChangePasswordParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// RevokeOtherSessionsParams defines parameters for RevokeOtherSessions.
type RevokeOtherSessionsParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// SetOperatorSupportBanParams defines parameters for SetOperatorSupportBan.
type SetOperatorSupportBanParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// GetOperatorSupportHistoryParams defines parameters for GetOperatorSupportHistory.
type GetOperatorSupportHistoryParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// CreateOperatorSupportMessageParams defines parameters for CreateOperatorSupportMessage.
type CreateOperatorSupportMessageParams struct {
	Origin         string             `json:"Origin"`
	XCSRFToken     string             `json:"X-CSRF-Token"`
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// AcknowledgeOperatorSupportParams defines parameters for AcknowledgeOperatorSupport.
type AcknowledgeOperatorSupportParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// SetOperatorSupportStateParams defines parameters for SetOperatorSupportState.
type SetOperatorSupportStateParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// GetSupportHistoryParams defines parameters for GetSupportHistory.
type GetSupportHistoryParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// CreateSupportMessageParams defines parameters for CreateSupportMessage.
type CreateSupportMessageParams struct {
	Origin         string             `json:"Origin"`
	XCSRFToken     string             `json:"X-CSRF-Token"`
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// AcknowledgeSupportParams defines parameters for AcknowledgeSupport.
type AcknowledgeSupportParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// SetSupportStateParams defines parameters for SetSupportState.
type SetSupportStateParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// CreateTrialRequestParams defines parameters for CreateTrialRequest.
type CreateTrialRequestParams struct {
	Origin         string             `json:"Origin"`
	XCSRFToken     string             `json:"X-CSRF-Token"`
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// ReconcileTrialOperationParams defines parameters for ReconcileTrialOperation.
type ReconcileTrialOperationParams struct {
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// ReconsiderTrialRequestParams defines parameters for ReconsiderTrialRequest.
type ReconsiderTrialRequestParams struct {
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// ConfirmEmailChangeJSONRequestBody defines body for ConfirmEmailChange for application/json ContentType.
type ConfirmEmailChangeJSONRequestBody = EmailChangeConfirmInput

// LoginAccountJSONRequestBody defines body for LoginAccount for application/json ContentType.
type LoginAccountJSONRequestBody = LoginInput

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody = PasswordResetInput

// CompletePasswordResetJSONRequestBody defines body for CompletePasswordReset for application/json ContentType.
type CompletePasswordResetJSONRequestBody = PasswordResetCompleteInput

// RegisterAccountJSONRequestBody defines body for RegisterAccount for application/json ContentType.
type RegisterAccountJSONRequestBody = RegisterInput

// ResendVerificationJSONRequestBody defines body for ResendVerification for application/json ContentType.
type ResendVerificationJSONRequestBody = ResendInput

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody = VerifyInput

// RequestEmailChangeJSONRequestBody defines body for RequestEmailChange for application/json ContentType.
type RequestEmailChangeJSONRequestBody = EmailChangeInput

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = PasswordChangeInput

// RevokeOtherSessionsJSONRequestBody defines body for RevokeOtherSessions for application/json ContentType.
type RevokeOtherSessionsJSONRequestBody = CurrentPasswordInput

// SetOperatorSupportBanJSONRequestBody defines body for SetOperatorSupportBan for application/json ContentType.
type SetOperatorSupportBanJSONRequestBody = SupportBanInput

// GetOperatorSupportHistoryJSONRequestBody defines body for GetOperatorSupportHistory for application/json ContentType.
type GetOperatorSupportHistoryJSONRequestBody = SupportHistoryInput

// CreateOperatorSupportMessageJSONRequestBody defines body for CreateOperatorSupportMessage for application/json ContentType.
type CreateOperatorSupportMessageJSONRequestBody = SupportMessageInput

// CreateOperatorSupportMessageMultipartRequestBody defines body for CreateOperatorSupportMessage for multipart/form-data ContentType.
type CreateOperatorSupportMessageMultipartRequestBody = SupportMultipartInput

// AcknowledgeOperatorSupportJSONRequestBody defines body for AcknowledgeOperatorSupport for application/json ContentType.
type AcknowledgeOperatorSupportJSONRequestBody = SupportReadInput

// SetOperatorSupportStateJSONRequestBody defines body for SetOperatorSupportState for application/json ContentType.
type SetOperatorSupportStateJSONRequestBody = SupportStateInput

// GetSupportHistoryJSONRequestBody defines body for GetSupportHistory for application/json ContentType.
type GetSupportHistoryJSONRequestBody = SupportHistoryInput

// CreateSupportMessageJSONRequestBody defines body for CreateSupportMessage for application/json ContentType.
type CreateSupportMessageJSONRequestBody = SupportMessageInput

// CreateSupportMessageMultipartRequestBody defines body for CreateSupportMessage for multipart/form-data ContentType.
type CreateSupportMessageMultipartRequestBody = SupportMultipartInput

// AcknowledgeSupportJSONRequestBody defines body for AcknowledgeSupport for application/json ContentType.
type AcknowledgeSupportJSONRequestBody = SupportReadInput

// SetSupportStateJSONRequestBody defines body for SetSupportState for application/json ContentType.
type SetSupportStateJSONRequestBody = SupportStateInput

// CreateTrialRequestJSONRequestBody defines body for CreateTrialRequest for application/json ContentType.
type CreateTrialRequestJSONRequestBody = TrialRequestInput

// ClaimTelegramJobsJSONRequestBody defines body for ClaimTelegramJobs for application/json ContentType.
type ClaimTelegramJobsJSONRequestBody = ClaimInput

// CompleteTelegramJobJSONRequestBody defines body for CompleteTelegramJob for application/json ContentType.
type CompleteTelegramJobJSONRequestBody = TelegramResultInput

// ReconcileTrialOperationJSONRequestBody defines body for ReconcileTrialOperation for application/json ContentType.
type ReconcileTrialOperationJSONRequestBody = ReconcileInput

// DecideTrialRequestJSONRequestBody defines body for DecideTrialRequest for application/json ContentType.
type DecideTrialRequestJSONRequestBody = DecisionInput

// ReconsiderTrialRequestJSONRequestBody defines body for ReconsiderTrialRequest for application/json ContentType.
type ReconsiderTrialRequestJSONRequestBody = ReconsiderInput

// AsEmailChangeConfirmInput0 returns the union data inside the EmailChangeConfirmInput as a EmailChangeConfirmInput0
func (t EmailChangeConfirmInput) AsEmailChangeConfirmInput0() (EmailChangeConfirmInput0, error) {
	var body EmailChangeConfirmInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmailChangeConfirmInput0 overwrites any union data inside the EmailChangeConfirmInput as the provided EmailChangeConfirmInput0
func (t *EmailChangeConfirmInput) FromEmailChangeConfirmInput0(v EmailChangeConfirmInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmailChangeConfirmInput0 performs a merge with any union data inside the EmailChangeConfirmInput, using the provided EmailChangeConfirmInput0
func (t *EmailChangeConfirmInput) MergeEmailChangeConfirmInput0(v EmailChangeConfirmInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmailChangeConfirmInput1 returns the union data inside the EmailChangeConfirmInput as a EmailChangeConfirmInput1
func (t EmailChangeConfirmInput) AsEmailChangeConfirmInput1() (EmailChangeConfirmInput1, error) {
	var body EmailChangeConfirmInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmailChangeConfirmInput1 overwrites any union data inside the EmailChangeConfirmInput as the provided EmailChangeConfirmInput1
func (t *EmailChangeConfirmInput) FromEmailChangeConfirmInput1(v EmailChangeConfirmInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmailChangeConfirmInput1 performs a merge with any union data inside the EmailChangeConfirmInput, using the provided EmailChangeConfirmInput1
func (t *EmailChangeConfirmInput) MergeEmailChangeConfirmInput1(v EmailChangeConfirmInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmailChangeConfirmInput) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.ChallengeId != nil {
		object["challenge_id"], err = json.Marshal(t.ChallengeId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'challenge_id': %w", err)
		}
	}

	if t.Code != nil {
		object["code"], err = json.Marshal(t.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if t.Token != nil {
		object["token"], err = json.Marshal(t.Token)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'token': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *EmailChangeConfirmInput) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["challenge_id"]; found {
		err = json.Unmarshal(raw, &t.ChallengeId)
		if err != nil {
			return fmt.Errorf("error reading 'challenge_id': %w", err)
		}
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &t.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
	}

	if raw, found := object["token"]; found {
		err = json.Unmarshal(raw, &t.Token)
		if err != nil {
			return fmt.Errorf("error reading 'token': %w", err)
		}
	}

	return err
}

// AsPasswordResetCompleteInput0 returns the union data inside the PasswordResetCompleteInput as a PasswordResetCompleteInput0
func (t PasswordResetCompleteInput) AsPasswordResetCompleteInput0() (PasswordResetCompleteInput0, error) {
	var body PasswordResetCompleteInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPasswordResetCompleteInput0 overwrites any union data inside the PasswordResetCompleteInput as the provided PasswordResetCompleteInput0
func (t *PasswordResetCompleteInput) FromPasswordResetCompleteInput0(v PasswordResetCompleteInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePasswordResetCompleteInput0 performs a merge with any union data inside the PasswordResetCompleteInput, using the provided PasswordResetCompleteInput0
func (t *PasswordResetCompleteInput) MergePasswordResetCompleteInput0(v PasswordResetCompleteInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPasswordResetCompleteInput1 returns the union data inside the PasswordResetCompleteInput as a PasswordResetCompleteInput1
func (t PasswordResetCompleteInput) AsPasswordResetCompleteInput1() (PasswordResetCompleteInput1, error) {
	var body PasswordResetCompleteInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPasswordResetCompleteInput1 overwrites any union data inside the PasswordResetCompleteInput as the provided PasswordResetCompleteInput1
func (t *PasswordResetCompleteInput) FromPasswordResetCompleteInput1(v PasswordResetCompleteInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePasswordResetCompleteInput1 performs a merge with any union data inside the PasswordResetCompleteInput, using the provided PasswordResetCompleteInput1
func (t *PasswordResetCompleteInput) MergePasswordResetCompleteInput1(v PasswordResetCompleteInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PasswordResetCompleteInput) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.ChallengeId != nil {
		object["challenge_id"], err = json.Marshal(t.ChallengeId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'challenge_id': %w", err)
		}
	}

	if t.Code != nil {
		object["code"], err = json.Marshal(t.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	object["new_password"], err = json.Marshal(t.NewPassword)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'new_password': %w", err)
	}

	if t.Token != nil {
		object["token"], err = json.Marshal(t.Token)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'token': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *PasswordResetCompleteInput) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["challenge_id"]; found {
		err = json.Unmarshal(raw, &t.ChallengeId)
		if err != nil {
			return fmt.Errorf("error reading 'challenge_id': %w", err)
		}
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &t.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
	}

	if raw, found := object["new_password"]; found {
		err = json.Unmarshal(raw, &t.NewPassword)
		if err != nil {
			return fmt.Errorf("error reading 'new_password': %w", err)
		}
	}

	if raw, found := object["token"]; found {
		err = json.Unmarshal(raw, &t.Token)
		if err != nil {
			return fmt.Errorf("error reading 'token': %w", err)
		}
	}

	return err
}

// AsTelegramSent returns the union data inside the TelegramResult as a TelegramSent
func (t TelegramResult) AsTelegramSent() (TelegramSent, error) {
	var body TelegramSent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTelegramSent overwrites any union data inside the TelegramResult as the provided TelegramSent
func (t *TelegramResult) FromTelegramSent(v TelegramSent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"sent"}`))
	t.union = b
	return err
}

// MergeTelegramSent performs a merge with any union data inside the TelegramResult, using the provided TelegramSent
func (t *TelegramResult) MergeTelegramSent(v TelegramSent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"sent"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTelegramFailed returns the union data inside the TelegramResult as a TelegramFailed
func (t TelegramResult) AsTelegramFailed() (TelegramFailed, error) {
	var body TelegramFailed
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTelegramFailed overwrites any union data inside the TelegramResult as the provided TelegramFailed
func (t *TelegramResult) FromTelegramFailed(v TelegramFailed) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"delivery_failed"}`))
	t.union = b
	return err
}

// MergeTelegramFailed performs a merge with any union data inside the TelegramResult, using the provided TelegramFailed
func (t *TelegramResult) MergeTelegramFailed(v TelegramFailed) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"delivery_failed"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t TelegramResult) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t TelegramResult) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "delivery_failed":
		return t.AsTelegramFailed()
	case "sent":
		return t.AsTelegramSent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t TelegramResult) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *TelegramResult) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsVerifyInput0 returns the union data inside the VerifyInput as a VerifyInput0
func (t VerifyInput) AsVerifyInput0() (VerifyInput0, error) {
	var body VerifyInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVerifyInput0 overwrites any union data inside the VerifyInput as the provided VerifyInput0
func (t *VerifyInput) FromVerifyInput0(v VerifyInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVerifyInput0 performs a merge with any union data inside the VerifyInput, using the provided VerifyInput0
func (t *VerifyInput) MergeVerifyInput0(v VerifyInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsVerifyInput1 returns the union data inside the VerifyInput as a VerifyInput1
func (t VerifyInput) AsVerifyInput1() (VerifyInput1, error) {
	var body VerifyInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVerifyInput1 overwrites any union data inside the VerifyInput as the provided VerifyInput1
func (t *VerifyInput) FromVerifyInput1(v VerifyInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVerifyInput1 performs a merge with any union data inside the VerifyInput, using the provided VerifyInput1
func (t *VerifyInput) MergeVerifyInput1(v VerifyInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t VerifyInput) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.ChallengeId != nil {
		object["challenge_id"], err = json.Marshal(t.ChallengeId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'challenge_id': %w", err)
		}
	}

	if t.Code != nil {
		object["code"], err = json.Marshal(t.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	object["new_password"], err = json.Marshal(t.NewPassword)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'new_password': %w", err)
	}

	if t.Token != nil {
		object["token"], err = json.Marshal(t.Token)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'token': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *VerifyInput) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["challenge_id"]; found {
		err = json.Unmarshal(raw, &t.ChallengeId)
		if err != nil {
			return fmt.Errorf("error reading 'challenge_id': %w", err)
		}
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &t.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
	}

	if raw, found := object["new_password"]; found {
		err = json.Unmarshal(raw, &t.NewPassword)
		if err != nil {
			return fmt.Errorf("error reading 'new_password': %w", err)
		}
	}

	if raw, found := object["token"]; found {
		err = json.Unmarshal(raw, &t.Token)
		if err != nil {
			return fmt.Errorf("error reading 'token': %w", err)
		}
	}

	return err
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F3dctu4kn4VFvfcLRXZ+Zmd47lSZM0ezTi2V3JSO5XysiCyLSMmAQ4AOtG69O6nAIIU/yRRtC3aEa4S",
	"UwS6ATS+r9FoEA+2R8OIEiCC2ycPNvduIUTqv4PL8YgxyuT/ke9jgSlBwSWjETCBgdsnNyjg4NhR7tGD",
	"DWmZfzC4sU/s/+ivJPR19X1V8UfqL+zl0rEZ/B1jBr598lUXv3ZssYjAPrHp7Bt4wl469sDzaEzEjuqg",
	"pJSLffnXDWUhEvaJHcfYtzMhXDBM5lIIhAgHhTeTJ+tede+B4RsMqnb9yozSABCR7wTUQwHI34DEoWwf",
	"i23HBmJf19QoIIA5Q6EbYHIHfq6Yatq1U5FQ6rxcY51M8ZKemVJVeRt6fQI8Dlr2/TZjSAd26dgeitAM",
	"BzitYVOxYf5dWZazG1fQOyC5sUg7t76j7EKpkvgNvTEFL2ZYLHadGmuNK0Q/zoDMxa198vbD+xrTuEXc",
	"peIWmMuBc0wJrze4CIiPydxNBt27RWSuzA8FwcWNffJ1c5deJqVHsvAwKbu8dmwSBwGaSTsWLIbKjNVt",
	"qFFxjT51PTssjfwO3SoYRoGL7hHWWj5smyflErUKBQiHYxLFu1p9gEMscnP3eFU7JgLmwCr6JEXWatFq",
	"8n2jM/UvFhBunUtXGgn+oDMpNUQ/xkmx40wnxBiqwrWSUqs4DaMABDTUvVo+ZgyIuEScf6fMbzMQXlKF",
	"G+k65LPcRDt++6tjh5hkf39wtqBGpcLr9YpfSRObwN8x8F31ZrlSjaZtQdb2CZvWX6f9KXhYzt1W/Y2C",
	"YIa8O/fvGNjCxVs7vAbnfC0/T5koihi9B1u2QulZx51SESQoc8W8zPWYiF/e20o0DuMwLzibkLJuxCkp",
	"q3x0dLTNKkqSc21warpkU6e3muceSiy7yfS+RIuAIj/p6ADfS524QKLgoWjIth2bg6LIG4SDgndQ7nVM",
	"yRr/qmiINRXkbL25ha+x55I6TtI1labWjUCO8QaeB5EAf9dhUIUbu5k/IsyAu0gUXveRgJ7AIdi1XcWB",
	"+C66EaD8603mXAauTLmC6FKdWzpmSMkNZg0pkRLQwEVo8jZZ6AcFxagP9vXSeSirGwSgNb5eXpfZW3lr",
	"qpSuvPbX9VU6qdzrmlFcvdZkIFVFJw92hIQARuwT+/++HvX+ef3w6/Ifde9n/mkOZN6/K8Di+3eVcsvN",
	"I9MNOTo2ge9ua592G7fmq99ime1wUzsofgN/cfVurSbZYnZXDfwC8I7PvwzOxqfu+Pzy85XtZH8PJ6PT",
	"0fnVeHA2tR179GkwPnO/jCbj38fDwdX44tydjP7n83gyOrUdezAcXnw+v3Ino+nVZDy8Ug+vJuPBmXs6",
	"ng4+nuUeDM4mo8HpX+7nae7hZDS8OJ+OT0eTSt3yv6PplTu9GlyN3OHF+e9n46FU9OIyffv8QooenP4l",
	"1T8dfbq8uBqdD//KvzyRhc/Gn8aJbtPR5Mt4OHI/nw++DMZnUsNapkntQ4O9wvKY1/OWdhj8zGNYw14h",
	"cI7mULNcfDpmawYkFXvzwV7pV6iszgLP6By3ctkesSJ9Mq86lbjRq1Yt3FcQ4rGBhLoGpAuZ7hH7+ZZD",
	"pfo3dcMEOIj2rtZuJF32nNavDI6auFJ5R2KrA1VocLooNj7UY3yoxxnxI3ywfGfsZul7xuZdws5r0FhX",
	"UduyapSwHZLpoGCyrlgXQm+zVHqUY5orvlm3GotIRRQWWeuaWy+orscn4FHi4aAVbzxnZGRjNGdbnETX",
	"u7HBrSh/m+9WGfBNzqR0JVV0JvmTAPjcZXCP4Xviaga41r2sbX0WmtAS17adYx/Y4Yz2HHPRrr1I+xBu",
	"xPA98hZyo4vjSgN+PaoZ9qysABbyXUq+CGxe2wBnfa+s7/7EOg/BJZuoF1q29CkVb6jpXp2HWpOr022a",
	"bPINKRHwY+e1zA5LrC0Lq2k84x7DkdBTd0fs4NyNGL3BpSkJ8zhAzHZsiNX0jInao1OsPUOEqP/E5I7Q",
	"7/V7+R4lBDwF+Bt3Jh3pySAZzlj7O9xjD3hhMJsYWyPXaWsYg844sHvwH1VJhAgEbpYZkvZyTFZd49jY",
	"ByKwWLgh5iES3u2qh90Qwhkwfosj+SK5RwH2XcHQzQ32bEfKv26gRpXmCSWwneM9gdX2U9KfBRPwMZci",
	"k8D6LYr5uliTVtb16Xci92Dc2UI0GNQ1bcoNclqxss+Gta6vhckJL7vhyfWLo2dpdszh6SrNZrmbm3TV",
	"Gbl6LTXB7asDbXulpUEqpn4Ya1tZnJIF+NgGj3/CriFqnivtxqzIKDHDWyOZlQrqdYwiysRACOTdhrBz",
	"jhdBIbTYa+b4/2GT6aAf2k0+ev/rh//65cjZZctN6VSQsaHlH1Gr6K1GoVobfSI3PgO6De67bsSQEull",
	"ohZE7DFAYjPH1GwIcEFDYC4DD7CcDlwGyYkHLeCvodeaLWqeQmaVjWiUZKEFlK9hEZ50tbtp5OPI37Ez",
	"S2OeX6BWRDr5wSoI2zgkG/tug1H9C3NB2aLV7IAbyqDhCG2f0OXqNij9abWvtIs3WoS/Rpk/VeSsSf9x",
	"Ws2vNGsib6ByLCCXUrHGSptGXYD4UHAIUwPKmUv9NGg7po6dLlbysd8GST7JnFhZs9Zd11eaFLmRzPXj",
	"doNpY+Vr27MLyqtKNukXBwJHiLWKY6drq2ygZpggtrBrE6BbDc429SeAWi2iW4N72QlqgBktcxhKlLsL",
	"aBT4uhY2ZEZvSNmadanenW6eZFpCx0Ke6YejcqKpY9PAVzv9TSf7Nv++ssmea3+uObl2V3XYMIJTgUSr",
	"Kby7I1C/tqjTLc38+z3J4XtcgoqkChoLtUIW3ym7sx05IjPs+0pf8LFwdbbgapnOgEeUcKhF8jtM8ucc",
	"Vrl6a5MOS21XFaSbkRs6QGY27xzTFO1C6N/orGkctNz+JHUFBa7OXUwTP3zwsK+6NYtVrAIUq0frtyMc",
	"OwDEwW2znZaUXBeuc+xIp5XumoVazSVPIrh5eTV6O9nQOOnwpxpssoDLlZa7pYmlLtm2vOB2ftYOJ472",
	"m5O0eVusLsdq50BabaAMsTkIV8Nxkwm4I+7nOqGSMVwVvjpHlVpCydlrAL4rbvcx9xgOMVGurbKpKJIN",
	"P3moQN+WWfR7irMqS3vLy1NIUpu0bS/OVcQkmT3LfKZJk/mrK2v2slZTJaAU+6PV2ZotSMSynm6imx6X",
	"ymmcAvzoKjeN73T3kFV7cikzhhr+DdmNbaSs4dgMdXNV1/ZL+7Mv7Vaqihsft83xWGiNJMrRmLubMbZr",
	"iN7qTxXQMQsCFRAv198VAK3rhm0m0ioZsjkt1yXPfwGGbxYmDe/nT8NLRrrV6jp/tFvPLjlptx/DzgpW",
	"FVLBq+Tw8FSyUXrYFUUC2EdALAmI+ZDb07ZPwceenH/WjIqeftnyGKgdUxS8sc6pld9p6d3Bwkp2t9/I",
	"aawkSYUTAZlWt0JESTxN7+XTO6xsAEuxXvKno/dXbNf9F+Wip19e1YIiLHeWlrJxmNxQWYHAQoKcPUQz",
	"TEBY06Nja3A5th07y7Kxj98cvTnS4EtQhO0T+92bozfvlD8vblXP9FGE+/fHfRSL277yxHrJYaa+zphT",
	"Fku5qPba52Tv2FJH76wIMRSCAMYtRHzrj+nFuXWDIfC5hRhYKUC+SX6ZUX9h6Q0g6/gX60/88U0e7Ma+",
	"bFuiQT4P0rFXchRCqI68BZQEC3VHXjA8x8TOG03CBomD0mCT7TojivTciUeJSN0QuQj0lJ79b3oTaFXz",
	"xs8yrDnttVwuy8qqB8nCXg3U26Oj51Ajc9GWTml4p7Gyb2k/759QdvbVizqR6AasJItBST3uROq7TqS+",
	"70TqP7uQ+nbvUh0NEWomTUCwRW+QJpiVCoFHic+tZDfKYvJduxY4Gvn5UqsPHVhUjgbtk6/X8u8C0gdU",
	"AmR30K6OGw2ysz2vGtRzh8P2jOP5Q1sGwQ2CGwQ/KASnsegWwmks9o3hzpqa/7c3nE5+713poOKqvloS",
	"KODx+xobMshpkNMg58+AnA/l4MvX62UVTdMQV48Bhy5RVYdsC4dbX7uDXHNSt5Gj/PZ5NMgOJhmX2QC/",
	"Af7DcZmLIN9PPzrUaYQ7UeHnhfviFzkawb7xxw0sG1g+HFhm+usEnXrdiQo/SUS6+L2HPfvatV87MK62",
	"wXSD6YeE6RyI30sSdbzs/Exn8C61+ZJX5tUj/OrDJXvH98LXXQyyG2Q3yH44yJ5mJ5482HPoAsz/G0Tp",
	"00jPmGFRkmTAzoCdAbvD3ipUPu2ilx0r7MinTfLuR9m3vV+xM5s/LLLnDLrC6QWD7gbdDbofhCsbQqcO",
	"7CrO/GzIVrxX0kCbgTYDbQfruIZQONvXfX5bF2f6GqYOr69/t3O0z3+EsJPwb91NfoZdDLsYdjHskp4c",
	"R8SDLmMjQ6XAC+YYczzFgKsBVwOuzcA1y1vu3HtP0PRydR+h8dx3z4ve2Xk3DGAYwDDAITPA6vXug9bT",
	"VJfnD15nokyAwSCgQcDDRkD1Bu8zuKd30KPiVvdXZ4FsqceFVEMniXHjD+9kLMPk2t7ULTYOsaEDQweG",
	"DrbTQXp1Ud8LsJL3gP1lX9+j1cxF7iuM1xSwgn+N5D0fmLxBy0KeoOw3KxVoMRoL4JbGJyv9Dq0FRH2P",
	"NQQiNIeoawaPf/kTf/zNCtPbffTTo0/443+q3xyLErBucADqoWPl70yx/o6pQB/kD/IDtD11OVStZ36h",
	"9dMXpazhIfnN1xVXYL8hA9V+zbgmTv2ESdeFG3uM72/Afm9Sj98ZijEUs4Vi+jPU9DTjT8Qz0wrPfERk",
	"H1TjvNx11J5WSuVbbM0iyfCm4U3Dm6+NN2+Ty4YPjzurazR977Lhzz3yZ+Gu6z0fNDNrWsPNhpsNN79Y",
	"bs7fNn1Y5DxUd++V+Dm9RNvwc5MKxz6EERVAvEVPXlX26Mjys/kAelxTH8CxM9vqS8V6PhJo90qL1/d3",
	"41pk175XQWP0A3OBydzC6TgJS1+7unTst0fHe9RliiQuYGLNkHcHxP/NYuDhCEud0ht6LXWvsQU/pBpY",
	"WMiTyBOAP1cIYXwk4yMZH8n4SHv3kRgg//D8o8EKfTvYaDbRiyx0gEyOlKFPQ5+GPl8pfXKBBBwef1Y3",
	"zqeqIwx57o88VY8b9jTsadjTsOdLZU8ez3I1dfl95bwizxq5zMkxe6IGcg34GfCTGt3B4sUAYLqftQcM",
	"lKI2wGDBhIbIu4We/DA9o0G1l87hHpjlyZcsj4EPRGAU8IIdAZE289UmeuliX1f9/KXBXoO9Bnt/duw9",
	"2KNzq50Mk/pnoNZEFgzA/8QAf9AJ+I0S702OvMmRN0RpiNIQ5WET5aFnwzfKgjcJ6yZh3SSsm4R147AY",
	"h8U4LC/DYUky7pAQyLsNgRxyTHew6oQX90E06gkQPS4YoLBoQ5mcGSaILWokVcznkuF7JMBajbrl0+8k",
	"oMj/zSLUwiTARM4IIgeSzEsbiYmGvVPMI8pxmnyy3qcyW4KGzQybGTZ7RjY7+INWmw9YmbNQ5iyU4TLD",
	"ZYbLXgGXHe6ppwannczBJHMwyVCZoTJDZS+ZygTDKOhpFOzy0p1kc/JKqqMvkjdbkx1sTeYHoJMdxIIF",
	"NN4/1K8/7QbiNlUMOxt2Njx5iDzZ95ILzjo9yaYvWStR5rMBc504A4oGFA0oHh4oSk0ZQYFCRghgzlDY",
	"/0ZnvO8FCIddLiOk/Cut0h90xu1nuuFSyunEQVaSTSK9wV+Dvz89/iIfRQLYR0AMWCP8VTliOp+2QxSm",
	"YRSAgBwQ7y1R6xliIroVCeh2A/q6Qw3uG9w3uG9wP4tIZLibQb9HiYcD6PT+fK2DihVcpL91+VXMVxB5",
	"z3ptB4J5+/TSDcMYhjEMYximGvNW/OKDh7k+R9ARvZyCh/0mO8WvYW1xqvuzk1VFKtxgvsF8g/kG89dg",
	"vlpTcOwD6xD1J5kS+0b+176mUJ22A7+YBBrDLoZdDLs8Bbssl/8eAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
