// Package wire provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package wire

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AccountLocale.
const (
	AccountLocaleEn AccountLocale = "en"
	AccountLocaleRu AccountLocale = "ru"
)

// Valid indicates whether the value is a known member of the AccountLocale enum.
func (e AccountLocale) Valid() bool {
	switch e {
	case AccountLocaleEn:
		return true
	case AccountLocaleRu:
		return true
	default:
		return false
	}
}

// Defines values for AccountTelegramLinked.
const (
	False AccountTelegramLinked = false
)

// Valid indicates whether the value is a known member of the AccountTelegramLinked enum.
func (e AccountTelegramLinked) Valid() bool {
	switch e {
	case False:
		return true
	default:
		return false
	}
}

// Defines values for CataloguePlanSnapshotProfile.
const (
	CataloguePlanSnapshotProfileEuru      CataloguePlanSnapshotProfile = "euru"
	CataloguePlanSnapshotProfileRegular   CataloguePlanSnapshotProfile = "regular"
	CataloguePlanSnapshotProfileUnlimited CataloguePlanSnapshotProfile = "unlimited"
)

// Valid indicates whether the value is a known member of the CataloguePlanSnapshotProfile enum.
func (e CataloguePlanSnapshotProfile) Valid() bool {
	switch e {
	case CataloguePlanSnapshotProfileEuru:
		return true
	case CataloguePlanSnapshotProfileRegular:
		return true
	case CataloguePlanSnapshotProfileUnlimited:
		return true
	default:
		return false
	}
}

// Defines values for CataloguePriceCurrency.
const (
	RUB CataloguePriceCurrency = "RUB"
	USD CataloguePriceCurrency = "USD"
	XTR CataloguePriceCurrency = "XTR"
)

// Valid indicates whether the value is a known member of the CataloguePriceCurrency enum.
func (e CataloguePriceCurrency) Valid() bool {
	switch e {
	case RUB:
		return true
	case USD:
		return true
	case XTR:
		return true
	default:
		return false
	}
}

// Defines values for CatalogueTermsProfile.
const (
	CatalogueTermsProfileEuru      CatalogueTermsProfile = "euru"
	CatalogueTermsProfileRegular   CatalogueTermsProfile = "regular"
	CatalogueTermsProfileUnlimited CatalogueTermsProfile = "unlimited"
)

// Valid indicates whether the value is a known member of the CatalogueTermsProfile enum.
func (e CatalogueTermsProfile) Valid() bool {
	switch e {
	case CatalogueTermsProfileEuru:
		return true
	case CatalogueTermsProfileRegular:
		return true
	case CatalogueTermsProfileUnlimited:
		return true
	default:
		return false
	}
}

// Defines values for ClaimInputLimit.
const (
	N1 ClaimInputLimit = 1
)

// Valid indicates whether the value is a known member of the ClaimInputLimit enum.
func (e ClaimInputLimit) Valid() bool {
	switch e {
	case N1:
		return true
	default:
		return false
	}
}

// Defines values for DecisionInputDecision.
const (
	DecisionInputDecisionApprove DecisionInputDecision = "approve"
	DecisionInputDecisionReject  DecisionInputDecision = "reject"
)

// Valid indicates whether the value is a known member of the DecisionInputDecision enum.
func (e DecisionInputDecision) Valid() bool {
	switch e {
	case DecisionInputDecisionApprove:
		return true
	case DecisionInputDecisionReject:
		return true
	default:
		return false
	}
}

// Defines values for DecisionResultDeliveryState.
const (
	DecisionResultDeliveryStateFailed  DecisionResultDeliveryState = "failed"
	DecisionResultDeliveryStatePending DecisionResultDeliveryState = "pending"
	DecisionResultDeliveryStateSent    DecisionResultDeliveryState = "sent"
)

// Valid indicates whether the value is a known member of the DecisionResultDeliveryState enum.
func (e DecisionResultDeliveryState) Valid() bool {
	switch e {
	case DecisionResultDeliveryStateFailed:
		return true
	case DecisionResultDeliveryStatePending:
		return true
	case DecisionResultDeliveryStateSent:
		return true
	default:
		return false
	}
}

// Defines values for ErrorBodyCode.
const (
	ACCOUNTRESTRICTED            ErrorBodyCode = "ACCOUNT_RESTRICTED"
	CATALOGUEDEVICESCONFLICT     ErrorBodyCode = "CATALOGUE_DEVICES_CONFLICT"
	CATALOGUELASTVISIBLE         ErrorBodyCode = "CATALOGUE_LAST_VISIBLE"
	CATALOGUEREVISIONCONFLICT    ErrorBodyCode = "CATALOGUE_REVISION_CONFLICT"
	EMAILVERIFICATIONREQUIRED    ErrorBodyCode = "EMAIL_VERIFICATION_REQUIRED"
	IDEMPOTENCYCONFLICT          ErrorBodyCode = "IDEMPOTENCY_CONFLICT"
	INVALIDCREDENTIALS           ErrorBodyCode = "INVALID_CREDENTIALS"
	INVALIDINPUT                 ErrorBodyCode = "INVALID_INPUT"
	OPERATIONNOTREADY            ErrorBodyCode = "OPERATION_NOT_READY"
	OPERATORACCOUNTPROTECTED     ErrorBodyCode = "OPERATOR_ACCOUNT_PROTECTED"
	RATELIMITED                  ErrorBodyCode = "RATE_LIMITED"
	REQUESTSTATECONFLICT         ErrorBodyCode = "REQUEST_STATE_CONFLICT"
	SERVICEUNAVAILABLE           ErrorBodyCode = "SERVICE_UNAVAILABLE"
	TRIALALREADYUSED             ErrorBodyCode = "TRIAL_ALREADY_USED"
	TRIALDISABLED                ErrorBodyCode = "TRIAL_DISABLED"
	TRIALRECONSIDERATIONREQUIRED ErrorBodyCode = "TRIAL_RECONSIDERATION_REQUIRED"
)

// Valid indicates whether the value is a known member of the ErrorBodyCode enum.
func (e ErrorBodyCode) Valid() bool {
	switch e {
	case ACCOUNTRESTRICTED:
		return true
	case CATALOGUEDEVICESCONFLICT:
		return true
	case CATALOGUELASTVISIBLE:
		return true
	case CATALOGUEREVISIONCONFLICT:
		return true
	case EMAILVERIFICATIONREQUIRED:
		return true
	case IDEMPOTENCYCONFLICT:
		return true
	case INVALIDCREDENTIALS:
		return true
	case INVALIDINPUT:
		return true
	case OPERATIONNOTREADY:
		return true
	case OPERATORACCOUNTPROTECTED:
		return true
	case RATELIMITED:
		return true
	case REQUESTSTATECONFLICT:
		return true
	case SERVICEUNAVAILABLE:
		return true
	case TRIALALREADYUSED:
		return true
	case TRIALDISABLED:
		return true
	case TRIALRECONSIDERATIONREQUIRED:
		return true
	default:
		return false
	}
}

// Defines values for ErrorBodyCurrentRequestStatus.
const (
	ErrorBodyCurrentRequestStatusApproved ErrorBodyCurrentRequestStatus = "approved"
	ErrorBodyCurrentRequestStatusPending  ErrorBodyCurrentRequestStatus = "pending"
	ErrorBodyCurrentRequestStatusRejected ErrorBodyCurrentRequestStatus = "rejected"
)

// Valid indicates whether the value is a known member of the ErrorBodyCurrentRequestStatus enum.
func (e ErrorBodyCurrentRequestStatus) Valid() bool {
	switch e {
	case ErrorBodyCurrentRequestStatusApproved:
		return true
	case ErrorBodyCurrentRequestStatusPending:
		return true
	case ErrorBodyCurrentRequestStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for OperatorCataloguePlanProfile.
const (
	OperatorCataloguePlanProfileEuru      OperatorCataloguePlanProfile = "euru"
	OperatorCataloguePlanProfileRegular   OperatorCataloguePlanProfile = "regular"
	OperatorCataloguePlanProfileUnlimited OperatorCataloguePlanProfile = "unlimited"
)

// Valid indicates whether the value is a known member of the OperatorCataloguePlanProfile enum.
func (e OperatorCataloguePlanProfile) Valid() bool {
	switch e {
	case OperatorCataloguePlanProfileEuru:
		return true
	case OperatorCataloguePlanProfileRegular:
		return true
	case OperatorCataloguePlanProfileUnlimited:
		return true
	default:
		return false
	}
}

// Defines values for OperatorCataloguePlanSource.
const (
	OperatorCataloguePlanSourceLegacyImport  OperatorCataloguePlanSource = "legacy_import"
	OperatorCataloguePlanSourceOperator      OperatorCataloguePlanSource = "operator"
	OperatorCataloguePlanSourceUnlimitedSeed OperatorCataloguePlanSource = "unlimited_seed"
)

// Valid indicates whether the value is a known member of the OperatorCataloguePlanSource enum.
func (e OperatorCataloguePlanSource) Valid() bool {
	switch e {
	case OperatorCataloguePlanSourceLegacyImport:
		return true
	case OperatorCataloguePlanSourceOperator:
		return true
	case OperatorCataloguePlanSourceUnlimitedSeed:
		return true
	default:
		return false
	}
}

// Defines values for OperatorClientKind.
const (
	Telegram OperatorClientKind = "telegram"
	Web      OperatorClientKind = "web"
)

// Valid indicates whether the value is a known member of the OperatorClientKind enum.
func (e OperatorClientKind) Valid() bool {
	switch e {
	case Telegram:
		return true
	case Web:
		return true
	default:
		return false
	}
}

// Defines values for OperatorClientLocale.
const (
	OperatorClientLocaleEn OperatorClientLocale = "en"
	OperatorClientLocaleRu OperatorClientLocale = "ru"
)

// Valid indicates whether the value is a known member of the OperatorClientLocale enum.
func (e OperatorClientLocale) Valid() bool {
	switch e {
	case OperatorClientLocaleEn:
		return true
	case OperatorClientLocaleRu:
		return true
	default:
		return false
	}
}

// Defines values for OperatorDecisionInputDecision.
const (
	OperatorDecisionInputDecisionApprove OperatorDecisionInputDecision = "approve"
	OperatorDecisionInputDecisionReject  OperatorDecisionInputDecision = "reject"
)

// Valid indicates whether the value is a known member of the OperatorDecisionInputDecision enum.
func (e OperatorDecisionInputDecision) Valid() bool {
	switch e {
	case OperatorDecisionInputDecisionApprove:
		return true
	case OperatorDecisionInputDecisionReject:
		return true
	default:
		return false
	}
}

// Defines values for OperatorHistoryInputKind.
const (
	OperatorHistoryInputKindAudit  OperatorHistoryInputKind = "audit"
	OperatorHistoryInputKindLegacy OperatorHistoryInputKind = "legacy"
	OperatorHistoryInputKindTrials OperatorHistoryInputKind = "trials"
)

// Valid indicates whether the value is a known member of the OperatorHistoryInputKind enum.
func (e OperatorHistoryInputKind) Valid() bool {
	switch e {
	case OperatorHistoryInputKindAudit:
		return true
	case OperatorHistoryInputKindLegacy:
		return true
	case OperatorHistoryInputKindTrials:
		return true
	default:
		return false
	}
}

// Defines values for OperatorHistoryResultKind.
const (
	OperatorHistoryResultKindAudit  OperatorHistoryResultKind = "audit"
	OperatorHistoryResultKindLegacy OperatorHistoryResultKind = "legacy"
	OperatorHistoryResultKindTrials OperatorHistoryResultKind = "trials"
)

// Valid indicates whether the value is a known member of the OperatorHistoryResultKind enum.
func (e OperatorHistoryResultKind) Valid() bool {
	switch e {
	case OperatorHistoryResultKindAudit:
		return true
	case OperatorHistoryResultKindLegacy:
		return true
	case OperatorHistoryResultKindTrials:
		return true
	default:
		return false
	}
}

// Defines values for OperatorLegacyApprovalStatus.
const (
	OperatorLegacyApprovalStatusApproved OperatorLegacyApprovalStatus = "approved"
	OperatorLegacyApprovalStatusPending  OperatorLegacyApprovalStatus = "pending"
	OperatorLegacyApprovalStatusRejected OperatorLegacyApprovalStatus = "rejected"
)

// Valid indicates whether the value is a known member of the OperatorLegacyApprovalStatus enum.
func (e OperatorLegacyApprovalStatus) Valid() bool {
	switch e {
	case OperatorLegacyApprovalStatusApproved:
		return true
	case OperatorLegacyApprovalStatusPending:
		return true
	case OperatorLegacyApprovalStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for OperatorLegacyApprovalEventAction.
const (
	ApprovalApprove OperatorLegacyApprovalEventAction = "approval.approve"
	ApprovalReject  OperatorLegacyApprovalEventAction = "approval.reject"
)

// Valid indicates whether the value is a known member of the OperatorLegacyApprovalEventAction enum.
func (e OperatorLegacyApprovalEventAction) Valid() bool {
	switch e {
	case ApprovalApprove:
		return true
	case ApprovalReject:
		return true
	default:
		return false
	}
}

// Defines values for OperatorOperationStatus.
const (
	OperatorOperationStatusApplied      OperatorOperationStatus = "applied"
	OperatorOperationStatusNeedsReview  OperatorOperationStatus = "needs_review"
	OperatorOperationStatusPending      OperatorOperationStatus = "pending"
	OperatorOperationStatusProvisioning OperatorOperationStatus = "provisioning"
)

// Valid indicates whether the value is a known member of the OperatorOperationStatus enum.
func (e OperatorOperationStatus) Valid() bool {
	switch e {
	case OperatorOperationStatusApplied:
		return true
	case OperatorOperationStatusNeedsReview:
		return true
	case OperatorOperationStatusPending:
		return true
	case OperatorOperationStatusProvisioning:
		return true
	default:
		return false
	}
}

// Defines values for OperatorTelegramTrialInputLocale.
const (
	OperatorTelegramTrialInputLocaleEn OperatorTelegramTrialInputLocale = "en"
	OperatorTelegramTrialInputLocaleRu OperatorTelegramTrialInputLocale = "ru"
)

// Valid indicates whether the value is a known member of the OperatorTelegramTrialInputLocale enum.
func (e OperatorTelegramTrialInputLocale) Valid() bool {
	switch e {
	case OperatorTelegramTrialInputLocaleEn:
		return true
	case OperatorTelegramTrialInputLocaleRu:
		return true
	default:
		return false
	}
}

// Defines values for OperatorTrialRequestStatus.
const (
	OperatorTrialRequestStatusApproved OperatorTrialRequestStatus = "approved"
	OperatorTrialRequestStatusPending  OperatorTrialRequestStatus = "pending"
	OperatorTrialRequestStatusRejected OperatorTrialRequestStatus = "rejected"
)

// Valid indicates whether the value is a known member of the OperatorTrialRequestStatus enum.
func (e OperatorTrialRequestStatus) Valid() bool {
	switch e {
	case OperatorTrialRequestStatusApproved:
		return true
	case OperatorTrialRequestStatusPending:
		return true
	case OperatorTrialRequestStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for PasswordResetInputLocale.
const (
	PasswordResetInputLocaleEn PasswordResetInputLocale = "en"
	PasswordResetInputLocaleRu PasswordResetInputLocale = "ru"
)

// Valid indicates whether the value is a known member of the PasswordResetInputLocale enum.
func (e PasswordResetInputLocale) Valid() bool {
	switch e {
	case PasswordResetInputLocaleEn:
		return true
	case PasswordResetInputLocaleRu:
		return true
	default:
		return false
	}
}

// Defines values for ReconcileResultStatus.
const (
	ReconcileResultStatusApplied      ReconcileResultStatus = "applied"
	ReconcileResultStatusNeedsReview  ReconcileResultStatus = "needs_review"
	ReconcileResultStatusPending      ReconcileResultStatus = "pending"
	ReconcileResultStatusProvisioning ReconcileResultStatus = "provisioning"
)

// Valid indicates whether the value is a known member of the ReconcileResultStatus enum.
func (e ReconcileResultStatus) Valid() bool {
	switch e {
	case ReconcileResultStatusApplied:
		return true
	case ReconcileResultStatusNeedsReview:
		return true
	case ReconcileResultStatusPending:
		return true
	case ReconcileResultStatusProvisioning:
		return true
	default:
		return false
	}
}

// Defines values for RegisterInputLocale.
const (
	RegisterInputLocaleEn RegisterInputLocale = "en"
	RegisterInputLocaleRu RegisterInputLocale = "ru"
)

// Valid indicates whether the value is a known member of the RegisterInputLocale enum.
func (e RegisterInputLocale) Valid() bool {
	switch e {
	case RegisterInputLocaleEn:
		return true
	case RegisterInputLocaleRu:
		return true
	default:
		return false
	}
}

// Defines values for SubscriptionAccessProfile.
const (
	SubscriptionAccessProfileBanned    SubscriptionAccessProfile = "banned"
	SubscriptionAccessProfileEuru      SubscriptionAccessProfile = "euru"
	SubscriptionAccessProfileRegular   SubscriptionAccessProfile = "regular"
	SubscriptionAccessProfileUnknown   SubscriptionAccessProfile = "unknown"
	SubscriptionAccessProfileUnlimited SubscriptionAccessProfile = "unlimited"
)

// Valid indicates whether the value is a known member of the SubscriptionAccessProfile enum.
func (e SubscriptionAccessProfile) Valid() bool {
	switch e {
	case SubscriptionAccessProfileBanned:
		return true
	case SubscriptionAccessProfileEuru:
		return true
	case SubscriptionAccessProfileRegular:
		return true
	case SubscriptionAccessProfileUnknown:
		return true
	case SubscriptionAccessProfileUnlimited:
		return true
	default:
		return false
	}
}

// Defines values for SubscriptionPanelError.
const (
	IdentityMismatch  SubscriptionPanelError = "identity_mismatch"
	InvalidTraffic    SubscriptionPanelError = "invalid_traffic"
	LessThannil       SubscriptionPanelError = "<nil>"
	Unavailable       SubscriptionPanelError = "unavailable"
	UnknownMembership SubscriptionPanelError = "unknown_membership"
)

// Valid indicates whether the value is a known member of the SubscriptionPanelError enum.
func (e SubscriptionPanelError) Valid() bool {
	switch e {
	case IdentityMismatch:
		return true
	case InvalidTraffic:
		return true
	case LessThannil:
		return true
	case Unavailable:
		return true
	case UnknownMembership:
		return true
	default:
		return false
	}
}

// Defines values for SubscriptionStatus.
const (
	SubscriptionStatusActive       SubscriptionStatus = "active"
	SubscriptionStatusBanned       SubscriptionStatus = "banned"
	SubscriptionStatusDisabled     SubscriptionStatus = "disabled"
	SubscriptionStatusExhausted    SubscriptionStatus = "exhausted"
	SubscriptionStatusExpired      SubscriptionStatus = "expired"
	SubscriptionStatusNeedsReview  SubscriptionStatus = "needs_review"
	SubscriptionStatusNone         SubscriptionStatus = "none"
	SubscriptionStatusProvisioning SubscriptionStatus = "provisioning"
)

// Valid indicates whether the value is a known member of the SubscriptionStatus enum.
func (e SubscriptionStatus) Valid() bool {
	switch e {
	case SubscriptionStatusActive:
		return true
	case SubscriptionStatusBanned:
		return true
	case SubscriptionStatusDisabled:
		return true
	case SubscriptionStatusExhausted:
		return true
	case SubscriptionStatusExpired:
		return true
	case SubscriptionStatusNeedsReview:
		return true
	case SubscriptionStatusNone:
		return true
	case SubscriptionStatusProvisioning:
		return true
	default:
		return false
	}
}

// Defines values for SupportConversationStatus.
const (
	SupportConversationStatusClosed SupportConversationStatus = "closed"
	SupportConversationStatusOpen   SupportConversationStatus = "open"
)

// Valid indicates whether the value is a known member of the SupportConversationStatus enum.
func (e SupportConversationStatus) Valid() bool {
	switch e {
	case SupportConversationStatusClosed:
		return true
	case SupportConversationStatusOpen:
		return true
	default:
		return false
	}
}

// Defines values for SupportMessageDelivery.
const (
	Delivered SupportMessageDelivery = "delivered"
	Stored    SupportMessageDelivery = "stored"
)

// Valid indicates whether the value is a known member of the SupportMessageDelivery enum.
func (e SupportMessageDelivery) Valid() bool {
	switch e {
	case Delivered:
		return true
	case Stored:
		return true
	default:
		return false
	}
}

// Defines values for SupportMessageSender.
const (
	SupportMessageSenderCustomer SupportMessageSender = "customer"
	SupportMessageSenderOperator SupportMessageSender = "operator"
)

// Valid indicates whether the value is a known member of the SupportMessageSender enum.
func (e SupportMessageSender) Valid() bool {
	switch e {
	case SupportMessageSenderCustomer:
		return true
	case SupportMessageSenderOperator:
		return true
	default:
		return false
	}
}

// Defines values for SupportStateInputStatus.
const (
	SupportStateInputStatusClosed SupportStateInputStatus = "closed"
	SupportStateInputStatusOpen   SupportStateInputStatus = "open"
)

// Valid indicates whether the value is a known member of the SupportStateInputStatus enum.
func (e SupportStateInputStatus) Valid() bool {
	switch e {
	case SupportStateInputStatusClosed:
		return true
	case SupportStateInputStatusOpen:
		return true
	default:
		return false
	}
}

// Defines values for TelegramFailedCode.
const (
	EditFailed      TelegramFailedCode = "edit_failed"
	Forbidden       TelegramFailedCode = "forbidden"
	InvalidResponse TelegramFailedCode = "invalid_response"
	Network         TelegramFailedCode = "network"
	Timeout         TelegramFailedCode = "timeout"
)

// Valid indicates whether the value is a known member of the TelegramFailedCode enum.
func (e TelegramFailedCode) Valid() bool {
	switch e {
	case EditFailed:
		return true
	case Forbidden:
		return true
	case InvalidResponse:
		return true
	case Network:
		return true
	case Timeout:
		return true
	default:
		return false
	}
}

// Defines values for TelegramFailedKind.
const (
	DeliveryFailed TelegramFailedKind = "delivery_failed"
)

// Valid indicates whether the value is a known member of the TelegramFailedKind enum.
func (e TelegramFailedKind) Valid() bool {
	switch e {
	case DeliveryFailed:
		return true
	default:
		return false
	}
}

// Defines values for TelegramJobKind.
const (
	ApprovalCard     TelegramJobKind = "approval_card"
	ProvisionApplied TelegramJobKind = "provision_applied"
	ProvisionReview  TelegramJobKind = "provision_review"
	RequestDecided   TelegramJobKind = "request_decided"
)

// Valid indicates whether the value is a known member of the TelegramJobKind enum.
func (e TelegramJobKind) Valid() bool {
	switch e {
	case ApprovalCard:
		return true
	case ProvisionApplied:
		return true
	case ProvisionReview:
		return true
	case RequestDecided:
		return true
	default:
		return false
	}
}

// Defines values for TelegramPayloadStatus.
const (
	TelegramPayloadStatusActive       TelegramPayloadStatus = "active"
	TelegramPayloadStatusApproved     TelegramPayloadStatus = "approved"
	TelegramPayloadStatusExpired      TelegramPayloadStatus = "expired"
	TelegramPayloadStatusNeedsReview  TelegramPayloadStatus = "needs_review"
	TelegramPayloadStatusPending      TelegramPayloadStatus = "pending"
	TelegramPayloadStatusProvisioning TelegramPayloadStatus = "provisioning"
	TelegramPayloadStatusRejected     TelegramPayloadStatus = "rejected"
)

// Valid indicates whether the value is a known member of the TelegramPayloadStatus enum.
func (e TelegramPayloadStatus) Valid() bool {
	switch e {
	case TelegramPayloadStatusActive:
		return true
	case TelegramPayloadStatusApproved:
		return true
	case TelegramPayloadStatusExpired:
		return true
	case TelegramPayloadStatusNeedsReview:
		return true
	case TelegramPayloadStatusPending:
		return true
	case TelegramPayloadStatusProvisioning:
		return true
	case TelegramPayloadStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for TelegramSentKind.
const (
	TelegramSentKindSent TelegramSentKind = "sent"
)

// Valid indicates whether the value is a known member of the TelegramSentKind enum.
func (e TelegramSentKind) Valid() bool {
	switch e {
	case TelegramSentKindSent:
		return true
	default:
		return false
	}
}

// Defines values for TrialRequestStatus.
const (
	TrialRequestStatusApproved TrialRequestStatus = "approved"
	TrialRequestStatusPending  TrialRequestStatus = "pending"
	TrialRequestStatusRejected TrialRequestStatus = "rejected"
)

// Valid indicates whether the value is a known member of the TrialRequestStatus enum.
func (e TrialRequestStatus) Valid() bool {
	switch e {
	case TrialRequestStatusApproved:
		return true
	case TrialRequestStatusPending:
		return true
	case TrialRequestStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for VerifyResultVerified.
const (
	True VerifyResultVerified = true
)

// Valid indicates whether the value is a known member of the VerifyResultVerified enum.
func (e VerifyResultVerified) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// APIError defines model for APIError.
type APIError struct {
	Error ErrorBody `json:"error"`
}

// Account defines model for Account.
type Account struct {
	AccountId      openapi_types.UUID    `json:"account_id"`
	Email          openapi_types.Email   `json:"email"`
	EmailVerified  bool                  `json:"email_verified"`
	Locale         AccountLocale         `json:"locale"`
	TelegramLinked AccountTelegramLinked `json:"telegram_linked"`
}

// AccountLocale defines model for Account.Locale.
type AccountLocale string

// AccountTelegramLinked defines model for Account.TelegramLinked.
type AccountTelegramLinked bool

// AccountResult defines model for AccountResult.
type AccountResult struct {
	Account      Account      `json:"account"`
	Capabilities Capabilities `json:"capabilities"`
	CsrfToken    string       `json:"csrf_token"`
}

// AccountSecurity defines model for AccountSecurity.
type AccountSecurity struct {
	Email              openapi_types.Email `json:"email"`
	HasOtherSessions   bool                `json:"has_other_sessions"`
	PendingEmailChange *PendingEmailChange `json:"pending_email_change"`
}

// Capabilities defines model for Capabilities.
type Capabilities struct {
	TrialAvailable bool `json:"trial_available"`
}

// CataloguePlanArchiveInput Archive creates a new immutable revision. Reason is trimmed 1-1000 Unicode characters, NUL forbidden.
type CataloguePlanArchiveInput struct {
	ExpectedRevision int64  `json:"expected_revision"`
	Reason           string `json:"reason"`
}

// CataloguePlanCreateInput Reason is trimmed by server to 1-1000 Unicode characters, NUL forbidden.
type CataloguePlanCreateInput struct {
	Reason string `json:"reason"`

	// Terms Full terms. Server requires complete RUB/USD/XTR matrix for each period on visible plans. Hidden plans may have empty prices; unlimited must be hidden.
	Terms CatalogueTerms `json:"terms"`
}

// CataloguePlanRevisionInput Full replacement terms; optimistic expected revision. Reason is trimmed 1-1000 Unicode characters, NUL forbidden.
type CataloguePlanRevisionInput struct {
	ExpectedRevision int64  `json:"expected_revision"`
	Reason           string `json:"reason"`

	// Terms Full terms. Server requires complete RUB/USD/XTR matrix for each period on visible plans. Hidden plans may have empty prices; unlimited must be hidden.
	Terms CatalogueTerms `json:"terms"`
}

// CataloguePlanSnapshot defines model for CataloguePlanSnapshot.
type CataloguePlanSnapshot struct {
	Devices   int                          `json:"devices"`
	Hidden    bool                         `json:"hidden"`
	Periods   []int64                      `json:"periods"`
	PlanId    openapi_types.UUID           `json:"plan_id"`
	Prices    []CataloguePrice             `json:"prices"`
	Profile   CataloguePlanSnapshotProfile `json:"profile"`
	Revision  int64                        `json:"revision"`
	TrafficGb int                          `json:"traffic_gb"`
}

// CataloguePlanSnapshotProfile defines model for CataloguePlanSnapshot.Profile.
type CataloguePlanSnapshotProfile string

// CataloguePrice defines model for CataloguePrice.
type CataloguePrice struct {
	// AmountMinor Nonnegative signed int64 minor units as canonical decimal text; server rejects values above 9223372036854775807. Never parse as JavaScript Number.
	AmountMinor string                 `json:"amount_minor"`
	Currency    CataloguePriceCurrency `json:"currency"`
	PeriodDays  int64                  `json:"period_days"`
}

// CataloguePriceCurrency defines model for CataloguePrice.Currency.
type CataloguePriceCurrency string

// CatalogueResult Only current active visible plans, no operator metadata.
type CatalogueResult struct {
	Plans []CataloguePlanSnapshot `json:"plans"`
}

// CatalogueTerms Full terms. Server requires complete RUB/USD/XTR matrix for each period on visible plans. Hidden plans may have empty prices; unlimited must be hidden.
type CatalogueTerms struct {
	Devices   int                   `json:"devices"`
	Hidden    bool                  `json:"hidden"`
	Periods   []int64               `json:"periods"`
	Prices    []CataloguePrice      `json:"prices"`
	Profile   CatalogueTermsProfile `json:"profile"`
	TrafficGb int                   `json:"traffic_gb"`
}

// CatalogueTermsProfile defines model for CatalogueTerms.Profile.
type CatalogueTermsProfile string

// ClaimInput defines model for ClaimInput.
type ClaimInput struct {
	Limit ClaimInputLimit `json:"limit"`
}

// ClaimInputLimit defines model for ClaimInput.Limit.
type ClaimInputLimit int

// ClaimResult defines model for ClaimResult.
type ClaimResult struct {
	Jobs []TelegramJob `json:"jobs"`
}

// CompleteResult defines model for CompleteResult.
type CompleteResult = map[string]interface{}

// CurrentPasswordInput defines model for CurrentPasswordInput.
type CurrentPasswordInput struct {
	CurrentPassword string `json:"current_password"`
}

// CurrentTrialRequest defines model for CurrentTrialRequest.
type CurrentTrialRequest struct {
	Request *TrialRequest `json:"request"`
}

// DecisionInput defines model for DecisionInput.
type DecisionInput struct {
	CallbackQueryId string                `json:"callback_query_id"`
	Decision        DecisionInputDecision `json:"decision"`
	OperatorTgId    int64                 `json:"operator_tg_id"`
	Reason          *string               `json:"reason,omitempty"`
}

// DecisionInputDecision defines model for DecisionInput.Decision.
type DecisionInputDecision string

// DecisionResult defines model for DecisionResult.
type DecisionResult struct {
	Card          TelegramPayload             `json:"card"`
	DeliveryState DecisionResultDeliveryState `json:"delivery_state"`
	OperationId   *openapi_types.UUID         `json:"operation_id"`
	Request       TrialRequest                `json:"request"`
}

// DecisionResultDeliveryState defines model for DecisionResult.DeliveryState.
type DecisionResultDeliveryState string

// EmailChangeAccepted defines model for EmailChangeAccepted.
type EmailChangeAccepted struct {
	ChangeId    openapi_types.UUID `json:"change_id"`
	ExpiresAt   time.Time          `json:"expires_at"`
	ResendAfter int                `json:"resend_after"`
}

// EmailChangeConfirmInput defines model for EmailChangeConfirmInput.
type EmailChangeConfirmInput struct {
	ChallengeId *openapi_types.UUID `json:"challenge_id,omitempty"`
	Code        *string             `json:"code,omitempty"`
	Token       *string             `json:"token,omitempty"`
	union       json.RawMessage
}

// EmailChangeConfirmInput0 defines model for EmailChangeConfirmInput.0.
type EmailChangeConfirmInput0 = interface{}

// EmailChangeConfirmInput1 defines model for EmailChangeConfirmInput.1.
type EmailChangeConfirmInput1 = interface{}

// EmailChangeInput defines model for EmailChangeInput.
type EmailChangeInput struct {
	CurrentPassword string              `json:"current_password"`
	NewEmail        openapi_types.Email `json:"new_email"`
}

// EmailChangeResult defines model for EmailChangeResult.
type EmailChangeResult struct {
	Completed bool `json:"completed"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Code                 ErrorBodyCode                  `json:"code"`
	CurrentRequestStatus *ErrorBodyCurrentRequestStatus `json:"current_request_status,omitempty"`
	Message              string                         `json:"message"`
	OperationId          *openapi_types.UUID            `json:"operation_id,omitempty"`
	RequestId            openapi_types.UUID             `json:"request_id"`
}

// ErrorBodyCode defines model for ErrorBody.Code.
type ErrorBodyCode string

// ErrorBodyCurrentRequestStatus defines model for ErrorBody.CurrentRequestStatus.
type ErrorBodyCurrentRequestStatus string

// LoginInput defines model for LoginInput.
type LoginInput struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResult defines model for LoginResult.
type LoginResult struct {
	Account   Account `json:"account"`
	CsrfToken string  `json:"csrf_token"`
}

// OperatorAuditEvent defines model for OperatorAuditEvent.
type OperatorAuditEvent struct {
	Action            string              `json:"action"`
	CreatedAt         time.Time           `json:"created_at"`
	Id                openapi_types.UUID  `json:"id"`
	OperationId       *openapi_types.UUID `json:"operation_id"`
	OperatorAccountId *openapi_types.UUID `json:"operator_account_id"`

	// OperatorTgId Positive signed int64 as decimal text. Server rejects values above 9223372036854775807; text preserves exact identity in JavaScript.
	OperatorTgId     *string             `json:"operator_tg_id"`
	Reason           *string             `json:"reason"`
	RequestId        *openapi_types.UUID `json:"request_id"`
	SupportMessageId *openapi_types.UUID `json:"support_message_id"`
}

// OperatorCataloguePlan Operator metadata. CLI-created revisions have null web actor/reason; every manual change records both.
type OperatorCataloguePlan struct {
	ActorAccountId *openapi_types.UUID          `json:"actor_account_id"`
	Archived       bool                         `json:"archived"`
	ChangedAt      time.Time                    `json:"changed_at"`
	Devices        int                          `json:"devices"`
	Hidden         bool                         `json:"hidden"`
	LegacyPlanId   *string                      `json:"legacy_plan_id"`
	Periods        []int64                      `json:"periods"`
	PlanId         openapi_types.UUID           `json:"plan_id"`
	Prices         []CataloguePrice             `json:"prices"`
	Profile        OperatorCataloguePlanProfile `json:"profile"`
	Reason         *string                      `json:"reason"`
	Revision       int64                        `json:"revision"`
	Source         OperatorCataloguePlanSource  `json:"source"`
	TrafficGb      int                          `json:"traffic_gb"`
}

// OperatorCataloguePlanProfile defines model for OperatorCataloguePlan.Profile.
type OperatorCataloguePlanProfile string

// OperatorCataloguePlanSource defines model for OperatorCataloguePlan.Source.
type OperatorCataloguePlanSource string

// OperatorCatalogueResult defines model for OperatorCatalogueResult.
type OperatorCatalogueResult struct {
	Page    int                     `json:"page"`
	PerPage int                     `json:"per_page"`
	Plans   []OperatorCataloguePlan `json:"plans"`
	Total   int64                   `json:"total"`
}

// OperatorClient defines model for OperatorClient.
type OperatorClient struct {
	AccountId openapi_types.UUID `json:"account_id"`

	// CreatedAt Null when historical account creation time was not recorded. Never an invented timestamp.
	CreatedAt       *time.Time           `json:"created_at"`
	DisplayName     string               `json:"display_name"`
	Email           *openapi_types.Email `json:"email"`
	HadSubscription bool                 `json:"had_subscription"`
	Kind            OperatorClientKind   `json:"kind"`
	Locale          OperatorClientLocale `json:"locale"`
	Restricted      bool                 `json:"restricted"`

	// TelegramId Positive signed int64 as decimal text. Server rejects values above 9223372036854775807; text preserves exact identity in JavaScript.
	TelegramId *string `json:"telegram_id"`
	VpnBanned  bool    `json:"vpn_banned"`
}

// OperatorClientKind defines model for OperatorClient.Kind.
type OperatorClientKind string

// OperatorClientLocale defines model for OperatorClient.Locale.
type OperatorClientLocale string

// OperatorClientCard defines model for OperatorClientCard.
type OperatorClientCard struct {
	AuditEvents    []OperatorAuditEvent          `json:"audit_events"`
	AuditHasMore   bool                          `json:"audit_has_more"`
	Client         OperatorClient                `json:"client"`
	LegacyApproval *OperatorLegacyApproval       `json:"legacy_approval"`
	LegacyEvents   []OperatorLegacyApprovalEvent `json:"legacy_events"`
	LegacyHasMore  bool                          `json:"legacy_has_more"`
	Server         *OperatorServer               `json:"server"`
	Subscription   Subscription                  `json:"subscription"`
	Support        *SupportConversation          `json:"support"`
	TrialHasMore   bool                          `json:"trial_has_more"`
	TrialRequests  []OperatorTrialRequest        `json:"trial_requests"`
}

// OperatorDecisionInput Reject requires a nonblank reason; approve permits an empty reason. Actor is only the authenticated operator session.
type OperatorDecisionInput struct {
	Decision OperatorDecisionInputDecision `json:"decision"`
	Reason   string                        `json:"reason"`
}

// OperatorDecisionInputDecision defines model for OperatorDecisionInput.Decision.
type OperatorDecisionInputDecision string

// OperatorDecisionResult defines model for OperatorDecisionResult.
type OperatorDecisionResult struct {
	OperationId *openapi_types.UUID `json:"operation_id"`
	Request     TrialRequest        `json:"request"`
}

// OperatorHistoryInput For legacy, before_created_at and before_source_id must both be present or absent; for trials/audit use before_created_at and UUID before_id. Descending created_at/source_id or created_at/id order.
type OperatorHistoryInput struct {
	BeforeCreatedAt *time.Time               `json:"before_created_at,omitempty"`
	BeforeId        *openapi_types.UUID      `json:"before_id,omitempty"`
	BeforeSourceId  *string                  `json:"before_source_id,omitempty"`
	Kind            OperatorHistoryInputKind `json:"kind"`
}

// OperatorHistoryInputKind defines model for OperatorHistoryInput.Kind.
type OperatorHistoryInputKind string

// OperatorHistoryResult defines model for OperatorHistoryResult.
type OperatorHistoryResult struct {
	AuditEvents   []OperatorAuditEvent          `json:"audit_events"`
	HasMore       bool                          `json:"has_more"`
	Kind          OperatorHistoryResultKind     `json:"kind"`
	LegacyEvents  []OperatorLegacyApprovalEvent `json:"legacy_events"`
	TrialRequests []OperatorTrialRequest        `json:"trial_requests"`
}

// OperatorHistoryResultKind defines model for OperatorHistoryResult.Kind.
type OperatorHistoryResultKind string

// OperatorLegacyApproval defines model for OperatorLegacyApproval.
type OperatorLegacyApproval struct {
	DecidedAt          *time.Time                   `json:"decided_at"`
	DecidedBy          *string                      `json:"decided_by"`
	RequestedAt        *time.Time                   `json:"requested_at"`
	SourceLegacyUserId string                       `json:"source_legacy_user_id"`
	SourceTgId         string                       `json:"source_tg_id"`
	Status             OperatorLegacyApprovalStatus `json:"status"`
}

// OperatorLegacyApprovalStatus defines model for OperatorLegacyApproval.Status.
type OperatorLegacyApprovalStatus string

// OperatorLegacyApprovalEvent defines model for OperatorLegacyApprovalEvent.
type OperatorLegacyApprovalEvent struct {
	Action     OperatorLegacyApprovalEventAction `json:"action"`
	ActorId    *string                           `json:"actor_id"`
	ActorName  *string                           `json:"actor_name"`
	ActorType  *string                           `json:"actor_type"`
	CreatedAt  time.Time                         `json:"created_at"`
	Source     *string                           `json:"source"`
	SourceId   string                            `json:"source_id"`
	TargetTgId string                            `json:"target_tg_id"`
}

// OperatorLegacyApprovalEventAction defines model for OperatorLegacyApprovalEvent.Action.
type OperatorLegacyApprovalEventAction string

// OperatorOperation defines model for OperatorOperation.
type OperatorOperation struct {
	CreatedAt   time.Time               `json:"created_at"`
	OperationId openapi_types.UUID      `json:"operation_id"`
	Status      OperatorOperationStatus `json:"status"`
}

// OperatorOperationStatus defines model for OperatorOperation.Status.
type OperatorOperationStatus string

// OperatorReasonInput defines model for OperatorReasonInput.
type OperatorReasonInput struct {
	Reason string `json:"reason"`
}

// OperatorRestrictionInput Reason is trimmed by server; 1-1000 Unicode characters after trim, NUL forbidden.
type OperatorRestrictionInput struct {
	Reason     string `json:"reason"`
	Restricted bool   `json:"restricted"`
}

// OperatorRestrictionResult Fields changed_at and operator_account_id describe the last actual manual restriction transition. They are null when no manual transition exists, including imported restrictions; no-op returns current stored metadata.
type OperatorRestrictionResult struct {
	ChangedAt         *time.Time          `json:"changed_at"`
	OperatorAccountId *openapi_types.UUID `json:"operator_account_id"`
	Restricted        bool                `json:"restricted"`
}

// OperatorSearchInput defines model for OperatorSearchInput.
type OperatorSearchInput struct {
	Page    int    `json:"page"`
	PerPage int    `json:"per_page"`
	Q       string `json:"q"`
}

// OperatorSearchResult defines model for OperatorSearchResult.
type OperatorSearchResult struct {
	Clients []OperatorClient `json:"clients"`
	Page    int              `json:"page"`
	PerPage int              `json:"per_page"`
	Total   int64            `json:"total"`
}

// OperatorServer defines model for OperatorServer.
type OperatorServer struct {
	Enabled bool   `json:"enabled"`
	PanelId string `json:"panel_id"`
}

// OperatorSession defines model for OperatorSession.
type OperatorSession struct {
	Account   Account `json:"account"`
	CsrfToken string  `json:"csrf_token"`
}

// OperatorTelegramTrialInput defines model for OperatorTelegramTrialInput.
type OperatorTelegramTrialInput struct {
	DisplayName string                           `json:"display_name"`
	Locale      OperatorTelegramTrialInputLocale `json:"locale"`

	// TelegramId Positive signed int64 as decimal text. Server rejects values above 9223372036854775807; text preserves exact identity in JavaScript.
	TelegramId string `json:"telegram_id"`
}

// OperatorTelegramTrialInputLocale defines model for OperatorTelegramTrialInput.Locale.
type OperatorTelegramTrialInputLocale string

// OperatorTelegramTrialResult defines model for OperatorTelegramTrialResult.
type OperatorTelegramTrialResult struct {
	Client      OperatorClient     `json:"client"`
	OperationId openapi_types.UUID `json:"operation_id"`
	Request     TrialRequest       `json:"request"`
}

// OperatorTrialRequest defines model for OperatorTrialRequest.
type OperatorTrialRequest struct {
	Comment           string              `json:"comment"`
	CreatedAt         time.Time           `json:"created_at"`
	DecidedAt         *time.Time          `json:"decided_at"`
	Operation         *OperatorOperation  `json:"operation"`
	OperationId       *openapi_types.UUID `json:"operation_id"`
	OperatorAccountId *openapi_types.UUID `json:"operator_account_id"`

	// OperatorTgId Positive signed int64 as decimal text. Server rejects values above 9223372036854775807; text preserves exact identity in JavaScript.
	OperatorTgId      *string                    `json:"operator_tg_id"`
	PreviousRequestId *openapi_types.UUID        `json:"previous_request_id"`
	Reason            *string                    `json:"reason"`
	RequestId         openapi_types.UUID         `json:"request_id"`
	Status            OperatorTrialRequestStatus `json:"status"`
}

// OperatorTrialRequestStatus defines model for OperatorTrialRequest.Status.
type OperatorTrialRequestStatus string

// PasswordChangeInput defines model for PasswordChangeInput.
type PasswordChangeInput struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// PasswordResetAccepted defines model for PasswordResetAccepted.
type PasswordResetAccepted struct {
	ChallengeId openapi_types.UUID `json:"challenge_id"`
	ResendAfter int64              `json:"resend_after"`
}

// PasswordResetCompleteInput defines model for PasswordResetCompleteInput.
type PasswordResetCompleteInput struct {
	ChallengeId *openapi_types.UUID `json:"challenge_id,omitempty"`
	Code        *string             `json:"code,omitempty"`
	NewPassword string              `json:"new_password"`
	Token       *string             `json:"token,omitempty"`
	union       json.RawMessage
}

// PasswordResetCompleteInput0 defines model for PasswordResetCompleteInput.0.
type PasswordResetCompleteInput0 = interface{}

// PasswordResetCompleteInput1 defines model for PasswordResetCompleteInput.1.
type PasswordResetCompleteInput1 = interface{}

// PasswordResetInput defines model for PasswordResetInput.
type PasswordResetInput struct {
	Email  openapi_types.Email      `json:"email"`
	Locale PasswordResetInputLocale `json:"locale"`
}

// PasswordResetInputLocale defines model for PasswordResetInput.Locale.
type PasswordResetInputLocale string

// PendingEmailChange defines model for PendingEmailChange.
type PendingEmailChange struct {
	CurrentEmailConfirmed bool                `json:"current_email_confirmed"`
	ExpiresAt             time.Time           `json:"expires_at"`
	NewEmail              openapi_types.Email `json:"new_email"`
	NewEmailConfirmed     bool                `json:"new_email_confirmed"`
}

// ReconcileInput defines model for ReconcileInput.
type ReconcileInput struct {
	OperatorTgId int64  `json:"operator_tg_id"`
	Reason       string `json:"reason"`
}

// ReconcileResult defines model for ReconcileResult.
type ReconcileResult struct {
	OperationId openapi_types.UUID    `json:"operation_id"`
	Status      ReconcileResultStatus `json:"status"`
}

// ReconcileResultStatus defines model for ReconcileResult.Status.
type ReconcileResultStatus string

// ReconsiderInput defines model for ReconsiderInput.
type ReconsiderInput struct {
	OperatorTgId int64  `json:"operator_tg_id"`
	Reason       string `json:"reason"`
}

// RegisterInput defines model for RegisterInput.
type RegisterInput struct {
	AcceptedPrivacyVersion string              `json:"accepted_privacy_version"`
	AcceptedTermsVersion   string              `json:"accepted_terms_version"`
	Email                  openapi_types.Email `json:"email"`
	Locale                 RegisterInputLocale `json:"locale"`
}

// RegisterInputLocale defines model for RegisterInput.Locale.
type RegisterInputLocale string

// RegistrationAccepted defines model for RegistrationAccepted.
type RegistrationAccepted struct {
	ChallengeId openapi_types.UUID `json:"challenge_id"`
	ResendAfter int64              `json:"resend_after"`
}

// ResendAccepted defines model for ResendAccepted.
type ResendAccepted struct {
	ResendAfter int64 `json:"resend_after"`
}

// ResendInput defines model for ResendInput.
type ResendInput struct {
	Email openapi_types.Email `json:"email"`
}

// SessionContext defines model for SessionContext.
type SessionContext struct {
	CsrfToken string `json:"csrf_token"`
}

// Subscription defines model for Subscription.
type Subscription struct {
	AccessProfile         *SubscriptionAccessProfile `json:"access_profile,omitempty"`
	ConnectionAvailable   *bool                      `json:"connection_available,omitempty"`
	DataStale             bool                       `json:"data_stale"`
	Devices               int64                      `json:"devices"`
	ExpiresAt             *time.Time                 `json:"expires_at"`
	ObservedAt            *time.Time                 `json:"observed_at"`
	PanelError            *SubscriptionPanelError    `json:"panel_error,omitempty"`
	Status                SubscriptionStatus         `json:"status"`
	TrafficDownloadBytes  *int64                     `json:"traffic_download_bytes,omitempty"`
	TrafficLimitBytes     int64                      `json:"traffic_limit_bytes"`
	TrafficRemainingBytes *int64                     `json:"traffic_remaining_bytes,omitempty"`
	TrafficUploadBytes    *int64                     `json:"traffic_upload_bytes,omitempty"`
	TrafficUsedBytes      *int64                     `json:"traffic_used_bytes"`
	UnlimitedDevices      *bool                      `json:"unlimited_devices,omitempty"`
	UnlimitedTraffic      *bool                      `json:"unlimited_traffic,omitempty"`
}

// SubscriptionAccessProfile defines model for Subscription.AccessProfile.
type SubscriptionAccessProfile string

// SubscriptionPanelError defines model for Subscription.PanelError.
type SubscriptionPanelError string

// SubscriptionStatus defines model for Subscription.Status.
type SubscriptionStatus string

// SubscriptionKey defines model for SubscriptionKey.
type SubscriptionKey struct {
	SubscriptionUrl string `json:"subscription_url"`
}

// SupportAttachment defines model for SupportAttachment.
type SupportAttachment struct {
	Name      string `json:"name"`
	SizeBytes int64  `json:"size_bytes"`
}

// SupportBanInput defines model for SupportBanInput.
type SupportBanInput struct {
	Banned bool   `json:"banned"`
	Reason string `json:"reason"`
}

// SupportConversation defines model for SupportConversation.
type SupportConversation struct {
	CreatedAt                time.Time                 `json:"created_at"`
	CustomerReceivedSequence int64                     `json:"customer_received_sequence"`
	Id                       openapi_types.UUID        `json:"id"`
	OperatorReceivedSequence int64                     `json:"operator_received_sequence"`
	Status                   SupportConversationStatus `json:"status"`
	SupportBanned            bool                      `json:"support_banned"`
	UpdatedAt                time.Time                 `json:"updated_at"`
}

// SupportConversationStatus defines model for SupportConversation.Status.
type SupportConversationStatus string

// SupportHistoryInput defines model for SupportHistoryInput.
type SupportHistoryInput struct {
	BeforeSequence int64 `json:"before_sequence"`
}

// SupportMessage defines model for SupportMessage.
type SupportMessage struct {
	Attachment *SupportAttachment     `json:"attachment"`
	CreatedAt  time.Time              `json:"created_at"`
	Delivery   SupportMessageDelivery `json:"delivery"`
	Id         openapi_types.UUID     `json:"id"`
	Sender     SupportMessageSender   `json:"sender"`
	Sequence   int64                  `json:"sequence"`
	Text       string                 `json:"text"`
}

// SupportMessageDelivery defines model for SupportMessage.Delivery.
type SupportMessageDelivery string

// SupportMessageSender defines model for SupportMessage.Sender.
type SupportMessageSender string

// SupportMessageInput defines model for SupportMessageInput.
type SupportMessageInput struct {
	Text string `json:"text"`
}

// SupportMultipartInput defines model for SupportMultipartInput.
type SupportMultipartInput struct {
	File *openapi_types.File `json:"file,omitempty"`
	Text string              `json:"text"`
}

// SupportReadInput defines model for SupportReadInput.
type SupportReadInput struct {
	Sequence int64 `json:"sequence"`
}

// SupportResult defines model for SupportResult.
type SupportResult struct {
	Conversation   *SupportConversation `json:"conversation"`
	HasMore        bool                 `json:"has_more"`
	Messages       []SupportMessage     `json:"messages"`
	OldestSequence *int64               `json:"oldest_sequence"`
}

// SupportStateInput defines model for SupportStateInput.
type SupportStateInput struct {
	Status SupportStateInputStatus `json:"status"`
}

// SupportStateInputStatus defines model for SupportStateInput.Status.
type SupportStateInputStatus string

// TelegramFailed defines model for TelegramFailed.
type TelegramFailed struct {
	Code TelegramFailedCode `json:"code"`
	Kind TelegramFailedKind `json:"kind"`
}

// TelegramFailedCode defines model for TelegramFailed.Code.
type TelegramFailedCode string

// TelegramFailedKind defines model for TelegramFailed.Kind.
type TelegramFailedKind string

// TelegramJob defines model for TelegramJob.
type TelegramJob struct {
	ChatId         int64              `json:"chat_id"`
	JobId          openapi_types.UUID `json:"job_id"`
	Kind           TelegramJobKind    `json:"kind"`
	LeaseExpiresAt time.Time          `json:"lease_expires_at"`
	LeaseToken     string             `json:"lease_token"`
	Payload        TelegramPayload    `json:"payload"`
}

// TelegramJobKind defines model for TelegramJob.Kind.
type TelegramJobKind string

// TelegramPayload defines model for TelegramPayload.
type TelegramPayload struct {
	Comment         string                `json:"comment"`
	CreatedAt       time.Time             `json:"created_at"`
	DisplayName     *string               `json:"display_name,omitempty"`
	Email           *openapi_types.Email  `json:"email"`
	OperationId     *openapi_types.UUID   `json:"operation_id"`
	RequestId       openapi_types.UUID    `json:"request_id"`
	Status          TelegramPayloadStatus `json:"status"`
	TargetMessageId *int64                `json:"target_message_id"`

	// TelegramId Positive signed int64 as decimal text. Server rejects values above 9223372036854775807; text preserves exact identity in JavaScript.
	TelegramId *string `json:"telegram_id,omitempty"`
}

// TelegramPayloadStatus defines model for TelegramPayload.Status.
type TelegramPayloadStatus string

// TelegramResult defines model for TelegramResult.
type TelegramResult struct {
	union json.RawMessage
}

// TelegramResultInput defines model for TelegramResultInput.
type TelegramResultInput struct {
	LeaseToken string         `json:"lease_token"`
	Result     TelegramResult `json:"result"`
}

// TelegramSent defines model for TelegramSent.
type TelegramSent struct {
	ChatId    int64            `json:"chat_id"`
	Kind      TelegramSentKind `json:"kind"`
	MessageId int64            `json:"message_id"`
}

// TelegramSentKind defines model for TelegramSent.Kind.
type TelegramSentKind string

// TrialRequest defines model for TrialRequest.
type TrialRequest struct {
	CreatedAt         time.Time           `json:"created_at"`
	DecidedAt         *time.Time          `json:"decided_at"`
	OperationId       *openapi_types.UUID `json:"operation_id"`
	PreviousRequestId *openapi_types.UUID `json:"previous_request_id"`
	RequestId         openapi_types.UUID  `json:"request_id"`
	Status            TrialRequestStatus  `json:"status"`
}

// TrialRequestStatus defines model for TrialRequest.Status.
type TrialRequestStatus string

// TrialRequestInput defines model for TrialRequestInput.
type TrialRequestInput struct {
	Comment *string `json:"comment,omitempty"`
}

// VerifyInput defines model for VerifyInput.
type VerifyInput struct {
	ChallengeId *openapi_types.UUID `json:"challenge_id,omitempty"`
	Code        *string             `json:"code,omitempty"`
	NewPassword string              `json:"new_password"`
	Token       *string             `json:"token,omitempty"`
	union       json.RawMessage
}

// VerifyInput0 defines model for VerifyInput.0.
type VerifyInput0 = interface{}

// VerifyInput1 defines model for VerifyInput.1.
type VerifyInput1 = interface{}

// VerifyResult defines model for VerifyResult.
type VerifyResult struct {
	Verified VerifyResultVerified `json:"verified"`
}

// VerifyResultVerified defines model for VerifyResult.Verified.
type VerifyResultVerified bool

// ConfirmEmailChangeParams defines parameters for ConfirmEmailChange.
type ConfirmEmailChangeParams struct {
	Origin string `json:"Origin"`
}

// LoginAccountParams defines parameters for LoginAccount.
type LoginAccountParams struct {
	Origin string `json:"Origin"`
}

// LogoutAccountParams defines parameters for LogoutAccount.
type LogoutAccountParams struct {
	Origin     string  `json:"Origin"`
	XCSRFToken *string `json:"X-CSRF-Token,omitempty"`
}

// RequestPasswordResetParams defines parameters for RequestPasswordReset.
type RequestPasswordResetParams struct {
	Origin string `json:"Origin"`
}

// CompletePasswordResetParams defines parameters for CompletePasswordReset.
type CompletePasswordResetParams struct {
	Origin string `json:"Origin"`
}

// RegisterAccountParams defines parameters for RegisterAccount.
type RegisterAccountParams struct {
	Origin string `json:"Origin"`
}

// ResendVerificationParams defines parameters for ResendVerification.
type ResendVerificationParams struct {
	Origin string `json:"Origin"`
}

// VerifyEmailParams defines parameters for VerifyEmail.
type VerifyEmailParams struct {
	Origin string `json:"Origin"`
}

// RequestEmailChangeParams defines parameters for RequestEmailChange.
type RequestEmailChangeParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// CancelEmailChangeParams defines parameters for CancelEmailChange.
type CancelEmailChangeParams struct {
	Origin     string  `json:"Origin"`
	XCSRFToken *string `json:"X-CSRF-Token,omitempty"`
}

// ChangePasswordParams defines parameters for ChangePassword.
type ChangePasswordParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// RevokeOtherSessionsParams defines parameters for RevokeOtherSessions.
type RevokeOtherSessionsParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// GetOperatorCatalogueParams defines parameters for GetOperatorCatalogue.
type GetOperatorCatalogueParams struct {
	Page    int `form:"page" json:"page"`
	PerPage int `form:"per_page" json:"per_page"`
}

// CreateCataloguePlanParams defines parameters for CreateCataloguePlan.
type CreateCataloguePlanParams struct {
	Origin         string             `json:"Origin"`
	XCSRFToken     string             `json:"X-CSRF-Token"`
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// ArchiveCataloguePlanParams defines parameters for ArchiveCataloguePlan.
type ArchiveCataloguePlanParams struct {
	Origin         string             `json:"Origin"`
	XCSRFToken     string             `json:"X-CSRF-Token"`
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// ReviseCataloguePlanParams defines parameters for ReviseCataloguePlan.
type ReviseCataloguePlanParams struct {
	Origin         string             `json:"Origin"`
	XCSRFToken     string             `json:"X-CSRF-Token"`
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// SearchOperatorClientsParams defines parameters for SearchOperatorClients.
type SearchOperatorClientsParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// CreateOperatorTelegramTrialParams defines parameters for CreateOperatorTelegramTrial.
type CreateOperatorTelegramTrialParams struct {
	Origin         string             `json:"Origin"`
	XCSRFToken     string             `json:"X-CSRF-Token"`
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// GetOperatorClientHistoryParams defines parameters for GetOperatorClientHistory.
type GetOperatorClientHistoryParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// SetOperatorRestrictionParams defines parameters for SetOperatorRestriction.
type SetOperatorRestrictionParams struct {
	Origin         string             `json:"Origin"`
	XCSRFToken     string             `json:"X-CSRF-Token"`
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// SetOperatorSupportBanParams defines parameters for SetOperatorSupportBan.
type SetOperatorSupportBanParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// GetOperatorSupportHistoryParams defines parameters for GetOperatorSupportHistory.
type GetOperatorSupportHistoryParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// CreateOperatorSupportMessageParams defines parameters for CreateOperatorSupportMessage.
type CreateOperatorSupportMessageParams struct {
	Origin         string             `json:"Origin"`
	XCSRFToken     string             `json:"X-CSRF-Token"`
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// AcknowledgeOperatorSupportParams defines parameters for AcknowledgeOperatorSupport.
type AcknowledgeOperatorSupportParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// SetOperatorSupportStateParams defines parameters for SetOperatorSupportState.
type SetOperatorSupportStateParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// ReconcileOperatorTrialOperationParams defines parameters for ReconcileOperatorTrialOperation.
type ReconcileOperatorTrialOperationParams struct {
	Origin         string             `json:"Origin"`
	XCSRFToken     string             `json:"X-CSRF-Token"`
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// DecideOperatorTrialRequestParams defines parameters for DecideOperatorTrialRequest.
type DecideOperatorTrialRequestParams struct {
	Origin         string             `json:"Origin"`
	XCSRFToken     string             `json:"X-CSRF-Token"`
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// ReconsiderOperatorTrialRequestParams defines parameters for ReconsiderOperatorTrialRequest.
type ReconsiderOperatorTrialRequestParams struct {
	Origin         string             `json:"Origin"`
	XCSRFToken     string             `json:"X-CSRF-Token"`
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// GetSupportHistoryParams defines parameters for GetSupportHistory.
type GetSupportHistoryParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// CreateSupportMessageParams defines parameters for CreateSupportMessage.
type CreateSupportMessageParams struct {
	Origin         string             `json:"Origin"`
	XCSRFToken     string             `json:"X-CSRF-Token"`
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// AcknowledgeSupportParams defines parameters for AcknowledgeSupport.
type AcknowledgeSupportParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// SetSupportStateParams defines parameters for SetSupportState.
type SetSupportStateParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// CreateTrialRequestParams defines parameters for CreateTrialRequest.
type CreateTrialRequestParams struct {
	Origin         string             `json:"Origin"`
	XCSRFToken     string             `json:"X-CSRF-Token"`
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// ReconcileTrialOperationParams defines parameters for ReconcileTrialOperation.
type ReconcileTrialOperationParams struct {
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// ReconsiderTrialRequestParams defines parameters for ReconsiderTrialRequest.
type ReconsiderTrialRequestParams struct {
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// ConfirmEmailChangeJSONRequestBody defines body for ConfirmEmailChange for application/json ContentType.
type ConfirmEmailChangeJSONRequestBody = EmailChangeConfirmInput

// LoginAccountJSONRequestBody defines body for LoginAccount for application/json ContentType.
type LoginAccountJSONRequestBody = LoginInput

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody = PasswordResetInput

// CompletePasswordResetJSONRequestBody defines body for CompletePasswordReset for application/json ContentType.
type CompletePasswordResetJSONRequestBody = PasswordResetCompleteInput

// RegisterAccountJSONRequestBody defines body for RegisterAccount for application/json ContentType.
type RegisterAccountJSONRequestBody = RegisterInput

// ResendVerificationJSONRequestBody defines body for ResendVerification for application/json ContentType.
type ResendVerificationJSONRequestBody = ResendInput

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody = VerifyInput

// RequestEmailChangeJSONRequestBody defines body for RequestEmailChange for application/json ContentType.
type RequestEmailChangeJSONRequestBody = EmailChangeInput

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = PasswordChangeInput

// RevokeOtherSessionsJSONRequestBody defines body for RevokeOtherSessions for application/json ContentType.
type RevokeOtherSessionsJSONRequestBody = CurrentPasswordInput

// CreateCataloguePlanJSONRequestBody defines body for CreateCataloguePlan for application/json ContentType.
type CreateCataloguePlanJSONRequestBody = CataloguePlanCreateInput

// ArchiveCataloguePlanJSONRequestBody defines body for ArchiveCataloguePlan for application/json ContentType.
type ArchiveCataloguePlanJSONRequestBody = CataloguePlanArchiveInput

// ReviseCataloguePlanJSONRequestBody defines body for ReviseCataloguePlan for application/json ContentType.
type ReviseCataloguePlanJSONRequestBody = CataloguePlanRevisionInput

// SearchOperatorClientsJSONRequestBody defines body for SearchOperatorClients for application/json ContentType.
type SearchOperatorClientsJSONRequestBody = OperatorSearchInput

// CreateOperatorTelegramTrialJSONRequestBody defines body for CreateOperatorTelegramTrial for application/json ContentType.
type CreateOperatorTelegramTrialJSONRequestBody = OperatorTelegramTrialInput

// GetOperatorClientHistoryJSONRequestBody defines body for GetOperatorClientHistory for application/json ContentType.
type GetOperatorClientHistoryJSONRequestBody = OperatorHistoryInput

// SetOperatorRestrictionJSONRequestBody defines body for SetOperatorRestriction for application/json ContentType.
type SetOperatorRestrictionJSONRequestBody = OperatorRestrictionInput

// SetOperatorSupportBanJSONRequestBody defines body for SetOperatorSupportBan for application/json ContentType.
type SetOperatorSupportBanJSONRequestBody = SupportBanInput

// GetOperatorSupportHistoryJSONRequestBody defines body for GetOperatorSupportHistory for application/json ContentType.
type GetOperatorSupportHistoryJSONRequestBody = SupportHistoryInput

// CreateOperatorSupportMessageJSONRequestBody defines body for CreateOperatorSupportMessage for application/json ContentType.
type CreateOperatorSupportMessageJSONRequestBody = SupportMessageInput

// CreateOperatorSupportMessageMultipartRequestBody defines body for CreateOperatorSupportMessage for multipart/form-data ContentType.
type CreateOperatorSupportMessageMultipartRequestBody = SupportMultipartInput

// AcknowledgeOperatorSupportJSONRequestBody defines body for AcknowledgeOperatorSupport for application/json ContentType.
type AcknowledgeOperatorSupportJSONRequestBody = SupportReadInput

// SetOperatorSupportStateJSONRequestBody defines body for SetOperatorSupportState for application/json ContentType.
type SetOperatorSupportStateJSONRequestBody = SupportStateInput

// ReconcileOperatorTrialOperationJSONRequestBody defines body for ReconcileOperatorTrialOperation for application/json ContentType.
type ReconcileOperatorTrialOperationJSONRequestBody = OperatorReasonInput

// DecideOperatorTrialRequestJSONRequestBody defines body for DecideOperatorTrialRequest for application/json ContentType.
type DecideOperatorTrialRequestJSONRequestBody = OperatorDecisionInput

// ReconsiderOperatorTrialRequestJSONRequestBody defines body for ReconsiderOperatorTrialRequest for application/json ContentType.
type ReconsiderOperatorTrialRequestJSONRequestBody = OperatorReasonInput

// GetSupportHistoryJSONRequestBody defines body for GetSupportHistory for application/json ContentType.
type GetSupportHistoryJSONRequestBody = SupportHistoryInput

// CreateSupportMessageJSONRequestBody defines body for CreateSupportMessage for application/json ContentType.
type CreateSupportMessageJSONRequestBody = SupportMessageInput

// CreateSupportMessageMultipartRequestBody defines body for CreateSupportMessage for multipart/form-data ContentType.
type CreateSupportMessageMultipartRequestBody = SupportMultipartInput

// AcknowledgeSupportJSONRequestBody defines body for AcknowledgeSupport for application/json ContentType.
type AcknowledgeSupportJSONRequestBody = SupportReadInput

// SetSupportStateJSONRequestBody defines body for SetSupportState for application/json ContentType.
type SetSupportStateJSONRequestBody = SupportStateInput

// CreateTrialRequestJSONRequestBody defines body for CreateTrialRequest for application/json ContentType.
type CreateTrialRequestJSONRequestBody = TrialRequestInput

// ClaimTelegramJobsJSONRequestBody defines body for ClaimTelegramJobs for application/json ContentType.
type ClaimTelegramJobsJSONRequestBody = ClaimInput

// CompleteTelegramJobJSONRequestBody defines body for CompleteTelegramJob for application/json ContentType.
type CompleteTelegramJobJSONRequestBody = TelegramResultInput

// ReconcileTrialOperationJSONRequestBody defines body for ReconcileTrialOperation for application/json ContentType.
type ReconcileTrialOperationJSONRequestBody = ReconcileInput

// DecideTrialRequestJSONRequestBody defines body for DecideTrialRequest for application/json ContentType.
type DecideTrialRequestJSONRequestBody = DecisionInput

// ReconsiderTrialRequestJSONRequestBody defines body for ReconsiderTrialRequest for application/json ContentType.
type ReconsiderTrialRequestJSONRequestBody = ReconsiderInput

// AsEmailChangeConfirmInput0 returns the union data inside the EmailChangeConfirmInput as a EmailChangeConfirmInput0
func (t EmailChangeConfirmInput) AsEmailChangeConfirmInput0() (EmailChangeConfirmInput0, error) {
	var body EmailChangeConfirmInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmailChangeConfirmInput0 overwrites any union data inside the EmailChangeConfirmInput as the provided EmailChangeConfirmInput0
func (t *EmailChangeConfirmInput) FromEmailChangeConfirmInput0(v EmailChangeConfirmInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmailChangeConfirmInput0 performs a merge with any union data inside the EmailChangeConfirmInput, using the provided EmailChangeConfirmInput0
func (t *EmailChangeConfirmInput) MergeEmailChangeConfirmInput0(v EmailChangeConfirmInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmailChangeConfirmInput1 returns the union data inside the EmailChangeConfirmInput as a EmailChangeConfirmInput1
func (t EmailChangeConfirmInput) AsEmailChangeConfirmInput1() (EmailChangeConfirmInput1, error) {
	var body EmailChangeConfirmInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmailChangeConfirmInput1 overwrites any union data inside the EmailChangeConfirmInput as the provided EmailChangeConfirmInput1
func (t *EmailChangeConfirmInput) FromEmailChangeConfirmInput1(v EmailChangeConfirmInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmailChangeConfirmInput1 performs a merge with any union data inside the EmailChangeConfirmInput, using the provided EmailChangeConfirmInput1
func (t *EmailChangeConfirmInput) MergeEmailChangeConfirmInput1(v EmailChangeConfirmInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmailChangeConfirmInput) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.ChallengeId != nil {
		object["challenge_id"], err = json.Marshal(t.ChallengeId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'challenge_id': %w", err)
		}
	}

	if t.Code != nil {
		object["code"], err = json.Marshal(t.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if t.Token != nil {
		object["token"], err = json.Marshal(t.Token)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'token': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *EmailChangeConfirmInput) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["challenge_id"]; found {
		err = json.Unmarshal(raw, &t.ChallengeId)
		if err != nil {
			return fmt.Errorf("error reading 'challenge_id': %w", err)
		}
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &t.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
	}

	if raw, found := object["token"]; found {
		err = json.Unmarshal(raw, &t.Token)
		if err != nil {
			return fmt.Errorf("error reading 'token': %w", err)
		}
	}

	return err
}

// AsPasswordResetCompleteInput0 returns the union data inside the PasswordResetCompleteInput as a PasswordResetCompleteInput0
func (t PasswordResetCompleteInput) AsPasswordResetCompleteInput0() (PasswordResetCompleteInput0, error) {
	var body PasswordResetCompleteInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPasswordResetCompleteInput0 overwrites any union data inside the PasswordResetCompleteInput as the provided PasswordResetCompleteInput0
func (t *PasswordResetCompleteInput) FromPasswordResetCompleteInput0(v PasswordResetCompleteInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePasswordResetCompleteInput0 performs a merge with any union data inside the PasswordResetCompleteInput, using the provided PasswordResetCompleteInput0
func (t *PasswordResetCompleteInput) MergePasswordResetCompleteInput0(v PasswordResetCompleteInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPasswordResetCompleteInput1 returns the union data inside the PasswordResetCompleteInput as a PasswordResetCompleteInput1
func (t PasswordResetCompleteInput) AsPasswordResetCompleteInput1() (PasswordResetCompleteInput1, error) {
	var body PasswordResetCompleteInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPasswordResetCompleteInput1 overwrites any union data inside the PasswordResetCompleteInput as the provided PasswordResetCompleteInput1
func (t *PasswordResetCompleteInput) FromPasswordResetCompleteInput1(v PasswordResetCompleteInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePasswordResetCompleteInput1 performs a merge with any union data inside the PasswordResetCompleteInput, using the provided PasswordResetCompleteInput1
func (t *PasswordResetCompleteInput) MergePasswordResetCompleteInput1(v PasswordResetCompleteInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PasswordResetCompleteInput) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.ChallengeId != nil {
		object["challenge_id"], err = json.Marshal(t.ChallengeId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'challenge_id': %w", err)
		}
	}

	if t.Code != nil {
		object["code"], err = json.Marshal(t.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	object["new_password"], err = json.Marshal(t.NewPassword)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'new_password': %w", err)
	}

	if t.Token != nil {
		object["token"], err = json.Marshal(t.Token)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'token': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *PasswordResetCompleteInput) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["challenge_id"]; found {
		err = json.Unmarshal(raw, &t.ChallengeId)
		if err != nil {
			return fmt.Errorf("error reading 'challenge_id': %w", err)
		}
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &t.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
	}

	if raw, found := object["new_password"]; found {
		err = json.Unmarshal(raw, &t.NewPassword)
		if err != nil {
			return fmt.Errorf("error reading 'new_password': %w", err)
		}
	}

	if raw, found := object["token"]; found {
		err = json.Unmarshal(raw, &t.Token)
		if err != nil {
			return fmt.Errorf("error reading 'token': %w", err)
		}
	}

	return err
}

// AsTelegramSent returns the union data inside the TelegramResult as a TelegramSent
func (t TelegramResult) AsTelegramSent() (TelegramSent, error) {
	var body TelegramSent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTelegramSent overwrites any union data inside the TelegramResult as the provided TelegramSent
func (t *TelegramResult) FromTelegramSent(v TelegramSent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"sent"}`))
	t.union = b
	return err
}

// MergeTelegramSent performs a merge with any union data inside the TelegramResult, using the provided TelegramSent
func (t *TelegramResult) MergeTelegramSent(v TelegramSent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"sent"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTelegramFailed returns the union data inside the TelegramResult as a TelegramFailed
func (t TelegramResult) AsTelegramFailed() (TelegramFailed, error) {
	var body TelegramFailed
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTelegramFailed overwrites any union data inside the TelegramResult as the provided TelegramFailed
func (t *TelegramResult) FromTelegramFailed(v TelegramFailed) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"delivery_failed"}`))
	t.union = b
	return err
}

// MergeTelegramFailed performs a merge with any union data inside the TelegramResult, using the provided TelegramFailed
func (t *TelegramResult) MergeTelegramFailed(v TelegramFailed) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"delivery_failed"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t TelegramResult) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t TelegramResult) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "delivery_failed":
		return t.AsTelegramFailed()
	case "sent":
		return t.AsTelegramSent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t TelegramResult) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *TelegramResult) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsVerifyInput0 returns the union data inside the VerifyInput as a VerifyInput0
func (t VerifyInput) AsVerifyInput0() (VerifyInput0, error) {
	var body VerifyInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVerifyInput0 overwrites any union data inside the VerifyInput as the provided VerifyInput0
func (t *VerifyInput) FromVerifyInput0(v VerifyInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVerifyInput0 performs a merge with any union data inside the VerifyInput, using the provided VerifyInput0
func (t *VerifyInput) MergeVerifyInput0(v VerifyInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsVerifyInput1 returns the union data inside the VerifyInput as a VerifyInput1
func (t VerifyInput) AsVerifyInput1() (VerifyInput1, error) {
	var body VerifyInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVerifyInput1 overwrites any union data inside the VerifyInput as the provided VerifyInput1
func (t *VerifyInput) FromVerifyInput1(v VerifyInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVerifyInput1 performs a merge with any union data inside the VerifyInput, using the provided VerifyInput1
func (t *VerifyInput) MergeVerifyInput1(v VerifyInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t VerifyInput) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.ChallengeId != nil {
		object["challenge_id"], err = json.Marshal(t.ChallengeId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'challenge_id': %w", err)
		}
	}

	if t.Code != nil {
		object["code"], err = json.Marshal(t.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	object["new_password"], err = json.Marshal(t.NewPassword)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'new_password': %w", err)
	}

	if t.Token != nil {
		object["token"], err = json.Marshal(t.Token)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'token': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *VerifyInput) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["challenge_id"]; found {
		err = json.Unmarshal(raw, &t.ChallengeId)
		if err != nil {
			return fmt.Errorf("error reading 'challenge_id': %w", err)
		}
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &t.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
	}

	if raw, found := object["new_password"]; found {
		err = json.Unmarshal(raw, &t.NewPassword)
		if err != nil {
			return fmt.Errorf("error reading 'new_password': %w", err)
		}
	}

	if raw, found := object["token"]; found {
		err = json.Unmarshal(raw, &t.Token)
		if err != nil {
			return fmt.Errorf("error reading 'token': %w", err)
		}
	}

	return err
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F1tV+O4kv4rOt77YfdcA6Hfpzn7IQ3MHWYYYBPoc++ZZXMUuyCatiWPJNOd7eW/75Esv8aJX0IIDfrW",
	"HWypVCo9T6lUKn93PBZGjAKVwvn43RHeDEKs/zm8ODnmnHH1b+z7RBJGcXDBWQRcEhDOxxscCHCdqPDT",
	"dwfSd/7G4cb56PzbXt7Dnml+Tzf8iflz5/7edTj8FRMOvvPxD/P6tevIeQTOR4dN/wRPOveuM/Q8FlPZ",
	"URycvDUhvvrfDeMhls5HJ46J72SdCMkJvVWdQIhJUHoy+WXZo5M74OSGgG7dPDJlLABM1TMB83AA6m9A",
	"41CNj8eO6wB1rmtalBDALcfhJCD0C/iF1/TQrt2FHirKKwzWzQSvyJkJtdjfCq2PQMRBT903GUM6sfeu",
	"4+EIT0lA0hZWvXZYfFa9K/jNRLIvQAtzkSq3XlFO6a1K9yu0MQYv5kTOuy6NpcYV4m+nQG/lzPn46u2b",
	"GtOYYTFhcgZ8IkAIwqioN7gIqE/o7SSZdG+G6a02PxwE5zfOxz9Wq/QieftYvXyYvHt/7To0DgI8VXYs",
	"eQwLK9aMoUbEJfLUafawMvMd1Co5wcEE32FipPzetE6qb9QLJHHAbmO4CDAdcm9G7uCERnHzIvBBeJxE",
	"6u/OR8e8ijwOWIJAGFH4ikgYxlL1jTjcEaWtXTQCLBhFRCDJSRiCj/Z39geDAbqixGM+IG+GOfYkcOGi",
	"s6tTdMP4lPg+0F1nwdS+ReBJ8Cdp8yWzI1S+e6PMjlASKoDZzxRAqIRb4I7WGBbJiyGhqXnuuw1La7Hn",
	"rKVGNR9qHfXR8qLupnMkgN8BR5KtociWSnAdCTxsgVlmtJf66QW71L+219fIqLiPxn6OgwBxiALsQQhU",
	"It35AWKRJCERkngoncof30YfdnrWMfExxZGYsa5U6sMd8ZJ/hvibUchgMBg0KWimlb+MLDhhvm6USAhF",
	"vf7z7t69f7vf1F+Iv50kbe0PBtkDmHM8d1wnpuSvGMwDmkxcJwowbeueRTzVQiZwq/m8UO+VxXu9IJ5u",
	"n92QisMGt3GAueM6EGvnLaYBCYks+Uu5hGvYsuT45oZ4k9vp4jQX53mw+HLFUFOVFsRxMxMqdZQPOTOV",
	"3C4yfa+2avVMV88w1H5qSGiyVyhD0xmjFG6xVLQpyC0FH2kNIv08iimRAmGBPEwZJR4OkA8eCXGAJHyT",
	"Bynuc1CyCnSHg1gR75TdAfrp1avXr9+/Grx+9+Htm/fv334YvN9FZ6CejzAXoNr9Fd/hsZYHncXhFLjG",
	"LiwlcCXe//z74P/+2N/56fqPwc5P198H7v6H+//4W525ejHnQL150Z5GV58c17kaHzmu88/LUa0RJRMw",
	"8fH8AdZk1TYKbRckdMtzsnLGW24GypN6ToM5SrqTCHt6cpVtKh9I2atwEWVINYIl4ygEiX0s8SJt6Id7",
	"QEARfO+rS79mATWY/WVKKF05V7PILhqnRqp7FUjJHoAENLr6tHc1Ptr75+UIhVhy8k2RKALszVAyeYjR",
	"sup20S967Sb/QyGeoxm+AwRhJOcoWcQHKAMuFMZCoimg2RJmfs5s8+QZ5OFo4KERP8AkbOdqls1Jj7ag",
	"kf3rRtGTV5ZK0Ssc8Sebtp/4SxMb+ZVNK4bWAB26l1rBzQJvKfvi+wl2XmAhvjLu95kIA7+TyLRhDCzz",
	"m199cEt+9Numzd5Cg9fLBb9Um+4R/BWD6Co3L7zVKpBR6qs5hJG2Xyf9EXgd9lgVfeMgmGLvy+SvGPh8",
	"QhoVXgMHvum/iCg4iji7A+3faTnrcCSl0om8rbrXnfdWBZEHg8FCZxV1VnoujMGtUckqpfda5x5OLLvN",
	"8r7A84BhP1F0QO6UTEJiWQJwE8RyXEeADhreYBIsQe9k7IQt29KUDbF2A5HZensLX2LPFXHcRDULQ62b",
	"gUIMcOh5EEnwu06Dfrl14P1bRDiICZalx30sYUeSEJxaVQmg/gTfSOAmBNDWC86FK3VdabNBMYeM3hDe",
	"khIZBQNc1Oz+6dz8UBKM+eBc37vfq+IGARiJr++vK6NJ4tf6LdN47V+XN+mm/V7XzGL+WJuJ1A19/F7c",
	"LyX7pA/3tXukLGJfAJk3r0uw+Ob1wnv3q2dmO+ToOhS+TnpH+Zu4tdh8g2X2w03joPgtIuj5s7WSZMd7",
	"XSXwS8B7cvZ5eHpyNDk5u7i6dNzs/4ej46Pjs8uT4enYcZ3j34cnp5PPx6OTn08Oh5cn52eT0fF/XZ2M",
	"jtUee3h4eH51djkZHY8vRyeHl/rHy9HJ8HRydDIefjot/DA8HR0Pj/41uRoXfhwdH56fjU+OjkcLbat/",
	"Ho8vJ+PL4eXx5PD87OfTk0Ml6PlF+vTZuep6ePQvJf7R8e8X55fHZ4f/Kj48Ui+fnvx+ksg2Ph59Pjk8",
	"nlydDT8PT06VhFmL56NJOp6L0fnlsRnO4fByeHr+j6vjyej488lY9VtoP//r6XB8OVEPJG3mfzg6Vl2O",
	"87eul0Yz5MSwiyaPWNQTpfFQ/MxFWUKXIQiBb6HmxO7hqLQdci0YuA9OLl+psTqTP2W3pJePuMah4IO5",
	"8WmPK914PcLHOgde9yy3bgDnxi0dxj6Rx3fQI5dAEkabtF23cjhgCX4n56Yl3a69SDJnfXWmRPt2su1G",
	"OfZ1wQRZjOhiUYrdFsJi7WK3B/o1FHHQQV+B4Bv2JCI+UEnkHBFaiObulhfV/k+Lwyp6LZUQ79/qXdCl",
	"e6Q14anxdRFHEeNyYiCqXzOVtaRfKVirm9p8SdqFbcXChq/OqDJl1Yq+asGWYrhdw84LAWV0eHqyY8aY",
	"nWyKJGCqtIW+wlQFqBnfSwQ+QKA2SyjENMYBSrYOiIPHuC/QlMnZYgQVe5XR95lhnKQOLMktSuToBiob",
	"CewGcIu9+aRwjrfuqrIHk5s4mEyRqgUw9T7DFCzmXknMFAqczFBIqBZ/UeCJgI0Hwx/6THTB7gvr1V1c",
	"/5lqSgt3Zd7AAvz1cr4i415nunu1/+b9mw+v37153zSZEfDJwutvG7Gi2wFdPciXVsTbmgUhmcTBagNt",
	"ZxPCSRtzE10Vxr1yVgICm85GLfuNlUNyTVUzoGhGhGRcn4Ob9pNkM8IokiQE9BULRJk0lAV+euCNKSJU",
	"+cHg6weFxGGkuKyWTBphwyciCvB8QnEIdU5yh2Tbxr5m2J+IeFpQSB0zfSG0mEXrfIVpIe21FnC6Zexy",
	"UP/25DKOTrt6QR7xXUQnU0xpqzBSCSD1bFXMKE9jLqqykMNcclYL01ESpMZempf2oTlG6LK81c5yAndp",
	"Nn0nACxsSxvRL+lIZdyGjMMS/zADqFbwmzydu3NJBAcH7Q/d0qZOdQPD9P2a47esk56qKvfQUmemy9VK",
	"02uGdx9zskjrx1rFqVXtjYvP5pu89gKNkxcOGb0DLnDSTp1USQ70am0kz5idX/dpKp9RrZ6favgtMceK",
	"8rL5yRWzIOTCyNzyslxYPIsWXzXPRdtZhR7dDoyracyqtTwpCCPK6DTA9AtK96KJlIAi4KHOg6MmzSd5",
	"YBcNleupMnSZyriSM0A4ljOgknh6y5ulWJk0/br0n55Hzr1PjAsHxC0c4rVOh5/yAe2qQf+ivbx5r1Rv",
	"xlFiwS6awg3jMMlpE2Hqp78mW5QJSTPEmJypNDHtS1CJGEd4qv51oDPS9DoTe3o5oVjAkravrk6O0j8R",
	"fxcdgfCScwKUP7mXd8148Xf9g29SMEsTudBb+zBIJk0rL7yqnKp9/9TdSao6pokqU2zKAKdmkVUMSTfU",
	"wmz6xe0fy51ZzUL9lbUVP2N7pGkc6AVCrPDfIvOZP62yo7IqOt9e8Ii/eo027y5NG9N5zfpbP4yvlbWm",
	"iAYhjFJjAfxh0MK0K28fqLm1z20rdlc/7orcWb8VbbtF6yhNc3tzXO8wr+zi4GA393Wyn1Y4PUmor3Zm",
	"1jXLpOk0ntJ8XqAfT35u8Xgf5szju21Xw4OYrMT8FuQDrYB66024v9jPspOwgpoLs1+arUxRq2z4PHX9",
	"umbJ9Ji3Jq+3E0ioNaEd8OS/FMAX+i4cfE3WTEDawEblEDGDh8L4VqkvuYrYJ+VixTaly03XFjuVkQlI",
	"9d4OLr3VerD84iXSyYv6lYe73ro60rmgGZHH4bqpqdfdop8JBL5A+cGK3njUHEKj5L0p6H1xgIW+iqRO",
	"dc3hLs8lQZJjKrQIu+hyBnOEeXpCrMLulKUv5Q8i+EaEFC4i1AtivcdJTrvALzYtDhBlOyxCHGTMqcju",
	"RSlfHfz8rNqpT6pdz015qIyP/iZROgGrE2eVsYxBnbP1WfePfxT2VwVkXr1914Qqf3U8h0rU0S/hUwfZ",
	"ehzVZbHi1TuhTGGbUO2DHACmGuh3BDjOg8XtlQ5ULaol50URphD0uSdSGVfWjpv1t3ogQnT3Q55YWl96",
	"pUNvoPvAQ9P5ZQND9qz18+OcDK7lZZeP7ypnfEZ1rWd3DbTrjnGdXeeHCBBn5x89IsVrXLTzWBgaJTVF",
	"8PvtHx8iEsRK+6ZOx3T5lqv2TMwm0241dSBSe0gWi8mambGbS8rdfCytlGZbtyWuxMsqm+g6FbrZsi6k",
	"4LZM2c2ar0Wc9C7y9i9dbe5Gc6X9VWoYgQDZ/7Zkt3t21cuPa7nB5buAjXcgSwNO77Xba5DrXINcz4jX",
	"uEZZVEY3S3/k205d/Osl95tW+Jk1pQ/7IZmpdJhcDV62z+tz23mtu6WF11fLVmMRaRele9LLhlvfUZ3G",
	"R+Ax6pGgF29ssrhBl432Ao2uiHZmA95I3srTieAvHbsgPvCXM9u3RMh+48XGh5hEnNypM1WVy7d49fDD",
	"oPYQ0Lyr60x1efNJYPPSAbjLtbJc/Yl1vgSXbKQf6DnShxS8paSP6jzUmlydbCYQesio2gl3tZcO0c2G",
	"mOa4kjLcETuEmHS7MOY6WaZ8TL9Q9rU+aOkxSkGfYK0ut+w6PpZ4IiRe+vf8ImInY2vlOjWHV6Y6wLFe",
	"GCqJsWfl7lMtxzRXjeuksZNJSESIpTfLNTwJIZwCFzMSqQfpHQ6IPzH30BxX9X/dQoxFmqeMQjPH6wqM",
	"mVdXMgGfiOTMQP11hmPRVKrOZ19pwLDK2pEtJnXJmGpKoWr7bNnq8la4WvBKDQ8uXxxtZNixgIdrNL9l",
	"WVh0iysyfyw1webdQRafKm0NFi9VFqexdpTlJVmCjyZ4/A26VpkpXimYxLzMKDEnzRlD1QbqZdQXFIZS",
	"Ym8Wds9P63kKJcj/wirTyW/Qvvnw9v27QafasWluU97HipF/wr2Sc5bfHXswNz4DuhXue909ms2naXmx",
	"kCwEPuHggbpKPBEqjks9KLXRDv46VRBhD9PnIhuxKPm0RsDEEhZJq0Gsmvk48jsqs66yRYZXlS4rAfZC",
	"ZyunZKXuVhhVp6sctZce2s1Q84KuNrdC6N/zSk0d5MVl+Otyha2AnLWHdf2OH5PCh0UDTXKu8qqIS6y0",
	"bdQFqA8lhzA1oIK51C+DvnPqOulmpRj7bXHrKlkTuTUb2U17lUVRmMmCHpsNpo+VLx1PF5TXjaySLw4k",
	"iTDvFcdO91bZRE0JxXzu1GZ69JqcJvFHgHttonuDe9UJaoEZPcsQVij3Ye+9rr5rZCoStc+Jq6BjY04c",
	"C3xdO6/tYm/y7xfK1hXGXxhO6dZPVYYVMziWrT/IUzGzzo5A/d6iTrY0F+jnpAzvejUmJQmBxVLvkOVX",
	"xr8k9S+maeEX8ImcmIK/+Tadg4gYFVCL5NULa1m53aV1g+svciWHkSsUoIqTd45pyn4h9D/ZtG0ctDr+",
	"9BbNxJQfTnMTTCJDMVaRByjyn5YfR7hOAFjApM9xWvLmsnCd60SmMnTXQtKL5eBNxYpCfzVyu9nUZIUw",
	"UglWWcBFLuWTSvN6xFIwj1smtHvKT+dI3PXyC1BLav31IY4XWJxmVapV5ShzUd95JZo8m6rkILcgrNwf",
	"8olSdkio3g7oFRJFSsiP3xfoogF5fk65SeglvfrhsUlqNXgwP9MLNEGc+2J2ThvMM421e9iIqZN2yvro",
	"9UmRBvTmmabbyGbmZeEjJCXINk2umt9x9zBff0Kusqye/hU1lvv0ssQvyZiqoYDnOpnI204u7ssmD5fE",
	"+uwSUZtMpFcCaXtXpu6bAZ+Bk5u5TV18/qmLyUz3ikgUv/FtVpdatM3f485eXBRILVnzFemxYqP0q8c4",
	"ksA/AeZQ82HEI/BNEacpkzvmYeRx0P4TDnbRGUPF06mdL+raqs4IUN6U5j0tcNJBJtVMyiiJQZr8B/aF",
	"aBsgqlsv+a9rzqScyeQXJuSOeThvBUdEncbdq8EResNUA5JIBXLOIZ4SChKNB/toeHHiuE6WmeTs7w52",
	"BwZ8KY6I89F5vTvYfZ18dXGmNbOHI7J3t7+nalntaU9sJ7lFumeyDLXFMlFTKfMqOW9H+otDKMIch5Dc",
	"k6Y++nV8foZukvvDmANKAXI3+cuU+XNkDs3Q/jv0G/m0WwS7E1+NLZGgmDvqOnk/GiG0ImeAkwCrUeQ5",
	"J7eEOkWjSdggcVBaHExeZ0SRfm7DY1SmbojaOHtazr0/zcFZ3vLK7/Mv+cjN/f19VVj9QxIM0RP1ajDY",
	"hBiZi3Zfvfw9jrV9K/t584B9Dy9O9GdMarvEN4CSzA/d6/5Wen29lV7fbKXXn7bR66tH79U1EKFX0ggk",
	"n+8M06S8ykvgMarKz+sTPMTVs04tcLTy85VUb7dgUQUadD7+ca3+X0L6gCmA3B6064+eDLOryD80qBc+",
	"UfPIOF78dIxFcIvgFsFfFIKzWG4XwlksHxvD3SUt/3PncDz6eefSBBXz9mpJoITHb2psyCKnRU6LnM8B",
	"Ob9Xgy9/XN8vomka4trhIGCbqGpCtqULwT+6g1xzu7mVo/xqMxJkl7msy2yB3wL/y3GZyyC/l35reasR",
	"7kSE5wv35SomrWDf+uMWli0svxxY5qaiw1a97kSEZxKRLtfIeGRfu7ZChHW1LaZbTH9JmC6A+jtJoo6X",
	"3TnaGrwraT4XhfnhET4v9vLo+F6qiGOR3SK7RfaXg+wir2l/C9sA83+ArJST2mCGRaUnC3YW7CzYveyj",
	"Qu3Tzneym5Vb8mmTvPtjc3fuh3Zmi5dFHjmDrnR7waK7RXeL7i/ClfWwxAG7jWGpHzssfdw9pvmH1pD5",
	"ksMuOjSfl0uumiN1GX0aABIUR2LGZPKpeH15qEoDB0gX25WgPlinKyWhFONqPd7DTN4NgmHWicVDi4cW",
	"D1+6txvCVjf5+VncxgDPdGHhzsKdhTsLd6X7z9vPAd7GveeW1yuWt9+t1sDmr1lv5Yis0L89J7PsYtnF",
	"skuFXfY8TD3YZvz4UAvwhDnGXuGz4GrB1YJrO3DN7nZs3XtP0PQi/86t9dy73x3p7LxbBrAMYBngJTNA",
	"/vj2g9bjVJbNB6+zrmyAwSKgRcCXjYD6CbHH4Y59gR0mZ0ZfWwtkKznOlRgmkVZYf7hbSkaSYZK6xdYh",
	"tnRg6cDSQTMdpJ/Ea5Hp9tlU0y4nuX2FKUob2UVj/TOK8C3sRcAn6h+GN1SO24H+C9r/u4uyv+7v7r4d",
	"7KIT6gWxDwLN9JefNLdg7s3IHfjIMwl0Wcac2zEv7txIWMyPq+MXLWpOAkrAJvBPTODV/pv3bz68fvfm",
	"fYNduEt6Mupo19vbpu/GXm9wQ7GgS5sXY5nEMollkiqT7EUBpiv2FW0IZehJxjV3oBvOQmSEOECJ5+8i",
	"5aVrsri6OjlCJz6EEZNAvfnObzBHKZZmzKQ3Jf8dDwavvf9MtiMuogzFZouTbGQ6scshBywhA8OLANMf",
	"Z/PStsGKXlvKXPuBk41tgYozkExKh23Q/uboUVtEzVpLbwWQMIwlVhcCOCTfqbN8afnS8uUL5cu978S/",
	"3zNbn+dOnsNkmG3YM8JylhMS8dfiINdS8mNTspnqrVzftZxsOdlysuXk9Tg5g4JnTsojNU7LyS+Ak0fG",
	"oi0pW1K2pGxJ+YmTckCS/kDtjtdhYVNww6TGJUSrGJezAJDHQkioWc4gp2e4U6eYXzmRSvMRYCn0A0D1",
	"N3ZDhVDeDLwvKKY+8LT6x55uM2DeF1Fb4QMxnnF1IZfmIPlPQEIi07wZdNGew8daRxnEJpr7cePSGyLD",
	"VD+JtrbKgokI9ijVMp5lPMt4FcaTnODAEl7zMWyKppcQwC3H4aVWnD2Offx9Zu1MbJVhS5IsJ9pMt1JZ",
	"fYDniN0kCwOHgDxlZmbnuYlT45ZCWm/AegPWG3ih3oAKRq+Rpfv8fYFiwq/W2WOErx8l5VaP5hBzWyfI",
	"koIlBUsKZVLYmxEhGZ/bnWIndvjFaM2ecT7ivtAofas7QiOD3WZZRrWMahm1jlG/wNxutbqQaRKO/KF3",
	"W+N4mk2zGo4lBksMlhgsMZSIIUX8NfNBc9zHOi+0mBK6u5gSujwb9IIzqQuv5E1LzG9BJmVaBAQ3qCAz",
	"8oES9d4IsGAUSU7CEHy0v7M/GAzQFSUe8wF5M8yxJ4ELnVR6dnV6UJNw2jEzJWOMUUGHdvP1zA7+CpO7",
	"1U1eQQ670bN8bvnc8nkdn4s4ihiX7apC7umyZqbqWV7xzBQv2/GB67I1mtIPckLmLJYgUtJGd6l3UNja",
	"7Rb2Y/vvfiOfDlAYB5JEmEvz6+B38unv+m8uYhTQDQlA/+gij9E74EIrG/0VM4nfqj+oDWHCyys3cGOj",
	"gh9++6aHYcHegv1j97r/2lKMpZgGitmbYtqy2OYz4pnxAs98stcKH2dHluvb1gW1vGl50/Lmj8mbjdkt",
	"L2ePZlNWHp8/t5mxYve0lpstN1tufrLcHIIQ+BbEyyPn8sVDA9S/J+qw/PxcTjXL85r6AK6T2daeEmzH",
	"xxJ3bzRtY5uuRWqxNaBx/I0ISegtIsWrkYkn8rC3IJtlGWOFC4SiKfa+APUPEAePRAqRkA8B0clzFMAX",
	"CL4pMYhE2FPIE4B/qxHC+kjWR7I+kvWRHt1H4oD9l+cfDXP03cJBs41eZKEDbD8LZunT0qelzx+UPoXE",
	"EuzBOZdjrQhLno9Hnlrjlj0te1r2tOz55NnTPGfvrba7t2qcAudRirwmXdkDXMsPFqktUuu6rjsZMmVX",
	"Sz1GPRKAreOz+jMlRk1Z7UylzfP0GbtBen43SrHodJn01YOJkNmazcCyBG4J3BJ4icAN6Bn69sFb+zNh",
	"z5+9j8Ajfpm6R4kaLXE/N+I+Mitiq3UgUiEsg1sGtwxuGXwFg+sNuCA+cMvhjTtwrSfL43YDXsPiD0dn",
	"JcOy3G2523L3i+VuUajP2q5eU5EKFQUXOBBhDoUMIf0XnTwU4m9KUykv1p0gFgvFOo9UkNaCnwU/C34W",
	"/LREq6qTPzYApr7r9otyl0zoEHsz2DlkVHIWLGrpTO24kKceQh4HH6gkOBAlOwKqbOYPJ90ROdeLnve9",
	"xV6LvRZ7nzv2vtgaofmVLVvjxEKtTaG2AP+MAf5FVxprVWHMFgOzxcAsUVqitET5sonypZf9alXuyx5O",
	"28pctjKXrcxlHRbrsFiH5Wk4LEmiH5YSe7MQ6EuO6Q5zJTy5Lz8xT4LcEZIDDss2lPUzJRTzeU1PC+aT",
	"Zjbms4589pUGDPsHiDJEaECoWhFUTSS9rRwkJhLuHBERMUHS5JPlPpU9ErRsZtnMstkG2ezFV5RcXUnS",
	"Fn20RR8tl1kus1z2A3DZyy3v2KKso63AaCswWiqzVGap7ClTWfkucUsu20RqfnI42eIyrj2a3CR3FSdg",
	"KyeITbdm688PzeOuvcBr2dneo7A8uWGe3PNizlsfwW3oJtthIkOFMjcGzHXdWVC0oGhB8eWBopKUUxxo",
	"ZIQAbjkO9/5kU7HnBZiE29xGqP4vjUi/sqlwNuMn63624iDrnm0ivcVfi7/PHn+xjyMJ/BNgDrwV/ppi",
	"cBodtojCLIwCkFAA4kdL1NpATMSMIgHd7YC+UajFfYv7Fvct7mcRiR4f4tg4+mdfHng6X7f4ASLvmdbs",
	"1yIsw1iGsQzzRBim65ciNk4vyWcYHrts84ZQf6vfGbDfF7CYbzHfYn4D5rf5tsDjbCq0EE+lYP+PsqfQ",
	"SrMV8C27WHax7PLI7HJ///8DAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
