// Package wire provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package wire

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AccountLocale.
const (
	AccountLocaleEn AccountLocale = "en"
	AccountLocaleRu AccountLocale = "ru"
)

// Valid indicates whether the value is a known member of the AccountLocale enum.
func (e AccountLocale) Valid() bool {
	switch e {
	case AccountLocaleEn:
		return true
	case AccountLocaleRu:
		return true
	default:
		return false
	}
}

// Defines values for AccountTelegramLinked.
const (
	False AccountTelegramLinked = false
)

// Valid indicates whether the value is a known member of the AccountTelegramLinked enum.
func (e AccountTelegramLinked) Valid() bool {
	switch e {
	case False:
		return true
	default:
		return false
	}
}

// Defines values for ClaimInputLimit.
const (
	N1 ClaimInputLimit = 1
)

// Valid indicates whether the value is a known member of the ClaimInputLimit enum.
func (e ClaimInputLimit) Valid() bool {
	switch e {
	case N1:
		return true
	default:
		return false
	}
}

// Defines values for DecisionInputDecision.
const (
	Approve DecisionInputDecision = "approve"
	Reject  DecisionInputDecision = "reject"
)

// Valid indicates whether the value is a known member of the DecisionInputDecision enum.
func (e DecisionInputDecision) Valid() bool {
	switch e {
	case Approve:
		return true
	case Reject:
		return true
	default:
		return false
	}
}

// Defines values for DecisionResultDeliveryState.
const (
	DecisionResultDeliveryStateFailed  DecisionResultDeliveryState = "failed"
	DecisionResultDeliveryStatePending DecisionResultDeliveryState = "pending"
	DecisionResultDeliveryStateSent    DecisionResultDeliveryState = "sent"
)

// Valid indicates whether the value is a known member of the DecisionResultDeliveryState enum.
func (e DecisionResultDeliveryState) Valid() bool {
	switch e {
	case DecisionResultDeliveryStateFailed:
		return true
	case DecisionResultDeliveryStatePending:
		return true
	case DecisionResultDeliveryStateSent:
		return true
	default:
		return false
	}
}

// Defines values for ErrorBodyCode.
const (
	ACCOUNTRESTRICTED            ErrorBodyCode = "ACCOUNT_RESTRICTED"
	EMAILVERIFICATIONREQUIRED    ErrorBodyCode = "EMAIL_VERIFICATION_REQUIRED"
	IDEMPOTENCYCONFLICT          ErrorBodyCode = "IDEMPOTENCY_CONFLICT"
	INVALIDCREDENTIALS           ErrorBodyCode = "INVALID_CREDENTIALS"
	INVALIDINPUT                 ErrorBodyCode = "INVALID_INPUT"
	OPERATIONNOTREADY            ErrorBodyCode = "OPERATION_NOT_READY"
	RATELIMITED                  ErrorBodyCode = "RATE_LIMITED"
	REQUESTSTATECONFLICT         ErrorBodyCode = "REQUEST_STATE_CONFLICT"
	SERVICEUNAVAILABLE           ErrorBodyCode = "SERVICE_UNAVAILABLE"
	TRIALALREADYUSED             ErrorBodyCode = "TRIAL_ALREADY_USED"
	TRIALDISABLED                ErrorBodyCode = "TRIAL_DISABLED"
	TRIALRECONSIDERATIONREQUIRED ErrorBodyCode = "TRIAL_RECONSIDERATION_REQUIRED"
)

// Valid indicates whether the value is a known member of the ErrorBodyCode enum.
func (e ErrorBodyCode) Valid() bool {
	switch e {
	case ACCOUNTRESTRICTED:
		return true
	case EMAILVERIFICATIONREQUIRED:
		return true
	case IDEMPOTENCYCONFLICT:
		return true
	case INVALIDCREDENTIALS:
		return true
	case INVALIDINPUT:
		return true
	case OPERATIONNOTREADY:
		return true
	case RATELIMITED:
		return true
	case REQUESTSTATECONFLICT:
		return true
	case SERVICEUNAVAILABLE:
		return true
	case TRIALALREADYUSED:
		return true
	case TRIALDISABLED:
		return true
	case TRIALRECONSIDERATIONREQUIRED:
		return true
	default:
		return false
	}
}

// Defines values for ErrorBodyCurrentRequestStatus.
const (
	ErrorBodyCurrentRequestStatusApproved ErrorBodyCurrentRequestStatus = "approved"
	ErrorBodyCurrentRequestStatusPending  ErrorBodyCurrentRequestStatus = "pending"
	ErrorBodyCurrentRequestStatusRejected ErrorBodyCurrentRequestStatus = "rejected"
)

// Valid indicates whether the value is a known member of the ErrorBodyCurrentRequestStatus enum.
func (e ErrorBodyCurrentRequestStatus) Valid() bool {
	switch e {
	case ErrorBodyCurrentRequestStatusApproved:
		return true
	case ErrorBodyCurrentRequestStatusPending:
		return true
	case ErrorBodyCurrentRequestStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for PasswordResetInputLocale.
const (
	PasswordResetInputLocaleEn PasswordResetInputLocale = "en"
	PasswordResetInputLocaleRu PasswordResetInputLocale = "ru"
)

// Valid indicates whether the value is a known member of the PasswordResetInputLocale enum.
func (e PasswordResetInputLocale) Valid() bool {
	switch e {
	case PasswordResetInputLocaleEn:
		return true
	case PasswordResetInputLocaleRu:
		return true
	default:
		return false
	}
}

// Defines values for ReconcileResultStatus.
const (
	ReconcileResultStatusApplied      ReconcileResultStatus = "applied"
	ReconcileResultStatusNeedsReview  ReconcileResultStatus = "needs_review"
	ReconcileResultStatusPending      ReconcileResultStatus = "pending"
	ReconcileResultStatusProvisioning ReconcileResultStatus = "provisioning"
)

// Valid indicates whether the value is a known member of the ReconcileResultStatus enum.
func (e ReconcileResultStatus) Valid() bool {
	switch e {
	case ReconcileResultStatusApplied:
		return true
	case ReconcileResultStatusNeedsReview:
		return true
	case ReconcileResultStatusPending:
		return true
	case ReconcileResultStatusProvisioning:
		return true
	default:
		return false
	}
}

// Defines values for RegisterInputLocale.
const (
	RegisterInputLocaleEn RegisterInputLocale = "en"
	RegisterInputLocaleRu RegisterInputLocale = "ru"
)

// Valid indicates whether the value is a known member of the RegisterInputLocale enum.
func (e RegisterInputLocale) Valid() bool {
	switch e {
	case RegisterInputLocaleEn:
		return true
	case RegisterInputLocaleRu:
		return true
	default:
		return false
	}
}

// Defines values for SubscriptionStatus.
const (
	SubscriptionStatusActive       SubscriptionStatus = "active"
	SubscriptionStatusExpired      SubscriptionStatus = "expired"
	SubscriptionStatusNeedsReview  SubscriptionStatus = "needs_review"
	SubscriptionStatusNone         SubscriptionStatus = "none"
	SubscriptionStatusProvisioning SubscriptionStatus = "provisioning"
)

// Valid indicates whether the value is a known member of the SubscriptionStatus enum.
func (e SubscriptionStatus) Valid() bool {
	switch e {
	case SubscriptionStatusActive:
		return true
	case SubscriptionStatusExpired:
		return true
	case SubscriptionStatusNeedsReview:
		return true
	case SubscriptionStatusNone:
		return true
	case SubscriptionStatusProvisioning:
		return true
	default:
		return false
	}
}

// Defines values for TelegramFailedCode.
const (
	EditFailed      TelegramFailedCode = "edit_failed"
	Forbidden       TelegramFailedCode = "forbidden"
	InvalidResponse TelegramFailedCode = "invalid_response"
	Network         TelegramFailedCode = "network"
	Timeout         TelegramFailedCode = "timeout"
)

// Valid indicates whether the value is a known member of the TelegramFailedCode enum.
func (e TelegramFailedCode) Valid() bool {
	switch e {
	case EditFailed:
		return true
	case Forbidden:
		return true
	case InvalidResponse:
		return true
	case Network:
		return true
	case Timeout:
		return true
	default:
		return false
	}
}

// Defines values for TelegramFailedKind.
const (
	DeliveryFailed TelegramFailedKind = "delivery_failed"
)

// Valid indicates whether the value is a known member of the TelegramFailedKind enum.
func (e TelegramFailedKind) Valid() bool {
	switch e {
	case DeliveryFailed:
		return true
	default:
		return false
	}
}

// Defines values for TelegramJobKind.
const (
	ApprovalCard     TelegramJobKind = "approval_card"
	ProvisionApplied TelegramJobKind = "provision_applied"
	ProvisionReview  TelegramJobKind = "provision_review"
	RequestDecided   TelegramJobKind = "request_decided"
)

// Valid indicates whether the value is a known member of the TelegramJobKind enum.
func (e TelegramJobKind) Valid() bool {
	switch e {
	case ApprovalCard:
		return true
	case ProvisionApplied:
		return true
	case ProvisionReview:
		return true
	case RequestDecided:
		return true
	default:
		return false
	}
}

// Defines values for TelegramPayloadStatus.
const (
	TelegramPayloadStatusActive       TelegramPayloadStatus = "active"
	TelegramPayloadStatusApproved     TelegramPayloadStatus = "approved"
	TelegramPayloadStatusExpired      TelegramPayloadStatus = "expired"
	TelegramPayloadStatusNeedsReview  TelegramPayloadStatus = "needs_review"
	TelegramPayloadStatusPending      TelegramPayloadStatus = "pending"
	TelegramPayloadStatusProvisioning TelegramPayloadStatus = "provisioning"
	TelegramPayloadStatusRejected     TelegramPayloadStatus = "rejected"
)

// Valid indicates whether the value is a known member of the TelegramPayloadStatus enum.
func (e TelegramPayloadStatus) Valid() bool {
	switch e {
	case TelegramPayloadStatusActive:
		return true
	case TelegramPayloadStatusApproved:
		return true
	case TelegramPayloadStatusExpired:
		return true
	case TelegramPayloadStatusNeedsReview:
		return true
	case TelegramPayloadStatusPending:
		return true
	case TelegramPayloadStatusProvisioning:
		return true
	case TelegramPayloadStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for TelegramSentKind.
const (
	TelegramSentKindSent TelegramSentKind = "sent"
)

// Valid indicates whether the value is a known member of the TelegramSentKind enum.
func (e TelegramSentKind) Valid() bool {
	switch e {
	case TelegramSentKindSent:
		return true
	default:
		return false
	}
}

// Defines values for TrialRequestStatus.
const (
	TrialRequestStatusApproved TrialRequestStatus = "approved"
	TrialRequestStatusPending  TrialRequestStatus = "pending"
	TrialRequestStatusRejected TrialRequestStatus = "rejected"
)

// Valid indicates whether the value is a known member of the TrialRequestStatus enum.
func (e TrialRequestStatus) Valid() bool {
	switch e {
	case TrialRequestStatusApproved:
		return true
	case TrialRequestStatusPending:
		return true
	case TrialRequestStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for VerifyResultVerified.
const (
	True VerifyResultVerified = true
)

// Valid indicates whether the value is a known member of the VerifyResultVerified enum.
func (e VerifyResultVerified) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// APIError defines model for APIError.
type APIError struct {
	Error ErrorBody `json:"error"`
}

// Account defines model for Account.
type Account struct {
	AccountId      openapi_types.UUID    `json:"account_id"`
	Email          openapi_types.Email   `json:"email"`
	EmailVerified  bool                  `json:"email_verified"`
	Locale         AccountLocale         `json:"locale"`
	TelegramLinked AccountTelegramLinked `json:"telegram_linked"`
}

// AccountLocale defines model for Account.Locale.
type AccountLocale string

// AccountTelegramLinked defines model for Account.TelegramLinked.
type AccountTelegramLinked bool

// AccountResult defines model for AccountResult.
type AccountResult struct {
	Account      Account      `json:"account"`
	Capabilities Capabilities `json:"capabilities"`
	CsrfToken    string       `json:"csrf_token"`
}

// AccountSecurity defines model for AccountSecurity.
type AccountSecurity struct {
	Email              openapi_types.Email `json:"email"`
	HasOtherSessions   bool                `json:"has_other_sessions"`
	PendingEmailChange *PendingEmailChange `json:"pending_email_change"`
}

// Capabilities defines model for Capabilities.
type Capabilities struct {
	TrialAvailable bool `json:"trial_available"`
}

// ClaimInput defines model for ClaimInput.
type ClaimInput struct {
	Limit ClaimInputLimit `json:"limit"`
}

// ClaimInputLimit defines model for ClaimInput.Limit.
type ClaimInputLimit int

// ClaimResult defines model for ClaimResult.
type ClaimResult struct {
	Jobs []TelegramJob `json:"jobs"`
}

// CompleteResult defines model for CompleteResult.
type CompleteResult = map[string]interface{}

// CurrentPasswordInput defines model for CurrentPasswordInput.
type CurrentPasswordInput struct {
	CurrentPassword string `json:"current_password"`
}

// CurrentTrialRequest defines model for CurrentTrialRequest.
type CurrentTrialRequest struct {
	Request *TrialRequest `json:"request"`
}

// DecisionInput defines model for DecisionInput.
type DecisionInput struct {
	CallbackQueryId string                `json:"callback_query_id"`
	Decision        DecisionInputDecision `json:"decision"`
	OperatorTgId    int64                 `json:"operator_tg_id"`
	Reason          *string               `json:"reason,omitempty"`
}

// DecisionInputDecision defines model for DecisionInput.Decision.
type DecisionInputDecision string

// DecisionResult defines model for DecisionResult.
type DecisionResult struct {
	Card          TelegramPayload             `json:"card"`
	DeliveryState DecisionResultDeliveryState `json:"delivery_state"`
	OperationId   *openapi_types.UUID         `json:"operation_id"`
	Request       TrialRequest                `json:"request"`
}

// DecisionResultDeliveryState defines model for DecisionResult.DeliveryState.
type DecisionResultDeliveryState string

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Code                 ErrorBodyCode                  `json:"code"`
	CurrentRequestStatus *ErrorBodyCurrentRequestStatus `json:"current_request_status,omitempty"`
	Message              string                         `json:"message"`
	OperationId          *openapi_types.UUID            `json:"operation_id,omitempty"`
	RequestId            openapi_types.UUID             `json:"request_id"`
}

// ErrorBodyCode defines model for ErrorBody.Code.
type ErrorBodyCode string

// ErrorBodyCurrentRequestStatus defines model for ErrorBody.CurrentRequestStatus.
type ErrorBodyCurrentRequestStatus string

// LoginInput defines model for LoginInput.
type LoginInput struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResult defines model for LoginResult.
type LoginResult struct {
	Account   Account `json:"account"`
	CsrfToken string  `json:"csrf_token"`
}

// PasswordChangeInput defines model for PasswordChangeInput.
type PasswordChangeInput struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// PasswordResetAccepted defines model for PasswordResetAccepted.
type PasswordResetAccepted struct {
	ChallengeId openapi_types.UUID `json:"challenge_id"`
	ResendAfter int64              `json:"resend_after"`
}

// PasswordResetCompleteInput defines model for PasswordResetCompleteInput.
type PasswordResetCompleteInput struct {
	ChallengeId *openapi_types.UUID `json:"challenge_id,omitempty"`
	Code        *string             `json:"code,omitempty"`
	NewPassword string              `json:"new_password"`
	Token       *string             `json:"token,omitempty"`
	union       json.RawMessage
}

// PasswordResetCompleteInput0 defines model for PasswordResetCompleteInput.0.
type PasswordResetCompleteInput0 = interface{}

// PasswordResetCompleteInput1 defines model for PasswordResetCompleteInput.1.
type PasswordResetCompleteInput1 = interface{}

// PasswordResetInput defines model for PasswordResetInput.
type PasswordResetInput struct {
	Email  openapi_types.Email      `json:"email"`
	Locale PasswordResetInputLocale `json:"locale"`
}

// PasswordResetInputLocale defines model for PasswordResetInput.Locale.
type PasswordResetInputLocale string

// PendingEmailChange defines model for PendingEmailChange.
type PendingEmailChange struct {
	CurrentEmailConfirmed bool                `json:"current_email_confirmed"`
	ExpiresAt             time.Time           `json:"expires_at"`
	NewEmail              openapi_types.Email `json:"new_email"`
	NewEmailConfirmed     bool                `json:"new_email_confirmed"`
}

// ReconcileInput defines model for ReconcileInput.
type ReconcileInput struct {
	OperatorTgId int64  `json:"operator_tg_id"`
	Reason       string `json:"reason"`
}

// ReconcileResult defines model for ReconcileResult.
type ReconcileResult struct {
	OperationId openapi_types.UUID    `json:"operation_id"`
	Status      ReconcileResultStatus `json:"status"`
}

// ReconcileResultStatus defines model for ReconcileResult.Status.
type ReconcileResultStatus string

// ReconsiderInput defines model for ReconsiderInput.
type ReconsiderInput struct {
	OperatorTgId int64  `json:"operator_tg_id"`
	Reason       string `json:"reason"`
}

// RegisterInput defines model for RegisterInput.
type RegisterInput struct {
	AcceptedPrivacyVersion string              `json:"accepted_privacy_version"`
	AcceptedTermsVersion   string              `json:"accepted_terms_version"`
	Email                  openapi_types.Email `json:"email"`
	Locale                 RegisterInputLocale `json:"locale"`
}

// RegisterInputLocale defines model for RegisterInput.Locale.
type RegisterInputLocale string

// RegistrationAccepted defines model for RegistrationAccepted.
type RegistrationAccepted struct {
	ChallengeId openapi_types.UUID `json:"challenge_id"`
	ResendAfter int64              `json:"resend_after"`
}

// ResendAccepted defines model for ResendAccepted.
type ResendAccepted struct {
	ResendAfter int64 `json:"resend_after"`
}

// ResendInput defines model for ResendInput.
type ResendInput struct {
	Email openapi_types.Email `json:"email"`
}

// SessionContext defines model for SessionContext.
type SessionContext struct {
	CsrfToken string `json:"csrf_token"`
}

// Subscription defines model for Subscription.
type Subscription struct {
	DataStale         bool               `json:"data_stale"`
	Devices           int64              `json:"devices"`
	ExpiresAt         *time.Time         `json:"expires_at"`
	ObservedAt        *time.Time         `json:"observed_at"`
	Status            SubscriptionStatus `json:"status"`
	TrafficLimitBytes int64              `json:"traffic_limit_bytes"`
	TrafficUsedBytes  *int64             `json:"traffic_used_bytes"`
}

// SubscriptionStatus defines model for Subscription.Status.
type SubscriptionStatus string

// SubscriptionKey defines model for SubscriptionKey.
type SubscriptionKey struct {
	SubscriptionUrl string `json:"subscription_url"`
}

// TelegramFailed defines model for TelegramFailed.
type TelegramFailed struct {
	Code TelegramFailedCode `json:"code"`
	Kind TelegramFailedKind `json:"kind"`
}

// TelegramFailedCode defines model for TelegramFailed.Code.
type TelegramFailedCode string

// TelegramFailedKind defines model for TelegramFailed.Kind.
type TelegramFailedKind string

// TelegramJob defines model for TelegramJob.
type TelegramJob struct {
	ChatId         int64              `json:"chat_id"`
	JobId          openapi_types.UUID `json:"job_id"`
	Kind           TelegramJobKind    `json:"kind"`
	LeaseExpiresAt time.Time          `json:"lease_expires_at"`
	LeaseToken     string             `json:"lease_token"`
	Payload        TelegramPayload    `json:"payload"`
}

// TelegramJobKind defines model for TelegramJob.Kind.
type TelegramJobKind string

// TelegramPayload defines model for TelegramPayload.
type TelegramPayload struct {
	Comment         string                `json:"comment"`
	CreatedAt       time.Time             `json:"created_at"`
	Email           openapi_types.Email   `json:"email"`
	OperationId     *openapi_types.UUID   `json:"operation_id"`
	RequestId       openapi_types.UUID    `json:"request_id"`
	Status          TelegramPayloadStatus `json:"status"`
	TargetMessageId *int64                `json:"target_message_id"`
}

// TelegramPayloadStatus defines model for TelegramPayload.Status.
type TelegramPayloadStatus string

// TelegramResult defines model for TelegramResult.
type TelegramResult struct {
	union json.RawMessage
}

// TelegramResultInput defines model for TelegramResultInput.
type TelegramResultInput struct {
	LeaseToken string         `json:"lease_token"`
	Result     TelegramResult `json:"result"`
}

// TelegramSent defines model for TelegramSent.
type TelegramSent struct {
	ChatId    int64            `json:"chat_id"`
	Kind      TelegramSentKind `json:"kind"`
	MessageId int64            `json:"message_id"`
}

// TelegramSentKind defines model for TelegramSent.Kind.
type TelegramSentKind string

// TrialRequest defines model for TrialRequest.
type TrialRequest struct {
	CreatedAt         time.Time           `json:"created_at"`
	DecidedAt         *time.Time          `json:"decided_at"`
	OperationId       *openapi_types.UUID `json:"operation_id"`
	PreviousRequestId *openapi_types.UUID `json:"previous_request_id"`
	RequestId         openapi_types.UUID  `json:"request_id"`
	Status            TrialRequestStatus  `json:"status"`
}

// TrialRequestStatus defines model for TrialRequest.Status.
type TrialRequestStatus string

// TrialRequestInput defines model for TrialRequestInput.
type TrialRequestInput struct {
	Comment *string `json:"comment,omitempty"`
}

// VerifyInput defines model for VerifyInput.
type VerifyInput struct {
	ChallengeId *openapi_types.UUID `json:"challenge_id,omitempty"`
	Code        *string             `json:"code,omitempty"`
	NewPassword string              `json:"new_password"`
	Token       *string             `json:"token,omitempty"`
	union       json.RawMessage
}

// VerifyInput0 defines model for VerifyInput.0.
type VerifyInput0 = interface{}

// VerifyInput1 defines model for VerifyInput.1.
type VerifyInput1 = interface{}

// VerifyResult defines model for VerifyResult.
type VerifyResult struct {
	Verified VerifyResultVerified `json:"verified"`
}

// VerifyResultVerified defines model for VerifyResult.Verified.
type VerifyResultVerified bool

// LoginAccountParams defines parameters for LoginAccount.
type LoginAccountParams struct {
	Origin string `json:"Origin"`
}

// LogoutAccountParams defines parameters for LogoutAccount.
type LogoutAccountParams struct {
	Origin     string  `json:"Origin"`
	XCSRFToken *string `json:"X-CSRF-Token,omitempty"`
}

// RequestPasswordResetParams defines parameters for RequestPasswordReset.
type RequestPasswordResetParams struct {
	Origin string `json:"Origin"`
}

// CompletePasswordResetParams defines parameters for CompletePasswordReset.
type CompletePasswordResetParams struct {
	Origin string `json:"Origin"`
}

// RegisterAccountParams defines parameters for RegisterAccount.
type RegisterAccountParams struct {
	Origin string `json:"Origin"`
}

// ResendVerificationParams defines parameters for ResendVerification.
type ResendVerificationParams struct {
	Origin string `json:"Origin"`
}

// VerifyEmailParams defines parameters for VerifyEmail.
type VerifyEmailParams struct {
	Origin string `json:"Origin"`
}

// ChangePasswordParams defines parameters for ChangePassword.
type ChangePasswordParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// RevokeOtherSessionsParams defines parameters for RevokeOtherSessions.
type RevokeOtherSessionsParams struct {
	Origin     string `json:"Origin"`
	XCSRFToken string `json:"X-CSRF-Token"`
}

// CreateTrialRequestParams defines parameters for CreateTrialRequest.
type CreateTrialRequestParams struct {
	Origin         string             `json:"Origin"`
	XCSRFToken     string             `json:"X-CSRF-Token"`
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// ReconcileTrialOperationParams defines parameters for ReconcileTrialOperation.
type ReconcileTrialOperationParams struct {
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// ReconsiderTrialRequestParams defines parameters for ReconsiderTrialRequest.
type ReconsiderTrialRequestParams struct {
	IdempotencyKey openapi_types.UUID `json:"Idempotency-Key"`
}

// LoginAccountJSONRequestBody defines body for LoginAccount for application/json ContentType.
type LoginAccountJSONRequestBody = LoginInput

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody = PasswordResetInput

// CompletePasswordResetJSONRequestBody defines body for CompletePasswordReset for application/json ContentType.
type CompletePasswordResetJSONRequestBody = PasswordResetCompleteInput

// RegisterAccountJSONRequestBody defines body for RegisterAccount for application/json ContentType.
type RegisterAccountJSONRequestBody = RegisterInput

// ResendVerificationJSONRequestBody defines body for ResendVerification for application/json ContentType.
type ResendVerificationJSONRequestBody = ResendInput

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody = VerifyInput

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = PasswordChangeInput

// RevokeOtherSessionsJSONRequestBody defines body for RevokeOtherSessions for application/json ContentType.
type RevokeOtherSessionsJSONRequestBody = CurrentPasswordInput

// CreateTrialRequestJSONRequestBody defines body for CreateTrialRequest for application/json ContentType.
type CreateTrialRequestJSONRequestBody = TrialRequestInput

// ClaimTelegramJobsJSONRequestBody defines body for ClaimTelegramJobs for application/json ContentType.
type ClaimTelegramJobsJSONRequestBody = ClaimInput

// CompleteTelegramJobJSONRequestBody defines body for CompleteTelegramJob for application/json ContentType.
type CompleteTelegramJobJSONRequestBody = TelegramResultInput

// ReconcileTrialOperationJSONRequestBody defines body for ReconcileTrialOperation for application/json ContentType.
type ReconcileTrialOperationJSONRequestBody = ReconcileInput

// DecideTrialRequestJSONRequestBody defines body for DecideTrialRequest for application/json ContentType.
type DecideTrialRequestJSONRequestBody = DecisionInput

// ReconsiderTrialRequestJSONRequestBody defines body for ReconsiderTrialRequest for application/json ContentType.
type ReconsiderTrialRequestJSONRequestBody = ReconsiderInput

// AsPasswordResetCompleteInput0 returns the union data inside the PasswordResetCompleteInput as a PasswordResetCompleteInput0
func (t PasswordResetCompleteInput) AsPasswordResetCompleteInput0() (PasswordResetCompleteInput0, error) {
	var body PasswordResetCompleteInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPasswordResetCompleteInput0 overwrites any union data inside the PasswordResetCompleteInput as the provided PasswordResetCompleteInput0
func (t *PasswordResetCompleteInput) FromPasswordResetCompleteInput0(v PasswordResetCompleteInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePasswordResetCompleteInput0 performs a merge with any union data inside the PasswordResetCompleteInput, using the provided PasswordResetCompleteInput0
func (t *PasswordResetCompleteInput) MergePasswordResetCompleteInput0(v PasswordResetCompleteInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPasswordResetCompleteInput1 returns the union data inside the PasswordResetCompleteInput as a PasswordResetCompleteInput1
func (t PasswordResetCompleteInput) AsPasswordResetCompleteInput1() (PasswordResetCompleteInput1, error) {
	var body PasswordResetCompleteInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPasswordResetCompleteInput1 overwrites any union data inside the PasswordResetCompleteInput as the provided PasswordResetCompleteInput1
func (t *PasswordResetCompleteInput) FromPasswordResetCompleteInput1(v PasswordResetCompleteInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePasswordResetCompleteInput1 performs a merge with any union data inside the PasswordResetCompleteInput, using the provided PasswordResetCompleteInput1
func (t *PasswordResetCompleteInput) MergePasswordResetCompleteInput1(v PasswordResetCompleteInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PasswordResetCompleteInput) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.ChallengeId != nil {
		object["challenge_id"], err = json.Marshal(t.ChallengeId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'challenge_id': %w", err)
		}
	}

	if t.Code != nil {
		object["code"], err = json.Marshal(t.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	object["new_password"], err = json.Marshal(t.NewPassword)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'new_password': %w", err)
	}

	if t.Token != nil {
		object["token"], err = json.Marshal(t.Token)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'token': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *PasswordResetCompleteInput) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["challenge_id"]; found {
		err = json.Unmarshal(raw, &t.ChallengeId)
		if err != nil {
			return fmt.Errorf("error reading 'challenge_id': %w", err)
		}
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &t.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
	}

	if raw, found := object["new_password"]; found {
		err = json.Unmarshal(raw, &t.NewPassword)
		if err != nil {
			return fmt.Errorf("error reading 'new_password': %w", err)
		}
	}

	if raw, found := object["token"]; found {
		err = json.Unmarshal(raw, &t.Token)
		if err != nil {
			return fmt.Errorf("error reading 'token': %w", err)
		}
	}

	return err
}

// AsTelegramSent returns the union data inside the TelegramResult as a TelegramSent
func (t TelegramResult) AsTelegramSent() (TelegramSent, error) {
	var body TelegramSent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTelegramSent overwrites any union data inside the TelegramResult as the provided TelegramSent
func (t *TelegramResult) FromTelegramSent(v TelegramSent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"sent"}`))
	t.union = b
	return err
}

// MergeTelegramSent performs a merge with any union data inside the TelegramResult, using the provided TelegramSent
func (t *TelegramResult) MergeTelegramSent(v TelegramSent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"sent"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTelegramFailed returns the union data inside the TelegramResult as a TelegramFailed
func (t TelegramResult) AsTelegramFailed() (TelegramFailed, error) {
	var body TelegramFailed
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTelegramFailed overwrites any union data inside the TelegramResult as the provided TelegramFailed
func (t *TelegramResult) FromTelegramFailed(v TelegramFailed) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"delivery_failed"}`))
	t.union = b
	return err
}

// MergeTelegramFailed performs a merge with any union data inside the TelegramResult, using the provided TelegramFailed
func (t *TelegramResult) MergeTelegramFailed(v TelegramFailed) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"kind":"delivery_failed"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t TelegramResult) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t TelegramResult) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "delivery_failed":
		return t.AsTelegramFailed()
	case "sent":
		return t.AsTelegramSent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t TelegramResult) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *TelegramResult) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsVerifyInput0 returns the union data inside the VerifyInput as a VerifyInput0
func (t VerifyInput) AsVerifyInput0() (VerifyInput0, error) {
	var body VerifyInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVerifyInput0 overwrites any union data inside the VerifyInput as the provided VerifyInput0
func (t *VerifyInput) FromVerifyInput0(v VerifyInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVerifyInput0 performs a merge with any union data inside the VerifyInput, using the provided VerifyInput0
func (t *VerifyInput) MergeVerifyInput0(v VerifyInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsVerifyInput1 returns the union data inside the VerifyInput as a VerifyInput1
func (t VerifyInput) AsVerifyInput1() (VerifyInput1, error) {
	var body VerifyInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVerifyInput1 overwrites any union data inside the VerifyInput as the provided VerifyInput1
func (t *VerifyInput) FromVerifyInput1(v VerifyInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVerifyInput1 performs a merge with any union data inside the VerifyInput, using the provided VerifyInput1
func (t *VerifyInput) MergeVerifyInput1(v VerifyInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t VerifyInput) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.ChallengeId != nil {
		object["challenge_id"], err = json.Marshal(t.ChallengeId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'challenge_id': %w", err)
		}
	}

	if t.Code != nil {
		object["code"], err = json.Marshal(t.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	object["new_password"], err = json.Marshal(t.NewPassword)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'new_password': %w", err)
	}

	if t.Token != nil {
		object["token"], err = json.Marshal(t.Token)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'token': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *VerifyInput) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["challenge_id"]; found {
		err = json.Unmarshal(raw, &t.ChallengeId)
		if err != nil {
			return fmt.Errorf("error reading 'challenge_id': %w", err)
		}
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &t.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
	}

	if raw, found := object["new_password"]; found {
		err = json.Unmarshal(raw, &t.NewPassword)
		if err != nil {
			return fmt.Errorf("error reading 'new_password': %w", err)
		}
	}

	if raw, found := object["token"]; found {
		err = json.Unmarshal(raw, &t.Token)
		if err != nil {
			return fmt.Errorf("error reading 'token': %w", err)
		}
	}

	return err
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F1bcxq5s/8qlM4+DsZOslu7vBFMzmHXi32ApM5WymdKzDRY8Yw0KwknlIvv/i9pLsxFw802k8R6shlG",
	"6lar9euLGukReSyMGAUqBeo+IuHdQYj1v72b4YBzxtX/2PeJJIzi4IazCLgkIFB3jgMBDopyjx4RpG1+",
	"4TBHXfRfnQ2FTtJ9R3f8nvkrtF47iMO/S8LBR93PSfNbB8lVBKiL2OwLeBKtHdTzPLak8kB2cNzKJb76",
	"NGc8xBJ10XJJfJQREZITulBEIMQkKLwZP6l71X0ATuYEdO/JKzPGAsBUvRMwDwegvgO6DNX4+BI5CCi6",
	"NfQoIYAFx6EbEHoPfq6ZHtqtU6FQEl5usE7GeInPjKkqvS1SH4NYBkfKfpcypBO7dpCHIzwjAUl72Nas",
	"n39XtRV87kp2DzQ3F6lwzYJChVYl8lukMQFvyYlcHbo0apUrxN+ugC7kHeq++fWdQTXusHCZvAPuChCC",
	"MCrMChcB9QlduPGke3eYLrT64SC4nqPu5+0ivYlbD1Tjftx2fesgugwCPFN6LPkSKis2GYOBxRp+TJLt",
	"l2b+ALFKTnDg4gdMEi4fd62TcgsjQwEm4ZBGy0O1PiAhkbm1e7HpnVAJC+AVfuImtVwctfi+sJn+SySE",
	"O9fSNEGCP9lMUQ3xt2Hc7CLjCXOOq3CtqRgZZ2EUgIQ9ea+2X3IOVN5gIb4y7h8zEV7chRslfahnuYV2",
	"8eZ3B4WEZp9/dXagRqXD23rGp0rFxvDvEsShfPNcq72WbYHW7gWb9m/i/hI8otbuUfLGQTDD3r377xL4",
	"yiU7BW7AOT+hnzeZOIo4ewCkRqH5NNlOxQiWjLtyUbb1hMrf3iFNmoTLME84W5CqbywYLbN8fn6+SytK",
	"lHNjcAwi2Sb0o9a5h2PN3md53+BVwLAfCzogD4onIbEseCgJZCMHCdAmco5JUPAOylInjNb4V0VFNHSQ",
	"0/X9NbxGn0vsOLFoKkM1zcDGHz1Q+MwvyG44+tS7Gl66w9HNxylyss/98eByMJoOe1cT5KDB373hlftp",
	"MB5+GPZ70+H1yB0P/vfjcDy4RA7q9fvXH0dTdzyYTMfD/lQ/nI6HvSv3cjjpvb/KPehdjQe9y3/cj5Pc",
	"w/Ggfz2aDC8H40rf6t/BZOpOpr3pwO1fjz5cDfuK0eub9O3RtSLdu/xHsX85+PvmejoY9f/JvzxWja+G",
	"fw9j3iaD8adhf+B+HPU+9YZXikOjsqTwmcyXno6lMKtesub9bNHXKGAIQuAFGDy+51PO/WKHsq1QmrHh",
	"r9CZSQOv2IIchbpPcCqfzTCmFLcaRj3CU8URT40FTANIfZHYM27GI3EQha8v6NGU+t8mhjEIkD3Pg0iC",
	"f6gg7nAQAF3AvnE5BwHUd/FcAt9u3M93etsF4qWudw449Wv3m35GIfHfKIvfpqvkQQUsbtfOYz2ft+vb",
	"0jASRV07WefGb7cNPaF7++TpSe1ghKUETlEX/f/n8/Yft4+/r39Bz67EDsqWdq7hu7eFdu/eVtqVhHGY",
	"pp8Ymw/JHNWgcdKFcWTVQP84JEviekbnhId1WTD4FhEOwsWyIAsfS2hLEkKdhjxBfFnz7bwZNCIlkWPa",
	"qR2umZBJ4mPwGPVIcJTdeMngZmtAtivUSfrdOuCjTP4u360y4ducSeVK6gAr/kgBfOFyeCDwNXY1A2J0",
	"L42jz6KLhGLt2AXxgb+e2V4QIY8bL058CDfi5AF7K5WrFqQygN/PDdOetZXAQ3FIy+8Cm2sH4NRLpV78",
	"sXa+BpdsrF84cqTPyfienJ7UeTCqnIm3SZyn7zMq4dvBscwBIdaOwGqynAmPk0gmS/cALnwssUokmNP+",
	"DvLhgXggCmLcZ5r3clp2JhDYTAB/AP9JnVQtG2UUdps1TxKdNI0HYk6fSI7nc+K5egPCna3kUaJKe1kK",
	"8PfspGbUdcsskUHJK0sn1zwOI1/FOXHy+rNLM/+CQ7ODItfaXfLiYl5ysjOJVOnAxGOa3P0Qp2mflsBU",
	"SsmWUquT/Mr4PXIUyzPi+3qHFHwi3SQh7CBCH3BAfJeDiBgVYNSxe0LzW9mbdGxtXrkkBd1BGqxuEYDa",
	"vDrY5snjXKwvbLavnSyPP05t4sBN0tNpYlBtG/harNnC3qzmzaN6d9VBAWAB7jHhVtyyDs4dFCU7B4du",
	"NFS3C2MLn6dn4NvJpsZJpz/lYJsG3Gy4PGgNhCHE6cVdWz8O8jhguR3Rn1JUctqc9fawyZSDfx6rg/kC",
	"pJvkxvdZgAeai5wQKptCVeKbUplUEwrTvDXSSzVvE+T6REF2SCiWcR1UiKNIDbz7WIG+HavoQ4qzeiNu",
	"x8sTiFPfiW6vRjhUrOrVs85nIvdZv0ln+72csKkTlEV5HFU+sQOJeCbpfXhL5qVScFGAn6TLbfM7gYMr",
	"z443LmWLoad/y+7XMVRqbGyGurmujXI5vrzhGARNbOPTnPGnQmukUI4thbsdY5uG6J3+VAEdM8+6gHg5",
	"eVcA1CSGXSpy1GbZ/mZ5bSD/CTiZr+w2zc+/TRPP9FFp5nz1brK61KLdXWmbNawypJZsUh86UdYorWfE",
	"kQT+HjCPs04+5HIe6BJ84qn115ox2U5ebnkcfKCS4OCsNWKtfDjYvodVS+UIhThTy1hTUgzHBDKu7qSM",
	"NIqkuR52T7QOEEXWiz86iMbeguv+DxOynby86QVHRIW/azU4QudMdSCJVCCH+nhGKMjW5Pyi1bsZIgdl",
	"WVh0cXZ+dp6AL8URQV309uz87K325+WdlkwHR6TzcNHBS3nXCVSRgHoaMSGrYvpI7yn7Slu6nKoVYY5D",
	"kMBFC1O/9efketSaEwh80cIcWikinsXfzJi/aoX4mzKJrYvfWn+R92d5dBv6qBsXKfSyioANBQ0GWmZ3",
	"gH3gG5ldc6J4zutHDPyxL7JH0H+b2YS0BMljVKYeh4r3PM1h50uS1t/0vM0HypWUrNfrMn/6QRy262l4",
	"c37+vJQz12vtlGZxstR6q/Ti3TNSzX6wYCKJ59CKf1ugqV40QvVtI1TfNUL1jyaovjk5VSfBA72GxiD5",
	"qt1LNxZKjcBj1BetGcyZRifJV8iIEnv574qrXxvQqJx5Q93Pt+pzGcHZUjYL4WwpT43hTk3P/9fuT8Yf",
	"2tMk1Nz0ZzQCBTx+Z9Ahi5wWOS1y/gzI+Vh2yT/frqtomgY+bQ4CmkTVJJAvlMT96A6yob5vL0f5zctw",
	"kJUzWJfZAr8F/tfjMhdBvuMlJeYNon1a5f7zwn2xjn8v2Lf+uIVlC8uvB5Z5UtPcqNcds/CTZKSLVeIn",
	"9rWNNdLW1baYbjH9NWG6AOq34+3bmJNG4V1x8ynPzA+P8JufO5wc3wu/CbHIbpHdIvvrQfa0ZqX7iBbQ",
	"BJj/N8jSD6pesMKiRMmCnQU7C3ave6tQ+7SrdvZjk4Z82rgac5CdCPQDO7P5EuITV9AValotult0t+j+",
	"KlzZEBp1YDd55hdDtuKB0hbaLLRZaHu1jmsIm+KHzWHlTRU9aAZuNkchfleVw/X9H/bjqhcursgfjmmr",
	"KqwFsBbAWoAdFmDzevOeb3azx8t7wBkp6wNbBLQI+LoRUL8hOhwe2D209TU6otHCBMXHtWJjkrvMx/rD",
	"eyuL8f4a6xBbc2DNgTUH28yBKB2G2lwxQ56RlyxlyNOxvrAFPwt+FvwUR/ew+m4AUJ1+dCIMzA5aMsNg",
	"QYX62LuDtqoC4yyoSmkED8Bbnnopd5aUKOjR5lDptpCMm87wXa8t9lrstdj7c2OvvhS3ncTCTSYf+vok",
	"ysIJoz9M7mHfDoc+hBGTQL1VO7Utu3k2Xzz4QhmM6vmdJ66BK136WdH1wTciJKGLFkmFKVs8fd1Bb84v",
	"TsaKjVGsnbR28jXayU5yNVyjkYrpzvEXBGYTOQuKFhQtKL4+UFSccooDjYzJZQmdL2wmOl6ASdhkGKHo",
	"5+4GEuiFdvoUnUYcZE3ZFlJb/LX4+9Pjb+n+gD3w95H4687mtpyGT5LLAXFNNifC8m6TICH+d5kTMVxv",
	"dGrQTwRqcd/ivsV9i/tZRiLD3Qz6kwvYG60jTHjQuYLr9LtTWIAfOPOeSa2hc5SKF/dbC2MtjLUw1sLk",
	"ct7avvjgEdHs+XmX+prCPXaKf4TY4jKRZyNRRUrcYr7FfIv5FvNrMF/HFIL4DR+KnTJxauT/0WMKLbQD",
	"7IstoLHWxVoXa12ew7qs1/8ZAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
