// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCredentialMail = `-- name: AddCredentialMail :exec
INSERT INTO mail_deliveries(id,credential_challenge_id,email_key,ciphertext,created_at,kind) VALUES($1,$2,$3,$4,$5,$6)
`

type AddCredentialMailParams struct {
	ID                    uuid.UUID
	CredentialChallengeID *uuid.UUID
	EmailKey              string
	Ciphertext            []byte
	CreatedAt             pgtype.Timestamptz
	Kind                  string
}

func (q *Queries) AddCredentialMail(ctx context.Context, arg AddCredentialMailParams) error {
	_, err := q.db.Exec(ctx, addCredentialMail,
		arg.ID,
		arg.CredentialChallengeID,
		arg.EmailKey,
		arg.Ciphertext,
		arg.CreatedAt,
		arg.Kind,
	)
	return err
}

const addCredentialProof = `-- name: AddCredentialProof :exec
INSERT INTO credential_challenges(id,purpose,account_id,change_id,original_email,target_email,credential_version,token_hash,code_hash,created_at,token_expires_at,code_expires_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
`

type AddCredentialProofParams struct {
	ID                uuid.UUID
	Purpose           string
	AccountID         *uuid.UUID
	ChangeID          *uuid.UUID
	OriginalEmail     string
	TargetEmail       string
	CredentialVersion int64
	TokenHash         []byte
	CodeHash          []byte
	CreatedAt         pgtype.Timestamptz
	TokenExpiresAt    pgtype.Timestamptz
	CodeExpiresAt     pgtype.Timestamptz
}

func (q *Queries) AddCredentialProof(ctx context.Context, arg AddCredentialProofParams) error {
	_, err := q.db.Exec(ctx, addCredentialProof,
		arg.ID,
		arg.Purpose,
		arg.AccountID,
		arg.ChangeID,
		arg.OriginalEmail,
		arg.TargetEmail,
		arg.CredentialVersion,
		arg.TokenHash,
		arg.CodeHash,
		arg.CreatedAt,
		arg.TokenExpiresAt,
		arg.CodeExpiresAt,
	)
	return err
}

const clearResetMail = `-- name: ClearResetMail :exec
UPDATE mail_deliveries m SET ciphertext=NULL FROM credential_challenges c WHERE m.credential_challenge_id=c.id AND m.kind='credential' AND c.target_email=$1 AND c.purpose='password_reset' AND (c.revoked OR c.used_at IS NOT NULL)
`

func (q *Queries) ClearResetMail(ctx context.Context, targetEmail string) error {
	_, err := q.db.Exec(ctx, clearResetMail, targetEmail)
	return err
}

const clearRevokedCredentialMail = `-- name: ClearRevokedCredentialMail :exec
UPDATE mail_deliveries m SET ciphertext=NULL FROM credential_challenges c WHERE m.credential_challenge_id=c.id AND m.kind='credential' AND c.account_id=$1 AND (c.revoked OR c.used_at IS NOT NULL)
`

func (q *Queries) ClearRevokedCredentialMail(ctx context.Context, accountID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearRevokedCredentialMail, accountID)
	return err
}

const consumeCredentialProof = `-- name: ConsumeCredentialProof :exec
UPDATE credential_challenges SET used_at=$2 WHERE id=$1
`

type ConsumeCredentialProofParams struct {
	ID     uuid.UUID
	UsedAt pgtype.Timestamptz
}

func (q *Queries) ConsumeCredentialProof(ctx context.Context, arg ConsumeCredentialProofParams) error {
	_, err := q.db.Exec(ctx, consumeCredentialProof, arg.ID, arg.UsedAt)
	return err
}

const credentialRecipients = `-- name: CredentialRecipients :many
SELECT DISTINCT (CASE WHEN purpose='email_change_old' THEN original_email ELSE target_email END)::text AS email FROM credential_challenges WHERE account_id=$1 AND NOT revoked AND used_at IS NULL
`

func (q *Queries) CredentialRecipients(ctx context.Context, accountID *uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, credentialRecipients, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAccountSessions = `-- name: DeleteAccountSessions :exec
DELETE FROM sessions WHERE account_id=$1
`

func (q *Queries) DeleteAccountSessions(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccountSessions, accountID)
	return err
}

const failCredentialCode = `-- name: FailCredentialCode :exec
UPDATE credential_challenges SET failed_guesses=LEAST(failed_guesses+1,5) WHERE id=$1
`

func (q *Queries) FailCredentialCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, failCredentialCode, id)
	return err
}

const lockCredentialProof = `-- name: LockCredentialProof :one
SELECT id, purpose, account_id, change_id, original_email, target_email, credential_version, token_hash, code_hash, created_at, token_expires_at, code_expires_at, failed_guesses, confirmed_at, used_at, revoked FROM credential_challenges WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockCredentialProof(ctx context.Context, id uuid.UUID) (CredentialChallenge, error) {
	row := q.db.QueryRow(ctx, lockCredentialProof, id)
	var i CredentialChallenge
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.AccountID,
		&i.ChangeID,
		&i.OriginalEmail,
		&i.TargetEmail,
		&i.CredentialVersion,
		&i.TokenHash,
		&i.CodeHash,
		&i.CreatedAt,
		&i.TokenExpiresAt,
		&i.CodeExpiresAt,
		&i.FailedGuesses,
		&i.ConfirmedAt,
		&i.UsedAt,
		&i.Revoked,
	)
	return i, err
}

const lookupCredentialByID = `-- name: LookupCredentialByID :one
SELECT id, purpose, account_id, change_id, original_email, target_email, credential_version, token_hash, code_hash, created_at, token_expires_at, code_expires_at, failed_guesses, confirmed_at, used_at, revoked FROM credential_challenges WHERE id=$1
`

func (q *Queries) LookupCredentialByID(ctx context.Context, id uuid.UUID) (CredentialChallenge, error) {
	row := q.db.QueryRow(ctx, lookupCredentialByID, id)
	var i CredentialChallenge
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.AccountID,
		&i.ChangeID,
		&i.OriginalEmail,
		&i.TargetEmail,
		&i.CredentialVersion,
		&i.TokenHash,
		&i.CodeHash,
		&i.CreatedAt,
		&i.TokenExpiresAt,
		&i.CodeExpiresAt,
		&i.FailedGuesses,
		&i.ConfirmedAt,
		&i.UsedAt,
		&i.Revoked,
	)
	return i, err
}

const lookupCredentialByToken = `-- name: LookupCredentialByToken :one
SELECT id, purpose, account_id, change_id, original_email, target_email, credential_version, token_hash, code_hash, created_at, token_expires_at, code_expires_at, failed_guesses, confirmed_at, used_at, revoked FROM credential_challenges WHERE token_hash=$1
`

func (q *Queries) LookupCredentialByToken(ctx context.Context, tokenHash []byte) (CredentialChallenge, error) {
	row := q.db.QueryRow(ctx, lookupCredentialByToken, tokenHash)
	var i CredentialChallenge
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.AccountID,
		&i.ChangeID,
		&i.OriginalEmail,
		&i.TargetEmail,
		&i.CredentialVersion,
		&i.TokenHash,
		&i.CodeHash,
		&i.CreatedAt,
		&i.TokenExpiresAt,
		&i.CodeExpiresAt,
		&i.FailedGuesses,
		&i.ConfirmedAt,
		&i.UsedAt,
		&i.Revoked,
	)
	return i, err
}

const revokeCredentialProofs = `-- name: RevokeCredentialProofs :exec
UPDATE credential_challenges SET revoked=true WHERE account_id=$1 AND NOT revoked AND used_at IS NULL
`

func (q *Queries) RevokeCredentialProofs(ctx context.Context, accountID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeCredentialProofs, accountID)
	return err
}

const revokeResetProofs = `-- name: RevokeResetProofs :exec
UPDATE credential_challenges SET revoked=true WHERE target_email=$1 AND purpose='password_reset' AND NOT revoked AND used_at IS NULL
`

func (q *Queries) RevokeResetProofs(ctx context.Context, targetEmail string) error {
	_, err := q.db.Exec(ctx, revokeResetProofs, targetEmail)
	return err
}

const setAccountPassword = `-- name: SetAccountPassword :exec
UPDATE accounts SET password_hash=$2,credential_version=credential_version+1 WHERE id=$1
`

type SetAccountPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) SetAccountPassword(ctx context.Context, arg SetAccountPasswordParams) error {
	_, err := q.db.Exec(ctx, setAccountPassword, arg.ID, arg.PasswordHash)
	return err
}
