// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                uuid.UUID
	EmailKey          pgtype.Text
	Locale            string
	PasswordHash      pgtype.Text
	VerifiedAt        pgtype.Timestamptz
	Restricted        bool
	VpnID             uuid.UUID
	SubID             string
	PanelKey          string
	TermsVersion      pgtype.Text
	PrivacyVersion    pgtype.Text
	TelegramID        pgtype.Int8
	LegacyUserID      pgtype.Int8
	AssignedPanelID   pgtype.Text
	HadSubscription   bool
	CredentialVersion int64
	VpnBanned         bool
	Kind              string
	DisplayName       pgtype.Text
	CreatedAt         pgtype.Timestamptz
}

type AuditEvent struct {
	ID                uuid.UUID
	CreatedAt         pgtype.Timestamptz
	Action            string
	AccountID         uuid.UUID
	RequestID         *uuid.UUID
	OperationID       *uuid.UUID
	OperatorTgID      pgtype.Int8
	Reason            pgtype.Text
	OperatorAccountID *uuid.UUID
	SupportMessageID  *uuid.UUID
}

type CredentialChallenge struct {
	ID                uuid.UUID
	Purpose           string
	AccountID         *uuid.UUID
	ChangeID          *uuid.UUID
	OriginalEmail     string
	TargetEmail       string
	CredentialVersion int64
	TokenHash         []byte
	CodeHash          []byte
	CreatedAt         pgtype.Timestamptz
	TokenExpiresAt    pgtype.Timestamptz
	CodeExpiresAt     pgtype.Timestamptz
	FailedGuesses     int32
	ConfirmedAt       pgtype.Timestamptz
	UsedAt            pgtype.Timestamptz
	Revoked           bool
}

type DecisionCallback struct {
	ID           string
	RequestID    uuid.UUID
	OperatorTgID int64
	BodyHash     []byte
	Result       []byte
	CreatedAt    pgtype.Timestamptz
}

type IdempotencyRecord struct {
	Principal string
	Operation string
	Key       uuid.UUID
	BodyHash  []byte
	Result    []byte
	CreatedAt pgtype.Timestamptz
}

type MailDelivery struct {
	ID                    uuid.UUID
	ChallengeID           *uuid.UUID
	EmailKey              string
	Ciphertext            []byte
	CreatedAt             pgtype.Timestamptz
	DeliveredAt           pgtype.Timestamptz
	Kind                  string
	CredentialChallengeID *uuid.UUID
}

type OperatorAccount struct {
	AccountID uuid.UUID
	GrantedAt pgtype.Timestamptz
}

type RegistrationChallenge struct {
	ID             uuid.UUID
	EmailKey       string
	Locale         string
	TermsVersion   string
	PrivacyVersion string
	TokenHash      []byte
	CodeHash       []byte
	CreatedAt      pgtype.Timestamptz
	TokenExpiresAt pgtype.Timestamptz
	CodeExpiresAt  pgtype.Timestamptz
	FailedGuesses  int32
	Revoked        bool
}

type Session struct {
	IDHash            []byte
	AccountID         uuid.UUID
	CsrfToken         string
	CreatedAt         pgtype.Timestamptz
	LastSeen          pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
}

type SupportConversation struct {
	ID                       uuid.UUID
	AccountID                uuid.UUID
	Status                   string
	SupportBanned            bool
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	CustomerReceivedSequence int64
	OperatorReceivedSequence int64
}

type SupportMessage struct {
	ID              uuid.UUID
	ConversationID  uuid.UUID
	Sequence        int64
	SenderAccountID uuid.UUID
	SenderKind      string
	Text            string
	CreatedAt       pgtype.Timestamptz
	AttachmentName  pgtype.Text
	AttachmentBytes []byte
}

type TelegramDelivery struct {
	ID             uuid.UUID
	Sequence       pgtype.Int8
	RequestID      uuid.UUID
	OperationID    *uuid.UUID
	ChatID         int64
	Kind           string
	Payload        []byte
	State          string
	CreatedAt      pgtype.Timestamptz
	AvailableAt    pgtype.Timestamptz
	LeaseHash      []byte
	LeaseExpiresAt pgtype.Timestamptz
	Attempts       int32
	MessageID      pgtype.Int8
	CompletedAt    pgtype.Timestamptz
	FailureCode    pgtype.Text
	ResultHash     []byte
}

type TrialGrant struct {
	AccountID   uuid.UUID
	RequestID   uuid.UUID
	OperationID uuid.UUID
	Status      string
	CreatedAt   pgtype.Timestamptz
	GrantedAt   pgtype.Timestamptz
}

type TrialOperation struct {
	ID               uuid.UUID
	AccountID        uuid.UUID
	RequestID        uuid.UUID
	Status           string
	TrialEnabled     bool
	PeriodDays       int64
	TrafficGb        int64
	Devices          int64
	PanelID          string
	CreatedAt        pgtype.Timestamptz
	FirstStartedAt   pgtype.Timestamptz
	Target           []byte
	WriteStarted     bool
	Attempts         int32
	LeaseHash        []byte
	LeaseExpiresAt   pgtype.Timestamptz
	WorkerPid        pgtype.Int4
	TrafficUsedBytes pgtype.Int8
	ObservedAt       pgtype.Timestamptz
	TrafficUpBytes   pgtype.Int8
	TrafficDownBytes pgtype.Int8
	ProfileSnapshot  []byte
}

type TrialRequest struct {
	ID                uuid.UUID
	Sequence          pgtype.Int8
	AccountID         uuid.UUID
	Status            string
	Comment           string
	CreatedAt         pgtype.Timestamptz
	DecidedAt         pgtype.Timestamptz
	OperatorTgID      pgtype.Int8
	Reason            pgtype.Text
	OperationID       *uuid.UUID
	PreviousRequestID *uuid.UUID
	OperatorAccountID *uuid.UUID
}
