// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID             uuid.UUID
	EmailKey       string
	Locale         string
	PasswordHash   string
	VerifiedAt     pgtype.Timestamptz
	Restricted     bool
	VpnID          uuid.UUID
	SubID          string
	PanelKey       string
	TermsVersion   string
	PrivacyVersion string
	TelegramID     pgtype.Int8
	LegacyUserID   pgtype.Int8
}

type MailDelivery struct {
	ID          uuid.UUID
	ChallengeID *uuid.UUID
	EmailKey    string
	Ciphertext  []byte
	CreatedAt   pgtype.Timestamptz
	DeliveredAt pgtype.Timestamptz
}

type RegistrationChallenge struct {
	ID             uuid.UUID
	EmailKey       string
	Locale         string
	TermsVersion   string
	PrivacyVersion string
	TokenHash      []byte
	CodeHash       []byte
	CreatedAt      pgtype.Timestamptz
	TokenExpiresAt pgtype.Timestamptz
	CodeExpiresAt  pgtype.Timestamptz
	FailedGuesses  int32
	Revoked        bool
}
