// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provisioning.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const accountOperation = `-- name: AccountOperation :one
SELECT id, account_id, request_id, status, trial_enabled, period_days, traffic_gb, devices, panel_id, created_at, first_started_at, target, write_started, attempts, lease_hash, lease_expires_at, worker_pid, traffic_used_bytes, observed_at, traffic_up_bytes, traffic_down_bytes, profile_snapshot FROM trial_operations WHERE account_id=$1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) AccountOperation(ctx context.Context, accountID uuid.UUID) (TrialOperation, error) {
	row := q.db.QueryRow(ctx, accountOperation, accountID)
	var i TrialOperation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RequestID,
		&i.Status,
		&i.TrialEnabled,
		&i.PeriodDays,
		&i.TrafficGb,
		&i.Devices,
		&i.PanelID,
		&i.CreatedAt,
		&i.FirstStartedAt,
		&i.Target,
		&i.WriteStarted,
		&i.Attempts,
		&i.LeaseHash,
		&i.LeaseExpiresAt,
		&i.WorkerPid,
		&i.TrafficUsedBytes,
		&i.ObservedAt,
		&i.TrafficUpBytes,
		&i.TrafficDownBytes,
		&i.ProfileSnapshot,
	)
	return i, err
}

const applyOperation = `-- name: ApplyOperation :execrows
UPDATE trial_operations SET status='applied',lease_hash=NULL,lease_expires_at=NULL,worker_pid=NULL WHERE id=$1 AND lease_hash=$2 AND lease_expires_at>clock_timestamp() AND status='provisioning'
`

type ApplyOperationParams struct {
	ID        uuid.UUID
	LeaseHash []byte
}

func (q *Queries) ApplyOperation(ctx context.Context, arg ApplyOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyOperation, arg.ID, arg.LeaseHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const grantApplied = `-- name: GrantApplied :exec
UPDATE trial_grants SET status='granted',granted_at=coalesce(granted_at,$2) WHERE operation_id=$1
`

type GrantAppliedParams struct {
	OperationID uuid.UUID
	GrantedAt   pgtype.Timestamptz
}

func (q *Queries) GrantApplied(ctx context.Context, arg GrantAppliedParams) error {
	_, err := q.db.Exec(ctx, grantApplied, arg.OperationID, arg.GrantedAt)
	return err
}

const leaseOperation = `-- name: LeaseOperation :one
UPDATE trial_operations SET status='provisioning',first_started_at=coalesce(first_started_at,$2),attempts=attempts+1,lease_hash=$3,lease_expires_at=clock_timestamp()+interval '3 minutes',worker_pid=pg_backend_pid() WHERE id=$1 AND status IN ('pending','provisioning') RETURNING id, account_id, request_id, status, trial_enabled, period_days, traffic_gb, devices, panel_id, created_at, first_started_at, target, write_started, attempts, lease_hash, lease_expires_at, worker_pid, traffic_used_bytes, observed_at, traffic_up_bytes, traffic_down_bytes, profile_snapshot
`

type LeaseOperationParams struct {
	ID             uuid.UUID
	FirstStartedAt pgtype.Timestamptz
	LeaseHash      []byte
}

func (q *Queries) LeaseOperation(ctx context.Context, arg LeaseOperationParams) (TrialOperation, error) {
	row := q.db.QueryRow(ctx, leaseOperation, arg.ID, arg.FirstStartedAt, arg.LeaseHash)
	var i TrialOperation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RequestID,
		&i.Status,
		&i.TrialEnabled,
		&i.PeriodDays,
		&i.TrafficGb,
		&i.Devices,
		&i.PanelID,
		&i.CreatedAt,
		&i.FirstStartedAt,
		&i.Target,
		&i.WriteStarted,
		&i.Attempts,
		&i.LeaseHash,
		&i.LeaseExpiresAt,
		&i.WorkerPid,
		&i.TrafficUsedBytes,
		&i.ObservedAt,
		&i.TrafficUpBytes,
		&i.TrafficDownBytes,
		&i.ProfileSnapshot,
	)
	return i, err
}

const markPanelWrite = `-- name: MarkPanelWrite :execrows
UPDATE trial_operations SET write_started=true WHERE id=$1 AND lease_hash=$2 AND lease_expires_at>clock_timestamp() AND status='provisioning'
`

type MarkPanelWriteParams struct {
	ID        uuid.UUID
	LeaseHash []byte
}

func (q *Queries) MarkPanelWrite(ctx context.Context, arg MarkPanelWriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPanelWrite, arg.ID, arg.LeaseHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const observeProfileTraffic = `-- name: ObserveProfileTraffic :exec
UPDATE trial_operations
SET traffic_up_bytes=$2,traffic_down_bytes=$3,traffic_used_bytes=$2::bigint+$3::bigint,observed_at=$4,profile_snapshot=$5::jsonb
WHERE id=$1 AND status='applied' AND (traffic_up_bytes IS NULL OR observed_at <= $4::timestamptz)
`

type ObserveProfileTrafficParams struct {
	ID               uuid.UUID
	TrafficUpBytes   pgtype.Int8
	TrafficDownBytes pgtype.Int8
	ObservedAt       pgtype.Timestamptz
	Snapshot         []byte
}

func (q *Queries) ObserveProfileTraffic(ctx context.Context, arg ObserveProfileTrafficParams) error {
	_, err := q.db.Exec(ctx, observeProfileTraffic,
		arg.ID,
		arg.TrafficUpBytes,
		arg.TrafficDownBytes,
		arg.ObservedAt,
		arg.Snapshot,
	)
	return err
}

const observeTraffic = `-- name: ObserveTraffic :exec
UPDATE trial_operations SET traffic_used_bytes=$2,observed_at=$3 WHERE id=$1 AND status='applied'
`

type ObserveTrafficParams struct {
	ID               uuid.UUID
	TrafficUsedBytes pgtype.Int8
	ObservedAt       pgtype.Timestamptz
}

func (q *Queries) ObserveTraffic(ctx context.Context, arg ObserveTrafficParams) error {
	_, err := q.db.Exec(ctx, observeTraffic, arg.ID, arg.TrafficUsedBytes, arg.ObservedAt)
	return err
}

const operationByID = `-- name: OperationByID :one
SELECT id, account_id, request_id, status, trial_enabled, period_days, traffic_gb, devices, panel_id, created_at, first_started_at, target, write_started, attempts, lease_hash, lease_expires_at, worker_pid, traffic_used_bytes, observed_at, traffic_up_bytes, traffic_down_bytes, profile_snapshot FROM trial_operations WHERE id=$1
`

func (q *Queries) OperationByID(ctx context.Context, id uuid.UUID) (TrialOperation, error) {
	row := q.db.QueryRow(ctx, operationByID, id)
	var i TrialOperation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RequestID,
		&i.Status,
		&i.TrialEnabled,
		&i.PeriodDays,
		&i.TrafficGb,
		&i.Devices,
		&i.PanelID,
		&i.CreatedAt,
		&i.FirstStartedAt,
		&i.Target,
		&i.WriteStarted,
		&i.Attempts,
		&i.LeaseHash,
		&i.LeaseExpiresAt,
		&i.WorkerPid,
		&i.TrafficUsedBytes,
		&i.ObservedAt,
		&i.TrafficUpBytes,
		&i.TrafficDownBytes,
		&i.ProfileSnapshot,
	)
	return i, err
}

const requeueOperation = `-- name: RequeueOperation :exec
UPDATE trial_operations SET status='pending',attempts=0 WHERE id=$1 AND status='needs_review'
`

func (q *Queries) RequeueOperation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, requeueOperation, id)
	return err
}

const retryOperation = `-- name: RetryOperation :exec
UPDATE trial_operations SET status='pending',lease_hash=NULL,lease_expires_at=NULL,worker_pid=NULL WHERE id=$1 AND status='provisioning' AND lease_hash=$2
`

type RetryOperationParams struct {
	ID        uuid.UUID
	LeaseHash []byte
}

func (q *Queries) RetryOperation(ctx context.Context, arg RetryOperationParams) error {
	_, err := q.db.Exec(ctx, retryOperation, arg.ID, arg.LeaseHash)
	return err
}

const reviewOperation = `-- name: ReviewOperation :execrows
UPDATE trial_operations SET status='needs_review',lease_hash=NULL,lease_expires_at=NULL,worker_pid=NULL WHERE id=$1 AND ((status='applied' AND $2::boolean) OR (status IN ('pending','provisioning') AND lease_hash=$3::bytea))
`

type ReviewOperationParams struct {
	ID             uuid.UUID
	IncludeApplied bool
	ExpectedLease  []byte
}

func (q *Queries) ReviewOperation(ctx context.Context, arg ReviewOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, reviewOperation, arg.ID, arg.IncludeApplied, arg.ExpectedLease)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveProvisionTarget = `-- name: SaveProvisionTarget :exec
UPDATE trial_operations SET target=$2 WHERE id=$1 AND target IS NULL
`

type SaveProvisionTargetParams struct {
	ID     uuid.UUID
	Target []byte
}

func (q *Queries) SaveProvisionTarget(ctx context.Context, arg SaveProvisionTargetParams) error {
	_, err := q.db.Exec(ctx, saveProvisionTarget, arg.ID, arg.Target)
	return err
}
