// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: restrictions.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertLegacyApproval = `-- name: InsertLegacyApproval :execrows
INSERT INTO legacy_approval_snapshots(account_id,source_legacy_user_id,source_tg_id,status,requested_at,decided_at,decided_by)
VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT DO NOTHING
`

type InsertLegacyApprovalParams struct {
	AccountID          uuid.UUID
	SourceLegacyUserID int64
	SourceTgID         int64
	Status             string
	RequestedAt        pgtype.Timestamptz
	DecidedAt          pgtype.Timestamptz
	DecidedBy          pgtype.Int8
}

func (q *Queries) InsertLegacyApproval(ctx context.Context, arg InsertLegacyApprovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLegacyApproval,
		arg.AccountID,
		arg.SourceLegacyUserID,
		arg.SourceTgID,
		arg.Status,
		arg.RequestedAt,
		arg.DecidedAt,
		arg.DecidedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertLegacyApprovalEvent = `-- name: InsertLegacyApprovalEvent :execrows
INSERT INTO legacy_approval_events(source_id,account_id,target_tg_id,created_at,action,actor_type,actor_id,actor_name,source)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT DO NOTHING
`

type InsertLegacyApprovalEventParams struct {
	SourceID   int64
	AccountID  uuid.UUID
	TargetTgID int64
	CreatedAt  pgtype.Timestamptz
	Action     string
	ActorType  pgtype.Text
	ActorID    pgtype.Int8
	ActorName  pgtype.Text
	Source     pgtype.Text
}

func (q *Queries) InsertLegacyApprovalEvent(ctx context.Context, arg InsertLegacyApprovalEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLegacyApprovalEvent,
		arg.SourceID,
		arg.AccountID,
		arg.TargetTgID,
		arg.CreatedAt,
		arg.Action,
		arg.ActorType,
		arg.ActorID,
		arg.ActorName,
		arg.Source,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const legacyApprovalByAccount = `-- name: LegacyApprovalByAccount :one
SELECT account_id, source_legacy_user_id, source_tg_id, status, requested_at, decided_at, decided_by FROM legacy_approval_snapshots WHERE account_id=$1
`

func (q *Queries) LegacyApprovalByAccount(ctx context.Context, accountID uuid.UUID) (LegacyApprovalSnapshot, error) {
	row := q.db.QueryRow(ctx, legacyApprovalByAccount, accountID)
	var i LegacyApprovalSnapshot
	err := row.Scan(
		&i.AccountID,
		&i.SourceLegacyUserID,
		&i.SourceTgID,
		&i.Status,
		&i.RequestedAt,
		&i.DecidedAt,
		&i.DecidedBy,
	)
	return i, err
}

const legacyApprovalBySourceID = `-- name: LegacyApprovalBySourceID :one
SELECT account_id, source_legacy_user_id, source_tg_id, status, requested_at, decided_at, decided_by FROM legacy_approval_snapshots WHERE source_legacy_user_id=$1
`

func (q *Queries) LegacyApprovalBySourceID(ctx context.Context, sourceLegacyUserID int64) (LegacyApprovalSnapshot, error) {
	row := q.db.QueryRow(ctx, legacyApprovalBySourceID, sourceLegacyUserID)
	var i LegacyApprovalSnapshot
	err := row.Scan(
		&i.AccountID,
		&i.SourceLegacyUserID,
		&i.SourceTgID,
		&i.Status,
		&i.RequestedAt,
		&i.DecidedAt,
		&i.DecidedBy,
	)
	return i, err
}

const legacyApprovalEventByID = `-- name: LegacyApprovalEventByID :one
SELECT source_id, account_id, target_tg_id, created_at, action, actor_type, actor_id, actor_name, source FROM legacy_approval_events WHERE source_id=$1
`

func (q *Queries) LegacyApprovalEventByID(ctx context.Context, sourceID int64) (LegacyApprovalEvent, error) {
	row := q.db.QueryRow(ctx, legacyApprovalEventByID, sourceID)
	var i LegacyApprovalEvent
	err := row.Scan(
		&i.SourceID,
		&i.AccountID,
		&i.TargetTgID,
		&i.CreatedAt,
		&i.Action,
		&i.ActorType,
		&i.ActorID,
		&i.ActorName,
		&i.Source,
	)
	return i, err
}

const legacyApprovalPage = `-- name: LegacyApprovalPage :many
SELECT source_id, account_id, target_tg_id, created_at, action, actor_type, actor_id, actor_name, source FROM legacy_approval_events
WHERE account_id=$1 AND ($2::timestamptz IS NULL OR
 (created_at,source_id)<($2::timestamptz,$3::bigint))
ORDER BY created_at DESC,source_id DESC LIMIT 51
`

type LegacyApprovalPageParams struct {
	AccountID       uuid.UUID
	BeforeCreatedAt pgtype.Timestamptz
	BeforeSourceID  int64
}

func (q *Queries) LegacyApprovalPage(ctx context.Context, arg LegacyApprovalPageParams) ([]LegacyApprovalEvent, error) {
	rows, err := q.db.Query(ctx, legacyApprovalPage, arg.AccountID, arg.BeforeCreatedAt, arg.BeforeSourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LegacyApprovalEvent
	for rows.Next() {
		var i LegacyApprovalEvent
		if err := rows.Scan(
			&i.SourceID,
			&i.AccountID,
			&i.TargetTgID,
			&i.CreatedAt,
			&i.Action,
			&i.ActorType,
			&i.ActorID,
			&i.ActorName,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const operatorRoleExists = `-- name: OperatorRoleExists :one
SELECT EXISTS(SELECT 1 FROM operator_accounts WHERE account_id=$1)
`

func (q *Queries) OperatorRoleExists(ctx context.Context, accountID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, operatorRoleExists, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setAccountRestriction = `-- name: SetAccountRestriction :exec
UPDATE accounts SET restricted=$2 WHERE id=$1
`

type SetAccountRestrictionParams struct {
	ID         uuid.UUID
	Restricted bool
}

func (q *Queries) SetAccountRestriction(ctx context.Context, arg SetAccountRestrictionParams) error {
	_, err := q.db.Exec(ctx, setAccountRestriction, arg.ID, arg.Restricted)
	return err
}

const setOperatorAccountRestriction = `-- name: SetOperatorAccountRestriction :exec
UPDATE accounts SET restricted=$2, restriction_changed_at=$3, restriction_operator_account_id=$4 WHERE id=$1
`

type SetOperatorAccountRestrictionParams struct {
	ID                           uuid.UUID
	Restricted                   bool
	RestrictionChangedAt         pgtype.Timestamptz
	RestrictionOperatorAccountID *uuid.UUID
}

func (q *Queries) SetOperatorAccountRestriction(ctx context.Context, arg SetOperatorAccountRestrictionParams) error {
	_, err := q.db.Exec(ctx, setOperatorAccountRestriction,
		arg.ID,
		arg.Restricted,
		arg.RestrictionChangedAt,
		arg.RestrictionOperatorAccountID,
	)
	return err
}
