// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type IdempotencyRecord struct {
	Principal string
	Operation string
	Key       uuid.UUID
	BodyHash  []byte
	Result    []byte
	CreatedAt pgtype.Timestamptz
}
