// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const auditPage = `-- name: AuditPage :many
SELECT id, created_at, action, account_id, request_id, operation_id, operator_tg_id, reason, operator_account_id, support_message_id, access_operation_id, system_actor, monthly_period FROM audit_events
WHERE account_id=$1
 AND ($2::timestamptz IS NULL OR
      (created_at,id)<($2::timestamptz,$3::uuid))
ORDER BY created_at DESC,id DESC LIMIT 51
`

type AuditPageParams struct {
	AccountID       uuid.UUID
	BeforeCreatedAt pgtype.Timestamptz
	BeforeID        uuid.UUID
}

func (q *Queries) AuditPage(ctx context.Context, arg AuditPageParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, auditPage, arg.AccountID, arg.BeforeCreatedAt, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Action,
			&i.AccountID,
			&i.RequestID,
			&i.OperationID,
			&i.OperatorTgID,
			&i.Reason,
			&i.OperatorAccountID,
			&i.SupportMessageID,
			&i.AccessOperationID,
			&i.SystemActor,
			&i.MonthlyPeriod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAudit = `-- name: RecordAudit :exec
INSERT INTO audit_events(id,created_at,action,account_id,request_id,operation_id,operator_tg_id,reason,
 operator_account_id,support_message_id,access_operation_id,system_actor,monthly_period)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
`

type RecordAuditParams struct {
	ID                uuid.UUID
	CreatedAt         pgtype.Timestamptz
	Action            string
	AccountID         uuid.UUID
	RequestID         *uuid.UUID
	OperationID       *uuid.UUID
	OperatorTgID      pgtype.Int8
	Reason            pgtype.Text
	OperatorAccountID *uuid.UUID
	SupportMessageID  *uuid.UUID
	AccessOperationID *uuid.UUID
	SystemActor       pgtype.Bool
	MonthlyPeriod     pgtype.Text
}

func (q *Queries) RecordAudit(ctx context.Context, arg RecordAuditParams) error {
	_, err := q.db.Exec(ctx, recordAudit,
		arg.ID,
		arg.CreatedAt,
		arg.Action,
		arg.AccountID,
		arg.RequestID,
		arg.OperationID,
		arg.OperatorTgID,
		arg.Reason,
		arg.OperatorAccountID,
		arg.SupportMessageID,
		arg.AccessOperationID,
		arg.SystemActor,
		arg.MonthlyPeriod,
	)
	return err
}
