// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID                uuid.UUID
	CreatedAt         pgtype.Timestamptz
	Action            string
	AccountID         uuid.UUID
	RequestID         *uuid.UUID
	OperationID       *uuid.UUID
	OperatorTgID      pgtype.Int8
	Reason            pgtype.Text
	OperatorAccountID *uuid.UUID
	SupportMessageID  *uuid.UUID
	AccessOperationID *uuid.UUID
	SystemActor       pgtype.Bool
	MonthlyPeriod     pgtype.Text
}
