import {test,expect,type Page,type Route} from '@playwright/test';
import type {components} from '../src/api/schema.gen';

type Model<K extends keyof components['schemas']>=components['schemas'][K];
const planId='70000000-0000-4000-8000-000000000001';
const orderId='80000000-0000-4000-8000-000000000001';
const clientId='20000000-0000-4000-8000-000000000001';
const plan:Model<'CataloguePlanSnapshot'>={plan_id:planId,revision:3,devices:2,traffic_gb:20,profile:'regular',hidden:false,periods:[30],prices:[{period_days:30,currency:'RUB',amount_minor:'12345'}]};
const order:Model<'PurchaseOrder'>={order_id:orderId,action:'purchase',quote:{plan_id:planId,revision:3,devices:2,period_days:30,traffic_gb:20,profile:'regular',amount_minor:'12345',currency:'RUB'},payment_method:'manual',payment_type:'MANUAL',payment_status:'pending',fulfillment_status:'not_started',created_at:'2026-10-03T10:00:00Z',expires_at:'2026-10-03T10:30:00Z',expired:false,can_pay:true,can_cancel:true,review_required:false,access_operation_id:null,checkout:null,manual_payment:{state:'not_reported',instructions:'<b>Synthetic recipient</b>\nUse the order ID',can_report:true,reported_at:null,decided_at:null,reason:null}};
const reported:Model<'PurchaseOrder'>={...order,can_pay:false,can_cancel:false,manual_payment:{...order.manual_payment!,state:'pending',can_report:false,reported_at:'2026-10-03T10:05:00Z'}};
const subscription:Model<'Subscription'>={status:'active',expires_at:null,devices:1,traffic_limit_bytes:1024,traffic_used_bytes:0,observed_at:null,data_stale:false,connection_available:false,access_profile:'regular',vpn_banned:false,access_operation_id:null,access_operation_status:null};
const card:Model<'OperatorClientCard'>={client:{account_id:clientId,kind:'web',display_name:'',email:'customer@example.test',telegram_id:null,locale:'en',created_at:null,restricted:false,vpn_banned:false,had_subscription:true},subscription,server:null,support:null,trial_requests:[],trial_has_more:false,audit_events:[],audit_has_more:false,legacy_approval:null,legacy_events:[],legacy_has_more:false};

test.beforeEach(async({page})=>{await page.clock.install({time:new Date('2026-10-03T10:05:00Z')});});
async function routes(page:Page,extra?:(route:Route,path:string)=>Promise<boolean>){await page.route('**/api/v1/**',async route=>{const path=new URL(route.request().url()).pathname;if(extra&&await extra(route,path))return;if(path.endsWith('/operator/session'))return route.fulfill({json:{account:{account_id:'10000000-0000-4000-8000-000000000001',email:'operator@example.test',email_verified:true,locale:'en',telegram_linked:false},csrf_token:'s'.repeat(43)}});if(path.endsWith('/auth/session'))return route.fulfill({json:{csrf_token:'s'.repeat(43)}});if(path.endsWith('/operator/clients/'+clientId))return route.fulfill({json:card});if(path.endsWith('/support'))return route.fulfill({json:{conversation:null,messages:[],has_more:false,oldest_sequence:null}});if(path.endsWith('/payment-methods'))return route.fulfill({json:{methods:[{id:'manual',currency:'RUB'}]}});if(path.endsWith('/catalogue'))return route.fulfill({json:{plans:[plan]}});if(path.endsWith('/orders/current'))return route.fulfill({json:{order:null}});if(path.endsWith('/orders/'+orderId))return route.fulfill({json:order});return route.fulfill({json:{}});});}

test('manual catalogue creates the exact quote, escapes instructions and allows keyboard reporting',async({page})=>{
 const writes:unknown[]=[];await routes(page,async(route,path)=>{if(path.endsWith('/orders')&&route.request().method()==='POST'){writes.push(route.request().postDataJSON());await route.fulfill({status:201,json:order});return true;}return false;});
 await page.setViewportSize({width:375,height:812});await page.goto('/catalogue?lang=en');await page.getByRole('button',{name:'Select plan'}).click();await expect(page.getByLabel('Manual transfer')).toBeChecked();await page.getByRole('button',{name:'Buy plan'}).click();await page.getByRole('button',{name:'Confirm purchase'}).click();await expect(page).toHaveURL(/\/orders\/80000000/);expect(writes).toEqual([{action:'purchase',plan_id:planId,revision:3,period_days:30,payment_method:'manual',payment_type:'MANUAL'}]);const manual=page.getByRole('region',{name:'Manual transfer'});await expect(manual.getByText('<b>Synthetic recipient</b>\nUse the order ID')).toBeVisible();await expect(manual.locator('b')).toHaveCount(0);await expect(page.locator('form[action^="https://yoomoney"]')).toHaveCount(0);const report=manual.getByRole('button',{name:'I have paid'});await report.focus();await expect(report).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('lost report response reuses the key, waits past the deadline and shows an approved decision',async({page})=>{
 let current=order;const keys:string[]=[];await routes(page,async(route,path)=>{if(path.endsWith('/manual-report')){keys.push(route.request().headers()['idempotency-key']);expect(route.request().postDataJSON()).toEqual({});expect(route.request().headers()['x-csrf-token']).toBe('s'.repeat(43));if(keys.length===1)await route.abort();else{current=reported;await route.fulfill({json:current});}return true;}if(path.endsWith('/orders/'+orderId)){await route.fulfill({json:current});return true;}return false;});await page.goto('/orders/'+orderId+'?lang=en');await page.getByRole('button',{name:'I have paid'}).click();await expect(page.getByRole('alert')).toBeVisible();await page.getByRole('button',{name:'I have paid'}).click();await expect.poll(()=>keys.length).toBe(2);expect(keys[0]).toBe(keys[1]);await page.clock.fastForward('02:00:00');await page.reload();await expect(page.getByRole('status').filter({hasText:'Your payment report is waiting for operator review.'})).toBeVisible();await expect(page.getByText('Payment period expired.')).toHaveCount(0);await expect(page.getByRole('button',{name:'Cancel order'})).toHaveCount(0);current={...reported,payment_status:'paid',fulfillment_status:'queued',manual_payment:{...reported.manual_payment!,state:'approved',decided_at:'2026-10-03T12:05:00Z',reason:'Bank receipt checked'}};await page.getByRole('button',{name:'Refresh status'}).click();await expect(page.getByRole('status').filter({hasText:'Payment received.'})).toBeVisible();await expect(page.getByText('Bank receipt checked')).toBeVisible();await expect(page.getByRole('button',{name:'I have paid'})).toHaveCount(0);
});

for(const state of ['expired','already_reported'] as const)test('fresh order '+state+' prevents a stale report',async({page})=>{
 let reads=0,writes=0;await routes(page,async(route,path)=>{if(path.endsWith('/manual-report')){writes++;await route.fulfill({json:reported});return true;}if(path.endsWith('/orders/'+orderId)){reads++;await route.fulfill({json:reads===1?order:state==='expired'?{...order,expired:true,can_pay:false,can_cancel:false,manual_payment:{...order.manual_payment!,can_report:false}}:reported});return true;}return false;});await page.goto('/orders/'+orderId+'?lang=en');await page.getByRole('button',{name:'I have paid'}).click();await expect.poll(()=>reads).toBe(2);await expect(page.getByRole('button',{name:'I have paid'})).toHaveCount(0);expect(writes).toBe(0);
});

test('Russian rejection is persistent and a foreign order hides instructions',async({page})=>{
 let foreign=false;await routes(page,async(route,path)=>{if(path.endsWith('/orders/'+orderId)){if(foreign)await route.fulfill({status:404,json:{error:{code:'INVALID_INPUT'}}});else await route.fulfill({json:{...reported,payment_status:'canceled',manual_payment:{...reported.manual_payment!,state:'rejected',reason:'Перевод не найден',decided_at:'2026-10-03T10:06:00Z'}}});return true;}return false;});await page.goto('/orders/'+orderId);await expect(page.getByRole('status').filter({hasText:'Ручная оплата отклонена.'})).toBeVisible();await expect(page.getByText('Перевод не найден')).toBeVisible();await expect(page.getByRole('button',{name:'Я оплатил'})).toHaveCount(0);foreign=true;await page.getByRole('button',{name:'Обновить состояние'}).click();await expect(page.getByText('Заказ не найден.')).toBeVisible();await expect(page.getByText(/Synthetic recipient/)).toHaveCount(0);
});

test('manual and YooMoney coexist and disabled manual remains absent',async({page})=>{
 let enabled=true;await routes(page,async(route,path)=>{if(path.endsWith('/payment-methods')){await route.fulfill({json:{methods:[{id:'yoomoney',currency:'RUB'},...(enabled?[{id:'manual',currency:'RUB'}]:[])]}});return true;}return false;});await page.goto('/catalogue?lang=en');await page.getByRole('button',{name:'Select plan'}).click();await expect(page.getByLabel('Bank card')).toBeChecked();await page.getByLabel('Manual transfer').check();await expect(page.getByLabel('Wallet')).not.toBeChecked();enabled=false;await page.reload();await page.getByRole('button',{name:'Select plan'}).click();await expect(page.getByLabel('Manual transfer')).toHaveCount(0);await expect(page.getByLabel('Bank card')).toBeChecked();
});

test('disabled manual method permits reporting an earlier transfer without asking for a new one',async({page})=>{
 let sent=false;await routes(page,async(route,path)=>{if(path.endsWith('/orders/'+orderId)){await route.fulfill({json:{...order,can_pay:false}});return true;}if(path.endsWith('/manual-report')){sent=true;await route.fulfill({json:reported});return true;}return false;});await page.goto('/orders/'+orderId+'?lang=en');await expect(page.getByText('New transfers are unavailable. If you already paid, report your payment.')).toBeVisible();await expect(page.getByText('After transferring the exact amount', {exact:false})).toHaveCount(0);await page.getByRole('button',{name:'I have paid'}).click();await expect.poll(()=>sent).toBe(true);await expect(page.getByRole('status').filter({hasText:'Your payment report is waiting for operator review.'})).toBeVisible();
});

test('operator queue paginates 50 plus one and opens the client card',async({page})=>{
 const items=Array.from({length:51},(_,i)=>({account_id:clientId,order:{...reported,order_id:`80000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`}}));const cursors:(string|null)[]=[];await routes(page,async(route,path)=>{if(path.endsWith('/operator/manual-payments')){const after=new URL(route.request().url()).searchParams.get('after');cursors.push(after);await route.fulfill({json:after?{items:items.slice(50),has_more:false,next_cursor:null}:{items:items.slice(0,50),has_more:true,next_cursor:items[49].order.order_id}});return true;}if(path.endsWith('/orders/current')){await route.fulfill({json:{order:reported}});return true;}return false;});await page.setViewportSize({width:375,height:812});await page.goto('/admin/manual-payments?lang=en');const list=page.getByRole('region',{name:'Manual payment requests'});await expect(list.getByRole('link',{name:'Open client'})).toHaveCount(50);await list.getByRole('button',{name:'Load more requests'}).click();await expect(list.getByRole('link',{name:'Open client'})).toHaveCount(51);expect(cursors).toEqual([null,items[49].order.order_id]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await list.getByRole('link',{name:'Open client'}).first().click();await expect(page).toHaveURL(new RegExp('/admin/clients/'+clientId+'/show'));await expect(page.getByRole('region',{name:'First purchase'}).getByRole('button',{name:'Confirm manual payment'})).toBeVisible();
});

test('operator validates bank acknowledgement and exact large amount, then replays the same decision',async({page})=>{
 const large={...reported,quote:{...reported.quote,amount_minor:'9007199254740993'}};let current:Model<'PurchaseOrder'>=large;const calls:{body:Model<'ManualPaymentDecisionInput'>;key:string}[]=[];await routes(page,async(route,path)=>{if(path.endsWith('/manual-decision')){calls.push({body:route.request().postDataJSON(),key:route.request().headers()['idempotency-key']});expect(route.request().headers()['x-csrf-token']).toBe('s'.repeat(43));if(calls.length===1)await route.abort();else{current={...large,payment_status:'paid',fulfillment_status:'queued',manual_payment:{...large.manual_payment!,state:'approved',decided_at:'2026-10-03T10:06:00Z',reason:'Checked bank statement'}};await route.fulfill({status:202,json:current});}return true;}if(path.endsWith('/orders/current')){await route.fulfill({json:{order:current}});return true;}return false;});await page.goto('/admin/clients/'+clientId+'/show?lang=en');const section=page.getByRole('region',{name:'First purchase'});await section.getByLabel('Decision reason').fill('Checked bank statement');await section.getByLabel('Received amount (RUB)').fill('90071992547409.92');await section.getByLabel('I checked the incoming funds in the bank').check();await section.getByRole('button',{name:'Confirm manual payment'}).click();await expect(section.getByRole('alert')).toBeVisible();expect(calls).toHaveLength(0);await section.getByLabel('Received amount (RUB)').fill('90071992547409.93');await section.getByLabel('I checked the incoming funds in the bank').uncheck();await section.getByRole('button',{name:'Confirm manual payment'}).click();await expect(section.getByRole('alert')).toBeVisible();expect(calls).toHaveLength(0);await section.getByLabel('I checked the incoming funds in the bank').check();await section.getByRole('button',{name:'Confirm manual payment'}).click();await expect(section.getByRole('alert')).toBeVisible();await section.getByRole('button',{name:'Confirm manual payment'}).click();await expect.poll(()=>calls.length).toBe(2);expect(calls[0]).toEqual(calls[1]);expect(calls[0].body).toEqual({decision:'approve',reason:'Checked bank statement',confirmed_amount_minor:'9007199254740993'});await expect(section.getByRole('button',{name:'Confirm manual payment'})).toHaveCount(0);await expect(section.getByText('Checked bank statement')).toBeVisible();
});

test('operator rejection omits amount, changing a decision gets a fresh key and revoked role clears the card',async({page})=>{
 const calls:{key:string;body:Model<'ManualPaymentDecisionInput'>}[]=[];await routes(page,async(route,path)=>{if(path.endsWith('/orders/current')){await route.fulfill({json:{order:reported}});return true;}if(path.endsWith('/manual-decision')){calls.push({key:route.request().headers()['idempotency-key'],body:route.request().postDataJSON()});if(calls.length===1)await route.abort();else await route.fulfill({status:403,json:{error:{code:'INVALID_CREDENTIALS'}}});return true;}return false;});await page.goto('/admin/clients/'+clientId+'/show?lang=en');const section=page.getByRole('region',{name:'First purchase'});await section.getByLabel('Decision reason').fill('Transfer not found');await section.getByRole('button',{name:'Reject manual payment'}).click();await expect(section.getByRole('alert')).toBeVisible();await section.getByLabel('Decision reason').fill('Corrected reason');await section.getByRole('button',{name:'Reject manual payment'}).click();await expect(page.getByRole('heading',{name:'Operator access required'})).toBeVisible();expect(calls[0].key).not.toBe(calls[1].key);expect(calls[0].body).toEqual({decision:'reject',reason:'Transfer not found'});await expect(page.getByText(/Synthetic recipient/)).toHaveCount(0);
});

test('queue empty, network retry and forbidden state are explicit',async({page})=>{
 let state='empty';await routes(page,async(route,path)=>{if(path.endsWith('/operator/manual-payments')){if(state==='empty')await route.fulfill({json:{items:[],has_more:false,next_cursor:null}});else if(state==='failure')await route.abort();else await route.fulfill({status:403,json:{error:{code:'INVALID_CREDENTIALS'}}});return true;}return false;});await page.goto('/admin/manual-payments?lang=en');await expect(page.getByText('No manual payment requests.')).toBeVisible();state='failure';await page.getByRole('button',{name:'Refresh status'}).click();await expect(page.getByRole('alert')).toBeVisible();state='forbidden';await page.getByRole('button',{name:'Retry'}).click();await expect(page.getByRole('heading',{name:'Operator access required'})).toBeVisible();
});
