import {test,expect,type Page,type Route} from '@playwright/test';
import type {components} from '../src/api/schema.gen';

type Model<K extends keyof components['schemas']>=components['schemas'][K];
const operator={account:{account_id:'10000000-0000-4000-8000-000000000001',email:'operator@example.test',email_verified:true,locale:'en',telegram_linked:false},csrf_token:'s'.repeat(43)};
const webClient:Model<'OperatorClient'>={account_id:'20000000-0000-4000-8000-000000000001',kind:'web',display_name:'',email:'customer@example.test',telegram_id:null,locale:'en',created_at:null,restricted:false,vpn_banned:false,had_subscription:true};
const tgClient:Model<'OperatorClient'>={account_id:'20000000-0000-4000-8000-000000000002',kind:'telegram',display_name:'Exact Person',email:null,telegram_id:'9223372036854775807',locale:'ru',created_at:'2026-10-02T10:00:00Z',restricted:false,vpn_banned:false,had_subscription:false};
const subscription:Model<'Subscription'>={status:'active',expires_at:null,devices:1,traffic_limit_bytes:1024,traffic_used_bytes:0,observed_at:'2026-10-02T10:00:00Z',data_stale:false,connection_available:true,access_profile:'regular',vpn_banned:false,access_operation_id:null,access_operation_status:null};
const pending:Model<'OperatorTrialRequest'>={request_id:'30000000-0000-4000-8000-000000000001',status:'pending',created_at:'2026-10-02T09:00:00Z',decided_at:null,operation_id:null,previous_request_id:null,comment:'Need access',reason:null,operator_tg_id:null,operator_account_id:null,operation:null};
const rejected:Model<'OperatorTrialRequest'>={...pending,request_id:'30000000-0000-4000-8000-000000000002',status:'rejected',decided_at:'2026-10-02T09:30:00Z',reason:'Initial reason',operator_account_id:operator.account.account_id};
const operation:Model<'OperatorOperation'>={operation_id:'40000000-0000-4000-8000-000000000001',status:'needs_review',created_at:'2026-10-02T09:40:00Z'};
const withOperation:Model<'OperatorTrialRequest'>={...pending,request_id:'30000000-0000-4000-8000-000000000003',status:'approved',operation_id:operation.operation_id,operation};
const audit:Model<'OperatorAuditEvent'>={id:'50000000-0000-4000-8000-000000000001',created_at:'2026-10-02T08:00:00Z',action:'trial.requested',request_id:pending.request_id,operation_id:null,operator_tg_id:'123456789',operator_account_id:null,reason:'Audited reason',support_message_id:null,access_operation_id:null,system_actor:null,monthly_period:null};
const card:Model<'OperatorClientCard'>={client:tgClient,subscription,server:{panel_id:'configured-panel',enabled:true},support:null,trial_requests:[pending,rejected,withOperation],trial_has_more:true,audit_events:[audit],audit_has_more:true,legacy_approval:null,legacy_events:[],legacy_has_more:false};

async function operatorRoutes(page:Page,extra?:(route:Route,path:string)=>Promise<boolean>,searches:{q:string;page:number;per_page:number}[]=[]){
 await page.route('**/api/v1/**',async route=>{const request=route.request(),path=new URL(request.url()).pathname;if(extra&&await extra(route,path))return;
  if(path.endsWith('/operator/session'))return route.fulfill({json:operator});
  if(path.endsWith('/operator/clients/search')){const body=request.postDataJSON();searches.push(body);return route.fulfill({json:{clients:[webClient,tgClient],total:51,page:body.page,per_page:body.per_page}});}
  if(path.endsWith('/operator/clients/'+tgClient.account_id))return route.fulfill({json:card});
  if(path.endsWith('/support')&&request.method()==='GET')return route.fulfill({json:{conversation:null,messages:[],has_more:false,oldest_sequence:null}});
  if(path.endsWith('/payment-history'))return route.fulfill({json:{kind:request.postDataJSON().kind,orders:[],receipts:[],legacy_transactions:[],has_more:false}});
  if(path.endsWith('/auth/logout'))return route.fulfill({status:204});
  return route.fulfill({json:{}});
 });
}

test('unauthorized direct admin exposes no resource and keeps secure logout',async({page})=>{
 let searches=0,logoutCsrf='';await page.route('**/api/v1/**',route=>{const path=new URL(route.request().url()).pathname;if(path.endsWith('/operator/session'))return route.fulfill({status:403,json:{error:{code:'ACCOUNT_RESTRICTED'}}});if(path.endsWith('/auth/session'))return route.fulfill({json:{csrf_token:'s'.repeat(43)}});if(path.endsWith('/operator/clients/search'))searches++;if(path.endsWith('/auth/logout')){logoutCsrf=route.request().headers()['x-csrf-token'];return route.fulfill({status:204});}return route.fulfill({json:{}});});
 await page.goto('/admin?lang=en');await expect(page.getByRole('heading',{name:'Operator access required'})).toBeVisible();await expect(page.getByRole('button',{name:'Sign out'})).toBeVisible();expect(searches).toBe(0);await page.getByRole('button',{name:'Sign out'}).click();await expect(page).toHaveURL(/\/login/);expect(logoutCsrf).toBe('s'.repeat(43));
});

test('search is body-only, memory-only, fixed page size and preserves exact Telegram identity',async({page})=>{
 const searches:{q:string;page:number;per_page:number}[]=[];await page.setViewportSize({width:375,height:812});await operatorRoutes(page,undefined,searches);await page.goto('/admin?lang=en');await expect(page.getByRole('heading',{name:'Clients'})).toBeVisible();const search=page.getByLabel('Search clients');await search.fill('Exact Person');await search.press('Enter');await expect.poll(()=>searches.at(-1)).toEqual({q:'Exact Person',page:1,per_page:50});
 await expect(page.getByText('9223372036854775807',{exact:true})).toBeVisible();await expect(page.getByText('No email',{exact:true})).toBeVisible();await expect(page.getByText('No data',{exact:true}).first()).toBeVisible();expect(page.url()).not.toContain('Exact');expect(await page.evaluate(()=>JSON.stringify([localStorage,sessionStorage]))).not.toContain('Exact Person');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'Next page'}).click();await expect.poll(()=>searches.at(-1)?.page).toBe(2);expect(searches.at(-1)?.per_page).toBe(50);
});

test('Russian operator search stays keyboard usable at mobile width',async({page})=>{
 const searches:{q:string;page:number;per_page:number}[]=[];await page.setViewportSize({width:375,height:812});await operatorRoutes(page,undefined,searches);await page.goto('/admin');await expect(page.getByRole('heading',{name:'Клиенты'})).toBeVisible();const search=page.getByLabel('Поиск клиентов');await search.focus();await expect(search).toBeFocused();await search.fill('Клиент');await search.press('Enter');await expect.poll(()=>searches.at(-1)).toEqual({q:'Клиент',page:1,per_page:50});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('card shows nullable identity, bounded history and honest deferred data',async({page})=>{
 const history:unknown[]=[];await operatorRoutes(page,async(route,path)=>{if(path.endsWith('/history')){history.push(route.request().postDataJSON());const kind=(route.request().postDataJSON() as {kind:string}).kind;await route.fulfill({json:{kind,trial_requests:[],audit_events:[],has_more:false}});return true;}return false;});await page.goto('/admin/clients/'+tgClient.account_id+'/show?lang=en');await expect(page.getByRole('heading',{name:'Exact Person'})).toBeVisible();
 await expect(page.getByText('Telegram-only')).toBeVisible();await expect(page.getByText('No email',{exact:true})).toBeVisible();await expect(page.getByText('9223372036854775807',{exact:true})).toBeVisible();await expect(page.getByText('configured-panel')).toBeVisible();await expect(page.getByRole('heading',{name:'Payment history',exact:true})).toBeVisible();await expect(page.getByText('No records of this type.')).toBeVisible();await expect(page.getByText('Promocodes are not available yet.')).toBeVisible();
 await expect(page.getByText('Account unrestricted')).toBeVisible();await expect(page.getByText('VPN access allowed')).toBeVisible();await expect(page.getByText('1 KiB',{exact:true})).toBeVisible();await expect(page.getByText('0 B',{exact:true})).toBeVisible();await expect(page.getByText('No expiry',{exact:true})).toBeVisible();await expect(page.getByText('Web operator: '+operator.account.account_id,{exact:true})).toBeVisible();await expect(page.getByText('Initial reason',{exact:true})).toBeVisible();await expect(page.getByText('Telegram operator: 123456789',{exact:true})).toBeVisible();await expect(page.getByText('Audited reason',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Load older trial requests'}).click();await page.getByRole('button',{name:'Load older audit events'}).click();expect(history).toEqual([{kind:'trials',before_created_at:withOperation.created_at,before_id:withOperation.request_id},{kind:'audit',before_created_at:audit.created_at,before_id:audit.id}]);
});

test('card keeps profile, finite limits, stale data and restrictions independent',async({page})=>{
 const restrictedCard:Model<'OperatorClientCard'>={...card,client:{...tgClient,restricted:true,vpn_banned:true},subscription:{...subscription,status:'exhausted',access_profile:'unlimited',vpn_banned:true,unlimited_traffic:false,unlimited_devices:false,devices:2,traffic_upload_bytes:128,traffic_download_bytes:256,traffic_used_bytes:384,traffic_remaining_bytes:640,data_stale:true,connection_available:false}};await operatorRoutes(page,async(route,path)=>{if(path.endsWith('/operator/clients/'+tgClient.account_id)){await route.fulfill({json:restrictedCard});return true;}return false;});await page.goto('/admin/clients/'+tgClient.account_id+'/show?lang=en');await expect(page.getByText('Account restricted')).toBeVisible();await expect(page.getByText('VPN access blocked')).toBeVisible();await expect(page.getByText('Traffic exhausted')).toBeVisible();await expect(page.getByText('Unlimited',{exact:true})).toBeVisible();await expect(page.getByText('2',{exact:true})).toBeVisible();await expect(page.getByText('128 B',{exact:true})).toBeVisible();await expect(page.getByText('256 B',{exact:true})).toBeVisible();await expect(page.getByText('640 B',{exact:true})).toBeVisible();await expect(page.getByText('Unavailable',{exact:true})).toBeVisible();await expect(page.getByRole('alert')).toContainText('Traffic data could not be refreshed.');
});

test('no subscription does not turn baseline zeroes into unlimited or no-expiry claims',async({page})=>{
 const emptyCard:Model<'OperatorClientCard'>={...card,subscription:{status:'none',expires_at:null,devices:0,traffic_limit_bytes:0,traffic_used_bytes:0,observed_at:null,data_stale:false,access_profile:'unknown',vpn_banned:false,access_operation_id:null,access_operation_status:null}};await operatorRoutes(page,async(route,path)=>{if(path.endsWith('/operator/clients/'+tgClient.account_id)){await route.fulfill({json:emptyCard});return true;}return false;});await page.goto('/admin/clients/'+tgClient.account_id+'/show?lang=en');await expect(page.getByText('Access is not active yet')).toBeVisible();await expect(page.getByText('Unlimited',{exact:true})).toHaveCount(0);await expect(page.getByText('No expiry',{exact:true})).toHaveCount(0);
});

test('key is explicit and clears on hide, page visibility, late response and role loss',async({page})=>{
 let keyReads=0,release!:()=>void;const wait=new Promise<void>(resolve=>release=resolve);let deny=false;await operatorRoutes(page,async(route,path)=>{if(path.endsWith('/key')){keyReads++;if(keyReads===3)await wait;await route.fulfill({json:{subscription_url:'https://subscriptions.example.test/sub/operator-private'}}).catch(()=>{});return true;}if(path.endsWith('/history')&&deny){await route.fulfill({status:403,json:{error:{code:'ACCOUNT_RESTRICTED'}}});return true;}return false;});await page.goto('/admin/clients/'+tgClient.account_id+'/show?lang=en');expect(keyReads).toBe(0);const show=page.getByRole('button',{name:'Show subscription link'});await show.click();await expect(page.getByLabel('Subscription link')).toBeVisible();await page.getByRole('button',{name:'Hide subscription link'}).click();await expect(page.getByLabel('Subscription link')).toHaveCount(0);await show.click();await page.evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,value:'hidden'});document.dispatchEvent(new Event('visibilitychange'));});await expect(page.getByLabel('Subscription link')).toHaveCount(0);
 await page.evaluate(()=>Object.defineProperty(document,'visibilityState',{configurable:true,value:'visible'}));await show.click({noWaitAfter:true});await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));release();await page.waitForTimeout(10);await expect(page.getByLabel('Subscription link')).toHaveCount(0);await show.click();await expect(page.getByLabel('Subscription link')).toBeVisible();deny=true;await page.getByRole('button',{name:'Load older audit events'}).click();await expect(page.getByRole('heading',{name:'Operator access required'})).toBeVisible();await expect(page.getByLabel('Subscription link')).toHaveCount(0);
});

test('decision, reconsider and reconcile validate reasons and retain idempotency after lost response',async({page})=>{
 const keys:Record<string,string[]>={decision:[],reconsider:[],reconcile:[]};const calls:Record<string,number>={decision:0,reconsider:0,reconcile:0};let currentCard=card;await operatorRoutes(page,async(route,path)=>{if(path.endsWith('/operator/clients/'+tgClient.account_id)){await route.fulfill({json:currentCard});return true;}const kind=path.endsWith('/decision')?'decision':path.endsWith('/reconsider')?'reconsider':path.endsWith('/reconcile')?'reconcile':'';if(!kind)return false;calls[kind]++;keys[kind].push(route.request().headers()['idempotency-key']);if(calls[kind]===1){await route.abort();return true;}const body=route.request().postDataJSON();expect(body).not.toHaveProperty('operator_account_id');if(kind==='decision'){const decided:Model<'OperatorTrialRequest'>={...pending,status:body.decision==='approve'?'approved':'rejected',decided_at:'2026-10-02T10:01:00Z',operator_account_id:operator.account.account_id};currentCard={...currentCard,trial_requests:[decided,rejected,withOperation]};await route.fulfill({json:{request:decided,operation_id:null}});}else if(kind==='reconsider')await route.fulfill({json:{...pending,previous_request_id:rejected.request_id}});else await route.fulfill({json:{operation_id:operation.operation_id,status:'pending'}});return true;});await page.goto('/admin/clients/'+tgClient.account_id+'/show?lang=en');
 await page.getByRole('button',{name:'Approve'}).click();await expect(page.getByRole('alert')).toBeVisible();await page.getByRole('button',{name:'Approve'}).click();await expect.poll(()=>keys.decision).toEqual([expect.any(String),expect.any(String)]);expect(keys.decision[0]).toBe(keys.decision[1]);await expect(page.getByText('approved: Need access',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Approve'})).toHaveCount(0);const reconsider=page.getByLabel('Reconsider reason');await page.getByRole('button',{name:'Reconsider'}).click();expect(calls.reconsider).toBe(0);await reconsider.fill('New evidence');await page.getByRole('button',{name:'Reconsider'}).click();await page.getByRole('button',{name:'Reconsider'}).click();await expect.poll(()=>keys.reconsider).toEqual([expect.any(String),expect.any(String)]);expect(keys.reconsider[0]).toBe(keys.reconsider[1]);const reconcile=page.getByLabel('Reconcile reason');await reconcile.fill('Retry assignment');await page.getByRole('button',{name:'Reconcile'}).click();await page.getByRole('button',{name:'Reconcile'}).click();await expect.poll(()=>keys.reconcile).toEqual([expect.any(String),expect.any(String)]);expect(keys.reconcile[0]).toBe(keys.reconcile[1]);
});

test('Telegram-only creation keeps decimal ID as text and retries with one idempotency key',async({page})=>{
 const bodies:unknown[]=[],keys:string[]=[];let calls=0;await operatorRoutes(page,async(route,path)=>{if(path.endsWith('/operator/clients/trial')){calls++;bodies.push(route.request().postDataJSON());keys.push(route.request().headers()['idempotency-key']);if(calls===1)await route.abort();else await route.fulfill({status:201,json:{client:tgClient,request:{request_id:pending.request_id,status:'approved',created_at:pending.created_at,decided_at:pending.created_at,operation_id:operation.operation_id,previous_request_id:null},operation_id:operation.operation_id}});return true;}return false;});await page.goto('/admin?lang=en');await page.getByLabel('Telegram ID').fill('9223372036854775807');await page.getByLabel('Display name').fill('Exact Person');await page.getByLabel('Client language').selectOption('ru');await page.getByRole('button',{name:'Create Telegram trial'}).click();await expect(page.getByRole('alert')).toBeVisible();await expect(page.getByLabel('Telegram ID')).toHaveValue('9223372036854775807');await page.getByRole('button',{name:'Create Telegram trial'}).click();expect(bodies).toEqual([{telegram_id:'9223372036854775807',display_name:'Exact Person',locale:'ru'},{telegram_id:'9223372036854775807',display_name:'Exact Person',locale:'ru'}]);expect(keys[0]).toBe(keys[1]);
});

test('operator support reuses thread, acknowledges customer sequence and support ban stays scoped',async({page})=>{
 const supportConversation:Model<'SupportConversation'>={id:'60000000-0000-4000-8000-000000000001',status:'open',support_banned:false,created_at:'2026-10-02T10:00:00Z',updated_at:'2026-10-02T10:00:00Z',customer_received_sequence:0,operator_received_sequence:0};const supportMessage=(sequence:number,sender:'customer'|'operator'):Model<'SupportMessage'>=>({id:`70000000-0000-4000-8000-${String(sequence).padStart(12,'0')}`,sequence,sender,text:sender==='customer'?'Customer question':'Own reply',created_at:'2026-10-02T10:00:00Z',attachment:null,delivery:'stored'});let read=0,replyType='',supportBanned=false;const bans:unknown[]=[],states:string[]=[];await operatorRoutes(page,async(route,path)=>{if(path.endsWith('/support')&&route.request().method()==='GET'){await route.fulfill({json:{conversation:{...supportConversation,support_banned:supportBanned},messages:[supportMessage(3,'customer'),supportMessage(4,'operator')],has_more:false,oldest_sequence:3}});return true;}if(path.endsWith('/support/read')){read=route.request().postDataJSON().sequence;await route.fulfill({status:204});return true;}if(path.endsWith('/support/state')){states.push(route.request().postDataJSON().status);await route.fulfill({status:204});return true;}if(path.endsWith('/support/ban')){const body=route.request().postDataJSON();bans.push(body);supportBanned=body.banned;await route.fulfill({status:204});return true;}if(path.endsWith('/support/messages')){replyType=route.request().headers()['content-type'];await route.fulfill({status:201,json:supportMessage(5,'operator')});return true;}return false;});await page.goto('/admin/clients/'+tgClient.account_id+'/show?lang=en');await expect(page.getByText('Customer question')).toBeVisible();await expect.poll(()=>read).toBe(3);await page.getByLabel('Support reply').fill('Answer');await page.getByLabel('Support file').setInputFiles({name:'answer.txt',mimeType:'text/plain',buffer:Buffer.from('answer')});await page.getByRole('button',{name:'Send support reply'}).click();expect(replyType).toContain('multipart/form-data');await page.getByRole('button',{name:'Close conversation'}).click();await page.getByRole('button',{name:'Reopen conversation'}).click();expect(states).toEqual(['closed','open']);
 const reason=page.getByLabel('Support restriction reason');await page.getByRole('button',{name:'Block support'}).click();await expect(page.getByRole('alert')).toContainText('reason');await reason.fill('Abuse');await page.getByRole('button',{name:'Block support'}).click();const unblock=page.getByRole('button',{name:'Unblock support'});await expect(unblock).toBeEnabled();await reason.fill('Resolved');await unblock.click();await expect.poll(()=>bans).toEqual([{banned:true,reason:'Abuse'},{banned:false,reason:'Resolved'}]);await expect(page.getByText('Trial active')).toBeVisible();
});

test('operator composer cannot be replaced while a reply is pending',async({page})=>{
 let release!:()=>void,received=0;const pending=new Promise<void>(resolve=>release=resolve);
 await operatorRoutes(page,async(route,path)=>{if(path.endsWith('/support/messages')){received++;await pending;await route.fulfill({status:201,json:{id:'70000000-0000-4000-8000-000000000001',sequence:10,sender:'operator',text:'First reply',created_at:'2026-10-02T10:00:00Z',attachment:null,delivery:'stored'}});return true;}return false;});
 await page.goto('/admin/clients/'+tgClient.account_id+'/show?lang=en');await page.getByLabel('Support reply').fill('First reply');await page.getByLabel('Support file').setInputFiles({name:'first.txt',mimeType:'text/plain',buffer:Buffer.from('first')});await page.getByRole('button',{name:'Send support reply'}).click();await expect.poll(()=>received).toBe(1);
 try{await expect(page.getByLabel('Support reply')).toBeDisabled();await expect(page.getByLabel('Support file')).toBeDisabled();await expect(page.getByLabel('Support reply')).toHaveValue('First reply');await expect(page.getByLabel('Support file')).toHaveValue(/first.txt/);}finally{release();}
 await expect(page.getByText('First reply',{exact:true})).toBeVisible();await expect(page.getByLabel('Support reply')).toBeEnabled();await page.getByLabel('Support reply').fill('Next reply');await expect(page.getByLabel('Support reply')).toHaveValue('Next reply');
});

test('operator keeps a new history gap when an older page finishes after polling',async({page})=>{
 const conversation:Model<'SupportConversation'>={id:'60000000-0000-4000-8000-000000000001',status:'open',support_banned:false,created_at:'2026-10-02T10:00:00Z',updated_at:'2026-10-02T10:00:00Z',customer_received_sequence:0,operator_received_sequence:0};
 const all:Model<'SupportMessage'>[]=Array.from({length:111},(_,index)=>({id:`70000000-0000-4000-8000-${String(index+1).padStart(12,'0')}`,sequence:(index+1)*10,sender:'customer',text:'Message '+(index+1),created_at:'2026-10-02T10:00:00Z',attachment:null,delivery:'stored'}));
 let later=false,release!:()=>void;const pending=new Promise<void>(resolve=>release=resolve),requests:number[]=[],reads:number[]=[];
 await operatorRoutes(page,async(route,path)=>{if(path.endsWith('/support')&&route.request().method()==='GET'){await route.fulfill({json:{conversation:{...conversation,operator_received_sequence:later?1110:600},messages:later?all.slice(-50):all.slice(10,60),has_more:true,oldest_sequence:later?620:110}});return true;}if(path.endsWith('/support/history')){const before=(route.request().postDataJSON() as {before_sequence:number}).before_sequence;requests.push(before);if(before===110)await pending;const older=all.filter(row=>row.sequence<before).slice(-50);await route.fulfill({json:{conversation,messages:older,has_more:all.some(row=>row.sequence<older[0]?.sequence),oldest_sequence:older[0]?.sequence??null}});return true;}if(path.endsWith('/support/read')){reads.push((route.request().postDataJSON() as {sequence:number}).sequence);await route.fulfill({status:204});return true;}return false;});
 await page.goto('/admin/clients/'+tgClient.account_id+'/show?lang=en');await expect(page.locator('[data-sequence]')).toHaveCount(50);await page.getByRole('button',{name:'Load older messages'}).click();await expect.poll(()=>requests).toEqual([110]);
 await page.evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,value:'hidden'});document.dispatchEvent(new Event('visibilitychange'));});later=true;await page.evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,value:'visible'});document.dispatchEvent(new Event('visibilitychange'));});
 try{await expect(page.locator('[data-sequence]')).toHaveCount(100);}finally{release();}
 await expect(page.locator('[data-sequence]')).toHaveCount(110);await page.getByRole('button',{name:'Load older messages'}).click();await expect(page.locator('[data-sequence]')).toHaveCount(111);expect(requests).toEqual([110,620]);
 await expect(page.locator('[data-sequence="610"]')).toBeVisible();await expect(page.locator('[data-sequence="1110"]')).toBeVisible();expect(reads).toEqual([]);
});
