import {test,expect,type Page,type Route} from '@playwright/test';
import type {components} from '../src/api/schema.gen';

type Model<K extends keyof components['schemas']>=components['schemas'][K];
test.beforeEach(async({page})=>{await page.clock.install({time:new Date('2026-10-03T10:05:00Z')});});
const planId='70000000-0000-4000-8000-000000000001';
const orderId='80000000-0000-4000-8000-000000000001';
const plan:Model<'CataloguePlanSnapshot'>={plan_id:planId,revision:3,devices:2,traffic_gb:20,profile:'regular',hidden:false,periods:[30],prices:[{period_days:30,currency:'RUB',amount_minor:'12345'},{period_days:30,currency:'USD',amount_minor:'200'},{period_days:30,currency:'XTR',amount_minor:'0'}]};
const order:Model<'PurchaseOrder'>={order_id:orderId,action:'purchase',quote:{plan_id:planId,revision:3,devices:2,period_days:30,traffic_gb:20,profile:'regular',amount_minor:'12345',currency:'RUB'},payment_method:'yoomoney',payment_type:'AC',payment_status:'pending',fulfillment_status:'not_started',created_at:'2026-10-03T10:00:00Z',expires_at:'2026-10-03T10:30:00Z',expired:false,can_pay:true,can_cancel:true,review_required:false,access_operation_id:null,checkout:{action:'https://yoomoney.ru/quickpay/confirm',method:'POST',fields:{receiver:'410011111111111', 'quickpay-form':'button',paymentType:'AC',sum:'123.45',label:orderId,successURL:'http://127.0.0.1:4173/orders/'+orderId}}};

async function routes(page:Page,extra?:(route:Route,path:string)=>Promise<boolean>){await page.route('**/api/v1/**',async route=>{const path=new URL(route.request().url()).pathname;if(extra&&await extra(route,path))return;if(path.endsWith('/support'))return route.fulfill({json:{conversation:null,messages:[],has_more:false,oldest_sequence:null}});if(path.endsWith('/auth/session'))return route.fulfill({json:{csrf_token:'s'.repeat(43)}});if(path.endsWith('/payment-methods'))return route.fulfill({json:{methods:[{id:'yoomoney',currency:'RUB'}]}});if(path.endsWith('/orders/current'))return route.fulfill({json:{order:null}});if(path.endsWith('/catalogue'))return route.fulfill({json:{plans:[plan]}});return route.fulfill({json:{}});});}

test('confirmed quote creates one order, supports wallet or card, and exposes exact POST form',async({page})=>{
 let providerPost='';await page.route('https://yoomoney.ru/quickpay/confirm',route=>{providerPost=route.request().method()+' '+route.request().postData();return route.abort();});let orderReads=0;const calls:{body:Model<'PurchaseOrderInput'>;key:string;csrf:string}[]=[];await routes(page,async(route,path)=>{if(path.endsWith('/orders/'+orderId)&&route.request().method()==='GET'){orderReads++;await route.fulfill({json:{...order,payment_type:'PC',checkout:{...order.checkout!,fields:{...order.checkout!.fields,paymentType:'PC'}}}});return true;}if(path.endsWith('/orders')&&route.request().method()==='POST'){calls.push({body:route.request().postDataJSON(),key:route.request().headers()['idempotency-key'],csrf:route.request().headers()['x-csrf-token']});await route.fulfill({status:201,json:{...order,payment_type:'PC',checkout:{...order.checkout!,fields:{...order.checkout!.fields,paymentType:'PC'}}}});return true;}return false;});
 await page.setViewportSize({width:375,height:812});await page.goto('/catalogue?lang=en');await page.getByRole('button',{name:'Select plan'}).click();await page.getByLabel('Wallet').check();await page.getByRole('button',{name:'Buy plan'}).click();await expect(page.getByText('Price: 123.45 RUB')).toBeVisible();expect(calls).toHaveLength(0);await page.getByRole('button',{name:'Confirm purchase'}).click();await expect(page).toHaveURL(/\/orders\/80000000/);await expect(page.getByRole('heading',{name:'Order'})).toBeVisible();expect(calls[0].body).toEqual({action:'purchase',plan_id:planId,revision:3,period_days:30,payment_method:'yoomoney',payment_type:'PC'});expect(calls[0].key).toMatch(/^[0-9a-f-]{36}$/i);expect(calls[0].csrf).toBe('s'.repeat(43));const form=page.locator('form[action="https://yoomoney.ru/quickpay/confirm"]');await expect(form).toHaveAttribute('method','post');for(const [name,value] of Object.entries({...order.checkout!.fields,paymentType:'PC'}))await expect(form.locator(`input[name="${name}"]`)).toHaveValue(value);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await form.getByRole('button',{name:'Continue to payment'}).click({noWaitAfter:true});await expect.poll(()=>providerPost).toContain('POST receiver=410011111111111');expect(orderReads).toBe(2);expect(providerPost).toContain('paymentType=PC');expect(providerPost).toContain('sum=123.45');
});

test('lost response retains order idempotency key and stale quote asks for reload',async({page})=>{
 let calls=0;const keys:string[]=[];await routes(page,async(route,path)=>{if(path.endsWith('/orders')&&route.request().method()==='POST'){calls++;keys.push(route.request().headers()['idempotency-key']);if(calls===1)await route.abort();else await route.fulfill({status:409,json:{error:{code:'CATALOGUE_REVISION_CONFLICT'}}});return true;}return false;});await page.goto('/catalogue?lang=en');await page.getByRole('button',{name:'Select plan'}).click();await page.getByRole('button',{name:'Buy plan'}).click();await page.getByRole('button',{name:'Confirm purchase'}).click();await expect(page.getByRole('alert')).toBeVisible();await page.getByRole('button',{name:'Confirm purchase'}).click();await expect.poll(()=>keys.length).toBe(2);expect(keys[0]).toBe(keys[1]);await expect(page.getByRole('alert')).toContainText(/reload/i);
});

for(const previous of [
 {...order,payment_status:'canceled' as const,can_pay:false,can_cancel:false,checkout:null},
 {...order,expired:true,can_pay:false,can_cancel:false,checkout:null},
])test(`retired ${previous.payment_status}${previous.expired?' expired':''} order stays linked while a new purchase uses a fresh key`,async({page})=>{
 const nextId='80000000-0000-4000-8000-000000000002';const keys:string[]=[];await routes(page,async(route,path)=>{if(path.endsWith('/orders/current')){await route.fulfill({json:{order:previous}});return true;}if(path.endsWith('/orders')&&route.request().method()==='POST'){keys.push(route.request().headers()['idempotency-key']);await route.fulfill({status:201,json:{...order,order_id:nextId}});return true;}if(path.endsWith('/orders/'+nextId)){await route.fulfill({json:{...order,order_id:nextId}});return true;}return false;});await page.goto('/catalogue?lang=en');await page.getByRole('button',{name:'Select plan'}).click();await expect(page.getByRole('link',{name:'Current order'})).toHaveAttribute('href','/orders/'+orderId+'?lang=en');await page.getByRole('button',{name:'Buy plan'}).click();await page.getByRole('button',{name:'Confirm purchase'}).click();await expect(page).toHaveURL(new RegExp('/orders/'+nextId));expect(keys).toHaveLength(1);expect(keys[0]).toMatch(/^[0-9a-f-]{36}$/i);
});

for(const previous of [
 order,
 {...order,payment_status:'paid' as const,fulfillment_status:'needs_review' as const,review_required:true,can_pay:false,checkout:null},
])test(`open ${previous.payment_status} order blocks another first purchase`,async({page})=>{
 let writes=0;await routes(page,async(route,path)=>{if(path.endsWith('/orders/current')){await route.fulfill({json:{order:previous}});return true;}if(path.endsWith('/orders')&&route.request().method()==='POST'){writes++;await route.abort();return true;}return false;});await page.goto('/catalogue?lang=en');await page.getByRole('button',{name:'Select plan'}).click();await expect(page.getByRole('link',{name:'Current order'})).toBeVisible();await expect(page.getByRole('button',{name:'Buy plan'})).toHaveCount(0);expect(writes).toBe(0);
});

test('return and reload read server status; paid remains preparing until applied',async({page})=>{
 let reads=0;await routes(page,async(route,path)=>{if(path.endsWith('/orders/'+orderId)){reads++;await route.fulfill({json:{...order,payment_status:'paid',fulfillment_status:reads===1?'queued':'applied',can_pay:false,can_cancel:false,checkout:null}});return true;}return false;});await page.goto('/orders/'+orderId+'?lang=en');await expect(page.getByRole('status')).toContainText('Payment received. Preparing access.');await expect(page.getByRole('button',{name:'Continue to payment'})).toHaveCount(0);await page.clock.runFor(5000);await expect(page.getByRole('status')).toContainText('Access is ready.');expect(reads).toBe(2);await page.reload();await expect(page.getByRole('status')).toContainText('Access is ready.');
});

test('local checkout deadline closes the form after polling stops',async({page})=>{
 let reads=0,providerPosts=0;await page.route('https://yoomoney.ru/quickpay/confirm',route=>{providerPosts++;return route.abort();});await routes(page,async(route,path)=>{if(path.endsWith('/orders/'+orderId)){reads++;await route.fulfill({json:order});return true;}return false;});await page.goto('/orders/'+orderId+'?lang=en');await expect(page.getByRole('button',{name:'Continue to payment'})).toBeVisible();for(let count=2;count<=25;count++){await page.clock.runFor(5000);await expect.poll(()=>reads).toBe(count);}await page.clock.fastForward(31*60*1000);await expect(page.getByRole('button',{name:'Continue to payment'})).toHaveCount(0);expect(providerPosts).toBe(0);expect(reads).toBe(25);
});

for(const [change,latest] of [
 ['canceled',{...order,payment_status:'canceled' as const,can_pay:false,can_cancel:false,checkout:null}],
 ['expired',{...order,expired:true,can_pay:false,can_cancel:false,checkout:null}],
 ['disabled',{...order,can_pay:false,can_cancel:false,checkout:null}],
] as const)test(`server ${change} before submit prevents external POST`,async({page})=>{
 let reads=0,providerPosts=0;await page.route('https://yoomoney.ru/quickpay/confirm',route=>{providerPosts++;return route.abort();});await routes(page,async(route,path)=>{if(path.endsWith('/orders/'+orderId)){reads++;await route.fulfill({json:reads===1?order:latest});return true;}return false;});await page.goto('/orders/'+orderId+'?lang=en');await page.getByRole('button',{name:'Continue to payment'}).click({noWaitAfter:true});await expect.poll(()=>reads,{timeout:2000}).toBe(2);await expect(page.locator('form[action="https://yoomoney.ru/quickpay/confirm"]')).toHaveCount(0);expect(providerPosts).toBe(0);
});

test('revoked session before submit cannot reach payment provider',async({page})=>{
 let reads=0,providerPosts=0;await page.route('https://yoomoney.ru/quickpay/confirm',route=>{providerPosts++;return route.abort();});await routes(page,async(route,path)=>{if(path.endsWith('/orders/'+orderId)){reads++;if(reads===1)await route.fulfill({json:order});else await route.fulfill({status:401,json:{error:{code:'INVALID_CREDENTIALS'}}});return true;}return false;});await page.goto('/orders/'+orderId+'?lang=en');await page.getByRole('button',{name:'Continue to payment'}).click({noWaitAfter:true});await expect(page).toHaveURL(/\/login\?lang=en/);expect(reads).toBe(2);expect(providerPosts).toBe(0);
});

test('pending order cancellation reuses its key after lost response and removes checkout',async({page})=>{
 const keys:string[]=[];let canceled=false;await routes(page,async(route,path)=>{if(path.endsWith('/orders/'+orderId+'/cancel')){keys.push(route.request().headers()['idempotency-key']);expect(route.request().headers()['x-csrf-token']).toBe('s'.repeat(43));expect(route.request().postDataJSON()).toEqual({});if(keys.length===1)await route.abort();else{canceled=true;await route.fulfill({json:{...order,payment_status:'canceled',can_pay:false,can_cancel:false,checkout:null}});}return true;}if(path.endsWith('/orders/'+orderId)){await route.fulfill({json:canceled?{...order,payment_status:'canceled',can_pay:false,can_cancel:false,checkout:null}:order});return true;}return false;});await page.goto('/orders/'+orderId+'?lang=en');await page.getByRole('button',{name:'Cancel order'}).click();await expect(page.getByRole('alert')).toBeVisible();await page.getByRole('button',{name:'Cancel order'}).click();await expect.poll(()=>keys.length).toBe(2);expect(keys[0]).toBe(keys[1]);await expect(page.getByRole('status')).toContainText('Order canceled.');await expect(page.locator('form[action="https://yoomoney.ru/quickpay/confirm"]')).toHaveCount(0);
});

test('invalid checkout action never presents payment form and disabled method keeps catalogue prices',async({page})=>{
 await routes(page,async(route,path)=>{if(path.endsWith('/orders/'+orderId)){await route.fulfill({json:{...order,checkout:{...order.checkout!,action:'https://example.test/steal'}}});return true;}if(path.endsWith('/payment-methods')){await route.fulfill({json:{methods:[]}});return true;}return false;});await page.goto('/orders/'+orderId+'?lang=en');await expect(page.getByRole('alert')).toContainText('Purchase is unavailable');await expect(page.locator('form')).toHaveCount(0);await page.goto('/catalogue?lang=en');await page.getByRole('button',{name:'Select plan'}).click();await page.getByLabel('Currency').selectOption('USD');await expect(page.getByText('2.00 USD')).toBeVisible();await expect(page.getByRole('button',{name:'Buy plan'})).toHaveCount(0);
});

test('expired order and foreign order cannot expose a checkout',async({page})=>{
 await routes(page,async(route,path)=>{if(path.endsWith('/orders/'+orderId)){await route.fulfill({json:{...order,expired:true,can_pay:false,can_cancel:false,checkout:null}});return true;}if(path.includes('/orders/')){await route.fulfill({status:404,json:{error:{code:'NOT_FOUND'}}});return true;}return false;});await page.goto('/orders/'+orderId+'?lang=en');await expect(page.getByRole('status')).toContainText('Payment period expired.');await expect(page.locator('form')).toHaveCount(0);await page.goto('/orders/80000000-0000-4000-8000-000000000002?lang=en');await expect(page.getByText('Order not found.')).toBeVisible();await expect(page.locator('form')).toHaveCount(0);
});

test('operator retries only preparation with reason and one key, then uses access operation',async({page})=>{
 const clientId='20000000-0000-4000-8000-000000000001';const client:Model<'OperatorClient'>={account_id:clientId,kind:'web',display_name:'',email:'client@example.test',telegram_id:null,locale:'en',created_at:null,restricted:false,vpn_banned:false,had_subscription:true};const subscription:Model<'Subscription'>={status:'needs_review',expires_at:null,devices:1,traffic_limit_bytes:1024,traffic_used_bytes:0,observed_at:null,data_stale:false,connection_available:false,access_profile:'regular',vpn_banned:false,access_operation_id:null,access_operation_status:null};const card:Model<'OperatorClientCard'>={client,subscription,server:null,support:null,trial_requests:[],trial_has_more:false,audit_events:[],audit_has_more:false,legacy_approval:null,legacy_events:[],legacy_has_more:false};let current:Model<'PurchaseOrder'>={...order,payment_status:'paid',fulfillment_status:'needs_review',can_pay:false,can_cancel:false,checkout:null,review_required:true};const keys:string[]=[];await routes(page,async(route,path)=>{if(path.endsWith('/operator/session')){await route.fulfill({json:{account:{account_id:'10000000-0000-4000-8000-000000000001',email:'operator@example.test',email_verified:true,locale:'en',telegram_linked:false},csrf_token:'s'.repeat(43)}});return true;}if(path.endsWith('/operator/clients/'+clientId)){await route.fulfill({json:card});return true;}if(path.endsWith('/operator/clients/'+clientId+'/orders/current')){await route.fulfill({json:{order:current}});return true;}if(path.endsWith('/operator/clients/'+clientId+'/orders/'+orderId+'/reconcile')){keys.push(route.request().headers()['idempotency-key']);expect(route.request().postDataJSON()).toEqual({reason:'Recover preparation'});if(keys.length===1)await route.abort();else{current={...current,fulfillment_status:'queued',review_required:false};await route.fulfill({status:202,json:current});}return true;}return false;});await page.goto('/admin/clients/'+clientId+'/show?lang=en');const section=page.getByRole('region',{name:'First purchase'});await expect(section.getByText('Payment received. Preparing access.')).toBeVisible();await section.getByRole('button',{name:'Retry preparation'}).click();await expect(section.getByRole('alert')).toBeVisible();await section.getByLabel('Reason for preparation retry').fill('Recover preparation');await section.getByRole('button',{name:'Retry preparation'}).click();await expect(section.getByRole('alert')).toBeVisible();await section.getByRole('button',{name:'Retry preparation'}).click();await expect.poll(()=>keys.length).toBe(2);expect(keys[0]).toBe(keys[1]);await expect(section.getByRole('button',{name:'Retry preparation'})).toHaveCount(0);
});
