import {test,expect,type Page,type Route} from '@playwright/test';
import type {components} from '../src/api/schema.gen';

type Model<K extends keyof components['schemas']>=components['schemas'][K];
const operatorId='10000000-0000-4000-8000-000000000001';
const clientId='20000000-0000-4000-8000-000000000002';
const otherId='20000000-0000-4000-8000-000000000003';
const operationId='30000000-0000-4000-8000-000000000003';
const planId='40000000-0000-4000-8000-000000000004';
const client:Model<'OperatorClient'>={account_id:clientId,kind:'telegram',display_name:'Access Client',email:null,telegram_id:'123456789',locale:'en',created_at:null,restricted:false,vpn_banned:false,had_subscription:true};
const subscription:Model<'Subscription'>={status:'active',expires_at:'2026-10-12T00:00:00Z',devices:2,traffic_limit_bytes:1024,traffic_used_bytes:128,observed_at:'2026-10-02T00:00:00Z',data_stale:false,access_profile:'regular',access_operation_id:null,access_operation_status:null};
const card=(id=clientId,sub=subscription):Model<'OperatorClientCard'>=>({client:{...client,account_id:id,display_name:id===clientId?'Access Client':'Other Client'},subscription:sub,server:{panel_id:'configured',enabled:true},support:null,trial_requests:[],trial_has_more:false,audit_events:[],audit_has_more:false,legacy_approval:null,legacy_events:[],legacy_has_more:false});
const desired:Model<'AccessDesired'>={expires_at:'2026-10-22T00:00:00Z',devices:2,traffic_limit_bytes:1024,profile:'regular',plan_id:null,revision:null,period_days:null,reset_traffic:false};
const operation:Model<'AccessOperation'>={operation_id:operationId,account_id:clientId,kind:'compensate',status:'pending',created_at:'2026-10-02T00:00:00Z',updated_at:'2026-10-02T00:00:00Z',reason:'Outage',operator_account_id:operatorId,desired,completed_steps:['prepared'],review_reason:null};
const plan:Model<'OperatorCataloguePlan'>={plan_id:planId,revision:7,devices:3,traffic_gb:20,profile:'euru',hidden:true,periods:[30,90],prices:[],legacy_plan_id:null,archived:false,actor_account_id:null,source:'operator',changed_at:'2026-10-02T00:00:00Z',reason:'Current'};

async function routes(page:Page,extra?:(route:Route,path:string)=>Promise<boolean>){await page.route('**/api/v1/**',async route=>{const path=new URL(route.request().url()).pathname;if(extra&&await extra(route,path))return;
 if(path.endsWith('/operator/session'))return route.fulfill({json:{account:{account_id:operatorId,email:'operator@example.test',email_verified:true,locale:'en',telegram_linked:false},csrf_token:'s'.repeat(43)}});
 if(path.endsWith('/operator/clients/'+clientId))return route.fulfill({json:card()});
 if(path.endsWith('/operator/clients/'+otherId))return route.fulfill({json:card(otherId)});
 if(path.endsWith('/support'))return route.fulfill({json:{conversation:null,messages:[],has_more:false,oldest_sequence:null}});
 return route.fulfill({json:{}});
});}

test('compensation validates days, preserves reason and one key after lost response, then shows pending',async({page})=>{
 const calls:{body:Model<'AccessOperationInput'>;key:string}[]=[];let release!:()=>void;const pending=new Promise<void>(resolve=>release=resolve);
 await routes(page,async(route,path)=>{if(path.endsWith('/access-operations')){calls.push({body:route.request().postDataJSON(),key:route.request().headers()['idempotency-key']});if(calls.length===1)await route.abort();else{await pending;await route.fulfill({status:202,json:operation});}return true;}return false;});
 await page.setViewportSize({width:375,height:812});await page.goto('/admin/clients/'+clientId+'/show?lang=en');const section=page.getByRole('region',{name:'Access operations'});
 await section.getByLabel('Days to add').fill('0');await section.getByLabel('Reason').fill('Outage');await section.getByRole('button',{name:'Add days'}).click();await expect(section.getByRole('alert')).toBeFocused();expect(calls).toHaveLength(0);
 await section.getByLabel('Days to add').fill('10');await section.getByRole('button',{name:'Add days'}).click();await expect(section.getByRole('alert')).toBeVisible();await expect(section.getByLabel('Reason')).toHaveValue('Outage');
 await section.getByRole('button',{name:'Add days'}).click();await expect.poll(()=>calls.length).toBe(2);try{await expect(section.getByLabel('Reason')).toBeDisabled();await expect(section.getByRole('button',{name:'Add days'})).toBeDisabled();}finally{release();}
 await expect(section.getByText('Pending',{exact:true})).toBeVisible();expect(calls[0].body).toEqual({kind:'compensate',days:10,reason:'Outage'});expect(calls[1].body).toEqual(calls[0].body);expect(calls[1].key).toBe(calls[0].key);expect(calls[0].key).toMatch(/^[0-9a-f-]{36}$/i);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('assignment pages through active offers, freezes revision and confirms reset consequences',async({page})=>{
 const pages:number[]=[],bodies:Model<'AccessOperationInput'>[]=[];let current=plan;
 await routes(page,async(route,path)=>{if(path.endsWith('/operator/catalogue')){const query=new URL(route.request().url()).searchParams;const number=Number(query.get('page'));pages.push(number);await route.fulfill({json:{plans:number===1?[]:[current,{...current,plan_id:'40000000-0000-4000-8000-000000000005',profile:'unlimited',hidden:true},{...current,plan_id:'40000000-0000-4000-8000-000000000006',archived:true}],total:51,page:number,per_page:50}});return true;}if(path.endsWith('/access-operations')){bodies.push(route.request().postDataJSON());await route.fulfill({status:202,json:{...operation,kind:'assign_plan',desired:{...desired,plan_id:planId,revision:7,period_days:90,reset_traffic:true}}});return true;}return false;});
 await page.goto('/admin/clients/'+clientId+'/show?lang=en');const section=page.getByRole('region',{name:'Access operations'});await section.getByLabel('Operation',{exact:true}).selectOption('assign_plan');await expect(section.getByText('No plans on this page.')).toBeVisible();await section.getByRole('button',{name:'Next plans'}).click();await expect(section.getByLabel('Plan',{exact:true})).toContainText('3 devices');await expect(section.getByLabel('Plan',{exact:true})).not.toContainText('Unlimited');
 await section.getByLabel('Plan',{exact:true}).selectOption(planId);await section.getByLabel('Period',{exact:true}).selectOption('90');await section.getByLabel('Reason',{exact:true}).fill('Move to EURU');current={...current,revision:8,devices:4};await page.getByRole('button',{name:'RU',exact:true}).click();const ruSection=page.getByRole('region',{name:'Операции доступа'});await expect(ruSection.locator('.access-plan-picker .notice')).toContainText(/редакция 7/i);
 await ruSection.getByRole('button',{name:'Назначить тариф'}).click();await expect(ruSection.locator('.access-create > .warning p')).toContainText(/сброс/i);expect(bodies).toHaveLength(0);await ruSection.getByRole('button',{name:'Подтвердить назначение'}).click();await expect(ruSection.getByText('Ожидает выполнения')).toBeVisible();expect(bodies).toEqual([{kind:'assign_plan',plan_id:planId,revision:7,period_days:90,reason:'Move to EURU'}]);expect(pages).toContain(2);
});

test('ambiguous reset reconciliation requires explicit cost acknowledgement',async({page})=>{
 const bodies:Model<'AccessReconcileInput'>[]=[];let current:Model<'AccessOperation'>={...operation,kind:'reset_traffic',status:'needs_review',desired:{...desired,reset_traffic:true},completed_steps:['prepared','reset_started'],review_reason:'reset_ambiguous'};
 await routes(page,async(route,path)=>{if(path.endsWith('/operator/clients/'+clientId)){await route.fulfill({json:card(clientId,{...subscription,access_operation_id:operationId,access_operation_status:'needs_review'})});return true;}if(path.endsWith('/access-operations/'+operationId)){await route.fulfill({json:current});return true;}if(path.endsWith('/reconcile')){bodies.push(route.request().postDataJSON());await route.fulfill({status:202,json:{...current,status:'provisioning'}});return true;}return false;});
 await page.goto('/admin/clients/'+clientId+'/show?lang=en');const section=page.getByRole('region',{name:'Access operations'});await expect(section.getByText('Needs review',{exact:true})).toBeVisible();await expect(section.getByText('reset_ambiguous')).toBeVisible();await section.getByLabel('Reconcile reason').fill('Readback checked');await section.getByRole('button',{name:'Reconcile operation'}).click();await expect(section.getByText(/new traffic may be lost/i)).toBeVisible();expect(bodies).toHaveLength(0);await section.getByLabel('I accept resetting new traffic').check();await section.getByRole('button',{name:'Confirm reconcile'}).click();expect(bodies).toEqual([{reason:'Readback checked',acknowledge_reset_cost:true}]);
});

test('starter trial explains the new period and requires confirmation',async({page})=>{
 const bodies:Model<'AccessOperationInput'>[]=[];await routes(page,async(route,path)=>{if(path.endsWith('/access-operations')){bodies.push(route.request().postDataJSON());await route.fulfill({status:202,json:operation});return true;}return false;});
 await page.goto('/admin/clients/'+clientId+'/show?lang=en');const section=page.getByRole('region',{name:'Access operations'});await section.getByLabel('Operation').selectOption('starter_trial');await section.getByLabel('Reason').fill('Recovery');await section.getByRole('button',{name:'Start trial'}).click();await expect(section.getByText(/new period.*reset/i)).toBeVisible();expect(bodies).toHaveLength(0);await section.getByRole('button',{name:'Confirm trial'}).click();await expect(section.getByText('Pending',{exact:true})).toBeVisible();expect(bodies).toEqual([{kind:'starter_trial',reason:'Recovery'}]);
});

test('revoked operator cannot reach access actions',async({page})=>{
 let reads=0;await routes(page,async(route,path)=>{if(path.endsWith('/operator/session')){await route.fulfill({status:403,json:{error:{code:'INVALID_CREDENTIALS'}}});return true;}if(path.includes('/access-operations'))reads++;return false;});await page.goto('/admin/clients/'+clientId+'/show?lang=en');await expect(page.getByRole('heading',{name:'Operator access required'})).toBeVisible();expect(reads).toBe(0);
});

test('manual reset confirms counter loss while preserving the ban warning',async({page})=>{
 const bodies:Model<'AccessOperationInput'>[]=[];await routes(page,async(route,path)=>{if(path.endsWith('/access-operations')){bodies.push(route.request().postDataJSON());await route.fulfill({status:202,json:{...operation,kind:'reset_traffic',desired:{...desired,reset_traffic:true}}});return true;}return false;});
 await page.goto('/admin/clients/'+clientId+'/show?lang=en');const section=page.getByRole('region',{name:'Access operations'});await section.getByLabel('Operation',{exact:true}).selectOption('reset_traffic');await section.getByLabel('Reason',{exact:true}).fill('Manual reset');await section.getByRole('button',{name:'Reset traffic'}).click();await expect(section.locator('.access-create > .warning p')).toContainText('VPN ban remains');expect(bodies).toHaveLength(0);await section.getByRole('button',{name:'Confirm reset'}).click();await expect(section.getByText('Pending',{exact:true})).toBeVisible();expect(bodies).toEqual([{kind:'reset_traffic',reason:'Manual reset'}]);
});

test('stale selected plan revision fails safely and explicit reload requires reselect',async({page})=>{
 let latest=plan,reads=0;const bodies:Model<'AccessOperationInput'>[]=[];await routes(page,async(route,path)=>{if(path.endsWith('/operator/catalogue')){reads++;await route.fulfill({json:{plans:[latest],total:1,page:1,per_page:50}});return true;}if(path.endsWith('/access-operations')){bodies.push(route.request().postDataJSON());if(bodies.length===1)await route.fulfill({status:409,json:{error:{code:'ACCESS_PLAN_CONFLICT'}}});else await route.fulfill({status:202,json:{...operation,kind:'assign_plan',desired:{...desired,plan_id:planId,revision:8,period_days:30,reset_traffic:true}}});return true;}return false;});
 await page.goto('/admin/clients/'+clientId+'/show?lang=en');const section=page.getByRole('region',{name:'Access operations'});await section.getByLabel('Operation',{exact:true}).selectOption('assign_plan');await section.getByLabel('Plan',{exact:true}).selectOption(planId);await section.getByLabel('Reason',{exact:true}).fill('Migration');latest={...latest,revision:8,devices:4};
 await section.getByRole('button',{name:'Assign plan'}).click();await section.getByRole('button',{name:'Confirm assignment'}).click();await expect(section.getByRole('alert')).toContainText('revision changed');await expect(section.getByRole('textbox',{name:'Reason'})).toHaveValue('Migration');expect(bodies[0]).toEqual({kind:'assign_plan',plan_id:planId,revision:7,period_days:30,reason:'Migration'});
 await section.getByRole('button',{name:'Reload plans'}).click();await expect(section.getByLabel('Plan',{exact:true})).toHaveValue('');await expect(section.getByLabel('Plan',{exact:true})).toContainText('4 devices');await section.getByLabel('Plan',{exact:true}).selectOption(planId);await section.getByRole('button',{name:'Assign plan'}).click();await section.getByRole('button',{name:'Confirm assignment'}).click();await expect(section.getByText('Pending',{exact:true})).toBeVisible();expect(bodies[1].revision).toBe(8);expect(reads).toBeGreaterThanOrEqual(2);
});

test('late operation read from previous client cannot appear on another card',async({page})=>{
 let release!:()=>void,requested=0;const pending=new Promise<void>(resolve=>release=resolve);await routes(page,async(route,path)=>{if(path.endsWith('/operator/clients/'+clientId)){await route.fulfill({json:card(clientId,{...subscription,access_operation_id:operationId,access_operation_status:'needs_review'})});return true;}if(path.endsWith('/access-operations/'+operationId)){requested++;await pending;await route.fulfill({json:{...operation,status:'needs_review',review_reason:'OLD CLIENT REVIEW'}}).catch(()=>{});return true;}return false;});
 await page.goto('/admin/clients/'+clientId+'/show?lang=en');await expect.poll(()=>requested).toBe(1);await page.evaluate(id=>{history.pushState({},'',`/admin/clients/${id}/show?lang=en`);dispatchEvent(new PopStateEvent('popstate'));},otherId);await expect(page.getByRole('heading',{name:'Other Client'})).toBeVisible();release();await expect(page.getByText('OLD CLIENT REVIEW')).toHaveCount(0);
});

test('late read of a previous operation cannot replace a newly accepted operation on the same card',async({page})=>{
 let release!:()=>void,requested=0;const pending=new Promise<void>(resolve=>release=resolve);const nextId='30000000-0000-4000-8000-000000000004';await routes(page,async(route,path)=>{if(path.endsWith('/operator/clients/'+clientId)){await route.fulfill({json:card(clientId,{...subscription,access_operation_id:operationId,access_operation_status:'applied'})});return true;}if(path.endsWith('/access-operations/'+operationId)){requested++;await pending;await route.fulfill({json:{...operation,status:'needs_review',review_reason:'OLD READBACK'}}).catch(()=>{});return true;}if(path.endsWith('/access-operations')){await route.fulfill({status:202,json:{...operation,operation_id:nextId,status:'pending'}});return true;}return false;});
 await page.goto('/admin/clients/'+clientId+'/show?lang=en');const section=page.getByRole('region',{name:'Access operations'});await expect.poll(()=>requested).toBe(1);await section.getByLabel('Days to add').fill('10');await section.getByLabel('Reason',{exact:true}).fill('New operation');await section.getByRole('button',{name:'Add days'}).click();await expect(section.getByText(nextId)).toBeVisible();release();await expect(section.getByText('OLD READBACK')).toHaveCount(0);await expect(section.getByText('Pending',{exact:true})).toBeVisible();
});

for(const status of [401,403])test(`operator ${status} during access-operation read closes the editor`,async({page})=>{
 await routes(page,async(route,path)=>{if(path.endsWith('/operator/clients/'+clientId)){await route.fulfill({json:card(clientId,{...subscription,access_operation_id:operationId,access_operation_status:'pending'})});return true;}if(path.endsWith('/access-operations/'+operationId)){await route.fulfill({status,json:{error:{code:status===401?'INVALID_CREDENTIALS':'ACCOUNT_RESTRICTED'}}});return true;}return false;});
 await page.goto('/admin/clients/'+clientId+'/show?lang=en');await expect(page.getByRole('heading',{name:'Operator access required'})).toBeVisible();await expect(page.getByRole('button',{name:'Add days'})).toHaveCount(0);
});

test('customer sees active confirmed access separately from a pending operation and refreshes its result',async({page})=>{
 await page.clock.install({time:new Date('2026-10-02T00:00:00Z')});let reads=0;await routes(page,async(route,path)=>{if(path.endsWith('/me')){await route.fulfill({json:{account:{account_id:clientId,email:'client@example.test',email_verified:true,locale:'en',telegram_linked:false},csrf_token:'s'.repeat(43),capabilities:{trial_available:false}}});return true;}if(path.endsWith('/trial-requests/current')){await route.fulfill({json:{request:null}});return true;}if(path.endsWith('/subscription')){reads++;await route.fulfill({json:reads===1?{...subscription,access_operation_id:operationId,access_operation_status:'pending'}:{...subscription,devices:3,expires_at:'2026-11-02T00:00:00Z',access_operation_id:operationId,access_operation_status:'applied'}});return true;}return false;});
 await page.goto('/cabinet?lang=en');await expect(page.getByText('Access operations: Pending')).toBeVisible();await expect(page.getByText('2',{exact:true})).toBeVisible();await page.clock.runFor(5000);await expect(page.getByText('3',{exact:true})).toBeVisible();await expect(page.getByText('Access operations: Pending')).toHaveCount(0);expect(reads).toBe(2);
});
