import {test,expect,type Page,type Route} from '@playwright/test';
import type {components} from '../src/api/schema.gen';

type Model<K extends keyof components['schemas']>=components['schemas'][K];
const operatorId='10000000-0000-4000-8000-000000000001';
const clientId='20000000-0000-4000-8000-000000000002';
const operationId='30000000-0000-4000-8000-000000000003';
const client:Model<'OperatorClient'>={account_id:clientId,kind:'telegram',display_name:'Access Client',email:null,telegram_id:'123456789',locale:'en',created_at:null,restricted:false,vpn_banned:false,had_subscription:true};
const subscription:Model<'Subscription'>={status:'active',expires_at:'2026-10-12T00:00:00Z',devices:2,traffic_limit_bytes:1024,traffic_used_bytes:128,observed_at:'2026-10-02T00:00:00Z',data_stale:false,access_profile:'regular',vpn_banned:false,access_operation_id:null,access_operation_status:null};
const desired:Model<'AccessDesired'>={expires_at:subscription.expires_at,devices:2,traffic_limit_bytes:1024,profile:'regular',plan_id:null,revision:null,period_days:null,reset_traffic:false,vpn_banned:false};
const operation:Model<'AccessOperation'>={operation_id:operationId,account_id:clientId,kind:'set_profile',status:'pending',created_at:'2026-10-02T00:00:00Z',updated_at:'2026-10-02T00:00:00Z',reason:'Switch profile',operator_account_id:operatorId,desired,completed_steps:['prepared'],review_reason:null};
const audit:Model<'OperatorAuditEvent'>={id:'50000000-0000-4000-8000-000000000001',created_at:'2026-10-02T00:00:00Z',action:'monthly_reset_requested',request_id:null,operation_id:null,operator_tg_id:null,operator_account_id:null,reason:null,support_message_id:null,access_operation_id:operationId,system_actor:true,monthly_period:'2026-10'};
const card=(sub=subscription):Model<'OperatorClientCard'>=>({client,subscription:sub,server:{panel_id:'configured',enabled:true},support:null,trial_requests:[],trial_has_more:false,audit_events:[audit],audit_has_more:false,legacy_approval:null,legacy_events:[],legacy_has_more:false});
async function routes(page:Page,extra?:(route:Route,path:string)=>Promise<boolean>){await page.route('**/api/v1/**',async route=>{const path=new URL(route.request().url()).pathname;if(extra&&await extra(route,path))return;if(path.endsWith('/operator/session'))return route.fulfill({json:{account:{account_id:operatorId,email:'operator@example.test',email_verified:true,locale:'en',telegram_linked:false},csrf_token:'s'.repeat(43)}});if(path.endsWith('/operator/clients/'+clientId))return route.fulfill({json:card()});if(path.endsWith('/support'))return route.fulfill({json:{conversation:null,messages:[],has_more:false,oldest_sequence:null}});return route.fulfill({json:{}});});}
const value=(page:Page,label:string)=>page.locator('dt').filter({hasText:new RegExp('^'+label+'$')}).locator('xpath=following-sibling::dd[1]').first();

test('profile change sends exact kind and shows preserving conditions before confirmation',async({page})=>{
 const bodies:Model<'AccessOperationInput'>[]=[];await routes(page,async(route,path)=>{if(path.endsWith('/access-operations')){bodies.push(route.request().postDataJSON());await route.fulfill({status:202,json:{...operation,desired:{...desired,profile:'euru'}}});return true;}return false;});
 await page.setViewportSize({width:375,height:812});await page.goto('/admin/clients/'+clientId+'/show?lang=en');const section=page.getByRole('region',{name:'Access operations'});
 await section.getByLabel('Operation',{exact:true}).selectOption('set_profile');await section.getByLabel('Profile',{exact:true}).selectOption('euru');await section.getByLabel('Profile',{exact:true}).focus();await page.keyboard.press('Tab');await expect(section.getByRole('textbox',{name:'Reason'})).toBeFocused();await section.getByLabel('Reason',{exact:true}).fill('Switch profile');await section.getByRole('button',{name:'Change profile'}).click();await expect(section.locator('.access-create > .warning')).toContainText(/expiry.*limits.*traffic.*VPN ban/i);expect(bodies).toHaveLength(0);
 await section.getByRole('button',{name:'Confirm profile change'}).click();await expect(section.getByText('Pending',{exact:true})).toBeVisible();expect(bodies).toEqual([{kind:'set_profile',profile:'euru',reason:'Switch profile'}]);await expect(value(page,'Access profile')).toHaveText('Regular');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('unlimited and revoke warn about hidden plan, new trial period and reset',async({page})=>{
 const bodies:Model<'AccessOperationInput'>[]=[];let sub=subscription;await routes(page,async(route,path)=>{if(path.endsWith('/operator/clients/'+clientId)){await route.fulfill({json:card(sub)});return true;}if(path.endsWith('/access-operations')){const body:Model<'AccessOperationInput'>=route.request().postDataJSON();bodies.push(body);await route.fulfill({status:202,json:{...operation,kind:'set_profile',desired:{...desired,profile:body.profile!,reset_traffic:body.profile!=='unlimited'}}});return true;}return false;});
 await page.goto('/admin/clients/'+clientId+'/show?lang=en');let section=page.getByRole('region',{name:'Access operations'});await section.getByLabel('Operation',{exact:true}).selectOption('set_profile');await section.getByLabel('Profile',{exact:true}).selectOption('unlimited');await section.getByLabel('Reason',{exact:true}).fill('Grant unlimited');await section.getByRole('button',{name:'Change profile'}).click();await expect(section.locator('.access-create > .warning')).toContainText(/hidden.*plan.*monthly reset/i);await section.getByRole('button',{name:'Confirm profile change'}).click();expect(bodies[0]).toEqual({kind:'set_profile',profile:'unlimited',reason:'Grant unlimited'});
 sub={...sub,access_profile:'unlimited',expires_at:null};await page.reload();section=page.getByRole('region',{name:'Access operations'});await section.getByLabel('Operation',{exact:true}).selectOption('set_profile');await section.getByLabel('Profile',{exact:true}).selectOption('euru');await section.getByLabel('Reason',{exact:true}).fill('Leave unlimited');await section.getByRole('button',{name:'Change profile'}).click();await expect(section.locator('.access-create > .warning')).toContainText(/new trial period.*reset/i);await section.getByRole('button',{name:'Confirm profile change'}).click();expect(bodies[1]).toEqual({kind:'set_profile',profile:'euru',reason:'Leave unlimited'});
});

test('ban remains distinct, retries with one key and keeps reason after lost response',async({page})=>{
 const calls:{body:Model<'AccessOperationInput'>;key:string}[]=[];await routes(page,async(route,path)=>{if(path.endsWith('/access-operations')){calls.push({body:route.request().postDataJSON(),key:route.request().headers()['idempotency-key']});if(calls.length===1)await route.abort();else await route.fulfill({status:202,json:{...operation,kind:'set_vpn_ban',desired:{...desired,vpn_banned:true}}});return true;}return false;});
 await page.goto('/admin/clients/'+clientId+'/show?lang=en');const section=page.getByRole('region',{name:'Access operations'});await section.getByLabel('Operation',{exact:true}).selectOption('set_vpn_ban');await section.getByLabel('VPN ban',{exact:true}).selectOption('true');await section.getByLabel('Reason',{exact:true}).fill('Abuse');await section.getByRole('button',{name:'Change VPN ban'}).click();await expect(section.locator('.access-create > .warning')).toContainText(/VPN.*account.*support/i);await section.getByRole('button',{name:'Confirm VPN ban'}).click();await expect(section.getByRole('alert')).toBeVisible();await expect(section.getByRole('textbox',{name:'Reason'})).toHaveValue('Abuse');await section.getByRole('button',{name:'Change VPN ban'}).click();await section.getByRole('button',{name:'Confirm VPN ban'}).click();await expect(section.getByText('Pending',{exact:true})).toBeVisible();expect(calls).toHaveLength(2);expect(calls[0].body).toEqual({kind:'set_vpn_ban',vpn_banned:true,reason:'Abuse'});expect(calls[1]).toEqual(calls[0]);await expect(value(page,'VPN access')).toHaveText('VPN access allowed');
});

test('no-client profile intent and same-state retry report different outcomes',async({page})=>{
 let empty:Model<'Subscription'>={...subscription,status:'none',access_profile:'euru',vpn_banned:true,expires_at:null,devices:0,traffic_limit_bytes:0,traffic_used_bytes:0};let writes=0;
 await routes(page,async(route,path)=>{if(path.endsWith('/operator/clients/'+clientId)){await route.fulfill({json:card(empty)});return true;}if(path.endsWith('/access-operations')){writes++;expect(route.request().postDataJSON()).toEqual({kind:'set_profile',profile:'regular',reason:'Keep intent'});if(writes===1)empty={...empty,access_profile:'regular'};await route.fulfill({status:202,json:{...operation,status:'applied',completed_steps:writes===1?['intent_saved']:['state_unchanged'],desired:{...desired,profile:'regular',vpn_banned:true}}});return true;}return false;});
 await page.goto('/admin/clients/'+clientId+'/show?lang=en');const section=page.getByRole('region',{name:'Access operations'});await expect(value(page,'Access profile')).toHaveText('EURU');await expect(value(page,'VPN access')).toHaveText('VPN access blocked');await section.getByLabel('Operation',{exact:true}).selectOption('set_profile');await section.getByLabel('Profile',{exact:true}).selectOption('regular');await section.getByLabel('Reason',{exact:true}).fill('Keep intent');await section.getByRole('button',{name:'Change profile'}).click();await expect(section.locator('.access-create > .warning')).toContainText(/future.*provision/i);await section.getByRole('button',{name:'Confirm profile change'}).click();await expect(section.getByText(/saved.*future/i)).toBeVisible();await expect(value(page,'Access profile')).toHaveText('Regular');
 await section.getByRole('button',{name:'Change profile'}).click();await section.getByRole('button',{name:'Confirm profile change'}).click();await expect(section.getByText(/already.*requested state/i)).toBeVisible();expect(writes).toBe(2);await page.getByRole('button',{name:'RU',exact:true}).click();await expect(page.getByRole('region',{name:'Операции доступа'}).getByText(/запрошенное состояние уже действует/i)).toBeVisible();
});

test('customer sees confirmed profile and ban separately while pending or skipped',async({page})=>{
 await routes(page,async(route,path)=>{if(path.endsWith('/me')){await route.fulfill({json:{account:{account_id:clientId,email:'client@example.test',email_verified:true,locale:'en',telegram_linked:false},csrf_token:'s'.repeat(43),capabilities:{trial_available:false}}});return true;}if(path.endsWith('/trial-requests/current')){await route.fulfill({json:{request:null}});return true;}if(path.endsWith('/subscription')){await route.fulfill({json:{...subscription,status:'none',access_profile:'euru',vpn_banned:true,access_operation_id:operationId,access_operation_status:'pending'}});return true;}return false;});await page.goto('/cabinet?lang=en');await expect(value(page,'Access profile')).toHaveText('EURU');await expect(value(page,'VPN access')).toHaveText('VPN access blocked');await expect(page.getByText('Access operations: Pending')).toBeVisible();await page.getByRole('button',{name:'RU',exact:true}).click();await expect(value(page,'Профиль доступа')).toHaveText('EURU');await expect(value(page,'VPN-доступ')).toHaveText('VPN заблокирован');
});

test('system monthly audit uses system actor and human period',async({page})=>{
 const actions=['monthly_reset_requested','monthly_reset_waiting','monthly_reset_skipped','monthly_reset_applied','monthly_reset_period_elapsed_unserved'];await routes(page,async(route,path)=>{if(path.endsWith('/operator/clients/'+clientId)){await route.fulfill({json:{...card(),audit_events:actions.map((action,index)=>({...audit,id:`50000000-0000-4000-8000-00000000000${index+1}`,action}))}});return true;}return false;});await page.goto('/admin/clients/'+clientId+'/show?lang=en');const rows=page.locator('.admin-audit');await expect(rows).toHaveCount(5);for(const row of await rows.all()){await expect(row).toContainText('System');await expect(row).toContainText('October 2026');await expect(row).not.toContainText('monthly_reset_');}await expect(rows.nth(0)).toContainText('Monthly reset requested');await expect(rows.nth(1)).toContainText('Waiting for the current access operation');await expect(rows.nth(2)).toContainText('Monthly reset skipped');await expect(rows.nth(3)).toContainText('Monthly reset applied');await expect(rows.nth(4)).toContainText('Period ended without a reset');
});

test('unban confirmation does not promise access after expiry',async({page})=>{
 const expired:Model<'Subscription'>={...subscription,status:'expired',vpn_banned:true};await routes(page,async(route,path)=>{if(path.endsWith('/operator/clients/'+clientId)){await route.fulfill({json:card(expired)});return true;}return false;});await page.goto('/admin/clients/'+clientId+'/show?lang=en');const section=page.getByRole('region',{name:'Access operations'});await section.getByLabel('Operation',{exact:true}).selectOption('set_vpn_ban');await section.getByLabel('VPN ban',{exact:true}).selectOption('false');await section.getByLabel('Reason',{exact:true}).fill('Reviewed');await section.getByRole('button',{name:'Change VPN ban'}).click();await expect(section.locator('.access-create > .warning')).toContainText(/expired or exhausted access may still be unavailable/i);await expect(value(page,'VPN access')).toHaveText('VPN access blocked');
});

test('skipped monthly operation keeps confirmed access and explains eligibility change',async({page})=>{
 const sub:Model<'Subscription'>={...subscription,access_operation_id:operationId,access_operation_status:'pending'};await routes(page,async(route,path)=>{if(path.endsWith('/operator/clients/'+clientId)){await route.fulfill({json:card(sub)});return true;}if(path.endsWith('/access-operations/'+operationId)){await route.fulfill({json:{...operation,kind:'monthly_reset',status:'skipped',completed_steps:['eligibility_changed']}});return true;}return false;});await page.goto('/admin/clients/'+clientId+'/show?lang=en');const section=page.getByRole('region',{name:'Access operations'});await expect(section.getByText('Skipped',{exact:true})).toBeVisible();await expect(section.getByText(/eligibility changed/i)).toBeVisible();await expect(value(page,'Access profile')).toHaveText('Regular');await expect(value(page,'VPN access')).toHaveText('VPN access allowed');
});

test('queued monthly reset whose period ended is skipped without implying an eligibility change',async({page})=>{
 const sub:Model<'Subscription'>={...subscription,access_operation_id:operationId,access_operation_status:'pending'};await routes(page,async(route,path)=>{if(path.endsWith('/operator/clients/'+clientId)){await route.fulfill({json:card(sub)});return true;}if(path.endsWith('/access-operations/'+operationId)){await route.fulfill({json:{...operation,kind:'monthly_reset',status:'skipped',completed_steps:['period_elapsed_unserved']}});return true;}return false;});await page.goto('/admin/clients/'+clientId+'/show?lang=en');const section=page.getByRole('region',{name:'Access operations'});await expect(section.getByText('Skipped',{exact:true})).toBeVisible();await expect(section.getByText('Period ended without a reset')).toBeVisible();await expect(section.getByText(/eligibility changed/i)).toHaveCount(0);await expect(section.getByText('period_elapsed_unserved')).toHaveCount(0);await page.getByRole('button',{name:'RU',exact:true}).click();await expect(page.getByRole('region',{name:'Операции доступа'}).getByText('Период завершился без сброса')).toBeVisible();
});

for(const status of [401,403])test(`role loss ${status} while changing VPN ban closes operator actions`,async({page})=>{
 await routes(page,async(route,path)=>{if(path.endsWith('/access-operations')){await route.fulfill({status,json:{error:{code:status===401?'INVALID_CREDENTIALS':'ACCOUNT_RESTRICTED'}}});return true;}return false;});await page.goto('/admin/clients/'+clientId+'/show?lang=en');const section=page.getByRole('region',{name:'Access operations'});await section.getByLabel('Operation',{exact:true}).selectOption('set_vpn_ban');await section.getByLabel('Reason',{exact:true}).fill('Role check');await section.getByRole('button',{name:'Change VPN ban'}).click();await section.getByRole('button',{name:'Confirm VPN ban'}).click();await expect(page.getByRole('heading',{name:'Operator access required'})).toBeVisible();await expect(page.getByRole('button',{name:'Change VPN ban'})).toHaveCount(0);
});
