// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shared.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addAudit = `-- name: AddAudit :exec
INSERT INTO audit_events(id,created_at,action,account_id,request_id,operation_id,operator_tg_id,reason) VALUES($1,$2,$3,$4,$5,$6,$7,$8)
`

type AddAuditParams struct {
	ID           uuid.UUID
	CreatedAt    pgtype.Timestamptz
	Action       string
	AccountID    uuid.UUID
	RequestID    *uuid.UUID
	OperationID  *uuid.UUID
	OperatorTgID pgtype.Int8
	Reason       pgtype.Text
}

func (q *Queries) AddAudit(ctx context.Context, arg AddAuditParams) error {
	_, err := q.db.Exec(ctx, addAudit,
		arg.ID,
		arg.CreatedAt,
		arg.Action,
		arg.AccountID,
		arg.RequestID,
		arg.OperationID,
		arg.OperatorTgID,
		arg.Reason,
	)
	return err
}

const addIdempotency = `-- name: AddIdempotency :exec
INSERT INTO idempotency_records(principal,operation,key,body_hash,result,created_at) VALUES($1,$2,$3,$4,$5,$6)
`

type AddIdempotencyParams struct {
	Principal string
	Operation string
	Key       uuid.UUID
	BodyHash  []byte
	Result    []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) AddIdempotency(ctx context.Context, arg AddIdempotencyParams) error {
	_, err := q.db.Exec(ctx, addIdempotency,
		arg.Principal,
		arg.Operation,
		arg.Key,
		arg.BodyHash,
		arg.Result,
		arg.CreatedAt,
	)
	return err
}

const addOperatorAudit = `-- name: AddOperatorAudit :exec
INSERT INTO audit_events(id,created_at,action,account_id,request_id,operation_id,operator_account_id,reason)
VALUES($1,$2,$3,$4,$5,$6,$7,$8)
`

type AddOperatorAuditParams struct {
	ID                uuid.UUID
	CreatedAt         pgtype.Timestamptz
	Action            string
	AccountID         uuid.UUID
	RequestID         *uuid.UUID
	OperationID       *uuid.UUID
	OperatorAccountID *uuid.UUID
	Reason            pgtype.Text
}

func (q *Queries) AddOperatorAudit(ctx context.Context, arg AddOperatorAuditParams) error {
	_, err := q.db.Exec(ctx, addOperatorAudit,
		arg.ID,
		arg.CreatedAt,
		arg.Action,
		arg.AccountID,
		arg.RequestID,
		arg.OperationID,
		arg.OperatorAccountID,
		arg.Reason,
	)
	return err
}

const addTelegramDelivery = `-- name: AddTelegramDelivery :exec
INSERT INTO telegram_deliveries(id,request_id,operation_id,chat_id,kind,payload,state,created_at,available_at) VALUES($1,$2,$3,$4,$5,$6,'pending',$7,$7)
`

type AddTelegramDeliveryParams struct {
	ID          uuid.UUID
	RequestID   uuid.UUID
	OperationID *uuid.UUID
	ChatID      int64
	Kind        string
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) AddTelegramDelivery(ctx context.Context, arg AddTelegramDeliveryParams) error {
	_, err := q.db.Exec(ctx, addTelegramDelivery,
		arg.ID,
		arg.RequestID,
		arg.OperationID,
		arg.ChatID,
		arg.Kind,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const idempotencyByKey = `-- name: IdempotencyByKey :one
SELECT principal, operation, key, body_hash, result, created_at FROM idempotency_records WHERE principal=$1 AND operation=$2 AND key=$3
`

type IdempotencyByKeyParams struct {
	Principal string
	Operation string
	Key       uuid.UUID
}

func (q *Queries) IdempotencyByKey(ctx context.Context, arg IdempotencyByKeyParams) (IdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, idempotencyByKey, arg.Principal, arg.Operation, arg.Key)
	var i IdempotencyRecord
	err := row.Scan(
		&i.Principal,
		&i.Operation,
		&i.Key,
		&i.BodyHash,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const latestTelegramMessage = `-- name: LatestTelegramMessage :one
SELECT message_id FROM telegram_deliveries WHERE request_id=$1 AND chat_id=$2 AND state='sent' AND message_id IS NOT NULL ORDER BY sequence DESC LIMIT 1
`

type LatestTelegramMessageParams struct {
	RequestID uuid.UUID
	ChatID    int64
}

func (q *Queries) LatestTelegramMessage(ctx context.Context, arg LatestTelegramMessageParams) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, latestTelegramMessage, arg.RequestID, arg.ChatID)
	var message_id pgtype.Int8
	err := row.Scan(&message_id)
	return message_id, err
}

const latestTelegramState = `-- name: LatestTelegramState :one
SELECT state FROM telegram_deliveries WHERE request_id=$1 AND chat_id=$2 ORDER BY sequence DESC LIMIT 1
`

type LatestTelegramStateParams struct {
	RequestID uuid.UUID
	ChatID    int64
}

func (q *Queries) LatestTelegramState(ctx context.Context, arg LatestTelegramStateParams) (string, error) {
	row := q.db.QueryRow(ctx, latestTelegramState, arg.RequestID, arg.ChatID)
	var state string
	err := row.Scan(&state)
	return state, err
}

const lockDecisionCallback = `-- name: LockDecisionCallback :exec
SELECT pg_advisory_xact_lock(hashtextextended('callback:'||$1::text,0))
`

func (q *Queries) LockDecisionCallback(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, lockDecisionCallback, dollar_1)
	return err
}

const lockIdempotency = `-- name: LockIdempotency :exec
SELECT pg_advisory_xact_lock(hashtextextended('idem:'||$1::text||':'||$2::text||':'||$3::uuid::text,0))
`

type LockIdempotencyParams struct {
	Principal string
	Operation string
	Key       uuid.UUID
}

func (q *Queries) LockIdempotency(ctx context.Context, arg LockIdempotencyParams) error {
	_, err := q.db.Exec(ctx, lockIdempotency, arg.Principal, arg.Operation, arg.Key)
	return err
}

const lockIdempotencySession = `-- name: LockIdempotencySession :exec
SELECT pg_advisory_lock(hashtextextended('idem:'||$1::text||':'||$2::text||':'||$3::uuid::text,0))
`

type LockIdempotencySessionParams struct {
	Principal string
	Operation string
	Key       uuid.UUID
}

func (q *Queries) LockIdempotencySession(ctx context.Context, arg LockIdempotencySessionParams) error {
	_, err := q.db.Exec(ctx, lockIdempotencySession, arg.Principal, arg.Operation, arg.Key)
	return err
}
