// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trials.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCallback = `-- name: AddCallback :exec
INSERT INTO decision_callbacks(id,request_id,operator_tg_id,body_hash,result,created_at) VALUES($1,$2,$3,$4,$5,$6)
`

type AddCallbackParams struct {
	ID           string
	RequestID    uuid.UUID
	OperatorTgID int64
	BodyHash     []byte
	Result       []byte
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) AddCallback(ctx context.Context, arg AddCallbackParams) error {
	_, err := q.db.Exec(ctx, addCallback,
		arg.ID,
		arg.RequestID,
		arg.OperatorTgID,
		arg.BodyHash,
		arg.Result,
		arg.CreatedAt,
	)
	return err
}

const addTrial = `-- name: AddTrial :one
INSERT INTO trial_requests(id,account_id,status,comment,created_at,previous_request_id) VALUES($1,$2,'pending',$3,$4,$5) RETURNING id, sequence, account_id, status, comment, created_at, decided_at, operator_tg_id, reason, operation_id, previous_request_id, operator_account_id, decision_source
`

type AddTrialParams struct {
	ID                uuid.UUID
	AccountID         uuid.UUID
	Comment           string
	CreatedAt         pgtype.Timestamptz
	PreviousRequestID *uuid.UUID
}

func (q *Queries) AddTrial(ctx context.Context, arg AddTrialParams) (TrialRequest, error) {
	row := q.db.QueryRow(ctx, addTrial,
		arg.ID,
		arg.AccountID,
		arg.Comment,
		arg.CreatedAt,
		arg.PreviousRequestID,
	)
	var i TrialRequest
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.AccountID,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.OperatorTgID,
		&i.Reason,
		&i.OperationID,
		&i.PreviousRequestID,
		&i.OperatorAccountID,
		&i.DecisionSource,
	)
	return i, err
}

const callbackByID = `-- name: CallbackByID :one
SELECT id, request_id, operator_tg_id, body_hash, result, created_at FROM decision_callbacks WHERE id=$1
`

func (q *Queries) CallbackByID(ctx context.Context, id string) (DecisionCallback, error) {
	row := q.db.QueryRow(ctx, callbackByID, id)
	var i DecisionCallback
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.OperatorTgID,
		&i.BodyHash,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const currentTrial = `-- name: CurrentTrial :one
SELECT id, sequence, account_id, status, comment, created_at, decided_at, operator_tg_id, reason, operation_id, previous_request_id, operator_account_id, decision_source FROM trial_requests WHERE account_id=$1 ORDER BY sequence DESC LIMIT 1
`

func (q *Queries) CurrentTrial(ctx context.Context, accountID uuid.UUID) (TrialRequest, error) {
	row := q.db.QueryRow(ctx, currentTrial, accountID)
	var i TrialRequest
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.AccountID,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.OperatorTgID,
		&i.Reason,
		&i.OperationID,
		&i.PreviousRequestID,
		&i.OperatorAccountID,
		&i.DecisionSource,
	)
	return i, err
}

const decideTrial = `-- name: DecideTrial :one
UPDATE trial_requests SET status=$2,decided_at=$3,operator_tg_id=$4,reason=$5,operation_id=$6 WHERE id=$1 AND status='pending' RETURNING id, sequence, account_id, status, comment, created_at, decided_at, operator_tg_id, reason, operation_id, previous_request_id, operator_account_id, decision_source
`

type DecideTrialParams struct {
	ID           uuid.UUID
	Status       string
	DecidedAt    pgtype.Timestamptz
	OperatorTgID pgtype.Int8
	Reason       pgtype.Text
	OperationID  *uuid.UUID
}

func (q *Queries) DecideTrial(ctx context.Context, arg DecideTrialParams) (TrialRequest, error) {
	row := q.db.QueryRow(ctx, decideTrial,
		arg.ID,
		arg.Status,
		arg.DecidedAt,
		arg.OperatorTgID,
		arg.Reason,
		arg.OperationID,
	)
	var i TrialRequest
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.AccountID,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.OperatorTgID,
		&i.Reason,
		&i.OperationID,
		&i.PreviousRequestID,
		&i.OperatorAccountID,
		&i.DecisionSource,
	)
	return i, err
}

const decideTrialAutomatic = `-- name: DecideTrialAutomatic :one
UPDATE trial_requests SET status='approved',decision_source='telegram_auto',decided_at=$2,operation_id=$3
WHERE id=$1 AND status='pending' RETURNING id, sequence, account_id, status, comment, created_at, decided_at, operator_tg_id, reason, operation_id, previous_request_id, operator_account_id, decision_source
`

type DecideTrialAutomaticParams struct {
	ID          uuid.UUID
	DecidedAt   pgtype.Timestamptz
	OperationID *uuid.UUID
}

func (q *Queries) DecideTrialAutomatic(ctx context.Context, arg DecideTrialAutomaticParams) (TrialRequest, error) {
	row := q.db.QueryRow(ctx, decideTrialAutomatic, arg.ID, arg.DecidedAt, arg.OperationID)
	var i TrialRequest
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.AccountID,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.OperatorTgID,
		&i.Reason,
		&i.OperationID,
		&i.PreviousRequestID,
		&i.OperatorAccountID,
		&i.DecisionSource,
	)
	return i, err
}

const decideTrialWeb = `-- name: DecideTrialWeb :one
UPDATE trial_requests SET status=$2,decided_at=$3,operator_account_id=$4,reason=$5,operation_id=$6
WHERE id=$1 AND status='pending' RETURNING id, sequence, account_id, status, comment, created_at, decided_at, operator_tg_id, reason, operation_id, previous_request_id, operator_account_id, decision_source
`

type DecideTrialWebParams struct {
	ID                uuid.UUID
	Status            string
	DecidedAt         pgtype.Timestamptz
	OperatorAccountID *uuid.UUID
	Reason            pgtype.Text
	OperationID       *uuid.UUID
}

func (q *Queries) DecideTrialWeb(ctx context.Context, arg DecideTrialWebParams) (TrialRequest, error) {
	row := q.db.QueryRow(ctx, decideTrialWeb,
		arg.ID,
		arg.Status,
		arg.DecidedAt,
		arg.OperatorAccountID,
		arg.Reason,
		arg.OperationID,
	)
	var i TrialRequest
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.AccountID,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.OperatorTgID,
		&i.Reason,
		&i.OperationID,
		&i.PreviousRequestID,
		&i.OperatorAccountID,
		&i.DecisionSource,
	)
	return i, err
}

const grantApplied = `-- name: GrantApplied :exec
UPDATE trial_grants SET status='granted',granted_at=coalesce(granted_at,$2) WHERE operation_id=$1
`

type GrantAppliedParams struct {
	OperationID uuid.UUID
	GrantedAt   pgtype.Timestamptz
}

func (q *Queries) GrantApplied(ctx context.Context, arg GrantAppliedParams) error {
	_, err := q.db.Exec(ctx, grantApplied, arg.OperationID, arg.GrantedAt)
	return err
}

const grantStatus = `-- name: GrantStatus :one
SELECT status FROM trial_grants WHERE operation_id=$1 AND account_id=$2
`

type GrantStatusParams struct {
	OperationID uuid.UUID
	AccountID   uuid.UUID
}

func (q *Queries) GrantStatus(ctx context.Context, arg GrantStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, grantStatus, arg.OperationID, arg.AccountID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const hasGrant = `-- name: HasGrant :one
SELECT EXISTS(SELECT 1 FROM trial_grants WHERE account_id=$1)
`

func (q *Queries) HasGrant(ctx context.Context, accountID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasGrant, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lockTrial = `-- name: LockTrial :one
SELECT id, sequence, account_id, status, comment, created_at, decided_at, operator_tg_id, reason, operation_id, previous_request_id, operator_account_id, decision_source FROM trial_requests WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockTrial(ctx context.Context, id uuid.UUID) (TrialRequest, error) {
	row := q.db.QueryRow(ctx, lockTrial, id)
	var i TrialRequest
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.AccountID,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.OperatorTgID,
		&i.Reason,
		&i.OperationID,
		&i.PreviousRequestID,
		&i.OperatorAccountID,
		&i.DecisionSource,
	)
	return i, err
}

const operatorTrialPage = `-- name: OperatorTrialPage :many
SELECT id, sequence, account_id, status, comment, created_at, decided_at, operator_tg_id, reason, operation_id, previous_request_id, operator_account_id, decision_source FROM trial_requests WHERE account_id=$1
 AND ($2::timestamptz IS NULL OR
      (created_at,id)<($2::timestamptz,$3::uuid))
ORDER BY created_at DESC,id DESC LIMIT 51
`

type OperatorTrialPageParams struct {
	AccountID       uuid.UUID
	BeforeCreatedAt pgtype.Timestamptz
	BeforeID        uuid.UUID
}

func (q *Queries) OperatorTrialPage(ctx context.Context, arg OperatorTrialPageParams) ([]TrialRequest, error) {
	rows, err := q.db.Query(ctx, operatorTrialPage, arg.AccountID, arg.BeforeCreatedAt, arg.BeforeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrialRequest
	for rows.Next() {
		var i TrialRequest
		if err := rows.Scan(
			&i.ID,
			&i.Sequence,
			&i.AccountID,
			&i.Status,
			&i.Comment,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.OperatorTgID,
			&i.Reason,
			&i.OperationID,
			&i.PreviousRequestID,
			&i.OperatorAccountID,
			&i.DecisionSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveGrant = `-- name: ReserveGrant :exec
INSERT INTO trial_grants(account_id,request_id,operation_id,status,created_at) VALUES($1,$2,$3,'reserved',$4)
`

type ReserveGrantParams struct {
	AccountID   uuid.UUID
	RequestID   uuid.UUID
	OperationID uuid.UUID
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ReserveGrant(ctx context.Context, arg ReserveGrantParams) error {
	_, err := q.db.Exec(ctx, reserveGrant,
		arg.AccountID,
		arg.RequestID,
		arg.OperationID,
		arg.CreatedAt,
	)
	return err
}

const trialByID = `-- name: TrialByID :one
SELECT id, sequence, account_id, status, comment, created_at, decided_at, operator_tg_id, reason, operation_id, previous_request_id, operator_account_id, decision_source FROM trial_requests WHERE id=$1
`

func (q *Queries) TrialByID(ctx context.Context, id uuid.UUID) (TrialRequest, error) {
	row := q.db.QueryRow(ctx, trialByID, id)
	var i TrialRequest
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.AccountID,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.OperatorTgID,
		&i.Reason,
		&i.OperationID,
		&i.PreviousRequestID,
		&i.OperatorAccountID,
		&i.DecisionSource,
	)
	return i, err
}
