// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mail.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCredentialMail = `-- name: AddCredentialMail :exec
INSERT INTO mail_deliveries(id,credential_challenge_id,email_key,ciphertext,created_at,kind) VALUES($1,$2,$3,$4,$5,$6)
`

type AddCredentialMailParams struct {
	ID                    uuid.UUID
	CredentialChallengeID *uuid.UUID
	EmailKey              string
	Ciphertext            []byte
	CreatedAt             pgtype.Timestamptz
	Kind                  string
}

func (q *Queries) AddCredentialMail(ctx context.Context, arg AddCredentialMailParams) error {
	_, err := q.db.Exec(ctx, addCredentialMail,
		arg.ID,
		arg.CredentialChallengeID,
		arg.EmailKey,
		arg.Ciphertext,
		arg.CreatedAt,
		arg.Kind,
	)
	return err
}

const addMail = `-- name: AddMail :exec
INSERT INTO mail_deliveries(id,challenge_id,email_key,ciphertext,created_at) VALUES($1,$2,$3,$4,$5)
`

type AddMailParams struct {
	ID          uuid.UUID
	ChallengeID *uuid.UUID
	EmailKey    string
	Ciphertext  []byte
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) AddMail(ctx context.Context, arg AddMailParams) error {
	_, err := q.db.Exec(ctx, addMail,
		arg.ID,
		arg.ChallengeID,
		arg.EmailKey,
		arg.Ciphertext,
		arg.CreatedAt,
	)
	return err
}

const addNoticeMail = `-- name: AddNoticeMail :exec
INSERT INTO mail_deliveries(id,notice_action_id,email_key,ciphertext,created_at,kind) VALUES($1,$2,$3,$4,$5,'operator_notice')
`

type AddNoticeMailParams struct {
	ID             uuid.UUID
	NoticeActionID *uuid.UUID
	EmailKey       string
	Ciphertext     []byte
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) AddNoticeMail(ctx context.Context, arg AddNoticeMailParams) error {
	_, err := q.db.Exec(ctx, addNoticeMail,
		arg.ID,
		arg.NoticeActionID,
		arg.EmailKey,
		arg.Ciphertext,
		arg.CreatedAt,
	)
	return err
}

const addReminderMail = `-- name: AddReminderMail :exec
INSERT INTO mail_deliveries(id,reminder_id,email_key,ciphertext,created_at,kind) VALUES($1,$2,$3,$4,$5,'reminder')
`

type AddReminderMailParams struct {
	ID         uuid.UUID
	ReminderID *uuid.UUID
	EmailKey   string
	Ciphertext []byte
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) AddReminderMail(ctx context.Context, arg AddReminderMailParams) error {
	_, err := q.db.Exec(ctx, addReminderMail,
		arg.ID,
		arg.ReminderID,
		arg.EmailKey,
		arg.Ciphertext,
		arg.CreatedAt,
	)
	return err
}

const clearCredentialMail = `-- name: ClearCredentialMail :exec
UPDATE mail_deliveries SET ciphertext=NULL WHERE credential_challenge_id=ANY($1::uuid[]) AND kind='credential'
`

func (q *Queries) ClearCredentialMail(ctx context.Context, proofIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCredentialMail, proofIds)
	return err
}

const completeMail = `-- name: CompleteMail :exec
UPDATE mail_deliveries SET ciphertext=NULL, delivered_at=$2 WHERE id=$1
`

type CompleteMailParams struct {
	ID          uuid.UUID
	DeliveredAt pgtype.Timestamptz
}

func (q *Queries) CompleteMail(ctx context.Context, arg CompleteMailParams) error {
	_, err := q.db.Exec(ctx, completeMail, arg.ID, arg.DeliveredAt)
	return err
}

const lookupMail = `-- name: LookupMail :one
SELECT id, challenge_id, email_key, ciphertext, created_at, delivered_at, kind, credential_challenge_id, reminder_id, notice_action_id FROM mail_deliveries WHERE id=$1
`

func (q *Queries) LookupMail(ctx context.Context, id uuid.UUID) (MailDelivery, error) {
	row := q.db.QueryRow(ctx, lookupMail, id)
	var i MailDelivery
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.EmailKey,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.Kind,
		&i.CredentialChallengeID,
		&i.ReminderID,
		&i.NoticeActionID,
	)
	return i, err
}

const mailByID = `-- name: MailByID :one
SELECT id, challenge_id, email_key, ciphertext, created_at, delivered_at, kind, credential_challenge_id, reminder_id, notice_action_id FROM mail_deliveries WHERE id=$1 FOR UPDATE
`

func (q *Queries) MailByID(ctx context.Context, id uuid.UUID) (MailDelivery, error) {
	row := q.db.QueryRow(ctx, mailByID, id)
	var i MailDelivery
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.EmailKey,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.Kind,
		&i.CredentialChallengeID,
		&i.ReminderID,
		&i.NoticeActionID,
	)
	return i, err
}

const revokeRegistrationMail = `-- name: RevokeRegistrationMail :exec
UPDATE mail_deliveries SET ciphertext = NULL WHERE email_key = $1 AND kind='registration' AND delivered_at IS NULL
`

func (q *Queries) RevokeRegistrationMail(ctx context.Context, emailKey string) error {
	_, err := q.db.Exec(ctx, revokeRegistrationMail, emailKey)
	return err
}
