// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telegram.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addTelegramDelivery = `-- name: AddTelegramDelivery :exec
INSERT INTO telegram_deliveries(id,request_id,operation_id,chat_id,kind,payload,state,created_at,available_at) VALUES($1,$2,$3,$4,$5,$6,'pending',$7,$7)
`

type AddTelegramDeliveryParams struct {
	ID          uuid.UUID
	RequestID   uuid.UUID
	OperationID *uuid.UUID
	ChatID      int64
	Kind        string
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) AddTelegramDelivery(ctx context.Context, arg AddTelegramDeliveryParams) error {
	_, err := q.db.Exec(ctx, addTelegramDelivery,
		arg.ID,
		arg.RequestID,
		arg.OperationID,
		arg.ChatID,
		arg.Kind,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const finishTelegram = `-- name: FinishTelegram :exec
UPDATE telegram_deliveries SET state=$2,message_id=$3,failure_code=$4,completed_at=clock_timestamp(),result_hash=$5 WHERE id=$1
`

type FinishTelegramParams struct {
	ID          uuid.UUID
	State       string
	MessageID   pgtype.Int8
	FailureCode pgtype.Text
	ResultHash  []byte
}

func (q *Queries) FinishTelegram(ctx context.Context, arg FinishTelegramParams) error {
	_, err := q.db.Exec(ctx, finishTelegram,
		arg.ID,
		arg.State,
		arg.MessageID,
		arg.FailureCode,
		arg.ResultHash,
	)
	return err
}

const latestTelegramMessage = `-- name: LatestTelegramMessage :one
SELECT message_id FROM telegram_deliveries WHERE request_id=$1 AND chat_id=$2 AND state='sent' AND message_id IS NOT NULL ORDER BY sequence DESC LIMIT 1
`

type LatestTelegramMessageParams struct {
	RequestID uuid.UUID
	ChatID    int64
}

func (q *Queries) LatestTelegramMessage(ctx context.Context, arg LatestTelegramMessageParams) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, latestTelegramMessage, arg.RequestID, arg.ChatID)
	var message_id pgtype.Int8
	err := row.Scan(&message_id)
	return message_id, err
}

const latestTelegramState = `-- name: LatestTelegramState :one
SELECT state FROM telegram_deliveries WHERE request_id=$1 AND chat_id=$2 ORDER BY sequence DESC LIMIT 1
`

type LatestTelegramStateParams struct {
	RequestID uuid.UUID
	ChatID    int64
}

func (q *Queries) LatestTelegramState(ctx context.Context, arg LatestTelegramStateParams) (string, error) {
	row := q.db.QueryRow(ctx, latestTelegramState, arg.RequestID, arg.ChatID)
	var state string
	err := row.Scan(&state)
	return state, err
}

const leaseTelegram = `-- name: LeaseTelegram :one
WITH candidate AS (
 SELECT id FROM telegram_deliveries WHERE state='pending' AND available_at<=clock_timestamp() AND (lease_expires_at IS NULL OR lease_expires_at<=clock_timestamp()) AND chat_id=ANY($2::bigint[]) ORDER BY sequence LIMIT 1 FOR UPDATE SKIP LOCKED
)
UPDATE telegram_deliveries SET lease_hash=$1,lease_expires_at=clock_timestamp()+interval '60 seconds',attempts=attempts+1 WHERE id=(SELECT id FROM candidate) RETURNING id, sequence, request_id, operation_id, chat_id, kind, payload, state, created_at, available_at, lease_hash, lease_expires_at, attempts, message_id, completed_at, failure_code, result_hash
`

type LeaseTelegramParams struct {
	LeaseHash   []byte
	OperatorIds []int64
}

func (q *Queries) LeaseTelegram(ctx context.Context, arg LeaseTelegramParams) (TelegramDelivery, error) {
	row := q.db.QueryRow(ctx, leaseTelegram, arg.LeaseHash, arg.OperatorIds)
	var i TelegramDelivery
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.RequestID,
		&i.OperationID,
		&i.ChatID,
		&i.Kind,
		&i.Payload,
		&i.State,
		&i.CreatedAt,
		&i.AvailableAt,
		&i.LeaseHash,
		&i.LeaseExpiresAt,
		&i.Attempts,
		&i.MessageID,
		&i.CompletedAt,
		&i.FailureCode,
		&i.ResultHash,
	)
	return i, err
}

const lockTelegram = `-- name: LockTelegram :one
SELECT id, sequence, request_id, operation_id, chat_id, kind, payload, state, created_at, available_at, lease_hash, lease_expires_at, attempts, message_id, completed_at, failure_code, result_hash,lease_expires_at>clock_timestamp() AS lease_valid FROM telegram_deliveries WHERE id=$1 FOR UPDATE
`

type LockTelegramRow struct {
	ID             uuid.UUID
	Sequence       pgtype.Int8
	RequestID      uuid.UUID
	OperationID    *uuid.UUID
	ChatID         int64
	Kind           string
	Payload        []byte
	State          string
	CreatedAt      pgtype.Timestamptz
	AvailableAt    pgtype.Timestamptz
	LeaseHash      []byte
	LeaseExpiresAt pgtype.Timestamptz
	Attempts       int32
	MessageID      pgtype.Int8
	CompletedAt    pgtype.Timestamptz
	FailureCode    pgtype.Text
	ResultHash     []byte
	LeaseValid     bool
}

func (q *Queries) LockTelegram(ctx context.Context, id uuid.UUID) (LockTelegramRow, error) {
	row := q.db.QueryRow(ctx, lockTelegram, id)
	var i LockTelegramRow
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.RequestID,
		&i.OperationID,
		&i.ChatID,
		&i.Kind,
		&i.Payload,
		&i.State,
		&i.CreatedAt,
		&i.AvailableAt,
		&i.LeaseHash,
		&i.LeaseExpiresAt,
		&i.Attempts,
		&i.MessageID,
		&i.CompletedAt,
		&i.FailureCode,
		&i.ResultHash,
		&i.LeaseValid,
	)
	return i, err
}
