// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type IdempotencyRecord struct {
	Principal string
	Operation string
	Key       uuid.UUID
	BodyHash  []byte
	Result    []byte
	CreatedAt pgtype.Timestamptz
}

type SupportConversation struct {
	ID                       uuid.UUID
	AccountID                uuid.UUID
	Status                   string
	SupportBanned            bool
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	CustomerReceivedSequence int64
	OperatorReceivedSequence int64
}

type SupportMessage struct {
	ID              uuid.UUID
	ConversationID  uuid.UUID
	Sequence        int64
	SenderAccountID uuid.UUID
	SenderKind      string
	Text            string
	CreatedAt       pgtype.Timestamptz
	AttachmentName  pgtype.Text
	AttachmentBytes []byte
}
