// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type IdempotencyRecord struct {
	Principal string
	Operation string
	Key       uuid.UUID
	BodyHash  []byte
	Result    []byte
	CreatedAt pgtype.Timestamptz
}

type SupportConversation struct {
	ID                       uuid.UUID
	AccountID                uuid.UUID
	Status                   string
	SupportBanned            bool
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	CustomerReceivedSequence int64
	OperatorReceivedSequence int64
}

type SupportMessage struct {
	ID              uuid.UUID
	ConversationID  uuid.UUID
	Sequence        int64
	SenderAccountID uuid.UUID
	SenderKind      string
	Text            string
	CreatedAt       pgtype.Timestamptz
	AttachmentName  pgtype.Text
	AttachmentBytes []byte
	TelegramOnly    pgtype.Bool
}

type SupportTelegramDelivery struct {
	ID              uuid.UUID
	Sequence        int64
	TopicID         uuid.UUID
	MessageID       *uuid.UUID
	ReceiptID       *uuid.UUID
	Kind            string
	Status          string
	Code            string
	Parts           []byte
	Lease           *uuid.UUID
	LeaseExpiresAt  pgtype.Timestamptz
	AvailableAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	PriorDeliveryID *uuid.UUID
}

type SupportTelegramReceipt struct {
	ID               uuid.UUID
	BotID            int64
	GroupID          int64
	ChatID           int64
	MessageID        int64
	UpdateID         int64
	ActorTgID        pgtype.Int8
	ThreadID         pgtype.Int8
	Action           string
	CallbackID       string
	Digest           []byte
	ActorAccountID   *uuid.UUID
	TargetAccountID  *uuid.UUID
	TopicID          *uuid.UUID
	SupportMessageID *uuid.UUID
	OwnerKey         uuid.UUID
	Result           []byte
	CreatedAt        pgtype.Timestamptz
}

type SupportTelegramTopic struct {
	ID        uuid.UUID
	BotID     int64
	GroupID   int64
	Kind      string
	AccountID *uuid.UUID
	GuestTgID pgtype.Int8
	ThreadID  pgtype.Int8
	Status    string
	Closed    bool
	CreatedAt pgtype.Timestamptz
	SourceID  pgtype.Int8
}
