// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telegram.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const accountTelegramTopic = `-- name: AccountTelegramTopic :one
SELECT id, bot_id, group_id, kind, account_id, guest_tg_id, thread_id, status, closed, support_banned, created_at, source_id FROM support_telegram_topics WHERE bot_id=$1 AND group_id=$2 AND account_id=$3 AND status<>'retired'
`

type AccountTelegramTopicParams struct {
	BotID     int64
	GroupID   int64
	AccountID *uuid.UUID
}

func (q *Queries) AccountTelegramTopic(ctx context.Context, arg AccountTelegramTopicParams) (SupportTelegramTopic, error) {
	row := q.db.QueryRow(ctx, accountTelegramTopic, arg.BotID, arg.GroupID, arg.AccountID)
	var i SupportTelegramTopic
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.GroupID,
		&i.Kind,
		&i.AccountID,
		&i.GuestTgID,
		&i.ThreadID,
		&i.Status,
		&i.Closed,
		&i.SupportBanned,
		&i.CreatedAt,
		&i.SourceID,
	)
	return i, err
}

const activeMessageTelegramDelivery = `-- name: ActiveMessageTelegramDelivery :one
SELECT EXISTS(SELECT 1 FROM support_telegram_deliveries WHERE message_id=$1 AND status IN ('queued','sending'))
`

func (q *Queries) ActiveMessageTelegramDelivery(ctx context.Context, messageID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, activeMessageTelegramDelivery, messageID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const addLegacyTelegramTopic = `-- name: AddLegacyTelegramTopic :exec
INSERT INTO support_telegram_topics(id,bot_id,group_id,kind,account_id,thread_id,status,closed,support_banned,created_at,source_id)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
`

type AddLegacyTelegramTopicParams struct {
	ID            uuid.UUID
	BotID         int64
	GroupID       int64
	Kind          string
	AccountID     *uuid.UUID
	ThreadID      pgtype.Int8
	Status        string
	Closed        bool
	SupportBanned bool
	CreatedAt     pgtype.Timestamptz
	SourceID      pgtype.Int8
}

func (q *Queries) AddLegacyTelegramTopic(ctx context.Context, arg AddLegacyTelegramTopicParams) error {
	_, err := q.db.Exec(ctx, addLegacyTelegramTopic,
		arg.ID,
		arg.BotID,
		arg.GroupID,
		arg.Kind,
		arg.AccountID,
		arg.ThreadID,
		arg.Status,
		arg.Closed,
		arg.SupportBanned,
		arg.CreatedAt,
		arg.SourceID,
	)
	return err
}

const addReplacementTelegramTopic = `-- name: AddReplacementTelegramTopic :one
INSERT INTO support_telegram_topics(id,bot_id,group_id,kind,account_id,guest_tg_id,thread_id,status,closed,support_banned,source_id)
SELECT $1::uuid,bot_id,group_id,kind,account_id,guest_tg_id,$2::bigint,'ready',false,support_banned,source_id
FROM support_telegram_topics WHERE id=$3::uuid RETURNING id, bot_id, group_id, kind, account_id, guest_tg_id, thread_id, status, closed, support_banned, created_at, source_id
`

type AddReplacementTelegramTopicParams struct {
	NewID     uuid.UUID
	NewThread int64
	OldID     uuid.UUID
}

func (q *Queries) AddReplacementTelegramTopic(ctx context.Context, arg AddReplacementTelegramTopicParams) (SupportTelegramTopic, error) {
	row := q.db.QueryRow(ctx, addReplacementTelegramTopic, arg.NewID, arg.NewThread, arg.OldID)
	var i SupportTelegramTopic
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.GroupID,
		&i.Kind,
		&i.AccountID,
		&i.GuestTgID,
		&i.ThreadID,
		&i.Status,
		&i.Closed,
		&i.SupportBanned,
		&i.CreatedAt,
		&i.SourceID,
	)
	return i, err
}

const addTelegramDelivery = `-- name: AddTelegramDelivery :exec
INSERT INTO support_telegram_deliveries(id,topic_id,message_id,receipt_id,kind,status,parts,prior_delivery_id) VALUES($1,$2,$3,$4,$5,'queued',$6,$7)
`

type AddTelegramDeliveryParams struct {
	ID              uuid.UUID
	TopicID         *uuid.UUID
	MessageID       *uuid.UUID
	ReceiptID       *uuid.UUID
	Kind            string
	Parts           []byte
	PriorDeliveryID *uuid.UUID
}

func (q *Queries) AddTelegramDelivery(ctx context.Context, arg AddTelegramDeliveryParams) error {
	_, err := q.db.Exec(ctx, addTelegramDelivery,
		arg.ID,
		arg.TopicID,
		arg.MessageID,
		arg.ReceiptID,
		arg.Kind,
		arg.Parts,
		arg.PriorDeliveryID,
	)
	return err
}

const addTelegramReceipt = `-- name: AddTelegramReceipt :exec
INSERT INTO support_telegram_receipts(id,bot_id,group_id,chat_id,message_id,update_id,actor_tg_id,thread_id,action,callback_id,digest,actor_account_id,target_account_id,topic_id,support_message_id,owner_key,result)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)
`

type AddTelegramReceiptParams struct {
	ID               uuid.UUID
	BotID            int64
	GroupID          int64
	ChatID           int64
	MessageID        int64
	UpdateID         int64
	ActorTgID        pgtype.Int8
	ThreadID         pgtype.Int8
	Action           string
	CallbackID       string
	Digest           []byte
	ActorAccountID   *uuid.UUID
	TargetAccountID  *uuid.UUID
	TopicID          *uuid.UUID
	SupportMessageID *uuid.UUID
	OwnerKey         uuid.UUID
	Result           []byte
}

func (q *Queries) AddTelegramReceipt(ctx context.Context, arg AddTelegramReceiptParams) error {
	_, err := q.db.Exec(ctx, addTelegramReceipt,
		arg.ID,
		arg.BotID,
		arg.GroupID,
		arg.ChatID,
		arg.MessageID,
		arg.UpdateID,
		arg.ActorTgID,
		arg.ThreadID,
		arg.Action,
		arg.CallbackID,
		arg.Digest,
		arg.ActorAccountID,
		arg.TargetAccountID,
		arg.TopicID,
		arg.SupportMessageID,
		arg.OwnerKey,
		arg.Result,
	)
	return err
}

const addTelegramTopic = `-- name: AddTelegramTopic :one
INSERT INTO support_telegram_topics(id,bot_id,group_id,kind,account_id,guest_tg_id,status) VALUES($1,$2,$3,$4,$5,$6,'pending') RETURNING id, bot_id, group_id, kind, account_id, guest_tg_id, thread_id, status, closed, support_banned, created_at, source_id
`

type AddTelegramTopicParams struct {
	ID        uuid.UUID
	BotID     int64
	GroupID   int64
	Kind      string
	AccountID *uuid.UUID
	GuestTgID pgtype.Int8
}

func (q *Queries) AddTelegramTopic(ctx context.Context, arg AddTelegramTopicParams) (SupportTelegramTopic, error) {
	row := q.db.QueryRow(ctx, addTelegramTopic,
		arg.ID,
		arg.BotID,
		arg.GroupID,
		arg.Kind,
		arg.AccountID,
		arg.GuestTgID,
	)
	var i SupportTelegramTopic
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.GroupID,
		&i.Kind,
		&i.AccountID,
		&i.GuestTgID,
		&i.ThreadID,
		&i.Status,
		&i.Closed,
		&i.SupportBanned,
		&i.CreatedAt,
		&i.SourceID,
	)
	return i, err
}

const bindLegacyTelegramTopic = `-- name: BindLegacyTelegramTopic :exec
UPDATE support_telegram_topics SET kind='account',account_id=$2 WHERE id=$1 AND kind='orphan'
`

type BindLegacyTelegramTopicParams struct {
	ID        uuid.UUID
	AccountID *uuid.UUID
}

func (q *Queries) BindLegacyTelegramTopic(ctx context.Context, arg BindLegacyTelegramTopicParams) error {
	_, err := q.db.Exec(ctx, bindLegacyTelegramTopic, arg.ID, arg.AccountID)
	return err
}

const claimTelegramDelivery = `-- name: ClaimTelegramDelivery :one
WITH candidate AS (
 SELECT d.id FROM support_telegram_deliveries d LEFT JOIN support_telegram_topics t ON t.id=d.topic_id LEFT JOIN support_telegram_receipts r ON r.id=d.receipt_id
 WHERE d.status='queued' AND d.available_at<=clock_timestamp() AND (d.lease_expires_at IS NULL OR d.lease_expires_at<=clock_timestamp())
 AND ((t.bot_id=$2 AND t.group_id=$3 AND (d.kind='topic_create' AND t.status='pending' OR d.kind<>'topic_create' AND t.status='ready'))
 OR (d.topic_id IS NULL AND d.kind='ack' AND r.bot_id=$2 AND r.group_id=$3))
 ORDER BY d.sequence LIMIT 1 FOR UPDATE OF d SKIP LOCKED
)
UPDATE support_telegram_deliveries SET lease=$1,lease_expires_at=clock_timestamp()+interval '60 seconds'
WHERE id=(SELECT id FROM candidate) RETURNING id, sequence, topic_id, message_id, receipt_id, kind, status, code, parts, lease, lease_expires_at, available_at, created_at, prior_delivery_id
`

type ClaimTelegramDeliveryParams struct {
	Lease   *uuid.UUID
	BotID   int64
	GroupID int64
}

func (q *Queries) ClaimTelegramDelivery(ctx context.Context, arg ClaimTelegramDeliveryParams) (SupportTelegramDelivery, error) {
	row := q.db.QueryRow(ctx, claimTelegramDelivery, arg.Lease, arg.BotID, arg.GroupID)
	var i SupportTelegramDelivery
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.TopicID,
		&i.MessageID,
		&i.ReceiptID,
		&i.Kind,
		&i.Status,
		&i.Code,
		&i.Parts,
		&i.Lease,
		&i.LeaseExpiresAt,
		&i.AvailableAt,
		&i.CreatedAt,
		&i.PriorDeliveryID,
	)
	return i, err
}

const completeTelegramReceipt = `-- name: CompleteTelegramReceipt :exec
UPDATE support_telegram_receipts SET result=$2,support_message_id=$3,topic_id=$4 WHERE id=$1
`

type CompleteTelegramReceiptParams struct {
	ID               uuid.UUID
	Result           []byte
	SupportMessageID *uuid.UUID
	TopicID          *uuid.UUID
}

func (q *Queries) CompleteTelegramReceipt(ctx context.Context, arg CompleteTelegramReceiptParams) error {
	_, err := q.db.Exec(ctx, completeTelegramReceipt,
		arg.ID,
		arg.Result,
		arg.SupportMessageID,
		arg.TopicID,
	)
	return err
}

const expireTelegramSending = `-- name: ExpireTelegramSending :exec
WITH expired AS (
 UPDATE support_telegram_deliveries d SET status='unknown',code='ACK_UNKNOWN',lease=NULL,lease_expires_at=NULL,
 parts=(SELECT jsonb_agg(CASE WHEN p->>'status'='sending' THEN jsonb_set(p,'{status}','"unknown"') ELSE p END ORDER BY n)
 FROM jsonb_array_elements(d.parts) WITH ORDINALITY AS a(p,n))
 WHERE d.status='sending' AND d.lease_expires_at<=clock_timestamp() RETURNING topic_id,kind
)
UPDATE support_telegram_topics SET status='unknown' WHERE id IN (SELECT topic_id FROM expired WHERE kind='topic_create')
`

func (q *Queries) ExpireTelegramSending(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireTelegramSending)
	return err
}

const guestTelegramTopic = `-- name: GuestTelegramTopic :one
SELECT id, bot_id, group_id, kind, account_id, guest_tg_id, thread_id, status, closed, support_banned, created_at, source_id FROM support_telegram_topics WHERE bot_id=$1 AND group_id=$2 AND guest_tg_id=$3 AND status<>'retired'
`

type GuestTelegramTopicParams struct {
	BotID     int64
	GroupID   int64
	GuestTgID pgtype.Int8
}

func (q *Queries) GuestTelegramTopic(ctx context.Context, arg GuestTelegramTopicParams) (SupportTelegramTopic, error) {
	row := q.db.QueryRow(ctx, guestTelegramTopic, arg.BotID, arg.GroupID, arg.GuestTgID)
	var i SupportTelegramTopic
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.GroupID,
		&i.Kind,
		&i.AccountID,
		&i.GuestTgID,
		&i.ThreadID,
		&i.Status,
		&i.Closed,
		&i.SupportBanned,
		&i.CreatedAt,
		&i.SourceID,
	)
	return i, err
}

const hasTelegramTopicCreator = `-- name: HasTelegramTopicCreator :one
SELECT EXISTS(SELECT 1 FROM support_telegram_deliveries WHERE topic_id=$1 AND kind='topic_create')
`

func (q *Queries) HasTelegramTopicCreator(ctx context.Context, topicID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasTelegramTopicCreator, topicID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertLegacySupport = `-- name: InsertLegacySupport :execrows
INSERT INTO legacy_support_imports(bot_id,group_id,source_id,source_hash,source_json) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING
`

type InsertLegacySupportParams struct {
	BotID      int64
	GroupID    int64
	SourceID   int64
	SourceHash []byte
	SourceJson []byte
}

func (q *Queries) InsertLegacySupport(ctx context.Context, arg InsertLegacySupportParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLegacySupport,
		arg.BotID,
		arg.GroupID,
		arg.SourceID,
		arg.SourceHash,
		arg.SourceJson,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const latestMessageTelegramDelivery = `-- name: LatestMessageTelegramDelivery :one
SELECT d.id, d.sequence, d.topic_id, d.message_id, d.receipt_id, d.kind, d.status, d.code, d.parts, d.lease, d.lease_expires_at, d.available_at, d.created_at, d.prior_delivery_id,t.status AS topic_status FROM support_telegram_deliveries d JOIN support_telegram_topics t ON t.id=d.topic_id
WHERE d.message_id=$1 ORDER BY d.sequence DESC LIMIT 1
`

type LatestMessageTelegramDeliveryRow struct {
	ID              uuid.UUID
	Sequence        int64
	TopicID         *uuid.UUID
	MessageID       *uuid.UUID
	ReceiptID       *uuid.UUID
	Kind            string
	Status          string
	Code            string
	Parts           []byte
	Lease           *uuid.UUID
	LeaseExpiresAt  pgtype.Timestamptz
	AvailableAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	PriorDeliveryID *uuid.UUID
	TopicStatus     string
}

func (q *Queries) LatestMessageTelegramDelivery(ctx context.Context, messageID *uuid.UUID) (LatestMessageTelegramDeliveryRow, error) {
	row := q.db.QueryRow(ctx, latestMessageTelegramDelivery, messageID)
	var i LatestMessageTelegramDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.TopicID,
		&i.MessageID,
		&i.ReceiptID,
		&i.Kind,
		&i.Status,
		&i.Code,
		&i.Parts,
		&i.Lease,
		&i.LeaseExpiresAt,
		&i.AvailableAt,
		&i.CreatedAt,
		&i.PriorDeliveryID,
		&i.TopicStatus,
	)
	return i, err
}

const latestTopicTelegramDelivery = `-- name: LatestTopicTelegramDelivery :one
SELECT id,status,code FROM support_telegram_deliveries WHERE topic_id=$1 ORDER BY sequence DESC LIMIT 1
`

type LatestTopicTelegramDeliveryRow struct {
	ID     uuid.UUID
	Status string
	Code   string
}

func (q *Queries) LatestTopicTelegramDelivery(ctx context.Context, topicID *uuid.UUID) (LatestTopicTelegramDeliveryRow, error) {
	row := q.db.QueryRow(ctx, latestTopicTelegramDelivery, topicID)
	var i LatestTopicTelegramDeliveryRow
	err := row.Scan(&i.ID, &i.Status, &i.Code)
	return i, err
}

const legacySupportDigest = `-- name: LegacySupportDigest :one
SELECT source_hash FROM legacy_support_imports WHERE bot_id=$1 AND group_id=$2 AND source_id=$3
`

type LegacySupportDigestParams struct {
	BotID    int64
	GroupID  int64
	SourceID int64
}

func (q *Queries) LegacySupportDigest(ctx context.Context, arg LegacySupportDigestParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, legacySupportDigest, arg.BotID, arg.GroupID, arg.SourceID)
	var source_hash []byte
	err := row.Scan(&source_hash)
	return source_hash, err
}

const legacySupportSource = `-- name: LegacySupportSource :one
SELECT bot_id, group_id, source_id, source_hash, source_json FROM legacy_support_imports WHERE bot_id=$1 AND group_id=$2 AND source_id=$3
`

type LegacySupportSourceParams struct {
	BotID    int64
	GroupID  int64
	SourceID int64
}

func (q *Queries) LegacySupportSource(ctx context.Context, arg LegacySupportSourceParams) (LegacySupportImport, error) {
	row := q.db.QueryRow(ctx, legacySupportSource, arg.BotID, arg.GroupID, arg.SourceID)
	var i LegacySupportImport
	err := row.Scan(
		&i.BotID,
		&i.GroupID,
		&i.SourceID,
		&i.SourceHash,
		&i.SourceJson,
	)
	return i, err
}

const legacyTelegramTopic = `-- name: LegacyTelegramTopic :one
SELECT id, bot_id, group_id, kind, account_id, guest_tg_id, thread_id, status, closed, support_banned, created_at, source_id FROM support_telegram_topics WHERE bot_id=$1 AND group_id=$2 AND source_id=$3 AND status<>'retired'
`

type LegacyTelegramTopicParams struct {
	BotID    int64
	GroupID  int64
	SourceID pgtype.Int8
}

func (q *Queries) LegacyTelegramTopic(ctx context.Context, arg LegacyTelegramTopicParams) (SupportTelegramTopic, error) {
	row := q.db.QueryRow(ctx, legacyTelegramTopic, arg.BotID, arg.GroupID, arg.SourceID)
	var i SupportTelegramTopic
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.GroupID,
		&i.Kind,
		&i.AccountID,
		&i.GuestTgID,
		&i.ThreadID,
		&i.Status,
		&i.Closed,
		&i.SupportBanned,
		&i.CreatedAt,
		&i.SourceID,
	)
	return i, err
}

const lockTelegramDelivery = `-- name: LockTelegramDelivery :one
SELECT id, sequence, topic_id, message_id, receipt_id, kind, status, code, parts, lease, lease_expires_at, available_at, created_at, prior_delivery_id FROM support_telegram_deliveries WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockTelegramDelivery(ctx context.Context, id uuid.UUID) (SupportTelegramDelivery, error) {
	row := q.db.QueryRow(ctx, lockTelegramDelivery, id)
	var i SupportTelegramDelivery
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.TopicID,
		&i.MessageID,
		&i.ReceiptID,
		&i.Kind,
		&i.Status,
		&i.Code,
		&i.Parts,
		&i.Lease,
		&i.LeaseExpiresAt,
		&i.AvailableAt,
		&i.CreatedAt,
		&i.PriorDeliveryID,
	)
	return i, err
}

const lockTelegramReceipt = `-- name: LockTelegramReceipt :one
SELECT id, bot_id, group_id, chat_id, message_id, update_id, actor_tg_id, thread_id, action, callback_id, digest, actor_account_id, target_account_id, topic_id, support_message_id, owner_key, result, created_at FROM support_telegram_receipts WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockTelegramReceipt(ctx context.Context, id uuid.UUID) (SupportTelegramReceipt, error) {
	row := q.db.QueryRow(ctx, lockTelegramReceipt, id)
	var i SupportTelegramReceipt
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.GroupID,
		&i.ChatID,
		&i.MessageID,
		&i.UpdateID,
		&i.ActorTgID,
		&i.ThreadID,
		&i.Action,
		&i.CallbackID,
		&i.Digest,
		&i.ActorAccountID,
		&i.TargetAccountID,
		&i.TopicID,
		&i.SupportMessageID,
		&i.OwnerKey,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const lockTelegramTopic = `-- name: LockTelegramTopic :one
SELECT id, bot_id, group_id, kind, account_id, guest_tg_id, thread_id, status, closed, support_banned, created_at, source_id FROM support_telegram_topics WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockTelegramTopic(ctx context.Context, id uuid.UUID) (SupportTelegramTopic, error) {
	row := q.db.QueryRow(ctx, lockTelegramTopic, id)
	var i SupportTelegramTopic
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.GroupID,
		&i.Kind,
		&i.AccountID,
		&i.GuestTgID,
		&i.ThreadID,
		&i.Status,
		&i.Closed,
		&i.SupportBanned,
		&i.CreatedAt,
		&i.SourceID,
	)
	return i, err
}

const messageTelegramDeliveries = `-- name: MessageTelegramDeliveries :many
SELECT DISTINCT ON(d.message_id) d.id,d.message_id,d.status,d.code,t.status AS topic_status
FROM support_telegram_deliveries d JOIN support_telegram_topics t ON t.id=d.topic_id
WHERE d.message_id=ANY($1::uuid[]) ORDER BY d.message_id,d.sequence DESC
`

type MessageTelegramDeliveriesRow struct {
	ID          uuid.UUID
	MessageID   *uuid.UUID
	Status      string
	Code        string
	TopicStatus string
}

func (q *Queries) MessageTelegramDeliveries(ctx context.Context, messageIds []uuid.UUID) ([]MessageTelegramDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, messageTelegramDeliveries, messageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageTelegramDeliveriesRow
	for rows.Next() {
		var i MessageTelegramDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Status,
			&i.Code,
			&i.TopicStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingTelegramTopics = `-- name: PendingTelegramTopics :many
SELECT id FROM support_telegram_topics WHERE bot_id=$1 AND group_id=$2 AND status IN('pending','sending','failed','unknown') ORDER BY created_at,id LIMIT 21
`

type PendingTelegramTopicsParams struct {
	BotID   int64
	GroupID int64
}

func (q *Queries) PendingTelegramTopics(ctx context.Context, arg PendingTelegramTopicsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, pendingTelegramTopics, arg.BotID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireTelegramTopic = `-- name: RetireTelegramTopic :exec
WITH retired AS(UPDATE support_telegram_topics t SET status='retired' WHERE t.id=$1 RETURNING t.id)
UPDATE support_telegram_deliveries d SET status='skipped',code='TOPIC_RETIRED',lease=NULL,lease_expires_at=NULL,
parts=(SELECT jsonb_agg(CASE WHEN p->>'status' IN ('queued','sending') THEN jsonb_set(p,'{status}','"skipped"') ELSE p END ORDER BY n)
 FROM jsonb_array_elements(d.parts) WITH ORDINALITY AS a(p,n))
WHERE d.topic_id IN(SELECT r.id FROM retired r) AND d.status IN('queued','sending')
`

func (q *Queries) RetireTelegramTopic(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, retireTelegramTopic, id)
	return err
}

const saveTelegramDelivery = `-- name: SaveTelegramDelivery :execrows
UPDATE support_telegram_deliveries SET status=$2,code=$3,parts=$4,available_at=clock_timestamp()+$5::integer*interval '1 second',
lease=CASE WHEN $2='sending' THEN lease ELSE NULL END,lease_expires_at=CASE WHEN $2='sending' THEN clock_timestamp()+interval '60 seconds' ELSE NULL END
WHERE id=$1 AND lease=$6::uuid AND lease_expires_at>clock_timestamp()
`

type SaveTelegramDeliveryParams struct {
	ID            uuid.UUID
	Status        string
	Code          string
	Parts         []byte
	DelaySeconds  int32
	ExpectedLease uuid.UUID
}

func (q *Queries) SaveTelegramDelivery(ctx context.Context, arg SaveTelegramDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveTelegramDelivery,
		arg.ID,
		arg.Status,
		arg.Code,
		arg.Parts,
		arg.DelaySeconds,
		arg.ExpectedLease,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTelegramAccountBan = `-- name: SetTelegramAccountBan :exec
UPDATE support_telegram_topics SET support_banned=$2 WHERE account_id=$1 AND status<>'retired'
`

type SetTelegramAccountBanParams struct {
	AccountID     *uuid.UUID
	SupportBanned bool
}

func (q *Queries) SetTelegramAccountBan(ctx context.Context, arg SetTelegramAccountBanParams) error {
	_, err := q.db.Exec(ctx, setTelegramAccountBan, arg.AccountID, arg.SupportBanned)
	return err
}

const setTelegramGuestBan = `-- name: SetTelegramGuestBan :exec
INSERT INTO support_telegram_guest_bans(telegram_id,banned) VALUES($1,$2)
ON CONFLICT(telegram_id) DO UPDATE SET banned=EXCLUDED.banned,updated_at=clock_timestamp()
`

type SetTelegramGuestBanParams struct {
	TelegramID int64
	Banned     bool
}

func (q *Queries) SetTelegramGuestBan(ctx context.Context, arg SetTelegramGuestBanParams) error {
	_, err := q.db.Exec(ctx, setTelegramGuestBan, arg.TelegramID, arg.Banned)
	return err
}

const setTelegramTopicBan = `-- name: SetTelegramTopicBan :exec
UPDATE support_telegram_topics SET support_banned=$2 WHERE id=$1
`

type SetTelegramTopicBanParams struct {
	ID            uuid.UUID
	SupportBanned bool
}

func (q *Queries) SetTelegramTopicBan(ctx context.Context, arg SetTelegramTopicBanParams) error {
	_, err := q.db.Exec(ctx, setTelegramTopicBan, arg.ID, arg.SupportBanned)
	return err
}

const setTelegramTopicClosed = `-- name: SetTelegramTopicClosed :exec
UPDATE support_telegram_topics SET closed=$2 WHERE id=$1
`

type SetTelegramTopicClosedParams struct {
	ID     uuid.UUID
	Closed bool
}

func (q *Queries) SetTelegramTopicClosed(ctx context.Context, arg SetTelegramTopicClosedParams) error {
	_, err := q.db.Exec(ctx, setTelegramTopicClosed, arg.ID, arg.Closed)
	return err
}

const setTelegramTopicState = `-- name: SetTelegramTopicState :exec
UPDATE support_telegram_topics SET status=$2,thread_id=$3 WHERE id=$1
`

type SetTelegramTopicStateParams struct {
	ID       uuid.UUID
	Status   string
	ThreadID pgtype.Int8
}

func (q *Queries) SetTelegramTopicState(ctx context.Context, arg SetTelegramTopicStateParams) error {
	_, err := q.db.Exec(ctx, setTelegramTopicState, arg.ID, arg.Status, arg.ThreadID)
	return err
}

const telegramConfirmationDelivered = `-- name: TelegramConfirmationDelivered :one
SELECT EXISTS(SELECT 1 FROM support_telegram_deliveries d, jsonb_array_elements(d.parts) p
 WHERE d.receipt_id=$1 AND d.kind='ack' AND d.status='sent' AND p->>'kind'='confirmation'
 AND p->>'confirmation_id'=$1::uuid::text AND p->>'status'='sent'
 AND p->>'confirmed_message_id'=$2::bigint::text)
`

type TelegramConfirmationDeliveredParams struct {
	ReceiptID *uuid.UUID
	Column2   int64
}

func (q *Queries) TelegramConfirmationDelivered(ctx context.Context, arg TelegramConfirmationDeliveredParams) (bool, error) {
	row := q.db.QueryRow(ctx, telegramConfirmationDelivered, arg.ReceiptID, arg.Column2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const telegramDeliveryByID = `-- name: TelegramDeliveryByID :one
SELECT id, sequence, topic_id, message_id, receipt_id, kind, status, code, parts, lease, lease_expires_at, available_at, created_at, prior_delivery_id FROM support_telegram_deliveries WHERE id=$1
`

func (q *Queries) TelegramDeliveryByID(ctx context.Context, id uuid.UUID) (SupportTelegramDelivery, error) {
	row := q.db.QueryRow(ctx, telegramDeliveryByID, id)
	var i SupportTelegramDelivery
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.TopicID,
		&i.MessageID,
		&i.ReceiptID,
		&i.Kind,
		&i.Status,
		&i.Code,
		&i.Parts,
		&i.Lease,
		&i.LeaseExpiresAt,
		&i.AvailableAt,
		&i.CreatedAt,
		&i.PriorDeliveryID,
	)
	return i, err
}

const telegramGuestBanned = `-- name: TelegramGuestBanned :one
SELECT EXISTS(SELECT 1 FROM support_telegram_guest_bans WHERE telegram_id=$1 AND banned)
`

func (q *Queries) TelegramGuestBanned(ctx context.Context, telegramID int64) (bool, error) {
	row := q.db.QueryRow(ctx, telegramGuestBanned, telegramID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const telegramReceipt = `-- name: TelegramReceipt :one
SELECT id, bot_id, group_id, chat_id, message_id, update_id, actor_tg_id, thread_id, action, callback_id, digest, actor_account_id, target_account_id, topic_id, support_message_id, owner_key, result, created_at FROM support_telegram_receipts WHERE id=$1
`

func (q *Queries) TelegramReceipt(ctx context.Context, id uuid.UUID) (SupportTelegramReceipt, error) {
	row := q.db.QueryRow(ctx, telegramReceipt, id)
	var i SupportTelegramReceipt
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.GroupID,
		&i.ChatID,
		&i.MessageID,
		&i.UpdateID,
		&i.ActorTgID,
		&i.ThreadID,
		&i.Action,
		&i.CallbackID,
		&i.Digest,
		&i.ActorAccountID,
		&i.TargetAccountID,
		&i.TopicID,
		&i.SupportMessageID,
		&i.OwnerKey,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const telegramThreadInUse = `-- name: TelegramThreadInUse :one
SELECT EXISTS(SELECT 1 FROM support_telegram_topics WHERE bot_id=$1 AND group_id=$2 AND thread_id=$3 AND id<>$4 AND status<>'retired')
`

type TelegramThreadInUseParams struct {
	BotID    int64
	GroupID  int64
	ThreadID pgtype.Int8
	ID       uuid.UUID
}

func (q *Queries) TelegramThreadInUse(ctx context.Context, arg TelegramThreadInUseParams) (bool, error) {
	row := q.db.QueryRow(ctx, telegramThreadInUse,
		arg.BotID,
		arg.GroupID,
		arg.ThreadID,
		arg.ID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const telegramTopicByID = `-- name: TelegramTopicByID :one
SELECT id, bot_id, group_id, kind, account_id, guest_tg_id, thread_id, status, closed, support_banned, created_at, source_id FROM support_telegram_topics WHERE id=$1
`

func (q *Queries) TelegramTopicByID(ctx context.Context, id uuid.UUID) (SupportTelegramTopic, error) {
	row := q.db.QueryRow(ctx, telegramTopicByID, id)
	var i SupportTelegramTopic
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.GroupID,
		&i.Kind,
		&i.AccountID,
		&i.GuestTgID,
		&i.ThreadID,
		&i.Status,
		&i.Closed,
		&i.SupportBanned,
		&i.CreatedAt,
		&i.SourceID,
	)
	return i, err
}

const telegramTopicByThread = `-- name: TelegramTopicByThread :one
SELECT id, bot_id, group_id, kind, account_id, guest_tg_id, thread_id, status, closed, support_banned, created_at, source_id FROM support_telegram_topics WHERE bot_id=$1 AND group_id=$2 AND thread_id=$3 AND status='ready'
`

type TelegramTopicByThreadParams struct {
	BotID    int64
	GroupID  int64
	ThreadID pgtype.Int8
}

func (q *Queries) TelegramTopicByThread(ctx context.Context, arg TelegramTopicByThreadParams) (SupportTelegramTopic, error) {
	row := q.db.QueryRow(ctx, telegramTopicByThread, arg.BotID, arg.GroupID, arg.ThreadID)
	var i SupportTelegramTopic
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.GroupID,
		&i.Kind,
		&i.AccountID,
		&i.GuestTgID,
		&i.ThreadID,
		&i.Status,
		&i.Closed,
		&i.SupportBanned,
		&i.CreatedAt,
		&i.SourceID,
	)
	return i, err
}

const unknownTelegramDelivery = `-- name: UnknownTelegramDelivery :exec
WITH uncertain AS (
 UPDATE support_telegram_deliveries d SET status='unknown',code='ACK_UNKNOWN',lease=NULL,lease_expires_at=NULL,
 parts=(SELECT jsonb_agg(CASE WHEN p->>'status'='sending' THEN jsonb_set(p,'{status}','"unknown"') ELSE p END ORDER BY n)
 FROM jsonb_array_elements(d.parts) WITH ORDINALITY AS a(p,n))
 WHERE d.id=$1 AND d.lease=$2 AND d.status='sending' RETURNING topic_id,kind
)
UPDATE support_telegram_topics SET status='unknown' WHERE id IN(SELECT topic_id FROM uncertain WHERE kind='topic_create')
`

type UnknownTelegramDeliveryParams struct {
	ID    uuid.UUID
	Lease *uuid.UUID
}

func (q *Queries) UnknownTelegramDelivery(ctx context.Context, arg UnknownTelegramDeliveryParams) error {
	_, err := q.db.Exec(ctx, unknownTelegramDelivery, arg.ID, arg.Lease)
	return err
}
