// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Promocode struct {
	ID                 uuid.UUID
	Code               string
	DurationDays       int32
	Revision           int64
	CreatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
	IsActivated        bool
	ActivatedAccountID *uuid.UUID
	ActivatedByTgID    pgtype.Int8
	ActivatedAt        pgtype.Timestamptz
	LegacySource       pgtype.Text
	LegacyPromocodeID  pgtype.Int8
}

type PromocodeEvent struct {
	ID             uuid.UUID
	PromocodeID    uuid.UUID
	ActorAccountID *uuid.UUID
	Action         string
	CreatedAt      pgtype.Timestamptz
	Reason         pgtype.Text
	BeforeSnapshot []byte
	AfterSnapshot  []byte
}
