// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: promocodes.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addPromocode = `-- name: AddPromocode :one
INSERT INTO promocodes(id,code,duration_days,created_at) VALUES($1,$2,$3,$4) RETURNING id, code, duration_days, revision, created_at, deleted_at, is_activated, activated_account_id, activated_by_tg_id, activated_at, legacy_source, legacy_promocode_id
`

type AddPromocodeParams struct {
	ID           uuid.UUID
	Code         string
	DurationDays int32
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) AddPromocode(ctx context.Context, arg AddPromocodeParams) (Promocode, error) {
	row := q.db.QueryRow(ctx, addPromocode,
		arg.ID,
		arg.Code,
		arg.DurationDays,
		arg.CreatedAt,
	)
	var i Promocode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DurationDays,
		&i.Revision,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.IsActivated,
		&i.ActivatedAccountID,
		&i.ActivatedByTgID,
		&i.ActivatedAt,
		&i.LegacySource,
		&i.LegacyPromocodeID,
	)
	return i, err
}

const addPromocodeEvent = `-- name: AddPromocodeEvent :exec
INSERT INTO promocode_events(id,promocode_id,actor_account_id,action,created_at,reason,before_snapshot,after_snapshot)
 VALUES($1,$2,$3,$4,$5,$6,$7,$8)
`

type AddPromocodeEventParams struct {
	ID             uuid.UUID
	PromocodeID    uuid.UUID
	ActorAccountID *uuid.UUID
	Action         string
	CreatedAt      pgtype.Timestamptz
	Reason         pgtype.Text
	BeforeSnapshot []byte
	AfterSnapshot  []byte
}

func (q *Queries) AddPromocodeEvent(ctx context.Context, arg AddPromocodeEventParams) error {
	_, err := q.db.Exec(ctx, addPromocodeEvent,
		arg.ID,
		arg.PromocodeID,
		arg.ActorAccountID,
		arg.Action,
		arg.CreatedAt,
		arg.Reason,
		arg.BeforeSnapshot,
		arg.AfterSnapshot,
	)
	return err
}

const countPromocodes = `-- name: CountPromocodes :one
SELECT count(*) FROM promocodes
`

func (q *Queries) CountPromocodes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPromocodes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePromocode = `-- name: DeletePromocode :one
UPDATE promocodes SET deleted_at=$2,revision=revision+1 WHERE id=$1 RETURNING id, code, duration_days, revision, created_at, deleted_at, is_activated, activated_account_id, activated_by_tg_id, activated_at, legacy_source, legacy_promocode_id
`

type DeletePromocodeParams struct {
	ID        uuid.UUID
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) DeletePromocode(ctx context.Context, arg DeletePromocodeParams) (Promocode, error) {
	row := q.db.QueryRow(ctx, deletePromocode, arg.ID, arg.DeletedAt)
	var i Promocode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DurationDays,
		&i.Revision,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.IsActivated,
		&i.ActivatedAccountID,
		&i.ActivatedByTgID,
		&i.ActivatedAt,
		&i.LegacySource,
		&i.LegacyPromocodeID,
	)
	return i, err
}

const editPromocode = `-- name: EditPromocode :one
UPDATE promocodes SET duration_days=$2,revision=revision+1 WHERE id=$1 RETURNING id, code, duration_days, revision, created_at, deleted_at, is_activated, activated_account_id, activated_by_tg_id, activated_at, legacy_source, legacy_promocode_id
`

type EditPromocodeParams struct {
	ID           uuid.UUID
	DurationDays int32
}

func (q *Queries) EditPromocode(ctx context.Context, arg EditPromocodeParams) (Promocode, error) {
	row := q.db.QueryRow(ctx, editPromocode, arg.ID, arg.DurationDays)
	var i Promocode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DurationDays,
		&i.Revision,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.IsActivated,
		&i.ActivatedAccountID,
		&i.ActivatedByTgID,
		&i.ActivatedAt,
		&i.LegacySource,
		&i.LegacyPromocodeID,
	)
	return i, err
}

const listPromocodes = `-- name: ListPromocodes :many
SELECT id, code, duration_days, revision, created_at, deleted_at, is_activated, activated_account_id, activated_by_tg_id, activated_at, legacy_source, legacy_promocode_id FROM promocodes ORDER BY created_at DESC NULLS LAST,id DESC
 LIMIT $2::integer OFFSET $1::bigint
`

type ListPromocodesParams struct {
	OffsetRows int64
	PerPage    int32
}

func (q *Queries) ListPromocodes(ctx context.Context, arg ListPromocodesParams) ([]Promocode, error) {
	rows, err := q.db.Query(ctx, listPromocodes, arg.OffsetRows, arg.PerPage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Promocode
	for rows.Next() {
		var i Promocode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.DurationDays,
			&i.Revision,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.IsActivated,
			&i.ActivatedAccountID,
			&i.ActivatedByTgID,
			&i.ActivatedAt,
			&i.LegacySource,
			&i.LegacyPromocodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPromocode = `-- name: LockPromocode :one
SELECT id, code, duration_days, revision, created_at, deleted_at, is_activated, activated_account_id, activated_by_tg_id, activated_at, legacy_source, legacy_promocode_id FROM promocodes WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockPromocode(ctx context.Context, id uuid.UUID) (Promocode, error) {
	row := q.db.QueryRow(ctx, lockPromocode, id)
	var i Promocode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DurationDays,
		&i.Revision,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.IsActivated,
		&i.ActivatedAccountID,
		&i.ActivatedByTgID,
		&i.ActivatedAt,
		&i.LegacySource,
		&i.LegacyPromocodeID,
	)
	return i, err
}

const readPromocode = `-- name: ReadPromocode :one
SELECT id, code, duration_days, revision, created_at, deleted_at, is_activated, activated_account_id, activated_by_tg_id, activated_at, legacy_source, legacy_promocode_id FROM promocodes WHERE id=$1
`

func (q *Queries) ReadPromocode(ctx context.Context, id uuid.UUID) (Promocode, error) {
	row := q.db.QueryRow(ctx, readPromocode, id)
	var i Promocode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DurationDays,
		&i.Revision,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.IsActivated,
		&i.ActivatedAccountID,
		&i.ActivatedByTgID,
		&i.ActivatedAt,
		&i.LegacySource,
		&i.LegacyPromocodeID,
	)
	return i, err
}

const readPromocodeEvents = `-- name: ReadPromocodeEvents :many
SELECT id, promocode_id, actor_account_id, action, created_at, reason, before_snapshot, after_snapshot FROM promocode_events WHERE promocode_id=$1 ORDER BY created_at DESC,id DESC LIMIT 51
`

func (q *Queries) ReadPromocodeEvents(ctx context.Context, promocodeID uuid.UUID) ([]PromocodeEvent, error) {
	rows, err := q.db.Query(ctx, readPromocodeEvents, promocodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromocodeEvent
	for rows.Next() {
		var i PromocodeEvent
		if err := rows.Scan(
			&i.ID,
			&i.PromocodeID,
			&i.ActorAccountID,
			&i.Action,
			&i.CreatedAt,
			&i.Reason,
			&i.BeforeSnapshot,
			&i.AfterSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
