// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: referred_trial.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyTrialBenefit = `-- name: ApplyTrialBenefit :one
UPDATE referrals SET referred_rewarded_at=$2::timestamptz
WHERE referred_account_id=$1 AND legacy_referral_id IS NULL
 AND referred_bonus_days IS NOT NULL AND referred_rewarded_at IS NULL
RETURNING id
`

type ApplyTrialBenefitParams struct {
	ReferredAccountID  uuid.UUID
	ReferredRewardedAt pgtype.Timestamptz
}

func (q *Queries) ApplyTrialBenefit(ctx context.Context, arg ApplyTrialBenefitParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, applyTrialBenefit, arg.ReferredAccountID, arg.ReferredRewardedAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const reserveTrialBenefit = `-- name: ReserveTrialBenefit :execrows
UPDATE referrals SET referred_bonus_days=$2::integer
WHERE id=$1 AND legacy_referral_id IS NULL
 AND referred_bonus_days IS NULL AND referred_rewarded_at IS NULL
`

type ReserveTrialBenefitParams struct {
	ID                uuid.UUID
	ReferredBonusDays int32
}

func (q *Queries) ReserveTrialBenefit(ctx context.Context, arg ReserveTrialBenefitParams) (int64, error) {
	result, err := q.db.Exec(ctx, reserveTrialBenefit, arg.ID, arg.ReferredBonusDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const trialReferral = `-- name: TrialReferral :one
SELECT id, legacy_referral_id, referred_bonus_days, referred_rewarded_at
FROM referrals WHERE referred_account_id=$1 FOR UPDATE
`

type TrialReferralRow struct {
	ID                 uuid.UUID
	LegacyReferralID   pgtype.Int8
	ReferredBonusDays  pgtype.Int4
	ReferredRewardedAt pgtype.Timestamptz
}

func (q *Queries) TrialReferral(ctx context.Context, referredAccountID uuid.UUID) (TrialReferralRow, error) {
	row := q.db.QueryRow(ctx, trialReferral, referredAccountID)
	var i TrialReferralRow
	err := row.Scan(
		&i.ID,
		&i.LegacyReferralID,
		&i.ReferredBonusDays,
		&i.ReferredRewardedAt,
	)
	return i, err
}
