from . import (
    admin_tools_handler,
    approval_handler,
    backup_handler,
    group_handler,
    invites_handler,
    maintenance_handler,
    notification_handler,
    pending_users_handler,
    plan_handler,
    promocode_handler,
    rejected_users_handler,
    restart_handler,
    server_handler,
    statistics_handler,
    user_handler,
)
