import {useEffect,useRef,useState} from 'react';
import * as api from './api/client';
import {text,errorText,type Lang} from './i18n';

type Kind=api.AccessOperationInput['kind'];
type Profile=NonNullable<api.AccessOperationInput['profile']>;
type Attempt={payload:string;key:string};
const isForbidden=(error:unknown)=>error instanceof api.ApiError&&(error.status===401||error.status===403);
const validReason=(value:string)=>{const trimmed=value.trim();return trimmed&&Array.from(trimmed).length<=1000&&!trimmed.includes('\0')?trimmed:null;};

export function AccessOperations({clientId,subscription,lang,onForbidden,onChange}:{clientId:string;subscription:api.Subscription;lang:Lang;onForbidden:()=>void;onChange:()=>void}){
 const t=text(lang);const[kind,setKind]=useState<Kind>('compensate');const[profile,setProfile]=useState<Profile>(subscription.access_profile==='euru'||subscription.access_profile==='unlimited'?subscription.access_profile:'regular');const[vpnBanned,setVpnBanned]=useState(subscription.vpn_banned);const[days,setDays]=useState('');const[reason,setReason]=useState('');const[confirming,setConfirming]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[operation,setOperation]=useState<api.AccessOperation>();const[statusError,setStatusError]=useState('');const[statusBusy,setStatusBusy]=useState(false);const[page,setPage]=useState(1);const[plans,setPlans]=useState<api.OperatorCatalogueResult>({plans:[],total:0,page:1,per_page:50});const[planLoading,setPlanLoading]=useState(false);const[planError,setPlanError]=useState('');const[planReload,setPlanReload]=useState(0);const[selectedPlan,setSelectedPlan]=useState<api.OperatorCataloguePlan>();const[period,setPeriod]=useState(0);const[reconcileReason,setReconcileReason]=useState('');const[reconcileConfirm,setReconcileConfirm]=useState(false);const[resetCost,setResetCost]=useState(false);const[reconcileBusy,setReconcileBusy]=useState(false);const[reconcileError,setReconcileError]=useState('');const createAttempt=useRef<Attempt|undefined>(undefined);const reconcileAttempt=useRef<Attempt|undefined>(undefined);const writeRequest=useRef<AbortController|undefined>(undefined);const operationRequest=useRef<AbortController|undefined>(undefined);const errorRef=useRef<HTMLParagraphElement>(null);
 const summaryId=subscription.access_operation_id;const summaryStatus=subscription.access_operation_status;const currentId=operation?.operation_id??summaryId;const currentStatus=operation?.status??summaryStatus;const locked=currentStatus==='pending'||currentStatus==='provisioning'||currentStatus==='needs_review';
 const ambiguousReset=!!operation?.desired.reset_traffic&&operation.completed_steps.includes('reset_started')&&!operation.completed_steps.includes('reset_confirmed');
 useEffect(()=>()=>{writeRequest.current?.abort();operationRequest.current?.abort();},[clientId]);
 useEffect(()=>{if(error)errorRef.current?.focus();},[error]);
 useEffect(()=>{if(!summaryId)return;const controller=new AbortController();operationRequest.current=controller;setStatusBusy(true);void api.getAccessOperation(clientId,summaryId,controller.signal).then(result=>{if(!controller.signal.aborted&&operationRequest.current===controller){setOperation(result);setStatusError('');if(result.status==='applied')onChange();}}).catch(failure=>{if(controller.signal.aborted)return;if(isForbidden(failure))onForbidden();else setStatusError(errorText(failure,lang));}).finally(()=>{if(operationRequest.current===controller){operationRequest.current=undefined;setStatusBusy(false);}});return()=>controller.abort();},[clientId,summaryId]);
 useEffect(()=>{if(kind!=='assign_plan')return;const controller=new AbortController();setPlanLoading(true);void api.getOperatorCatalogue(page,controller.signal).then(result=>{if(!controller.signal.aborted){setPlans(result);setPlanError('');}}).catch(failure=>{if(controller.signal.aborted)return;if(isForbidden(failure))onForbidden();else setPlanError(errorText(failure,lang));}).finally(()=>{if(!controller.signal.aborted)setPlanLoading(false);});return()=>controller.abort();},[clientId,kind,page,planReload,lang]);
 function changeKind(next:Kind){setKind(next);setConfirming(false);setError('');createAttempt.current=undefined;if(next!=='assign_plan'){setSelectedPlan(undefined);setPeriod(0);}else setPage(1);}
 function changeReason(value:string){setReason(value);setError('');setConfirming(false);createAttempt.current=undefined;}
 function changeDays(value:string){setDays(value);setError('');setConfirming(false);createAttempt.current=undefined;}
 function changeProfile(value:Profile){setProfile(value);setError('');setConfirming(false);createAttempt.current=undefined;}
 function changeVpnBan(value:boolean){setVpnBanned(value);setError('');setConfirming(false);createAttempt.current=undefined;}
 function selectPlan(id:string){const chosen=plans.plans.find(plan=>plan.plan_id===id);setSelectedPlan(chosen);setPeriod(chosen?.periods[0]??0);setError('');setConfirming(false);createAttempt.current=undefined;}
 function reloadPlans(){setSelectedPlan(undefined);setPeriod(0);setConfirming(false);setError('');createAttempt.current=undefined;setPlanReload(value=>value+1);}
 function message(failure:unknown){if(failure instanceof api.ApiError){switch(failure.code){case 'ACCESS_OPERATION_CONFLICT':return t.accessConflict;case 'ACCESS_NOT_ELIGIBLE':return t.accessIneligible;case 'ACCESS_PLAN_CONFLICT':return t.accessPlanConflict;case 'ACCESS_RECONCILE_REQUIRED':return t.accessReconcileRequired;case 'OPERATION_NOT_READY':return t.accessNotReady;case 'IDEMPOTENCY_CONFLICT':return t.catalogueIdempotencyConflict;}}return errorText(failure,lang);}
 function input():api.AccessOperationInput|null{const why=validReason(reason);if(!why){setError(t.accessReasonInvalid);return null;}if(kind==='compensate'){if(!/^(?:[1-9]|[1-9][0-9]{1,2})$/.test(days)||Number(days)>365){setError(t.daysInvalid);return null;}return{kind,days:Number(days),reason:why};}if(kind==='assign_plan'){if(!selectedPlan||!selectedPlan.periods.includes(period)){setError(t.planRequired);return null;}return{kind,plan_id:selectedPlan.plan_id,revision:selectedPlan.revision,period_days:period,reason:why};}if(kind==='set_profile')return{kind,profile,reason:why};if(kind==='set_vpn_ban')return{kind,vpn_banned:vpnBanned,reason:why};return{kind,reason:why};}
 function start(){if(busy||locked)return;const body=input();if(!body)return;setError('');if(kind==='compensate')void submit(body);else setConfirming(true);}
 async function submit(body?:api.AccessOperationInput){const inputBody=body??input();if(!inputBody||busy)return;const payload=JSON.stringify(inputBody);const attempt=createAttempt.current?.payload===payload?createAttempt.current:{payload,key:crypto.randomUUID()};const controller=new AbortController();createAttempt.current=attempt;writeRequest.current=controller;setBusy(true);setError('');try{const result=await api.createAccessOperation(clientId,inputBody,attempt.key,controller.signal);if(controller.signal.aborted||writeRequest.current!==controller)return;operationRequest.current?.abort();operationRequest.current=undefined;setStatusBusy(false);setOperation(result);setConfirming(false);createAttempt.current=undefined;onChange();}catch(failure){if(controller.signal.aborted)return;if(isForbidden(failure))onForbidden();else{setError(message(failure));setConfirming(false);}}finally{if(writeRequest.current===controller){writeRequest.current=undefined;if(!controller.signal.aborted)setBusy(false);}}}
 async function refreshOperation(){if(!currentId||statusBusy)return;operationRequest.current?.abort();const controller=new AbortController();operationRequest.current=controller;setStatusBusy(true);setStatusError('');try{const result=await api.getAccessOperation(clientId,currentId,controller.signal);if(controller.signal.aborted||operationRequest.current!==controller)return;setOperation(result);if(result.status==='applied')onChange();}catch(failure){if(!controller.signal.aborted){if(isForbidden(failure))onForbidden();else setStatusError(message(failure));}}finally{if(operationRequest.current===controller){operationRequest.current=undefined;if(!controller.signal.aborted)setStatusBusy(false);}}}
 function startReconcile(){if(!validReason(reconcileReason)){setReconcileError(t.accessReasonInvalid);return;}setReconcileError('');setReconcileConfirm(true);}
 async function reconcile(){if(!operation||reconcileBusy)return;const why=validReason(reconcileReason);if(!why){setReconcileError(t.accessReasonInvalid);return;}if(ambiguousReset&&!resetCost)return;const inputBody:api.AccessReconcileInput={reason:why,acknowledge_reset_cost:ambiguousReset&&resetCost};const payload=JSON.stringify(inputBody);const attempt=reconcileAttempt.current?.payload===payload?reconcileAttempt.current:{payload,key:crypto.randomUUID()};const controller=new AbortController();reconcileAttempt.current=attempt;writeRequest.current=controller;setReconcileBusy(true);setReconcileError('');try{const result=await api.reconcileAccessOperation(clientId,operation.operation_id,inputBody,attempt.key,controller.signal);if(controller.signal.aborted||writeRequest.current!==controller)return;operationRequest.current?.abort();operationRequest.current=undefined;setStatusBusy(false);setOperation(result);setReconcileConfirm(false);reconcileAttempt.current=undefined;onChange();}catch(failure){if(controller.signal.aborted)return;if(isForbidden(failure))onForbidden();else setReconcileError(message(failure));}finally{if(writeRequest.current===controller){writeRequest.current=undefined;if(!controller.signal.aborted)setReconcileBusy(false);}}}
 const eligible=plans.plans.filter(plan=>!plan.archived&&plan.profile!=='unlimited').map(plan=>plan.plan_id===selectedPlan?.plan_id?selectedPlan:plan);if(selectedPlan&&!eligible.some(plan=>plan.plan_id===selectedPlan.plan_id))eligible.unshift(selectedPlan);
 const labels={compensate:t.compensate,assign_plan:t.assignPlan,starter_trial:t.starterTrial,reset_traffic:t.resetTraffic,set_profile:t.setProfile,set_vpn_ban:t.setVpnBan};const statuses={pending:t.operationPending,provisioning:t.operationProvisioning,applied:t.operationApplied,needs_review:t.operationNeedsReview,skipped:t.operationSkipped};const warning=kind==='assign_plan'?t.assignWarning:kind==='starter_trial'?t.trialWarning:kind==='reset_traffic'?t.resetWarning:kind==='set_profile'?subscription.status==='none'&&profile!=='unlimited'?t.profileIntentWarning:subscription.access_profile==='unlimited'&&profile!=='unlimited'?t.profileLeaveUnlimitedWarning:profile==='unlimited'?t.profileUnlimitedWarning:t.profileFiniteWarning:kind==='set_vpn_ban'?(vpnBanned?t.banWarning:t.unbanWarning):'';const confirmLabel=kind==='assign_plan'?t.confirmAssignment:kind==='starter_trial'?t.confirmTrial:kind==='reset_traffic'?t.confirmReset:kind==='set_profile'?t.confirmProfile:t.confirmVpnBan;
 return <section className="admin-action access-operations" aria-label={t.accessOperations}><h2>{t.accessOperations}</h2>
  {currentId?<div className="access-operation-status"><p><strong>{statuses[currentStatus!]}</strong> · {t.accessOperationId}: {currentId}</p>{operation?.review_reason?<p className="warning">{operation.review_reason}</p>:null}{operation?.completed_steps.includes('state_unchanged')?<p className="notice">{t.stateUnchanged}</p>:null}{operation?.completed_steps.includes('intent_saved')?<p className="notice">{t.intentSaved}</p>:null}{operation?.completed_steps.includes('eligibility_changed')?<p className="notice">{t.eligibilityChanged}</p>:null}{operation?.completed_steps.includes('period_elapsed_unserved')?<p className="notice">{t.monthlyResetElapsed}</p>:null}{operation?.completed_steps.filter(step=>!['state_unchanged','intent_saved','eligibility_changed','period_elapsed_unserved'].includes(step)).length?<p className="help">{t.accessSteps}: {operation.completed_steps.filter(step=>!['state_unchanged','intent_saved','eligibility_changed','period_elapsed_unserved'].includes(step)).join(', ')}</p>:null}{statusBusy?<p role="status">{t.loading}</p>:null}{statusError?<p role="alert" className="error">{statusError}</p>:null}<button type="button" disabled={statusBusy||busy||reconcileBusy} onClick={()=>void refreshOperation()}>{t.refreshOperation}</button></div>:null}
  {currentStatus==='needs_review'&&operation?<div className="access-reconcile"><h3>{t.reconcileOperation}</h3>{reconcileError?<p role="alert" className="error">{reconcileError}</p>:null}<label>{t.reconcileReason}<textarea value={reconcileReason} disabled={reconcileBusy} onChange={event=>{setReconcileReason(event.target.value);setReconcileError('');setReconcileConfirm(false);reconcileAttempt.current=undefined;}}/></label>{reconcileConfirm?<div className="warning"><p>{ambiguousReset?t.resetCostWarning:t.accessReconcileRequired}</p>{ambiguousReset?<label className="check"><input type="checkbox" checked={resetCost} disabled={reconcileBusy} onChange={event=>{setResetCost(event.target.checked);reconcileAttempt.current=undefined;}}/>{t.acceptResetCost}</label>:null}<button type="button" disabled={reconcileBusy||(ambiguousReset&&!resetCost)} onClick={()=>void reconcile()}>{t.confirmReconcile}</button><button type="button" disabled={reconcileBusy} onClick={()=>setReconcileConfirm(false)}>{t.cancelRestriction}</button></div>:<button type="button" disabled={reconcileBusy} onClick={startReconcile}>{t.reconcileOperation}</button>}</div>:null}
  <div className="access-create">{error?<p ref={errorRef} tabIndex={-1} role="alert" className="error" id="access-error">{error}</p>:null}{busy?<p role="status">{t.sending}</p>:null}<fieldset disabled={busy||locked}><label>{t.accessOperation}<select aria-label={t.accessOperation} value={kind} onChange={event=>changeKind(event.target.value as Kind)}><option value="compensate">{t.compensate}</option><option value="assign_plan">{t.assignPlan}</option><option value="starter_trial">{t.starterTrial}</option><option value="reset_traffic">{t.resetTraffic}</option><option value="set_profile">{t.setProfile}</option><option value="set_vpn_ban">{t.setVpnBan}</option></select></label>{kind==='compensate'?<><p className="help">{subscription.status==='none'?t.bonusHelp:t.compensateHelp}</p><label>{t.daysToAdd}<input type="number" inputMode="numeric" value={days} onChange={event=>changeDays(event.target.value)}/></label></>:null}
   {kind==='assign_plan'?<div className="access-plan-picker">{planLoading?<p role="status">{t.loading}</p>:null}{planError?<p role="alert" className="error">{planError}</p>:null}<label>{t.plan}<select aria-label={t.plan} value={selectedPlan?.plan_id??''} onChange={event=>selectPlan(event.target.value)}><option value="">—</option>{eligible.map(plan=><option value={plan.plan_id} key={plan.plan_id}>{plan.devices} {t.devicesCount} · {plan.profile==='euru'?'EURU':t.profileRegular} · {t.revision} {plan.revision}{plan.hidden?' · '+t.hiddenPlan:''}</option>)}</select></label>{!planLoading&&eligible.length===0?<p>{t.noPlansPage}</p>:null}<div className="access-plan-pages"><button type="button" disabled={page<=1||planLoading} onClick={()=>setPage(value=>value-1)}>{t.previousPlans}</button><span>{page}</span><button type="button" disabled={page*50>=plans.total||planLoading} onClick={()=>setPage(value=>value+1)}>{t.nextPlans}</button><button type="button" disabled={planLoading} onClick={reloadPlans}>{t.reloadPlans}</button></div>{selectedPlan?<><p className="notice">{t.selectedPlan}: {selectedPlan.devices} {t.devicesCount} · {t.revision} {selectedPlan.revision} · {selectedPlan.traffic_gb} GB</p><label>{t.period}<select aria-label={t.period} value={period} onChange={event=>{setPeriod(Number(event.target.value));setConfirming(false);createAttempt.current=undefined;}}>{selectedPlan.periods.map(days=><option key={days} value={days}>{days} {t.days}</option>)}</select></label></>:null}</div>:null}
   {kind==='set_profile'?<label>{t.profileChoice}<select aria-label={t.profileChoice} value={profile} onChange={event=>changeProfile(event.target.value as Profile)}><option value="regular">{t.profileRegular}</option><option value="euru">EURU</option><option value="unlimited">{t.unlimited}</option></select></label>:null}{kind==='set_vpn_ban'?<label>{t.vpnBanChoice}<select aria-label={t.vpnBanChoice} value={String(vpnBanned)} onChange={event=>changeVpnBan(event.target.value==='true')}><option value="false">{t.vpnAllowed}</option><option value="true">{t.vpnBanned}</option></select></label>:null}
   <label>{t.accessReason}<textarea value={reason} aria-describedby={error?'access-error':undefined} onChange={event=>changeReason(event.target.value)}/></label></fieldset>{confirming?<div className="warning"><p>{warning}</p><button type="button" disabled={busy||locked} onClick={()=>void submit()}>{confirmLabel}</button><button type="button" disabled={busy} onClick={()=>setConfirming(false)}>{t.cancelRestriction}</button></div>:<button type="button" disabled={busy||locked} onClick={start}>{labels[kind]}</button>}</div>
 </section>;
}
