import {useEffect,useRef,useState,type FormEvent} from 'react';
import * as api from './api/client';
import {config} from './config';
import {text,link,errorText,loginRedirect,type Lang} from './i18n';
import {endMiniSession,isMiniApp} from './telegramSDK';

export function AccountIdentity({lang}:{lang:Lang}){
 const t=text(lang),mini=isMiniApp();
 const[info,setInfo]=useState<api.IdentityContext>(),[email,setEmail]=useState(''),[code,setCode]=useState(''),[current,setCurrent]=useState(''),[next,setNext]=useState(''),[repeat,setRepeat]=useState('');
 const[terms,setTerms]=useState(false),[privacy,setPrivacy]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0),[cooldown,setCooldown]=useState(0),[proof,setProof]=useState<api.TelegramLinkChallenge>();
 const controller=useRef<AbortController|undefined>(undefined),action=useRef<AbortController|undefined>(undefined);
 const password=useRef<HTMLInputElement>(null),codeInput=useRef<HTMLInputElement>(null),proofInput=useRef<HTMLInputElement>(null);
 function clearSecrets(){setCurrent('');setNext('');setRepeat('');setCode('');setProof(undefined);setTerms(false);setPrivacy(false);}
 function message(reason:unknown){if(reason instanceof api.ApiError&&reason.code==='IDENTITY_CONFLICT')return t.identityConflict;if(reason instanceof api.ApiError&&reason.code==='INVALID_VERIFICATION')return t.identityExpired;return errorText(reason,lang);}
 useEffect(()=>{
  const request=new AbortController();controller.current=request;setError('');
  void(async()=>{try{await api.getSessionContext(request.signal);const out=await api.getIdentity(request.signal);if(!request.signal.aborted){setInfo(out);if(out.pending_initial_email)setEmail(out.pending_initial_email.email);}}catch(reason){if(!request.signal.aborted)setError(message(reason));}})();
  const hide=()=>{request.abort();action.current?.abort();clearSecrets();setInfo(undefined);setBusy(false);};window.addEventListener('pagehide',hide);
  return()=>{request.abort();action.current?.abort();window.removeEventListener('pagehide',hide);};
 },[revision]);
 useEffect(()=>{if(!cooldown)return;const timer=setTimeout(()=>setCooldown(0),cooldown*1000);return()=>clearTimeout(timer);},[cooldown]);
 useEffect(()=>{if(!proof)return;const timer=setTimeout(()=>{setProof(undefined);setNotice(t.identityExpired);},Math.max(0,Date.parse(proof.expires_at)-Date.now()));return()=>clearTimeout(timer);},[proof]);
 function begin(){action.current?.abort();const request=new AbortController();action.current=request;setBusy(true);setError('');setNotice('');return request;}
 function active(request:AbortController){return action.current===request&&!request.signal.aborted;}
 async function sendEmail(event:FormEvent){event.preventDefault();if(busy||cooldown||!email.trim())return;const request=begin();try{const accepted=await api.requestInitialEmail({email},request.signal);if(!active(request))return;setCooldown(accepted.resend_after);setInfo(old=>old?{...old,pending_initial_email:{challenge_id:accepted.challenge_id,email,expires_at:new Date(Date.now()+600000).toISOString()}}:old);setNotice(t.mailSent);setCode('');}catch(reason){if(active(request))setError(message(reason));}finally{if(active(request))setBusy(false);}}
 async function enableEmail(event:FormEvent){event.preventDefault();if(busy||!info?.pending_initial_email||!terms||!privacy)return;if(Array.from(next).length<15||Array.from(next).length>128){setError(t.passwordInvalid);password.current?.focus();return;}if(next!==repeat){setError(t.passwordMismatch);return;}if(!/^[0-9]{8}$/.test(code)){setError(t.required);codeInput.current?.focus();return;}const request=begin();try{await api.completeInitialEmail({challenge_id:info.pending_initial_email.challenge_id,code,new_password:next,accepted_terms_version:config.termsVersion,accepted_privacy_version:config.privacyVersion},request.signal);if(active(request)){clearSecrets();api.clearSession();endMiniSession('identity-changed');}}catch(reason){if(active(request))setError(message(reason));}finally{if(active(request))setBusy(false);}}
 async function telegram(event:FormEvent,unlink:boolean){event.preventDefault();if(busy||!info?.independent_login)return;if(Array.from(current).length<15||Array.from(current).length>128){setError(t.passwordInvalid);password.current?.focus();return;}const request=begin();try{if(unlink){const out=await api.unlinkTelegram({current_password:current},request.signal);if(!active(request))return;clearSecrets();if(out.changed){api.clearSession();loginRedirect(lang);}else setRevision(value=>value+1);}else{const out=await api.startTelegramLink({current_password:current},request.signal);if(!active(request))return;if(!/^[A-Za-z0-9_-]{43}$/.test(out.link_token)||!Number.isFinite(Date.parse(out.expires_at)))throw new api.ApiError(503,'SERVICE_UNAVAILABLE','');setProof(out);}}catch(reason){if(active(request))setError(message(reason));}finally{if(active(request)){setCurrent('');setBusy(false);}}}
 async function copy(){if(!proof)return;const owned=proof.link_token,request=controller.current;try{await navigator.clipboard.writeText(owned);if(request&&!request.signal.aborted)setNotice(t.identityCopied);}catch{if(request&&!request.signal.aborted)proofInput.current?.select();}}
 async function logout(){if(busy)return;action.current?.abort();clearSecrets();setBusy(true);setError('');try{await api.logoutAccount();if(!controller.current?.signal.aborted)loginRedirect(lang);}catch(reason){if(!controller.current?.signal.aborted)setError(message(reason));}finally{if(!controller.current?.signal.aborted)setBusy(false);}}
 return <section className="card auth"><div className="cabinet-head"><h1>{t.identityTitle}</h1><button disabled={busy} onClick={logout}>{t.logout}</button></div>
  {error?<div className="error" role="alert"><p>{error}</p><button disabled={busy} onClick={()=>{clearSecrets();setRevision(value=>value+1);}}>{t.retry}</button></div>:null}{notice?<p role="status">{notice}</p>:null}
  {!info?<p role="status">{t.loading}</p>:<><p>{info.independent_login?t.identityIndependent:t.identityNoIndependent}</p><p>{info.telegram_linked?t.identityLinked:t.identityUnlinked}</p>{info.email?<p>{t.email}: {info.email}</p>:null}
   {mini&&!info.independent_login?<><form onSubmit={sendEmail} aria-busy={busy}><label htmlFor="identity-email">{t.email}<input id="identity-email" type="email" autoComplete="off" required maxLength={254} value={email} onChange={event=>setEmail(event.target.value)} disabled={busy}/></label><button disabled={busy||cooldown>0}>{t.identitySendCode}</button>{cooldown>0?<p role="status">{t.waiting} {cooldown} {t.seconds}</p>:null}</form>
    {info.pending_initial_email?<form onSubmit={enableEmail} aria-busy={busy}><label htmlFor="identity-code">{t.identityCode}<input ref={codeInput} id="identity-code" autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{8}" required value={code} onChange={event=>setCode(event.target.value)} disabled={busy}/></label><label htmlFor="identity-password">{t.newPassword}<input ref={password} id="identity-password" type="password" autoComplete="new-password" required minLength={15} maxLength={128} value={next} onChange={event=>setNext(event.target.value)} disabled={busy} aria-describedby="identity-password-help"/></label><p className="help" id="identity-password-help">{t.passwordHelp}</p><label htmlFor="identity-repeat">{t.repeatPassword}<input id="identity-repeat" type="password" autoComplete="new-password" required value={repeat} onChange={event=>setRepeat(event.target.value)} disabled={busy}/></label><label className="check"><input type="checkbox" checked={terms} onChange={event=>setTerms(event.target.checked)} disabled={busy}/>{t.terms}</label><a href={config.termsURL}>{t.termsLink}</a><label className="check"><input type="checkbox" checked={privacy} onChange={event=>setPrivacy(event.target.checked)} disabled={busy}/>{t.privacy}</label><a href={config.privacyURL}>{t.privacyLink}</a><button className="primary" disabled={busy||!terms||!privacy}>{t.identityEnableEmail}</button></form>:null}</>:null}
   {!mini&&info.independent_login?<>{!info.telegram_linked||info.can_unlink?<form aria-busy={busy} onSubmit={event=>void telegram(event,info.telegram_linked)}><label htmlFor="identity-current">{t.currentPassword}<input ref={password} id="identity-current" type="password" autoComplete="current-password" required minLength={15} maxLength={128} value={current} onChange={event=>setCurrent(event.target.value)} disabled={busy}/></label><button className="primary" disabled={busy}>{info.telegram_linked?t.identityUnlink:t.identityGetLink}</button></form>:<p>{info.unlink_blocked_reason==='INDEPENDENT_LOGIN_REQUIRED'?t.identityAddFirst:t.identityUnlinkUnavailable}</p>}
    {proof?<div><p>{t.identityLinkHelp}</p><label htmlFor="identity-link-code">{t.identityLinkCode}<input ref={proofInput} id="identity-link-code" readOnly autoComplete="off" value={proof.link_token}/></label><p><time dateTime={proof.expires_at}>{new Date(proof.expires_at).toLocaleString(lang==='ru'?'ru-RU':'en-US')}</time></p><button onClick={()=>void copy()}>{t.identityCopyLink}</button></div>:null}</>:null}
  </>}
  <p><a href={link('/cabinet',lang)}>{t.identityBack}</a></p><a href={config.supportURL}>{t.support}</a>
 </section>;
}
