import {useEffect,useRef,useState,type FormEvent} from 'react';
import * as api from './api/client';
import {errorText,text,type Lang} from './i18n';

type Attempt={payload:string;key:string};
const ru={servers:'Серверы',serverDetails:'Карточка сервера',serverName:'Название сервера',serverHost:'HTTPS-адрес',serverMaximum:'Максимум клиентов',serverNoLimit:'Без заданного лимита',serverAssigned:'Назначенные клиенты',serverReserved:'Резервы',serverObserved:'Последняя проверка',serverOnline:'В сети',serverOffline:'Не в сети',serversEmpty:'Серверов пока нет.',openServer:'Открыть сервер {name}',addServer:'Добавить сервер',serverAdded:'Сервер добавлен.',syncServers:'Синхронизировать серверы',serversSynced:'Серверы синхронизированы.',pingServer:'Проверить сервер',serverPinged:'Состояние сервера обновлено.',deleteServer:'Удалить сервер',confirmServerDelete:'Подтвердить удаление сервера',cancelServerDelete:'Отмена',serverDeleteWarning:'Удалить {name}? Это действие нельзя отменить.',serverDeleted:'Сервер выведен из работы.',serverInvalid:'Укажите название до 100 символов, корректный HTTPS-адрес и целое ограничение от 0 до 2147483647.',serverInUse:'Сервер ещё используется, поэтому удалить его нельзя.',serverConflict:'Сервер изменился или такое имя либо адрес уже заняты.',serverDeleteRefused:'Удаление недоступно, пока сервер используется или его состояние нельзя безопасно проверить.'};
const en:Record<keyof typeof ru,string>={servers:'Servers',serverDetails:'Server details',serverName:'Server name',serverHost:'HTTPS host',serverMaximum:'Maximum clients',serverNoLimit:'No configured limit',serverAssigned:'Assigned clients',serverReserved:'Reservations',serverObserved:'Last checked',serverOnline:'Online',serverOffline:'Offline',serversEmpty:'No servers yet.',openServer:'Open server {name}',addServer:'Add server',serverAdded:'Server added.',syncServers:'Sync servers',serversSynced:'Servers synchronized.',pingServer:'Ping server',serverPinged:'Server status updated.',deleteServer:'Delete server',confirmServerDelete:'Confirm server deletion',cancelServerDelete:'Cancel deletion',serverDeleteWarning:'Delete {name}? This action cannot be undone.',serverDeleted:'Server retired.',serverInvalid:'Enter a name up to 100 characters, a valid HTTPS address, and an integer limit from 0 to 2147483647.',serverInUse:'Server is still in use and cannot be deleted.',serverConflict:'The server changed, or its name or address is already in use.',serverDeleteRefused:'Deletion is unavailable while the server is in use or its state cannot be checked safely.'};
const denied=(reason:unknown)=>reason instanceof api.ApiError&&(reason.status===401||reason.status===403);
function validHost(value:string){try{const url=new URL(value);return url.protocol==='https:'&&!url.username&&!url.password&&!url.search&&!url.hash&&!!url.hostname;}catch{return false;}}
function message(reason:unknown,lang:Lang){const t=lang==='ru'?ru:en;if(reason instanceof api.ApiError&&reason.code==='SERVER_IN_USE')return t.serverInUse;if(reason instanceof api.ApiError&&reason.status===409)return t.serverConflict;return errorText(reason,lang);}
const format=(template:string,name:string)=>template.replace('{name}',name);

export function AdminServers({lang,onForbidden}:{lang:Lang;onForbidden:()=>void}){
 const t={...text(lang),...(lang==='ru'?ru:en)};const[servers,setServers]=useState<api.OperatorServerSummary[]>([]);const[selected,setSelected]=useState<api.OperatorServerDetail>();const[loading,setLoading]=useState(true);const[listError,setListError]=useState('');const[error,setError]=useState('');const[formInvalid,setFormInvalid]=useState(false);const[done,setDone]=useState('');const[busy,setBusy]=useState('');const[reload,setReload]=useState(0);const[confirming,setConfirming]=useState(false);const[name,setName]=useState('');const[host,setHost]=useState('');const[maxClients,setMaxClients]=useState('');const attempts=useRef(new Map<string,Attempt>());const alert=useRef<HTMLParagraphElement>(null);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setListError('');void api.getOperatorServers(controller.signal).then(value=>{if(!controller.signal.aborted)setServers(value.servers.filter(server=>!server.retired));}).catch(reason=>{if(controller.signal.aborted)return;if(denied(reason))onForbidden();else setListError(errorText(reason,lang));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[reload]);
 useEffect(()=>{if(listError||error)alert.current?.focus();},[listError,error]);
 function edited(){attempts.current.delete('create');setError('');setFormInvalid(false);setDone('');}
 function replace(next:api.OperatorServerDetail){setServers(current=>next.retired?current.filter(server=>server.id!==next.id):current.map(server=>server.id===next.id?next:server));setSelected(next.retired?undefined:next);}
 async function act<T>(action:string,payload:unknown,call:(key:string)=>Promise<T>,success:(value:T)=>void|Promise<void>){const serialized=JSON.stringify(payload);const saved=attempts.current.get(action);const attempt=saved?.payload===serialized?saved:{payload:serialized,key:crypto.randomUUID()};attempts.current.set(action,attempt);setBusy(action);setError('');setFormInvalid(false);setDone('');try{const result=await call(attempt.key);attempts.current.delete(action);await success(result);}catch(reason){if(denied(reason))onForbidden();else setError(message(reason,lang));}finally{setBusy('');}}
 async function open(server:api.OperatorServerSummary){setBusy('open');setError('');setFormInvalid(false);setDone('');setConfirming(false);attempts.current.delete('ping:'+server.id);attempts.current.delete('delete:'+server.id);try{setSelected(await api.getOperatorServer(server.id));}catch(reason){if(denied(reason))onForbidden();else setError(message(reason,lang));}finally{setBusy('');}}
 function create(event:FormEvent){event.preventDefault();const limit=Number(maxClients);if(!name.trim()||Array.from(name).length>100||!validHost(host)||!/^\d+$/.test(maxClients)||!Number.isSafeInteger(limit)||limit>2147483647){setFormInvalid(true);setError(t.serverInvalid);return;}const input={name:name.trim(),host,max_clients:limit};void act('create',input,key=>api.createOperatorServer(input,key),value=>{setName('');setHost('');setMaxClients('');setServers(current=>[...current.filter(server=>server.id!==value.id),value]);setSelected(value);setDone(t.serverAdded);});}
 function sync(){void act('sync',{},key=>api.syncOperatorServers(key),async value=>{setServers(value.servers.filter(server=>!server.retired));if(selected){const summary=value.servers.find(server=>server.id===selected.id);if(!summary||summary.retired){setSelected(undefined);setConfirming(false);attempts.current.delete('delete:'+selected.id);}else{try{const fresh=await api.getOperatorServer(selected.id);setSelected(fresh.retired?undefined:fresh);if(fresh.retired||!fresh.can_delete){setConfirming(false);attempts.current.delete('delete:'+selected.id);}}catch(reason){if(reason instanceof api.ApiError&&reason.status===404){setSelected(undefined);setConfirming(false);attempts.current.delete('delete:'+selected.id);}throw reason;}}}setDone(t.serversSynced);});}
 function ping(){if(!selected)return;void act('ping:'+selected.id,{},key=>api.pingOperatorServer(selected.id,key),value=>{replace(value);setDone(t.serverPinged);});}
 function remove(){if(!selected)return;void act('delete:'+selected.id,{confirmation:true},key=>api.deleteOperatorServer(selected.id,key),value=>{replace(value);setConfirming(false);setDone(t.serverDeleted);});}
 const described=formInvalid?'server-form-error':undefined;
 return <section className="admin-page admin-servers" aria-label={t.servers}><div className="admin-page-head"><h1>{t.servers}</h1><button disabled={!!busy} onClick={sync}>{t.syncServers}</button></div>{listError?<p ref={alert} tabIndex={-1} role="alert" className="error">{listError} <button onClick={()=>setReload(value=>value+1)}>{t.retry}</button></p>:loading?<p role="status">{t.loading}</p>:servers.length===0?<p>{t.serversEmpty}</p>:<div className="admin-client-list">{servers.map(server=><article className="admin-client" key={server.id}><h2>{server.name}</h2><p className={server.online?'notice':'warning'}>{server.online?t.serverOnline:t.serverOffline}</p><dl><div><dt>{t.serverHost}</dt><dd>{server.host}</dd></div><div><dt>{t.serverMaximum}</dt><dd>{server.max_clients??t.serverNoLimit}</dd></div><div><dt>{t.serverAssigned}</dt><dd>{server.assigned_clients}</dd></div><div><dt>{t.serverReserved}</dt><dd>{server.reserved_clients}</dd></div></dl><button disabled={!!busy} aria-label={format(t.openServer,server.name)} onClick={()=>void open(server)}>{format(t.openServer,server.name)}</button></article>)}</div>}
 {error?<p ref={alert} id="server-form-error" tabIndex={-1} role="alert" className="error">{error}</p>:null}{done?<p role="status" className="notice">{done}</p>:null}{busy?<p role="status">{t.loading}</p>:null}
 {selected?<section className="admin-action" aria-label={t.serverDetails}><h2>{selected.name}</h2><p className={selected.online?'notice':'warning'}>{selected.online?t.serverOnline:t.serverOffline}</p><dl><div><dt>{t.serverHost}</dt><dd>{selected.host}</dd></div><div><dt>{t.serverMaximum}</dt><dd>{selected.max_clients??t.serverNoLimit}</dd></div><div><dt>{t.serverAssigned}</dt><dd>{selected.assigned_clients}</dd></div><div><dt>{t.serverReserved}</dt><dd>{selected.reserved_clients}</dd></div><div><dt>{t.serverObserved}</dt><dd>{selected.observed_at?new Date(selected.observed_at).toLocaleString(lang==='ru'?'ru-RU':'en-US'):t.unknown}</dd></div></dl><div className="admin-buttons"><button disabled={!!busy||!selected.can_ping} onClick={ping}>{t.pingServer}</button>{selected.can_delete?<button disabled={!!busy} onClick={()=>{attempts.current.delete('delete:'+selected.id);setConfirming(true);setError('');setFormInvalid(false);}}>{t.deleteServer}</button>:null}</div>{!selected.can_delete?<p className="warning">{t.serverDeleteRefused}</p>:null}{confirming?<div className="warning"><p>{format(t.serverDeleteWarning,selected.name)}</p><div className="admin-buttons"><button className="primary" disabled={!!busy} onClick={remove}>{t.confirmServerDelete}</button><button disabled={!!busy} onClick={()=>{setConfirming(false);attempts.current.delete('delete:'+selected.id);}}>{t.cancelServerDelete}</button></div></div>:null}</section>:null}
 <form className="admin-create" onSubmit={create} noValidate><h2>{t.addServer}</h2><label>{t.serverName}<input value={name} maxLength={100} disabled={!!busy} aria-invalid={formInvalid} aria-describedby={described} onChange={event=>{setName(event.target.value);edited();}}/></label><label>{t.serverHost}<input type="url" value={host} disabled={!!busy} aria-invalid={formInvalid} aria-describedby={described} onChange={event=>{setHost(event.target.value);edited();}}/></label><label>{t.serverMaximum}<input type="number" min={0} max={2147483647} step={1} value={maxClients} disabled={!!busy} aria-invalid={formInvalid} aria-describedby={described} onChange={event=>{setMaxClients(event.target.value);edited();}}/></label><button className="primary" disabled={!!busy}>{t.addServer}</button></form></section>;
}
