import {createContext,useContext,useEffect,useMemo,useRef,useState,type FormEvent} from 'react';
import {Admin,Resource,List,Show,useListContext,useRecordContext,useRefresh,memoryStore,type AuthProvider,type DataProvider,type RaRecord} from 'react-admin';
import {AdminCatalogue} from './AdminCatalogue';
import {AccessOperations} from './AccessOperations';
import {OperatorPurchase} from './OperatorPurchase';
import {PaymentHistory} from './PaymentHistory';
import {ManualPaymentInbox} from './ManualPaymentInbox';
import * as api from './api/client';
import {SupportThread,type SupportAdapter} from './Support';
import {text,link,errorText,type Lang} from './i18n';

type ClientRecord=api.OperatorClient&RaRecord;
type CardRecord=api.OperatorClientCard&RaRecord;
const AdminContext=createContext<{lang:Lang;lost:()=>void}>({lang:'en',lost:()=>{}});
const forbidden=(reason:unknown)=>reason instanceof api.ApiError&&(reason.status===401||(reason.status===403&&reason.code!=='OPERATOR_ACCOUNT_PROTECTED'));
function validKey(value:string){if(value.length>2048||value.trim()!==value||/[\u0000-\u001f\u007f]/.test(value))return false;try{const parsed=new URL(value);return parsed.protocol==='https:'&&!parsed.username&&!parsed.password&&!!parsed.hostname;}catch{return false;}}
function guard<T>(promise:Promise<T>,lost:()=>void){return promise.catch(reason=>{if(forbidden(reason))lost();throw reason;});}
function displayDate(value:string|null|undefined,lang:Lang,unknown:string){return value?new Date(value).toLocaleString(lang==='ru'?'ru-RU':'en-US'):unknown;}
function displayBytes(value:number|null|undefined,lang:Lang,unknown:string){if(value==null)return unknown;const units=['B','KiB','MiB','GiB','TiB'];const unit=value===0?0:Math.min(Math.floor(Math.log(value)/Math.log(1024)),units.length-1);return new Intl.NumberFormat(lang,{maximumFractionDigits:2}).format(value/1024**unit)+' '+units[unit];}
function displayActor(value:{operator_account_id:string|null;operator_tg_id:string|null},labels:{webOperator:string;telegramOperator:string;unknown:string}){if(value.operator_account_id)return labels.webOperator+': '+value.operator_account_id;if(value.operator_tg_id)return labels.telegramOperator+': '+value.operator_tg_id;return labels.unknown;}

function createDataProvider(lost:()=>void):DataProvider{const provider={getList:async(resource:string,params:{filter?:Record<string,unknown>;pagination?:{page:number}})=>{if(resource!=='clients')throw new Error('resource');const result=await guard(api.searchOperatorClients(String(params.filter?.q??''),params.pagination?.page??1),lost);return{data:result.clients.map(client=>({...client,id:client.account_id})),total:result.total,pageInfo:{hasNextPage:result.page*result.per_page<result.total,hasPreviousPage:result.page>1}};},getOne:async(resource:string,params:{id:string|number})=>{if(resource!=='clients')throw new Error('resource');const result=await guard(api.getOperatorClient(String(params.id)),lost);return{data:{...result,id:result.client.account_id}};},getMany:async()=>({data:[]}),getManyReference:async()=>({data:[],total:0}),create:async()=>{throw new Error('unsupported');},update:async()=>{throw new Error('unsupported');},updateMany:async()=>({data:[]}),delete:async()=>{throw new Error('unsupported');},deleteMany:async()=>({data:[]})};return provider as unknown as DataProvider;}

function ClientRows(){const{data=[],page=1,setPage,total=0,isPending}=useListContext<ClientRecord>();const{lang}=useContext(AdminContext);const t=text(lang);if(isPending)return <p role="status">{t.loading}</p>;return <><div className="admin-client-list">{data.map(client=><article className="admin-client" key={client.id}><h2><a href={'/admin/clients/'+client.id+'/show?lang='+lang}>{client.display_name||client.email||client.telegram_id||t.unknown}</a></h2><dl><div><dt>{t.source}</dt><dd>{client.kind==='telegram'?t.telegramOnly:t.webAccount}</dd></div><div><dt>{t.email}</dt><dd>{client.email??t.noEmail}</dd></div><div><dt>{t.telegramId}</dt><dd>{client.telegram_id??t.unknown}</dd></div><div><dt>{t.created}</dt><dd>{client.created_at?new Date(client.created_at).toLocaleString(lang==='ru'?'ru-RU':'en-US'):t.unknown}</dd></div></dl></article>)}</div><div className="admin-pagination"><button onClick={()=>setPage(page-1)} disabled={page<=1}>{t.previousPage}</button><span>{page}</span><button onClick={()=>setPage(page+1)} disabled={page*50>=total}>{t.nextPage}</button></div></>}

function TelegramTrialForm(){const{lang,lost}=useContext(AdminContext);const t=text(lang);const[id,setId]=useState('');const[name,setName]=useState('');const[locale,setLocale]=useState<Lang>('ru');const[attempt,setAttempt]=useState<{key:string;payload:string}>();const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[done,setDone]=useState('');const change=()=>{setAttempt(undefined);setError('');setDone('');};async function submit(event:FormEvent){event.preventDefault();if(!/^\d+$/.test(id)||id==='0'||BigInt(id)>9223372036854775807n){setError(t.telegramIdInvalid);return;}if(Array.from(name.trim()).length<1||Array.from(name).length>128){setError(t.displayNameInvalid);return;}const input={telegram_id:id,display_name:name,locale};const payload=JSON.stringify(input);const current=attempt?.payload===payload?attempt:{key:crypto.randomUUID(),payload};setAttempt(current);setBusy(true);setError('');try{await guard(api.createOperatorTelegramTrial(input,current.key),lost);setDone(t.telegramTrialCreated);setAttempt(undefined);}catch(reason){if(!forbidden(reason))setError(errorText(reason,lang));}finally{setBusy(false);}}return <form className="admin-create" onSubmit={submit}><h2>{t.createTelegramTrial}</h2>{error?<p role="alert" className="error">{error}</p>:null}{done?<p role="status" className="notice">{done}</p>:null}<label>{t.telegramId}<input inputMode="numeric" value={id} onChange={event=>{setId(event.target.value);change();}}/></label><label>{t.displayName}<input value={name} onChange={event=>{setName(event.target.value);change();}}/></label><label>{t.clientLanguage}<select value={locale} onChange={event=>{setLocale(event.target.value as Lang);change();}}><option value="ru">RU</option><option value="en">EN</option></select></label><button className="primary" disabled={busy}>{t.createTelegramTrial}</button></form>}

function ClientList(){const{lang}=useContext(AdminContext);const t=text(lang);const[q,setQ]=useState('');const[filter,setFilter]=useState('');function search(event:FormEvent){event.preventDefault();if(Array.from(q).length<=256)setFilter(q);}return <section className="admin-page"><h1>{t.clients}</h1><form className="admin-search" onSubmit={search}><label>{t.searchClients}<input value={q} onChange={event=>setQ(event.target.value)} maxLength={256}/></label><button>{t.search}</button></form><List resource="clients" filter={{q:filter}} perPage={50} pagination={false} actions={false} title={false} disableSyncWithLocation storeKey={false}><ClientRows/></List><TelegramTrialForm/></section>}

function usePrivateKey(clientId:string,lost:()=>void,lang:Lang){const[value,setValue]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const request=useRef<AbortController|undefined>(undefined);const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);const clear=()=>{request.current?.abort();request.current=undefined;if(timer.current)clearTimeout(timer.current);timer.current=undefined;setValue('');setBusy(false);};useEffect(()=>{const pagehide=()=>clear();const visibility=()=>{if(document.visibilityState==='hidden')clear();};window.addEventListener('pagehide',pagehide);document.addEventListener('visibilitychange',visibility);return()=>{window.removeEventListener('pagehide',pagehide);document.removeEventListener('visibilitychange',visibility);clear();};},[clientId]);async function reveal(){clear();const current=new AbortController();request.current=current;setBusy(true);setError('');try{const result=await api.getOperatorClientKey(clientId,current.signal);if(current.signal.aborted||request.current!==current)return;if(!validKey(result.subscription_url))throw new api.ApiError(409,'INVALID_INPUT','');setValue(result.subscription_url);timer.current=setTimeout(clear,60000);}catch(reason){if(!current.signal.aborted){if(forbidden(reason))lost();else setError(errorText(reason,lang));}}finally{if(request.current===current){request.current=undefined;setBusy(false);}}}return{value,busy,error,reveal,clear};}

function OperatorSupport({clientId}:{clientId:string}){const{lang,lost}=useContext(AdminContext);const adapter=useMemo<SupportAdapter>(()=>({load:signal=>api.getOperatorSupport(clientId,signal),history:(before,signal)=>api.getOperatorSupportHistory(clientId,before,signal),send:(message,file,key,signal)=>api.createOperatorSupportMessage(clientId,message,file,key,signal),read:(sequence,signal)=>api.acknowledgeOperatorSupport(clientId,sequence,signal),state:(status,signal)=>api.setOperatorSupportState(clientId,status,signal),attachment:api.supportAttachmentURL,ban:(banned,reason,signal)=>api.setOperatorSupportBan(clientId,banned,reason,signal)}),[clientId]);return <SupportThread lang={lang} adapter={adapter} viewer="operator" onForbidden={lost}/>}

function RestrictionForm({clientId,restricted,onSuccess}:{clientId:string;restricted:boolean;onSuccess:()=>void}){
 const{lang,lost}=useContext(AdminContext);const t=text(lang);const[reason,setReason]=useState('');const[confirming,setConfirming]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[done,setDone]=useState(false);const attempt=useRef<{payload:string;key:string}|undefined>(undefined);const request=useRef<AbortController|undefined>(undefined);const reasonInput=useRef<HTMLTextAreaElement>(null);useEffect(()=>()=>request.current?.abort(),[clientId]);useEffect(()=>{if(error)reasonInput.current?.focus();},[error]);
 const input={restricted:!restricted,reason:reason.trim()};const payload=JSON.stringify(input);
 function change(value:string){setReason(value);setConfirming(false);setError('');setDone(false);attempt.current=undefined;}
 function start(){if(!input.reason||Array.from(input.reason).length>1000||input.reason.includes('\0')){setError(t.reasonRequired);reasonInput.current?.focus();return;}setError('');if(input.restricted)setConfirming(true);else void submit();}
 async function submit(){const current=attempt.current?.payload===payload?attempt.current:{payload,key:crypto.randomUUID()};const controller=new AbortController();attempt.current=current;request.current=controller;setBusy(true);setError('');try{await guard(api.setOperatorRestriction(clientId,input,current.key,controller.signal),lost);if(controller.signal.aborted)return;attempt.current=undefined;setReason('');setConfirming(false);setDone(true);onSuccess();}catch(failure){if(!controller.signal.aborted&&!forbidden(failure)){setError(errorText(failure,lang));setConfirming(false);reasonInput.current?.focus();}}finally{if(request.current===controller){request.current=undefined;if(!controller.signal.aborted)setBusy(false);}}}
 return <section className="admin-action" aria-label={t.accountRestriction}><h2>{t.accountRestriction}</h2>{error?<p role="alert" className="error">{error}</p>:null}{done?<p role="status" className="notice">{t.restrictionSaved}</p>:null}{busy?<p role="status">{t.sending}</p>:null}<label>{t.restrictionReason}<textarea ref={reasonInput} value={reason} disabled={busy} aria-invalid={!!error} onChange={event=>change(event.target.value)}/></label>{confirming?<div className="warning"><p>{t.restrictionWarning}</p><div className="admin-buttons"><button className="primary" disabled={busy} onClick={()=>void submit()}>{t.confirmRestriction}</button><button disabled={busy} onClick={()=>setConfirming(false)}>{t.cancelRestriction}</button></div></div>:<button disabled={busy} onClick={start}>{restricted?t.unrestrictAccount:t.restrictAccount}</button>}</section>;
}

function ClientCard(){const record=useRecordContext<CardRecord>();const refresh=useRefresh();const{lang,lost}=useContext(AdminContext);const t=text(lang);const[trials,setTrials]=useState<api.OperatorTrialRequest[]>([]);const[audits,setAudits]=useState<api.OperatorAuditEvent[]>([]);const[legacy,setLegacy]=useState<api.OperatorLegacyApprovalEvent[]>([]);const[legacyMore,setLegacyMore]=useState(false);const[historyBusy,setHistoryBusy]=useState('');const historyRequest=useRef<AbortController|undefined>(undefined);const[trialMore,setTrialMore]=useState(false);const[auditMore,setAuditMore]=useState(false);const[error,setError]=useState('');const[paymentRevision,setPaymentRevision]=useState(0);const[purchaseOperation,setPurchaseOperation]=useState<{clientId:string;operationId:string|null}>();const[reasons,setReasons]=useState<Record<string,string>>({});const[busy,setBusy]=useState('');const keys=useRef(new Map<string,{payload:string;key:string}>());useEffect(()=>{historyRequest.current?.abort();if(record){setTrials(record.trial_requests);setAudits(record.audit_events);setLegacy(record.legacy_events??[]);setTrialMore(record.trial_has_more);setAuditMore(record.audit_has_more);setLegacyMore(record.legacy_has_more??false);}return()=>historyRequest.current?.abort();},[record]);const privateKey=usePrivateKey(record?.client.account_id??'',lost,lang);if(!record)return <p role="status">{t.loading}</p>;const client=record.client;const reason=(name:string)=>reasons[name]??'';const setReason=(name:string,value:string)=>{setReasons(current=>({...current,[name]:value}));keys.current.delete(name);setError('');};async function action<T>(name:string,payload:unknown,call:(key:string)=>Promise<T>){const serialized=JSON.stringify(payload);const current=keys.current.get(name)?.payload===serialized?keys.current.get(name)!:{payload:serialized,key:crypto.randomUUID()};keys.current.set(name,current);setBusy(name);setError('');try{await guard(call(current.key),lost);keys.current.delete(name);refresh();}catch(reason){if(!forbidden(reason))setError(errorText(reason,lang));}finally{setBusy('');}}const requireReason=(name:string,call:()=>void)=>{if(!reason(name).trim()||Array.from(reason(name)).length>1000){setError(t.reasonRequired);return;}call();};async function older(kind:'trials'|'audit'|'legacy'){
  const rows=kind==='trials'?trials:kind==='audit'?audits:legacy;if(!rows.length||historyBusy)return;
  const last=rows.at(-1)!;const current=new AbortController();historyRequest.current=current;setHistoryBusy(kind);setError('');
  const input=kind==='legacy'?{kind,before_created_at:last.created_at,before_source_id:(last as api.OperatorLegacyApprovalEvent).source_id}:{kind,before_created_at:last.created_at,before_id:kind==='trials'?(last as api.OperatorTrialRequest).request_id:(last as api.OperatorAuditEvent).id};
  try{const result=await guard(api.getOperatorClientHistory(client.account_id,input,current.signal),lost);if(current.signal.aborted||historyRequest.current!==current)return;
   if(kind==='trials'){setTrials(rows=>[...rows,...result.trial_requests.filter(row=>!rows.some(old=>old.request_id===row.request_id))]);setTrialMore(result.has_more);}
   else if(kind==='audit'){setAudits(rows=>[...rows,...result.audit_events.filter(row=>!rows.some(old=>old.id===row.id))]);setAuditMore(result.has_more);}
   else{setLegacy(rows=>[...rows,...result.legacy_events.filter(row=>!rows.some(old=>old.source_id===row.source_id))]);setLegacyMore(result.has_more);}
  }catch(reason){if(!current.signal.aborted&&!forbidden(reason))setError(errorText(reason,lang));}finally{if(historyRequest.current===current){historyRequest.current=undefined;setHistoryBusy('');}}
 }
 const sub=record.subscription;const purchaseOperationId=purchaseOperation?.clientId===client.account_id?purchaseOperation.operationId:null;const hasSubscription=sub.status!=='none';const statuses={none:t.none,provisioning:t.provisioning,needs_review:t.needsReview,active:t.active,expired:t.expired,banned:t.banned,disabled:t.disabled,exhausted:t.exhausted};const profiles={regular:t.profileRegular,euru:'EURU',unlimited:t.unlimited,banned:t.profileBanned,unknown:t.unknown};const unlimitedTraffic=hasSubscription&&(sub.unlimited_traffic??sub.traffic_limit_bytes===0);const unlimitedDevices=hasSubscription&&(sub.unlimited_devices??sub.devices===0);const panelMessage=sub.panel_error?({unavailable:t.panelUnavailable,identity_mismatch:t.panelIdentity,unknown_membership:t.panelMembership,invalid_traffic:t.panelTraffic} as const)[sub.panel_error]:sub.data_stale?t.stale:'';const actorLabels={webOperator:t.webOperator,telegramOperator:t.telegramOperator,unknown:t.unknown};const systemActions:Record<string,string>={monthly_reset_requested:t.monthlyResetRequested,monthly_reset_waiting:t.monthlyResetWaiting,monthly_reset_skipped:t.monthlyResetSkipped,monthly_reset_applied:t.monthlyResetApplied,monthly_reset_period_elapsed_unserved:t.monthlyResetElapsed};
 return <section className="admin-card"><h1>{client.display_name||client.email||client.telegram_id||t.unknown}</h1>{error?<p role="alert" className="error">{error}</p>:null}
  <dl className="stats-grid"><div><dt>{t.source}</dt><dd>{client.kind==='telegram'?t.telegramOnly:t.webAccount}</dd></div><div><dt>{t.email}</dt><dd>{client.email??t.noEmail}</dd></div><div><dt>{t.telegramId}</dt><dd>{client.telegram_id??t.unknown}</dd></div><div><dt>{t.created}</dt><dd>{displayDate(client.created_at,lang,t.unknown)}</dd></div><div><dt>{t.accountRestriction}</dt><dd>{client.restricted?t.accountRestricted:t.accountUnrestricted}</dd></div><div><dt>{t.vpnAccess}</dt><dd>{sub.vpn_banned?t.vpnBanned:t.vpnAllowed}</dd></div><div><dt>{t.accessStatus}</dt><dd>{statuses[sub.status]}</dd></div><div><dt>{t.accessProfile}</dt><dd>{profiles[sub.access_profile]}</dd></div><div><dt>{t.devices}</dt><dd>{hasSubscription?(unlimitedDevices?t.unlimited:sub.devices):t.unknown}</dd></div><div><dt>{t.upload}</dt><dd>{hasSubscription?displayBytes(sub.traffic_upload_bytes,lang,t.unknown):t.unknown}</dd></div><div><dt>{t.download}</dt><dd>{hasSubscription?displayBytes(sub.traffic_download_bytes,lang,t.unknown):t.unknown}</dd></div><div><dt>{t.used}</dt><dd>{hasSubscription?displayBytes(sub.traffic_used_bytes,lang,t.unknown):t.unknown}</dd></div><div><dt>{t.remaining}</dt><dd>{hasSubscription?(unlimitedTraffic?t.unlimited:displayBytes(sub.traffic_remaining_bytes,lang,t.unknown)):t.unknown}</dd></div><div><dt>{t.traffic}</dt><dd>{hasSubscription?(unlimitedTraffic?t.unlimited:displayBytes(sub.traffic_limit_bytes,lang,t.unknown)):t.unknown}</dd></div><div><dt>{t.expires}</dt><dd>{!hasSubscription?t.unknown:sub.expires_at?displayDate(sub.expires_at,lang,t.unknown):['provisioning','needs_review'].includes(sub.status)?t.unknown:t.noExpiry}</dd></div><div><dt>{t.connectionStatus}</dt><dd>{hasSubscription?(sub.connection_available===true?t.connectionAvailable:sub.connection_available===false?t.connectionUnavailable:t.unknown):t.unknown}</dd></div><div><dt>{t.server}</dt><dd>{record.server?record.server.panel_id+' · '+(record.server.enabled?t.enabled:t.disabled):t.unknown}</dd></div></dl>
  {!hasSubscription&&sub.access_profile!=='unknown'?<p className="help">{t.futureProfileIntent}</p>:null}{sub.observed_at?<p className="help">{t.observed}: {displayDate(sub.observed_at,lang,t.unknown)}</p>:null}{panelMessage?<div className="warning" role="alert"><p>{panelMessage}</p></div>:null}
  {client.kind==='telegram'&&!client.email?<RecoveryAction key={'recovery-'+client.account_id} client={client}/>:null}<RestrictionForm key={client.account_id} clientId={client.account_id} restricted={client.restricted} onSuccess={()=>{privateKey.clear();refresh();}}/><AccessOperations key={'access-'+client.account_id+'/'+paymentRevision} clientId={client.account_id} subscription={!sub.access_operation_id&&purchaseOperationId?{...sub,access_operation_id:purchaseOperationId}:sub} lang={lang} onForbidden={lost} onChange={()=>{privateKey.clear();refresh();}}/><OperatorPurchase key={'purchase-'+client.account_id+'/'+paymentRevision} clientId={client.account_id} lang={lang} onForbidden={lost} onOperationId={id=>setPurchaseOperation({clientId:client.account_id,operationId:id})}/><section className="admin-key"><h2>{t.subscriptionKey}</h2>{privateKey.error?<p role="alert" className="error">{privateKey.error}</p>:null}{privateKey.value?<><label>{t.key}<input value={privateKey.value} readOnly/></label><button onClick={privateKey.clear}>{t.hideSubscriptionKey}</button></>:<button onClick={privateKey.reveal} disabled={privateKey.busy}>{t.showKey}</button>}</section>
  <section><h2>{t.trialRequests}</h2>{trials.map(request=><article className="admin-action" key={request.request_id}><p>{request.status}: {request.comment}</p><dl><div><dt>{t.created}</dt><dd>{displayDate(request.created_at,lang,t.unknown)}</dd></div><div><dt>{t.decided}</dt><dd>{displayDate(request.decided_at,lang,t.unknown)}</dd></div><div><dt>{t.actor}</dt><dd>{displayActor(request,actorLabels)}</dd></div><div><dt>{t.reason}</dt><dd>{request.reason??t.unknown}</dd></div></dl>{request.status==='pending'?<><button onClick={()=>action('approve-'+request.request_id,{decision:'approve',reason:''},key=>api.decideOperatorTrial(request.request_id,{decision:'approve',reason:''},key))} disabled={!!busy}>{t.approve}</button><label>{t.rejectReason}<input value={reason('reject-'+request.request_id)} onChange={event=>setReason('reject-'+request.request_id,event.target.value)}/></label><button onClick={()=>requireReason('reject-'+request.request_id,()=>void action('reject-'+request.request_id,{decision:'reject',reason:reason('reject-'+request.request_id)},key=>api.decideOperatorTrial(request.request_id,{decision:'reject',reason:reason('reject-'+request.request_id)},key)))} disabled={!!busy}>{t.reject}</button></>:null}{request.status==='rejected'?<><label>{t.reconsiderReason}<input value={reason('reconsider-'+request.request_id)} onChange={event=>setReason('reconsider-'+request.request_id,event.target.value)}/></label><button onClick={()=>requireReason('reconsider-'+request.request_id,()=>void action('reconsider-'+request.request_id,{reason:reason('reconsider-'+request.request_id)},key=>api.reconsiderOperatorTrial(request.request_id,reason('reconsider-'+request.request_id),key)))} disabled={!!busy}>{t.reconsider}</button></>:null}{request.operation?.status==='needs_review'?<><label>{t.reconcileReason}<input value={reason('reconcile-'+request.operation.operation_id)} onChange={event=>setReason('reconcile-'+request.operation!.operation_id,event.target.value)}/></label><button onClick={()=>requireReason('reconcile-'+request.operation!.operation_id,()=>void action('reconcile-'+request.operation!.operation_id,{reason:reason('reconcile-'+request.operation!.operation_id)},key=>api.reconcileOperatorTrial(request.operation!.operation_id,reason('reconcile-'+request.operation!.operation_id),key)))} disabled={!!busy}>{t.reconcile}</button></>:null}</article>)}{trialMore?<button disabled={!!historyBusy} onClick={()=>older('trials')}>{t.loadOlderTrials}</button>:null}</section>
  <section><h2>{t.auditEvents}</h2>{audits.map(event=><article className="admin-audit" key={event.id}><p>{event.system_actor?(systemActions[event.action]??t.systemAccessEvent):event.action}</p><dl><div><dt>{t.created}</dt><dd>{displayDate(event.created_at,lang,t.unknown)}</dd></div><div><dt>{t.actor}</dt><dd>{event.system_actor?t.systemActor:displayActor(event,actorLabels)}</dd></div><div><dt>{t.reason}</dt><dd>{event.reason??t.unknown}</dd></div>{event.monthly_period?<div><dt>{t.monthlyPeriod}</dt><dd>{new Intl.DateTimeFormat(lang==='ru'?'ru-RU':'en-US',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(event.monthly_period+'-01T00:00:00Z'))}</dd></div>:null}</dl></article>)}{auditMore?<button disabled={!!historyBusy} onClick={()=>older('audit')}>{t.loadOlderAudit}</button>:null}</section>
  <section aria-label={t.legacyHistory}><h2>{t.legacyHistory}</h2>{record.legacy_approval?<article className="admin-action"><h3>{t.legacySnapshot}</h3><dl><div><dt>{t.legacyUserId}</dt><dd>{record.legacy_approval.source_legacy_user_id}</dd></div><div><dt>{t.legacyTargetId}</dt><dd>{record.legacy_approval.source_tg_id}</dd></div><div><dt>{t.legacyStatus}</dt><dd>{record.legacy_approval.status}</dd></div><div><dt>{t.legacyRequested}</dt><dd>{displayDate(record.legacy_approval.requested_at,lang,t.legacyUnknown)}</dd></div><div><dt>{t.legacyDecided}</dt><dd>{displayDate(record.legacy_approval.decided_at,lang,t.legacyUnknown)}</dd></div><div><dt>{t.legacyDecidedBy}</dt><dd>{record.legacy_approval.decided_by??t.legacyUnknown}</dd></div></dl></article>:null}<h3>{t.legacyEvents}</h3>{historyBusy==='legacy'?<p role="status">{t.loading}</p>:null}{legacy.length===0?<p>{t.legacyEmpty}</p>:legacy.map(event=><article className="admin-audit" key={event.source_id}><p>{event.action}</p><dl><div><dt>{t.legacyEventId}</dt><dd>{event.source_id}</dd></div><div><dt>{t.created}</dt><dd>{displayDate(event.created_at,lang,t.legacyUnknown)}</dd></div><div><dt>{t.legacyActor}</dt><dd>{[event.actor_type,event.actor_name,event.actor_id].filter(Boolean).join(' · ')||t.legacyUnknown}</dd></div><div><dt>{t.legacySource}</dt><dd>{event.source??t.legacyUnknown}</dd></div></dl></article>)}{legacyMore&&legacy.length>0?<button disabled={!!historyBusy} onClick={()=>older('legacy')}>{t.loadOlderLegacy}</button>:null}</section>
  <PaymentHistory key={'payments-'+client.account_id} clientId={client.account_id} lang={lang} onDenied={lost} onChanged={()=>{setPurchaseOperation(undefined);setPaymentRevision(value=>value+1);privateKey.clear();refresh();}}/><section><h2>{t.promocodes}</h2><p>{t.promocodesUnavailable}</p></section><section><h2>{t.supportMessages}</h2><OperatorSupport clientId={client.account_id}/></section></section>}

function RecoveryAction({client}:{client:api.OperatorClient}){
 const{lang,lost}=useContext(AdminContext),t=text(lang);const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false),[cooldown,setCooldown]=useState(0);const request=useRef<AbortController|undefined>(undefined),alive=useRef(true),key=useRef<{fingerprint:string;value:string}|undefined>(undefined),input=useRef<HTMLInputElement>(null);
 useEffect(()=>{alive.current=true;const hide=()=>{request.current?.abort();setEmail('');setPassword('');setReason('');setConfirmed(false);setError('');setDone(false);setBusy(false);key.current=undefined;};const visibility=()=>{if(document.visibilityState==='hidden')hide();};window.addEventListener('pagehide',hide);document.addEventListener('visibilitychange',visibility);return()=>{alive.current=false;request.current?.abort();window.removeEventListener('pagehide',hide);document.removeEventListener('visibilitychange',visibility);};},[client.account_id]);
 useEffect(()=>{if(cooldown){const timer=setTimeout(()=>setCooldown(0),cooldown*1000);return()=>clearTimeout(timer);}},[cooldown]);
 function edited(){key.current=undefined;setError('');setDone(false);}
 async function submit(event:FormEvent){
  event.preventDefault();if(busy||cooldown||!confirmed)return;setError('');
  if(!email.trim()||!reason.trim()||Array.from(reason.trim()).length>1000||reason.includes('\0')){setError(t.reasonRequired);return;}
  if(Array.from(password).length<15||Array.from(password).length>128){setError(t.passwordInvalid);input.current?.focus();return;}
  const fingerprint=JSON.stringify({target:client.account_id,email:email.trim().toLowerCase(),reason:reason.trim(),confirmed});const currentKey=key.current?.fingerprint===fingerprint?key.current:{fingerprint,value:crypto.randomUUID()};key.current=currentKey;
  const controller=new AbortController();request.current=controller;setBusy(true);
  try{const out=await api.requestOperatorRecovery(client.account_id,{email,current_password:password,reason:reason.trim(),confirmed:true},currentKey.value,controller.signal);if(!alive.current||controller.signal.aborted)return;key.current=undefined;setDone(true);setCooldown(out.resend_after);}
  catch(failure){if(alive.current&&!controller.signal.aborted){if(forbidden(failure))lost();else setError(failure instanceof api.ApiError&&failure.code==='IDENTITY_CONFLICT'?t.identityConflict:errorText(failure,lang));}}
  finally{if(alive.current&&!controller.signal.aborted){setPassword('');setBusy(false);}}
 }
 return <section className="admin-action" aria-labelledby="identity-recovery-heading"><h2 id="identity-recovery-heading">{t.recoveryOperator}</h2>{error?<p role="alert">{error}</p>:null}{done?<p role="status">{t.recoveryQueued}</p>:null}<form aria-busy={busy} onSubmit={event=>void submit(event)}><label>{t.email}<input type="email" autoComplete="off" value={email} onChange={event=>{edited();setEmail(event.target.value);}} disabled={busy} required/></label><label>{t.currentPassword}<input ref={input} type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)} disabled={busy}/></label><label>{t.recoveryReason}<textarea value={reason} onChange={event=>{edited();setReason(event.target.value);}} disabled={busy}/></label><label className="check"><input type="checkbox" checked={confirmed} onChange={event=>{edited();setConfirmed(event.target.checked);}} disabled={busy}/>{t.recoveryConfirm}</label><button className="primary" disabled={busy||!confirmed||cooldown>0}>{busy?t.sending:t.recoverySend}</button></form></section>;
}

function ClientShow(){return <Show resource="clients" actions={false} title={false}><ClientCard/></Show>}
function Denied({lang}:{lang:Lang}){const t=text(lang);const[busy,setBusy]=useState(false);async function logout(){setBusy(true);try{await api.logoutAccount();location.replace(link('/login',lang));}catch{setBusy(false);}}return <main className="card admin-denied"><h1>{t.operatorRequired}</h1><p>{t.operatorRequiredHelp}</p><button onClick={logout} disabled={busy}>{t.logout}</button></main>}

function ManualPaymentList(){const{lang,lost}=useContext(AdminContext);return <ManualPaymentInbox lang={lang} onForbidden={lost}/>;}

function CatalogueList(){const{lang,lost}=useContext(AdminContext);return <AdminCatalogue lang={lang} onForbidden={lost}/>;}

export default function OperatorAdmin({lang}:{lang:Lang}){const t=text(lang);const[status,setStatus]=useState<'loading'|'ready'|'denied'>('loading');useEffect(()=>{const controller=new AbortController();void api.getOperatorSession(controller.signal).then(()=>setStatus('ready')).catch(async reason=>{if(controller.signal.aborted)return;if(forbidden(reason)){try{await api.getSessionContext(controller.signal);}catch{}setStatus('denied');}else setStatus('denied');});return()=>controller.abort();},[]);const lost=()=>setStatus('denied');const dataProvider=useMemo(()=>createDataProvider(lost),[]);const authProvider=useMemo<AuthProvider>(()=>({login:async params=>{await api.loginAccount({email:String(params.email??params.username??''),password:String(params.password??'')});await api.getOperatorSession();},logout:async()=>{await api.logoutAccount();},checkAuth:async()=>{await api.getOperatorSession();},checkError:async error=>{if(forbidden(error))throw error;},getPermissions:async()=>['operator'],getIdentity:async()=>({id:'operator',fullName:t.operatorCabinet})}),[t.operatorCabinet]);if(status==='loading')return <p role="status">{t.loading}</p>;if(status==='denied')return <Denied lang={lang}/>;return <AdminContext.Provider value={{lang,lost}}><Admin basename="/admin" title={t.operatorCabinet} dataProvider={dataProvider} authProvider={authProvider} store={memoryStore()} loginPage={false} requireAuth disableTelemetry><Resource name="clients" list={ClientList} show={ClientShow}/><Resource name="catalogue" list={CatalogueList} options={{label:t.plans}}/><Resource name="manual-payments" list={ManualPaymentList} options={{label:t.manualRequests}}/></Admin></AdminContext.Provider>}
