import {useEffect,useRef,useState} from 'react';
import * as api from './api/client';
import {displayPrice,type Currency} from './catalogueMoney';
import {text,link,errorText,type Lang} from './i18n';

export function Catalogue({lang}:{lang:Lang}){
 const t=text(lang);const[plans,setPlans]=useState<api.CataloguePlanSnapshot[]>([]);const[status,setStatus]=useState<'loading'|'ready'|'error'>('loading');const[error,setError]=useState('');const[stale,setStale]=useState(false);const[retry,setRetry]=useState(0);const[choice,setChoice]=useState<{planId:string;period:number;currency:Currency}>({planId:'',period:0,currency:'RUB'});const[methods,setMethods]=useState<api.PaymentMethods['methods']>([]);const[methodsStatus,setMethodsStatus]=useState<'loading'|'ready'|'error'>('loading');const[currentOrder,setCurrentOrder]=useState<api.PurchaseOrder|null>(null);const[confirming,setConfirming]=useState(false);const[paymentType,setPaymentType]=useState<'AC'|'PC'>('AC');const[busy,setBusy]=useState(false);const attempt=useRef<{body:api.PurchaseOrderInput;key:string}|null>(null);
 useEffect(()=>{const controller=new AbortController();setStatus('loading');void api.getCatalogue(controller.signal).then(result=>{if(controller.signal.aborted)return;const visible=result.plans.filter(plan=>!plan.hidden);setPlans(visible);setChoice(current=>{const selected=visible.find(plan=>plan.plan_id===current.planId);return selected?{...current,period:selected.periods.includes(current.period)?current.period:selected.periods[0]??0}:{planId:'',period:0,currency:'RUB'};});setError('');setStatus('ready');}).catch(reason=>{if(controller.signal.aborted)return;if(reason instanceof api.ApiError&&reason.status===401){location.replace(link('/login',lang));return;}setError(errorText(reason,lang));setStatus('error');});return()=>controller.abort();},[lang,retry]);
 useEffect(()=>{const controller=new AbortController();setMethodsStatus('loading');void Promise.all([api.getPaymentMethods(controller.signal),api.getCurrentPurchaseOrder(controller.signal)]).then(([result,current])=>{if(controller.signal.aborted)return;setMethods(Array.isArray(result.methods)?result.methods:[]);setCurrentOrder(current.order??null);setMethodsStatus('ready');}).catch(reason=>{if(controller.signal.aborted)return;if(reason instanceof api.ApiError&&reason.status===401){location.replace(link('/login',lang));return;}setMethods([]);setMethodsStatus('error');});return()=>controller.abort();},[retry]);
 const chosen=status==='ready'?plans.find(plan=>plan.plan_id===choice.planId):undefined;const offer=chosen?.prices.find(price=>price.period_days===choice.period&&price.currency===choice.currency);
 const blocksPurchase=!!currentOrder&&(currentOrder.review_required||currentOrder.payment_status==='paid'||currentOrder.fulfillment_status!=='not_started'||currentOrder.payment_status==='pending'&&!currentOrder.expired);
 const canBuy=!!chosen&&!!offer&&choice.currency==='RUB'&&chosen.profile!=='unlimited'&&methods.some(method=>method.id==='yoomoney')&&/^\d+$/.test(offer.amount_minor)&&BigInt(offer.amount_minor)>0n&&!blocksPurchase&&!stale;
 function select(plan:api.CataloguePlanSnapshot){setChoice({planId:plan.plan_id,period:plan.periods[0]??0,currency:'RUB'});setConfirming(false);attempt.current=null;}
 function changeChoice(next:{planId:string;period:number;currency:Currency}){setChoice(next);setConfirming(false);attempt.current=null;}
 async function create(){if(!chosen||!canBuy||busy)return;const body:api.PurchaseOrderInput={action:'purchase',plan_id:chosen.plan_id,revision:chosen.revision,period_days:choice.period,payment_method:'yoomoney',payment_type:paymentType};const pending=attempt.current??{body,key:crypto.randomUUID()};attempt.current=pending;setBusy(true);setError('');try{await api.getSessionContext();const order=await api.createPurchaseOrder(pending.body,pending.key);location.assign(link('/orders/'+order.order_id,lang));}catch(reason){if(reason instanceof api.ApiError&&reason.status===401){location.assign(link('/login',lang));return;}const old=reason instanceof api.ApiError&&['CATALOGUE_REVISION_CONFLICT','PURCHASE_PLAN_CONFLICT'].includes(reason.code);if(old){setStale(true);attempt.current=null;}setError(old?t.purchaseReload:errorText(reason,lang));}finally{setBusy(false);}}
 return <section className="card catalogue"><h1>{t.plans}</h1><nav className="account-links" aria-label={t.accountNavigation}><a href={link('/cabinet',lang)}>{t.backAccount}</a></nav>{status==='loading'?<p role="status">{t.loading}</p>:null}{status==='error'?<div className="error" role="alert"><p>{error}</p><button onClick={()=>setRetry(value=>value+1)}>{t.retry}</button></div>:null}{status==='ready'&&plans.length===0?<><p>{t.plansEmpty}</p><button onClick={()=>setRetry(value=>value+1)}>{t.retry}</button></>:null}
  {status==='ready'&&plans.length>0?<div className="catalogue-list">{plans.map(plan=><article className="admin-action" key={plan.plan_id}><h2>{plan.devices} {t.devicesCount}</h2><p>{plan.traffic_gb===0?t.unlimitedTraffic:`${plan.traffic_gb} GB`} · {plan.profile==='euru'?'EURU':t.profileRegular}</p><button disabled={busy} onClick={()=>select(plan)} aria-pressed={choice.planId===plan.plan_id}>{t.selectPlan}</button></article>)}</div>:null}
  {currentOrder?<p className="notice"><a href={link('/orders/'+currentOrder.order_id,lang)}>{t.currentOrder}</a></p>:null}{methodsStatus==='error'?<div className="error" role="alert"><p>{t.generic}</p><button onClick={()=>setRetry(value=>value+1)}>{t.retry}</button></div>:null}
  {chosen?<section className="catalogue-selection" aria-label={t.selectedOffer}><h2>{t.selectedOffer}</h2><dl><div><dt>{t.devices}</dt><dd>{chosen.devices} {t.devicesCount}</dd></div><div><dt>{t.traffic}</dt><dd>{chosen.traffic_gb===0?t.unlimitedTraffic:`${chosen.traffic_gb} GB`}</dd></div><div><dt>{t.accessProfile}</dt><dd>{chosen.profile==='euru'?'EURU':chosen.profile==='unlimited'?t.unlimited:t.profileRegular}</dd></div></dl><div className="catalogue-selectors"><label>{t.period}<select disabled={busy} value={choice.period} onChange={event=>changeChoice({...choice,period:Number(event.target.value)})}>{chosen.periods.map(days=><option value={days} key={days}>{days} {t.days}</option>)}</select></label><label>{t.currency}<select disabled={busy} value={choice.currency} onChange={event=>changeChoice({...choice,currency:event.target.value as Currency})}><option value="RUB">RUB</option><option value="USD">USD</option><option value="XTR">XTR</option></select></label></div><p className="notice" role="status">{t.price}: {offer?displayPrice(offer.amount_minor,choice.currency,lang):t.unknown}</p>{methods.some(method=>method.id==='yoomoney')&&!blocksPurchase?<><fieldset className="purchase-choice" disabled={busy}><legend>{t.paymentChoice}</legend><label className="check"><input type="radio" name="payment-type" value="AC" checked={paymentType==='AC'} onChange={()=>{setPaymentType('AC');setConfirming(false);attempt.current=null;}}/>{t.cardPayment}</label><label className="check"><input type="radio" name="payment-type" value="PC" checked={paymentType==='PC'} onChange={()=>{setPaymentType('PC');setConfirming(false);attempt.current=null;}}/>{t.walletPayment}</label></fieldset>{error?<p role="alert" className="error">{error}</p>:null}{stale?<button onClick={()=>{setStale(false);setConfirming(false);setChoice({planId:'',period:0,currency:'RUB'});setRetry(value=>value+1);}}>{t.reloadOffers}</button>:confirming?<div className="warning"><p>{t.purchaseConfirmHelp} {displayPrice(offer!.amount_minor,'RUB',lang)} · {choice.period} {t.days} · {chosen.devices} {t.devicesCount}</p><button className="primary" disabled={busy} onClick={()=>void create()}>{busy?t.sending:t.confirmPurchase}</button><button disabled={busy} onClick={()=>setConfirming(false)}>{t.cancelConfirmation}</button><button disabled={busy} onClick={()=>{setConfirming(false);setRetry(value=>value+1);}}>{t.reloadOffers}</button></div>:<button className="primary" disabled={!canBuy||busy} onClick={()=>setConfirming(true)}>{t.buyPlan}</button>}</>:<p className="help">{blocksPurchase?t.currentOrder:methodsStatus==='loading'?t.loading:t.paymentUnavailable}</p>}{!canBuy&&!blocksPurchase&&methods.length>0?<p className="help">{t.purchaseUnavailable}</p>:null}</section>:null}
 </section>;
}
