import {useEffect,useState} from 'react';
import * as api from './api/client';
import {displayPrice,type Currency} from './catalogueMoney';
import {text,link,errorText,type Lang} from './i18n';

export function Catalogue({lang}:{lang:Lang}){
 const t=text(lang);const[plans,setPlans]=useState<api.CataloguePlanSnapshot[]>([]);const[status,setStatus]=useState<'loading'|'ready'|'error'>('loading');const[error,setError]=useState('');const[retry,setRetry]=useState(0);const[choice,setChoice]=useState<{planId:string;period:number;currency:Currency}>({planId:'',period:0,currency:'RUB'});
 useEffect(()=>{const controller=new AbortController();setStatus('loading');void api.getCatalogue(controller.signal).then(result=>{if(controller.signal.aborted)return;const visible=result.plans.filter(plan=>!plan.hidden);setPlans(visible);setChoice(current=>{const selected=visible.find(plan=>plan.plan_id===current.planId);return selected?{...current,period:selected.periods.includes(current.period)?current.period:selected.periods[0]??0}:{planId:'',period:0,currency:'RUB'};});setError('');setStatus('ready');}).catch(reason=>{if(controller.signal.aborted)return;if(reason instanceof api.ApiError&&reason.status===401){location.replace(link('/login',lang));return;}setError(errorText(reason,lang));setStatus('error');});return()=>controller.abort();},[lang,retry]);
 const chosen=status==='ready'?plans.find(plan=>plan.plan_id===choice.planId):undefined;const offer=chosen?.prices.find(price=>price.period_days===choice.period&&price.currency===choice.currency);
 function select(plan:api.CataloguePlanSnapshot){setChoice({planId:plan.plan_id,period:plan.periods[0]??0,currency:'RUB'});}
 return <section className="card catalogue"><h1>{t.plans}</h1><nav className="account-links" aria-label={t.accountNavigation}><a href={link('/cabinet',lang)}>{t.backAccount}</a></nav>{status==='loading'?<p role="status">{t.loading}</p>:null}{status==='error'?<div className="error" role="alert"><p>{error}</p><button onClick={()=>setRetry(value=>value+1)}>{t.retry}</button></div>:null}{status==='ready'&&plans.length===0?<><p>{t.plansEmpty}</p><button onClick={()=>setRetry(value=>value+1)}>{t.retry}</button></>:null}
  {status==='ready'&&plans.length>0?<div className="catalogue-list">{plans.map(plan=><article className="admin-action" key={plan.plan_id}><h2>{plan.devices} {t.devicesCount}</h2><p>{plan.traffic_gb===0?t.unlimitedTraffic:`${plan.traffic_gb} GB`} · {plan.profile==='euru'?'EURU':t.profileRegular}</p><button onClick={()=>select(plan)} aria-pressed={choice.planId===plan.plan_id}>{t.selectPlan}</button></article>)}</div>:null}
  {chosen?<section className="catalogue-selection" aria-label={t.selectedOffer}><h2>{t.selectedOffer}</h2><dl><div><dt>{t.devices}</dt><dd>{chosen.devices} {t.devicesCount}</dd></div><div><dt>{t.traffic}</dt><dd>{chosen.traffic_gb===0?t.unlimitedTraffic:`${chosen.traffic_gb} GB`}</dd></div><div><dt>{t.accessProfile}</dt><dd>{chosen.profile==='euru'?'EURU':chosen.profile==='unlimited'?t.unlimited:t.profileRegular}</dd></div></dl><div className="catalogue-selectors"><label>{t.period}<select value={choice.period} onChange={event=>setChoice(current=>({...current,period:Number(event.target.value)}))}>{chosen.periods.map(days=><option value={days} key={days}>{days} {t.days}</option>)}</select></label><label>{t.currency}<select value={choice.currency} onChange={event=>setChoice(current=>({...current,currency:event.target.value as Currency}))}><option value="RUB">RUB</option><option value="USD">USD</option><option value="XTR">XTR</option></select></label></div><p className="notice" role="status">{t.price}: {offer?displayPrice(offer.amount_minor,choice.currency,lang):t.unknown}</p><p className="help">{t.offerCurrent}</p></section>:null}
 </section>;
}
