import {createContext,useContext,useEffect,useRef,useState,type FormEvent,type ReactNode} from 'react';
import * as api from './api/client';
import {text,errorText,type Lang} from './i18n';

type PublicState={status:api.MaintenanceStatus|null;error:boolean;refresh:()=>void};
const Context=createContext<PublicState>({status:null,error:false,refresh:()=>{}});
export const useMaintenance=()=>useContext(Context);

export function MaintenanceProvider({lang,path,children}:{lang:Lang;path:string;children:ReactNode}){
 const t=text(lang);const[status,setStatus]=useState<api.MaintenanceStatus|null>(null);const[error,setError]=useState(false);const[revision,setRevision]=useState(0);const active=useRef<AbortController|null>(null);
 useEffect(()=>{const controller=new AbortController();active.current?.abort();active.current=controller;void api.getMaintenance(controller.signal).then(value=>{if(!controller.signal.aborted){setStatus(value);setError(false);}}).catch(()=>{if(!controller.signal.aborted){setStatus(null);setError(true);}});return()=>controller.abort();},[path,revision]);
 useEffect(()=>{const onVisible=()=>{if(document.visibilityState==='visible')setRevision(value=>value+1);};document.addEventListener('visibilitychange',onVisible);const timer=setInterval(()=>{if(document.visibilityState==='visible')setRevision(value=>value+1);},30000);return()=>{document.removeEventListener('visibilitychange',onVisible);clearInterval(timer);active.current?.abort();};},[]);
 return <Context.Provider value={{status,error,refresh:()=>setRevision(value=>value+1)}}>{status?.enabled?<aside className="warning maintenance-banner" role="status"><strong>{t.maintenanceOn}</strong><p>{t.maintenanceClientHelp}</p></aside>:error?<aside className="warning maintenance-banner" aria-live="polite"><strong>{t.maintenanceUnknown}</strong><p>{t.maintenanceUnknownHelp}</p><button onClick={()=>setRevision(value=>value+1)}>{t.maintenanceRetry}</button></aside>:!status?<p className="help maintenance-banner">{t.maintenanceChecking}</p>:null}{children}</Context.Provider>;
}

export function OperatorMaintenance({lang,onForbidden}:{lang:Lang;onForbidden:()=>void}){
 const t=text(lang);const[status,setStatus]=useState<api.MaintenanceStatus|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[done,setDone]=useState('');const[reason,setReason]=useState('');const[confirmed,setConfirmed]=useState(false);const[revision,setRevision]=useState(0);const attempt=useRef<{input:api.MaintenanceInput;key:string}|null>(null);const stateRef=useRef<HTMLParagraphElement>(null);const focusAfterRefresh=useRef(false);
 useEffect(()=>{if(status&&focusAfterRefresh.current){stateRef.current?.focus();focusAfterRefresh.current=false;}},[status]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);void api.getOperatorMaintenance(controller.signal).then(value=>{if(!controller.signal.aborted){setStatus(value);setError(previous=>previous===t.maintenanceConflict?previous:'');}}).catch(failure=>{if(controller.signal.aborted)return;setStatus(null);if(failure instanceof api.ApiError&&[401,403].includes(failure.status))onForbidden();else setError(errorText(failure,lang));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[revision,lang,onForbidden]);
 async function submit(event:FormEvent){event.preventDefault();if(busy||!status)return;const clean=reason.trim();if(!clean||Array.from(clean).length>1000||clean.includes('\0')||!confirmed){setError(t.maintenanceValidation);return;}const pending=attempt.current??{input:{enabled:!status.enabled,expected_revision:status.revision,reason:clean,confirmed:true as const},key:crypto.randomUUID()};attempt.current=pending;setBusy(true);setError('');setDone('');try{await api.setOperatorMaintenance(pending.input,pending.key);attempt.current=null;setReason('');setConfirmed(false);focusAfterRefresh.current=true;setStatus(null);setLoading(true);const current=await api.getOperatorMaintenance();setStatus(current);setDone(t.maintenanceSaved);}catch(failure){if(failure instanceof api.ApiError&&[401,403].includes(failure.status)){onForbidden();return;}if(failure instanceof api.ApiError&&failure.code==='MAINTENANCE_CONFLICT'){attempt.current=null;setReason('');setConfirmed(false);focusAfterRefresh.current=true;setStatus(null);setError(t.maintenanceConflict);setRevision(value=>value+1);}else if(failure instanceof api.ApiError&&failure.code==='IDEMPOTENCY_CONFLICT'){attempt.current=null;focusAfterRefresh.current=true;setError(t.maintenanceConflict);setRevision(value=>value+1);}else setError(errorText(failure,lang));}finally{setBusy(false);setLoading(false);}}
 return <section className="admin-page"><h1>{t.maintenanceTitle}</h1>{loading?<p role="status">{t.loading}</p>:null}{error?<div className="error" role="alert"><p>{error}</p>{!status?<button disabled={busy} onClick={()=>setRevision(value=>value+1)}>{t.retry}</button>:null}</div>:null}{done?<p role="status" className="notice">{done}</p>:null}{status?<><p ref={stateRef} tabIndex={-1} className={status.enabled?'warning':'notice'} role="status">{status.enabled?t.maintenanceOn:t.maintenanceOff}</p><p className="help">{t.maintenanceRevision}: {status.revision}</p><form className="admin-action" onSubmit={submit} aria-busy={busy}><h2>{status.enabled?t.maintenanceDisable:t.maintenanceEnable}</h2><label>{t.maintenanceReason}<textarea value={reason} maxLength={1000} disabled={busy||!!attempt.current} onChange={event=>{setReason(event.target.value);setError('');}} required/></label><label className="check"><input type="checkbox" checked={confirmed} disabled={busy||!!attempt.current} onChange={event=>setConfirmed(event.target.checked)}/>{t.maintenanceConfirm}</label><button className="primary" disabled={busy||!confirmed||!reason.trim()}>{busy?t.sending:status.enabled?t.maintenanceDisable:t.maintenanceEnable}</button></form></>:null}</section>;
}
