import {lazy,Suspense,useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,Route,Routes,useLocation} from 'react-router-dom';
import {Auth} from './Auth';
import {MiniApp,miniText} from './MiniApp';
import {isMiniApp,openMiniBrowser} from './telegramSDK';
import {Security} from './Security';
import {AccountIdentity} from './AccountIdentity';
import {IdentityRecovery} from './IdentityRecovery';
import {Cabinet} from './Cabinet';
import {Catalogue} from './Catalogue';
import {PurchaseOrder} from './PurchaseOrder';
import {PaymentHistory} from './PaymentHistory';
import {Referrals} from './Referrals';
import {Support} from './Support';
import {MaintenanceProvider} from './Maintenance';
import {config,loadConfig} from './config';
import {text,link,type Lang} from './i18n';
import './style.css';
const OperatorAdmin=lazy(()=>import('./Admin'));
const mini=isMiniApp();const path=location.pathname;
if(path==='/admin')history.replaceState(null,'','/admin/clients'+location.search);
if(!['/verify-email','/reset-password','/confirm-email-change','/recover-account'].includes(path))delete window.__emailToken;
else window.addEventListener('hashchange',()=>location.reload());
function App(){
 const route=useLocation();const path=mini?route.pathname.replace(/^\/mini-app(?=\/|$)/,'')||'/cabinet':location.pathname;
 const[lang,setLang]=useState<Lang>(new URLSearchParams(location.search).get('lang')==='en'?'en':'ru');const t=text(lang),m=miniText(lang);const admin=!mini&&path.startsWith('/admin');
 const browserLogin=location.origin+'/login'+(lang==='en'?'?lang=en':'');
 useEffect(()=>{document.documentElement.lang=lang;const title=admin?t.operatorCabinet:path.startsWith('/orders/')?t.order:path==='/catalogue'?t.plans:path==='/cabinet/renew'?t.renewalTitle:path==='/cabinet/change-plan'?t.changePlanTitle:path==='/cabinet/support'?t.supportMessages:path==='/cabinet/history'?t.paymentHistory:path==='/cabinet/referrals'?t.referralsTitle:path==='/cabinet/identity'?t.identityTitle:path==='/recover-account'?t.recoveryTitle:t.cabinet;document.title=config.productName?title+' · '+config.productName:title;},[admin,lang,path,t]);
 const orderId=/^\/orders\/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$/i.exec(path)?.[1];
 const regular=orderId?<PurchaseOrder id={orderId} lang={lang}/>:path==='/catalogue'?<Catalogue lang={lang}/>:path==='/cabinet/renew'?<Catalogue lang={lang} action="renew"/>:path==='/cabinet/change-plan'?<Catalogue lang={lang} action="change_plan"/>:path==='/cabinet/history'?<PaymentHistory lang={lang}/>:path==='/cabinet/referrals'?<Referrals lang={lang}/>:path==='/cabinet/support'?<Support lang={lang}/>:path==='/recover-account'&&!mini?<IdentityRecovery lang={lang}/>:path==='/cabinet/identity'?<AccountIdentity lang={lang}/>:path==='/cabinet/security'&&!mini?<Security lang={lang}/>:path==='/cabinet'||path==='/'||mini?<Cabinet lang={lang}/>:<Auth mode={path==='/register'?'register':path==='/verify-email'?'verify-email':path==='/forgot-password'?'forgot-password':path==='/reset-password'?'reset-password':path==='/confirm-email-change'?'confirm-email-change':'login'} lang={lang}/>;
 return <div className={mini?'mini-app':undefined}><header><a href={link(admin?'/admin':'/cabinet',lang)} className="brand"><img src="/brand/3xui-mole-logo.png" width="64" height="64" alt=""/><span>{config.productName?config.productName+' · ':''}{admin?t.operatorCabinet:t.cabinet}</span></a>{mini?<a href={browserLogin}>{m.browser}</a>:null}<div aria-label="Language"><button type="button" aria-pressed={lang==='ru'} onClick={()=>setLang('ru')}>RU</button><button type="button" aria-pressed={lang==='en'} onClick={()=>setLang('en')}>EN</button></div></header>{admin?<div className="admin-root"><Routes><Route path="/admin/*" element={<Suspense fallback={<p role="status">{t.loading}</p>}><OperatorAdmin lang={lang}/></Suspense>}/></Routes></div>:mini?<MiniApp lang={lang}><main><MaintenanceProvider lang={lang} path={route.pathname}>{regular}{['/','/cabinet','/catalogue','/cabinet/renew','/cabinet/change-plan'].includes(path)||orderId?<section className="card" aria-label={m.otherPayments}><p className="help" id="mini-browser-payment-help">{m.paymentHelp}</p><div className="account-links"><button type="button" className="primary" aria-describedby="mini-browser-payment-help" onClick={()=>openMiniBrowser(browserLogin)}>{m.otherPayments}</button><a href={link('/cabinet/identity',lang)}>{m.setupEmail}</a></div></section>:null}</MaintenanceProvider></main></MiniApp>:<main><MaintenanceProvider lang={lang} path={route.pathname}>{regular}</MaintenanceProvider></main>}<footer><a href={config.termsURL}>{t.termsLink}</a><a href={config.privacyURL}>{t.privacyLink}</a></footer></div>;
}
const root=createRoot(document.getElementById('root')!);
root.render(<main><p role="status">Загрузка… / Loading…</p></main>);
void loadConfig().then(()=>root.render(<BrowserRouter><App/></BrowserRouter>)).catch(()=>root.render(<main><p role="alert">Сервис не настроен. / Service is not configured.</p></main>));
