import {useEffect,useRef,useState,type ReactNode} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import * as api from './api/client';
import {config} from './config';
import {text,errorText,type Lang} from './i18n';
import {applyMiniTheme,clearMiniLaunch,endMiniSession,loadTelegram,miniSessionEnded,openMiniBrowser,optionalSDK,type TelegramApp} from './telegramSDK';

export const miniText=(lang:Lang)=>lang==='ru'?{title:'Кабинет в Telegram',browser:'Открыть кабинет в браузере',empty:'Откройте кабинет из Telegram или воспользуйтесь браузером.',sdk:'Не удалось загрузить Telegram. Попробуйте ещё раз или откройте кабинет в браузере.',ended:'Сеанс завершён. Откройте кабинет заново из Telegram.',noEmail:'Email не привязан'}:{title:'Cabinet in Telegram',browser:'Open cabinet in browser',empty:'Open the cabinet from Telegram or use your browser.',sdk:'Telegram could not load. Try again or open the cabinet in your browser.',ended:'Session ended. Reopen the cabinet from Telegram.',noEmail:'Email is not linked'};

export function MiniApp({lang,children}:{lang:Lang;children:ReactNode}){
 const t=text(lang),m=miniText(lang);const route=useLocation(),navigate=useNavigate();const[state,setState]=useState<'loading'|'consent'|'ready'|'empty'|'error'|'ended'>('loading');const[error,setError]=useState('');const[terms,setTerms]=useState(false);const[privacy,setPrivacy]=useState(false);const[busy,setBusy]=useState(false);const[retry,setRetry]=useState(0);const[app,setApp]=useState<TelegramApp>();const login=useRef<AbortController|undefined>(undefined);const raw=useRef('');
 async function signIn(signal:AbortSignal,consent=false){setBusy(true);setError('');try{await api.loginMiniApp({init_data:raw.current,...(consent?{accepted_terms_version:config.termsVersion,accepted_privacy_version:config.privacyVersion}:{})},signal);if(!signal.aborted){raw.current='';clearMiniLaunch(true);setState('ready');}}catch(reason){if(signal.aborted)return;if(reason instanceof api.ApiError&&reason.status===401){endMiniSession();return;}if(reason instanceof api.ApiError&&reason.code==='CONSENT_REQUIRED')setState('consent');else{setError(errorText(reason,lang));setState('error');}}finally{if(!signal.aborted)setBusy(false);}}
 useEffect(()=>{
  const controller=new AbortController();login.current=controller;
  const ended=()=>{controller.abort();login.current?.abort();raw.current='';api.clearSession();setState('ended');setBusy(false);};
  const hide=()=>endMiniSession('closed');window.addEventListener(miniSessionEnded,ended);window.addEventListener('pagehide',hide);
  setState('loading');void loadTelegram(controller.signal).then(sdk=>{if(controller.signal.aborted)return;setApp(sdk);optionalSDK(()=>sdk.ready?.());optionalSDK(()=>sdk.expand?.());if(typeof sdk.initData!=='string'||!sdk.initData){setState('empty');return;}raw.current=sdk.initData;void signIn(controller.signal);}).catch(()=>{if(!controller.signal.aborted){setError('');setState('error');}});
  return()=>{controller.abort();login.current?.abort();raw.current='';api.clearSession();clearMiniLaunch();window.removeEventListener(miniSessionEnded,ended);window.removeEventListener('pagehide',hide);};
 },[retry]);
 useEffect(()=>()=>clearMiniLaunch(true),[]);
 useEffect(()=>{if(!app)return;const theme=()=>applyMiniTheme(app);theme();const events=['themeChanged','viewportChanged','safeAreaChanged','contentSafeAreaChanged'];for(const event of events)optionalSDK(()=>app.onEvent?.(event,theme));return()=>{for(const event of events)optionalSDK(()=>app.offEvent?.(event,theme));};},[app]);
 useEffect(()=>{
  const click=(event:MouseEvent)=>{if(event.defaultPrevented||event.button!==0||event.ctrlKey||event.metaKey||event.altKey||event.shiftKey)return;const anchor=(event.target as Element)?.closest<HTMLAnchorElement>('a[href]');if(!anchor||anchor.hasAttribute('download'))return;const url=new URL(anchor.href);if(url.origin===location.origin&&(url.pathname==='/mini-app'||url.pathname.startsWith('/mini-app/'))){event.preventDefault();navigate(url.pathname+url.search);}else if(url.protocol==='https:'||url.origin===location.origin&&url.pathname==='/cabinet'){event.preventDefault();openMiniBrowser(url.href);}};
  document.addEventListener('click',click,true);return()=>document.removeEventListener('click',click,true);
 },[navigate]);
 useEffect(()=>{if(!app?.BackButton)return;const button=app.BackButton,home=['/mini-app','/mini-app/','/mini-app/cabinet'].includes(route.pathname);const back=()=>navigate((route.pathname.startsWith('/mini-app/orders/')?'/mini-app/cabinet/history':'/mini-app/cabinet')+(lang==='en'?'?lang=en':''));optionalSDK(()=>home||state!=='ready'?button.hide?.():button.show?.());optionalSDK(()=>button.onClick?.(back));return()=>optionalSDK(()=>button.offClick?.(back));},[app,route.pathname,lang,navigate,state]);
 if(state==='ready')return children;
 return <main><section className="card auth"><h1>{m.title}</h1>{state==='loading'?<p role="status">{t.loading}</p>:state==='consent'?<form aria-busy={busy} onSubmit={event=>{event.preventDefault();if(busy||!terms||!privacy)return;const controller=new AbortController();login.current=controller;void signIn(controller.signal,true);}}><label className="check"><input type="checkbox" checked={terms} onChange={event=>setTerms(event.target.checked)}/>{t.terms}</label><a href={config.termsURL}>{t.termsLink}</a><label className="check"><input type="checkbox" checked={privacy} onChange={event=>setPrivacy(event.target.checked)}/>{t.privacy}</label><a href={config.privacyURL}>{t.privacyLink}</a><button className="primary" disabled={busy||!terms||!privacy}>{busy?t.sending:t.continue}</button></form>:<><p role="alert">{state==='ended'?m.ended:state==='empty'?m.empty:error||m.sdk}</p>{state==='error'?<button onClick={()=>setRetry(value=>value+1)}>{t.retry}</button>:null}</>}</section></main>;
}
