import {useEffect,useRef,useState} from 'react';
import * as api from './api/client';
import {displayPrice,majorToMinor} from './catalogueMoney';
import {text,errorText,type Lang} from './i18n';

export function OperatorPurchase({clientId,lang,onForbidden,onOperationId}:{clientId:string;lang:Lang;onForbidden:()=>void;onOperationId:(id:string|null)=>void}){
 const t=text(lang);const[order,setOrder]=useState<api.PurchaseOrder|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[reason,setReason]=useState('');const[busy,setBusy]=useState(false);const[revision,setRevision]=useState(0);const key=useRef<string|undefined>(undefined);const[amount,setAmount]=useState('');const[checked,setChecked]=useState(false);const decisionAttempt=useRef<{payload:string;key:string}|undefined>(undefined);const decisionRequest=useRef<AbortController|undefined>(undefined);
 useEffect(()=>{const controller=new AbortController();setLoading(true);void api.getOperatorPurchaseOrder(clientId,controller.signal).then(result=>{if(controller.signal.aborted)return;setOrder(result.order);onOperationId(result.order?.access_operation_id??null);setError('');}).catch(failure=>{if(controller.signal.aborted)return;if(failure instanceof api.ApiError&&(failure.status===401||failure.status===403))onForbidden();else setError(errorText(failure,lang));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[clientId,revision]);
 useEffect(()=>{setReason('');setAmount('');setChecked(false);decisionAttempt.current=undefined;return()=>decisionRequest.current?.abort();},[order?.order_id,clientId]);
 async function decide(decision:'approve'|'reject'){if(!order||busy)return;const why=reason.trim();if(!why||Array.from(why).length>1000||why.includes('\0')){setError(t.reasonRequired);return;}const input:api.ManualPaymentDecisionInput={decision,reason:why};if(decision==='approve'){try{input.confirmed_amount_minor=majorToMinor(amount,'RUB');}catch{setError(t.manualAmountInvalid);return;}if(!checked||input.confirmed_amount_minor!==order.quote.amount_minor){setError(t.manualAmountInvalid);return;}}const payload=JSON.stringify({orderId:order.order_id,input});const current=decisionAttempt.current?.payload===payload?decisionAttempt.current:{payload,key:crypto.randomUUID()};decisionAttempt.current=current;const controller=new AbortController();decisionRequest.current=controller;setBusy(true);setError('');try{const result=await api.decideManualPayment(clientId,order.order_id,input,current.key,controller.signal);if(controller.signal.aborted)return;setOrder(result);onOperationId(result.access_operation_id);decisionAttempt.current=undefined;setReason('');setAmount('');setChecked(false);}catch(failure){if(controller.signal.aborted)return;if(failure instanceof api.ApiError&&(failure.status===401||failure.status===403))onForbidden();else setError(errorText(failure,lang));}finally{if(decisionRequest.current===controller){decisionRequest.current=undefined;if(!controller.signal.aborted)setBusy(false);}}}
 async function retry(){if(!order||busy)return;const why=reason.trim();if(!why||Array.from(why).length>1000||why.includes('\0')){setError(t.reasonRequired);return;}const current=key.current??crypto.randomUUID();key.current=current;setBusy(true);setError('');try{const result=await api.reconcilePurchaseOrder(clientId,order.order_id,{reason:why},current);setOrder(result);onOperationId(result.access_operation_id);key.current=undefined;setReason('');}catch(failure){if(failure instanceof api.ApiError&&(failure.status===401||failure.status===403))onForbidden();else setError(errorText(failure,lang));}finally{setBusy(false);}}
 if(loading)return <section className="admin-action" aria-label={t.paymentHistoryPending}><h2>{t.paymentHistoryPending}</h2><p role="status">{t.loading}</p></section>;
 if(!order&&!error)return null;
 return <section className="admin-action operator-purchase" aria-label={t.paymentHistoryPending}><h2>{t.paymentHistoryPending}</h2>{error?<p role="alert" className="error">{error}</p>:null}{order?<><p>{t.orderId}: {order.order_id}</p><p>{t.orderPrice}: {displayPrice(order.quote.amount_minor,'RUB',lang)}</p><p className={order.review_required?'warning':'notice'} role="status">{order.manual_payment?.state==='rejected'?t.manualRejected:order.manual_payment?.state==='pending'&&!order.review_required?t.manualWaiting:order.payment_status==='paid'?order.fulfillment_status==='applied'?t.orderApplied:t.orderPaid:order.payment_status==='canceled'?t.orderCanceled:order.expired?t.orderExpired:t.orderPending}</p>{order.review_required?<p className="warning">{t.orderReview}</p>:null}{order.access_operation_id?<p><a href="#access-operations">{t.accessOperations}: {order.access_operation_id}</a></p>:null}{order.manual_payment?<><p className="manual-instructions">{order.manual_payment.instructions}</p>{order.manual_payment.reason?<p>{t.reason}: {order.manual_payment.reason}</p>:null}</>:null}{order.manual_payment?.state==='pending'&&order.payment_status==='pending'&&!order.review_required?<fieldset className="manual-decision" disabled={busy} aria-busy={busy}><legend>{t.manualPayment}</legend><label>{t.manualAmount}<input inputMode="decimal" value={amount} onChange={event=>{setAmount(event.target.value);setError('');decisionAttempt.current=undefined;}}/></label><label className="check"><input type="checkbox" checked={checked} onChange={event=>{setChecked(event.target.checked);setError('');decisionAttempt.current=undefined;}}/>{t.manualChecked}</label><label>{t.manualReason}<textarea value={reason} onChange={event=>{setReason(event.target.value);setError('');decisionAttempt.current=undefined;}}/></label><button className="primary" onClick={()=>void decide('approve')}>{busy?t.sending:t.manualApprove}</button><button onClick={()=>void decide('reject')}>{t.manualReject}</button></fieldset>:null}{order.payment_status==='paid'&&order.fulfillment_status==='needs_review'&&!order.access_operation_id?<><p className="help">{t.preparationOnly}</p><label>{t.preparationReason}<textarea value={reason} disabled={busy} onChange={event=>{setReason(event.target.value);setError('');key.current=undefined;}} aria-invalid={!!error}/></label><button disabled={busy} onClick={()=>void retry()}>{busy?t.sending:t.retryPreparation}</button></>:null}<button disabled={busy} onClick={()=>setRevision(value=>value+1)}>{t.orderRefresh}</button></>:null}</section>;
}
