import {useEffect,useId,useRef,useState,type FormEvent} from 'react';
import * as api from './api/client';
import {OperatorPurchase} from './OperatorPurchase';
import {displayPrice} from './catalogueMoney';
import {text,errorText,type Lang} from './i18n';

export function PaymentCase({clientId,orderId,receiptId,lang,onDenied,onChanged,onClose}:{clientId:string;orderId:string;receiptId?:string;lang:Lang;onDenied:()=>void;onChanged:()=>void;onClose:()=>void}){
 const t=text(lang),id=useId();const[data,setData]=useState<api.PaymentCase>();const[saved,setSaved]=useState<api.PaymentRefund>();const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[reference,setReference]=useState('');const[reason,setReason]=useState('');const[amount,setAmount]=useState('');const[full,setFull]=useState(false);const[keep,setKeep]=useState(false);const[revision,setRevision]=useState(0);const[conflict,setConflict]=useState(false);
 const read=useRef<AbortController|undefined>(undefined),write=useRef<AbortController|undefined>(undefined),attempt=useRef<{payload:string;key:string}|undefined>(undefined),heading=useRef<HTMLHeadingElement>(null),errorNode=useRef<HTMLParagraphElement>(null);
 const receipt=data?.receipt;const refund=data?.refund??(saved?.receipt_operation_id===receipt?.operation_id?saved:undefined);const isCrypto=receipt?.payment_method==='cryptomus'||receipt?.payment_method==='heleket';
 async function load(){read.current?.abort();const c=new AbortController();read.current=c;setLoading(true);setError('');try{const out=await api.getOperatorPaymentCase(clientId,orderId,receiptId,c.signal);if(c.signal.aborted||read.current!==c)return;if(out.order?.order_id!==orderId||typeof out.can_confirm_refund!=='boolean'||typeof out.financial_review_open!=='boolean'||out.receipt&&(out.receipt.order_id!==orderId||receiptId&&out.receipt.operation_id!==receiptId)||out.refund&&(out.refund.order_id!==orderId||out.refund.receipt_operation_id!==out.receipt?.operation_id||out.refund.source!=='operator'))throw new api.ApiError(503,'SERVICE_UNAVAILABLE','');if(out.receipt?.operation_id!==data?.receipt?.operation_id){setReference('');setReason('');setAmount('');setFull(false);setKeep(false);setSaved(undefined);attempt.current=undefined;}setData(out);setConflict(false);setRevision(value=>value+1);}catch(failure){if(c.signal.aborted)return;if(failure instanceof api.ApiError&&(failure.status===401||failure.status===403&&failure.code!=='OPERATOR_ACCOUNT_PROTECTED')){setData(undefined);setSaved(undefined);onDenied();}else{if(failure instanceof api.ApiError&&failure.status===404)setData(undefined);setError(errorText(failure,lang));}}finally{if(read.current===c&&!c.signal.aborted)setLoading(false);}}
 useEffect(()=>{heading.current?.focus();void load();return()=>{read.current?.abort();write.current?.abort();};},[clientId,orderId,receiptId,lang]);
 useEffect(()=>{if(error)errorNode.current?.focus();},[error]);
 function change(){attempt.current=undefined;setError('');}
 async function submit(event:FormEvent){event.preventDefault();if(!receipt||!data?.can_confirm_refund||refund||busy||loading||conflict||!full||!keep)return;const why=reason.trim();if(!/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(reference)||!why||Array.from(why).length>1000||why.includes('\0')||isCrypto&&!/^[0-9]{1,40}(\.[0-9]{1,40})?$/.test(amount)){setError(t.invalid);return;}const input:api.PurchaseRefundInput={receipt_operation_id:receipt.operation_id,reference,reason:why,confirm_full:true,keep_access:true,...(isCrypto?{returned_amount:amount}:{})};const payload=JSON.stringify({clientId,orderId,input});const current=attempt.current?.payload===payload?attempt.current:{payload,key:crypto.randomUUID()};attempt.current=current;const c=new AbortController();write.current=c;setBusy(true);setError('');try{const out=await api.confirmPurchaseRefund(clientId,orderId,input,current.key,c.signal);if(c.signal.aborted||write.current!==c)return;if(out.order_id!==orderId||out.receipt_operation_id!==receipt.operation_id||out.source!=='operator')throw new api.ApiError(503,'SERVICE_UNAVAILABLE','');setSaved(out);attempt.current=undefined;setFull(false);setKeep(false);onChanged();await load();}catch(failure){if(c.signal.aborted)return;if(failure instanceof api.ApiError&&(failure.status===401||failure.status===403&&failure.code!=='OPERATOR_ACCOUNT_PROTECTED')){setData(undefined);setSaved(undefined);onDenied();}else{const stale=failure instanceof api.ApiError&&failure.status===409&&failure.code!=='ACCOUNT_ACCESS_BUSY';setConflict(stale);setError(stale?t.refundConflict:failure instanceof api.ApiError&&failure.code==='OPERATOR_ACCOUNT_PROTECTED'?t.refundProtected:errorText(failure,lang));}}finally{if(write.current===c&&!c.signal.aborted){write.current=undefined;setBusy(false);}}}
 return <section className="admin-action payment-case" aria-labelledby={id+'-title'} aria-busy={loading||busy} onKeyDown={event=>{if(event.key==='Escape'){event.stopPropagation();onClose();}}}>
  <h3 id={id+'-title'} ref={heading} tabIndex={-1}>{t.caseTitle}</h3><p className="help">{t.refundHelp}</p>
  {loading?<p role="status">{t.loading}</p>:null}{error?<p className="error" role="alert" tabIndex={-1} ref={errorNode}>{error}</p>:null}
  {data?<><p>{data.financial_review_open?t.caseReviewOpen:t.caseReviewClosed}</p>{receipt?<dl className="stats-grid"><div><dt>{t.historyReceiptID}</dt><dd><code>{receipt.operation_id}</code></dd></div><div><dt>{t.historyGross}</dt><dd>{receipt.currency?displayPrice(receipt.gross_minor,receipt.currency,lang):receipt.gross_minor+' '+t.historyMinorUnits}</dd></div><div><dt>{t.historyNet}</dt><dd>{receipt.net_minor===null?t.unknown:receipt.currency?displayPrice(receipt.net_minor,receipt.currency,lang):receipt.net_minor+' '+t.historyMinorUnits}</dd></div><div><dt>{t.source}</dt><dd>{receipt.source==='operator'?t.historyOperator:t.historyProvider}</dd></div><div><dt>{t.historyFundsOrder}</dt><dd>{receipt.funds_order?t.historyYes:t.historyNo}</dd></div>{receipt.crypto_amounts?<><div><dt>{t.historyCryptoPayment}</dt><dd>{receipt.crypto_amounts.payment_amount+' '+receipt.crypto_amounts.payer_currency}</dd></div><div><dt>{t.historyCryptoPayer}</dt><dd>{receipt.crypto_amounts.payer_amount+' '+receipt.crypto_amounts.payer_currency}</dd></div></>:null}{receipt.review_reason?<div><dt>{t.historyReviewReason}</dt><dd>{receipt.review_reason}</dd></div>:null}</dl>:<p>{t.historyEmpty}</p>}
   {refund?<div className="notice"><p role="status">{t.refundRecorded}</p><p>{t.refundAmount}: {refund.returned_amount+' '+refund.returned_currency}</p><p>{t.source}: {t.historyOperator}</p><p>{t.refundReference}: {refund.reference}</p><p>{t.reason}: {refund.reason}</p></div>:null}
   {receipt&&data.can_confirm_refund&&!refund?<form onSubmit={event=>void submit(event)} aria-busy={busy}><fieldset disabled={busy||loading||conflict}><legend>{t.refundConfirm}</legend><label>{t.refundReference}<input required maxLength={128} pattern={"[A-Za-z0-9][A-Za-z0-9._\\-]{0,127}"} autoComplete="off" value={reference} onChange={event=>{setReference(event.target.value);change();}}/></label>{isCrypto?<label>{t.refundAmount} ({receipt.crypto_amounts?.payer_currency})<input required inputMode="decimal" maxLength={81} pattern="[0-9]{1,40}(\.[0-9]{1,40})?" value={amount} onChange={event=>{setAmount(event.target.value);change();}}/></label>:null}<label htmlFor={id+'-reason'}>{t.reason}</label><textarea id={id+'-reason'} required maxLength={1000} value={reason} onChange={event=>{setReason(event.target.value);change();}}/><label className="check"><input type="checkbox" checked={full} onChange={event=>{setFull(event.target.checked);change();}}/>{t.refundFullConsent}</label><label className="check"><input type="checkbox" checked={keep} onChange={event=>{setKeep(event.target.checked);change();}}/>{t.refundAccessConsent}</label><button className="primary" type="submit" disabled={!full||!keep}>{busy?t.sending:t.refundConfirm}</button></fieldset></form>:null}
   <OperatorPurchase key={revision} clientId={clientId} orderId={orderId} lang={lang} onForbidden={onDenied} onChanged={()=>{onChanged();void load();}}/>
  </>:null}<button disabled={loading||busy} onClick={()=>void load()}>{t.caseRefresh}</button><button onClick={onClose}>{t.caseClose}</button>
 </section>;
}
