import {useEffect,useRef,useState} from 'react';
import * as api from './api/client';
import {text,loginRedirect,errorText,type Lang} from './i18n';
import {useMaintenance} from './Maintenance';

export function StarsSubscription({lang,refreshKey}:{lang:Lang;refreshKey?:string|number}){
 const maintenance=useMaintenance();
 const t=text(lang);const[value,setValue]=useState<api.StarsSubscription>();const[error,setError]=useState('');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[revision,setRevision]=useState(0);const[confirmation,setConfirmation]=useState<'cancel'|'resume'>();
 const request=useRef<AbortController|null>(null),heading=useRef<HTMLHeadingElement>(null),cancelButton=useRef<HTMLButtonElement>(null),resumeButton=useRef<HTMLButtonElement>(null);const attempt=useRef<{action:'cancel'|'resume';key:string}|null>(null);
 const states={none:'',unknown:t.starsStatusUnknown,legacy_unknown:t.starsStatusUnknown,active:t.starsActive,canceled:t.starsCanceled,failed:t.starsFailed,user_canceled:t.starsUserCanceled,resume_allowed:t.starsResumeAllowed,cancel_pending:t.starsCancelPending,cancel_uncertain:t.starsCancelUncertain,cancel_rejected:t.starsCancelRejected,resume_pending:t.starsResumePending,resume_uncertain:t.starsResumeUncertain,resume_rejected:t.starsResumeRejected};
 const phases={none:t.unknown,current:t.starsCurrent,grace:t.starsGrace,lapsed:t.starsLapsed};
 function checked(result:api.StarsSubscription){if(!result||!Object.hasOwn(states,result.state)||!Object.hasOwn(phases,result.period_phase)||['can_cancel','can_resume','external_billing_blocked','needs_review'].some(key=>typeof result[key as keyof api.StarsSubscription]!=='boolean')||result.paid_until!==null&&!Number.isFinite(Date.parse(result.paid_until)))throw new api.ApiError(503,'SERVICE_UNAVAILABLE','');return result;}
 useEffect(()=>{const controller=new AbortController();request.current=controller;setLoading(true);setError('');setBusy(false);void api.starsSubscription(controller.signal).then(result=>{if(!controller.signal.aborted)setValue(checked(result));}).catch(reason=>{if(controller.signal.aborted)return;setValue(undefined);setError(errorText(reason,lang));if(reason instanceof api.ApiError&&reason.status===401)loginRedirect(lang);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[lang,revision,refreshKey]);
 function begin(action:'cancel'|'resume'){if(busy||(action==='resume'&&maintenance.status?.enabled&&attempt.current?.action!=='resume'))return;if(attempt.current?.action!==action)attempt.current=null;setConfirmation(action);setError('');}
 function close(){const action=confirmation;setConfirmation(undefined);(action==='cancel'?cancelButton:resumeButton).current?.focus();}
 async function control(){const controller=request.current;if(!confirmation||busy||!controller||controller.signal.aborted||(confirmation==='resume'&&maintenance.status?.enabled&&attempt.current?.action!=='resume'))return;const pending=attempt.current??{action:confirmation,key:crypto.randomUUID()};attempt.current=pending;setBusy(true);setError('');try{await api.getSessionContext(controller.signal);const result=checked(await api.controlStarsSubscription(pending.action,pending.key,controller.signal));if(controller.signal.aborted)return;setValue(result);setConfirmation(undefined);attempt.current=null;heading.current?.focus();}catch(reason){if(controller.signal.aborted)return;if(reason instanceof api.ApiError&&[401,403,404].includes(reason.status)){setValue(undefined);setConfirmation(undefined);}setError(errorText(reason,lang));if(reason instanceof api.ApiError&&reason.code==='MAINTENANCE')maintenance.refresh();if(reason instanceof api.ApiError&&reason.status===401)loginRedirect(lang);}finally{if(!controller.signal.aborted)setBusy(false);}}
 if(!loading&&!error&&value?.state==='none')return null;
 return <section className="admin-action" aria-label={t.starsAutoRenewal} aria-busy={loading||busy}><h2 tabIndex={-1} ref={heading}>{t.starsAutoRenewal}</h2>{loading?<p role="status">{t.loading}</p>:null}{error?<div className="error" role="alert"><p>{error}</p><button disabled={busy} onClick={()=>setRevision(n=>n+1)}>{t.retry}</button></div>:null}
  {value&&!loading?<><p className="notice" role="status" aria-live="polite">{states[value.state]}</p><dl><div><dt>{t.starsPaidUntil}</dt><dd>{value.paid_until?new Date(value.paid_until).toLocaleString(lang==='ru'?'ru-RU':'en-US'):t.unknown}</dd></div><div><dt>{t.starsPeriodPhase}</dt><dd>{phases[value.period_phase]}</dd></div></dl>{value.external_billing_blocked?<p className="help">{t.starsBillingBlocked}</p>:null}{value.needs_review?<p className="warning">{t.orderReview}</p>:null}<div className="purchase-actions">{value.can_cancel?<button ref={cancelButton} disabled={busy} onClick={()=>begin('cancel')}>{t.starsCancel}</button>:null}{value.can_resume?<button ref={resumeButton} disabled={busy||(maintenance.status?.enabled&&attempt.current?.action!=='resume')} onClick={()=>begin('resume')}>{t.starsResume}</button>:null}<button disabled={busy} onClick={()=>setRevision(n=>n+1)}>{t.starsRefresh}</button></div></>:null}
  {confirmation?<div className="warning"><p>{confirmation==='cancel'?t.starsCancelHelp:t.starsResumeHelp}</p><button autoFocus className="primary" disabled={busy||(confirmation==='resume'&&maintenance.status?.enabled&&attempt.current?.action!=='resume')} onClick={()=>void control()}>{busy?t.sending:confirmation==='cancel'?t.starsConfirmCancel:t.starsConfirmResume}</button><button disabled={busy} onClick={close}>{t.starsCloseConfirmation}</button></div>:null}
 </section>;
}
