import {useEffect,useRef,useState,type FormEvent} from 'react';
import * as api from './api/client';
import {text,link,errorText,type Lang} from './i18n';

const maxFile=10*1024*1024;
export function mergeSupportMessages(...groups:api.SupportMessage[][]){const bySequence=new Map<number,api.SupportMessage>();for(const group of groups)for(const message of group)bySequence.set(message.sequence,message);return [...bySequence.values()].sort((a,b)=>a.sequence-b.sequence);}
export type SupportAdapter={load:(signal?:AbortSignal)=>Promise<api.SupportResult>;history:(before:number,signal?:AbortSignal)=>Promise<api.SupportResult>;send:(text:string,file:File|undefined,key:string,signal?:AbortSignal)=>Promise<api.SupportMessage>;read:(sequence:number,signal?:AbortSignal)=>Promise<void>;state:(status:'open'|'closed',signal?:AbortSignal)=>Promise<void>;attachment:(id:string)=>string;ban?:(banned:boolean,reason:string,signal?:AbortSignal)=>Promise<void>};

export function SupportThread({lang,adapter,viewer,onForbidden}:{lang:Lang;adapter:SupportAdapter;viewer:'customer'|'operator';onForbidden?:()=>void}){
 const t=text(lang);const[conversation,setConversation]=useState<api.SupportConversation|null>(null);const[messages,setMessages]=useState<api.SupportMessage[]>([]);const[hasMore,setHasMore]=useState(false);const[oldest,setOldest]=useState<number|null>(null);const[draft,setDraft]=useState('');const[file,setFile]=useState<File>();const[attempt,setAttempt]=useState<{key:string;text:string;file?:File}>();const[banReason,setBanReason]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[ready,setReady]=useState(false);const poll=useRef<AbortController|undefined>(undefined);const mutation=useRef<AbortController|undefined>(undefined);const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);const fileInput=useRef<HTMLInputElement>(null);const exhausted=useRef(false);
 const handle=(reason:unknown)=>{if(reason instanceof api.ApiError&&(reason.status===401||reason.status===403)){onForbidden?.();return;}setError(errorText(reason,lang));};
 useEffect(()=>{let active=true,inFlight=false;const visible=()=>document.visibilityState!=='hidden';const stop=()=>{if(timer.current)clearTimeout(timer.current);timer.current=undefined;poll.current?.abort();poll.current=undefined;};const refresh=async()=>{if(!active||inFlight||!visible())return;inFlight=true;const current=new AbortController();poll.current=current;try{const result=await adapter.load(current.signal);if(!active||current.signal.aborted)return;setConversation(result.conversation);setMessages(previous=>mergeSupportMessages(previous,result.messages));setHasMore(!exhausted.current&&result.has_more);setOldest(previous=>previous===null?result.oldest_sequence:result.oldest_sequence===null?previous:Math.min(previous,result.oldest_sequence));setError('');setReady(true);}catch(reason){if(!current.signal.aborted){handle(reason);setReady(true);}}finally{inFlight=false;if(poll.current===current)poll.current=undefined;if(active&&visible())timer.current=setTimeout(refresh,5000);}};const visibility=()=>{if(visible())void refresh();else stop();};document.addEventListener('visibilitychange',visibility);void refresh();return()=>{active=false;document.removeEventListener('visibilitychange',visibility);stop();mutation.current?.abort();};},[adapter,lang]);
 useEffect(()=>{const sender=viewer==='customer'?'operator':'customer';const received=messages.filter(message=>message.sender===sender);if(!conversation||received.length===0)return;const highest=Math.max(...received.map(message=>message.sequence));const current=viewer==='customer'?conversation.customer_received_sequence:conversation.operator_received_sequence;if(highest<=current)return;const controller=new AbortController();void adapter.read(highest,controller.signal).then(()=>setConversation(value=>value?viewer==='customer'?{...value,customer_received_sequence:Math.max(value.customer_received_sequence,highest)}:{...value,operator_received_sequence:Math.max(value.operator_received_sequence,highest)}:value)).catch(reason=>{if(!controller.signal.aborted)handle(reason);});return()=>controller.abort();},[adapter,messages,viewer,conversation?.id,conversation?.customer_received_sequence,conversation?.operator_received_sequence]);
 const changeDraft=(value:string)=>{setDraft(value);setAttempt(undefined);setError('');};const changeFile=(value:File|undefined)=>{setFile(value);setAttempt(undefined);setError('');};
 async function run<T>(operation:(signal:AbortSignal)=>Promise<T>,success:(value:T)=>void){if(busy)return;const controller=new AbortController();mutation.current=controller;setBusy(true);setError('');try{const value=await operation(controller.signal);if(!controller.signal.aborted)success(value);}catch(reason){if(!controller.signal.aborted)handle(reason);}finally{if(mutation.current===controller)mutation.current=undefined;setBusy(false);}}
 function send(event:FormEvent){event.preventDefault();if(Array.from(draft).length>4000){setError(t.supportTextTooLong);return;}if(file&&file.size>maxFile){setError(t.supportFileTooLarge);return;}if(!draft.trim()&&(!file||file.size===0)){setError(t.supportMessageRequired);return;}const current=attempt??{key:crypto.randomUUID(),text:draft,file};setAttempt(current);void run(signal=>adapter.send(current.text,current.file,current.key,signal),created=>{setMessages(previous=>mergeSupportMessages(previous,[created]));setConversation(value=>value?{...value,status:'open'}:value);setDraft('');setFile(undefined);setAttempt(undefined);if(fileInput.current)fileInput.current.value='';});}
 const changeState=(status:'open'|'closed')=>void run(signal=>adapter.state(status,signal),()=>setConversation(value=>value?{...value,status}:value));
 const loadOlder=()=>{if(oldest===null)return;void run(signal=>adapter.history(oldest,signal),result=>{setMessages(previous=>mergeSupportMessages(result.messages,previous));setConversation(result.conversation);setOldest(result.oldest_sequence);setHasMore(result.has_more);if(!result.has_more)exhausted.current=true;});};
 const changeBan=()=>{if(!adapter.ban)return;if(!banReason.trim()||Array.from(banReason).length>1000){setError(t.reasonRequired);return;}const banned=!conversation?.support_banned;void run(signal=>adapter.ban!(banned,banReason,signal),()=>{setConversation(value=>value?{...value,support_banned:banned}:value);setBanReason('');});};
 const date=(value:string)=>new Date(value).toLocaleString(lang==='ru'?'ru-RU':'en-US');const size=(value:number)=>value<1024?value+' B':new Intl.NumberFormat(lang,{maximumFractionDigits:1}).format(value/1024)+' KiB';const closed=conversation?.status==='closed';const blocked=viewer==='customer'&&conversation?.support_banned;const prefix=viewer==='operator'?'operator-':'support-';
 return <div className="support-thread">{error?<p className="error" role="alert">{error}</p>:null}{blocked?<p className="warning" role="alert">{t.supportBlocked}</p>:null}{!ready?<p role="status">{t.loading}</p>:null}{hasMore?<button onClick={loadOlder} disabled={busy}>{t.loadOlder}</button>:null}{ready&&messages.length===0?<p className="notice">{t.noSupportMessages}</p>:<ol className="support-list" aria-label={t.supportHistory}>{messages.map(message=><li key={message.id} data-sequence={message.sequence} className={'support-message '+message.sender}><div className="message-meta"><strong>{message.sender===viewer?t.you:viewer==='operator'?t.customer:t.supportAgent}</strong><time dateTime={message.created_at}>{date(message.created_at)}</time></div>{message.text?<p>{message.text}</p>:null}{message.attachment?<a className="attachment" href={adapter.attachment(message.id)} download={message.attachment.name}>{t.downloadAttachment.replace('{name}',message.attachment.name)} · {size(message.attachment.size_bytes)}</a>:null}<p className="delivery">{message.delivery==='stored'?t.storedSupport:t.deliveredCabinet}</p></li>)}</ol>}
  {conversation?<div className="support-state"><p role="status">{closed?t.conversationClosed:t.conversationOpen}</p>{closed?!blocked?<button onClick={()=>changeState('open')} disabled={busy}>{t.reopenConversation}</button>:null:<button onClick={()=>changeState('closed')} disabled={busy}>{t.closeConversation}</button>}</div>:null}
  {!blocked?<form className="support-form" onSubmit={send} aria-busy={busy}><label htmlFor={prefix+'message'}>{viewer==='operator'?t.operatorSupportReply:t.supportMessage}<textarea id={prefix+'message'} rows={5} value={draft} onChange={event=>changeDraft(event.target.value)} aria-describedby={prefix+'message-help'}/></label><p id={prefix+'message-help'} className="help">{t.supportMessageHelp}</p><label htmlFor={prefix+'file'}>{viewer==='operator'?t.operatorSupportFile:t.supportFile}<input ref={fileInput} id={prefix+'file'} type="file" onChange={event=>changeFile(event.target.files?.[0])}/></label><p className="help">{t.supportFileHelp}</p><button className="primary" disabled={busy}>{busy?t.sending:viewer==='operator'?t.sendOperatorReply:closed?t.reopenSend:t.sendSupport}</button></form>:null}
  {viewer==='operator'&&adapter.ban&&conversation?<div className="support-ban"><label htmlFor="support-ban-reason">{t.supportBanReason}<textarea id="support-ban-reason" rows={2} value={banReason} onChange={event=>{setBanReason(event.target.value);setError('');}}/></label><button onClick={changeBan} disabled={busy}>{conversation.support_banned?t.unblockSupport:t.blockSupport}</button></div>:null}</div>;
}

const customerAdapter:SupportAdapter={load:api.getSupport,history:api.getSupportHistory,send:api.createSupportMessage,read:api.acknowledgeSupport,state:api.setSupportState,attachment:api.supportAttachmentURL};
export function Support({lang}:{lang:Lang}){const t=text(lang);const[sessionReady,setSessionReady]=useState(false);const[loggingOut,setLoggingOut]=useState(false);const[error,setError]=useState('');useEffect(()=>{const controller=new AbortController();void api.getAccount(controller.signal).then(()=>setSessionReady(true)).catch(reason=>{if(controller.signal.aborted)return;if(reason instanceof api.ApiError&&reason.status===401)location.replace(link('/login',lang));else setError(errorText(reason,lang));});return()=>controller.abort();},[lang]);async function logout(){setLoggingOut(true);try{await api.logoutAccount();location.replace(link('/login',lang));}catch(reason){setError(errorText(reason,lang));setLoggingOut(false);}}return <section className="card support-view"><div className="cabinet-head"><div><p className="eyebrow">{t.cabinet}</p><h1>{t.supportMessages}</h1></div><button onClick={logout} disabled={!sessionReady||loggingOut}>{t.logout}</button></div><nav className="account-links" aria-label={t.accountNavigation}><a href={link('/cabinet',lang)}>{t.backAccount}</a><a href={link('/cabinet/security',lang)}>{t.security}</a></nav><p>{t.supportIntro}</p>{error?<p className="error" role="alert">{error}</p>:null}{!sessionReady&&!error?<p role="status">{t.loading}</p>:null}{sessionReady&&!loggingOut?<SupportThread lang={lang} adapter={customerAdapter} viewer="customer" onForbidden={()=>setError(t.restricted)}/>:null}</section>;}
