import {useEffect,useRef,useState,type FormEvent} from 'react';
import * as api from './api/client';
import {isMiniApp} from './telegramSDK';
import {text,link,loginRedirect,errorText,type Lang} from './i18n';

const maxFile=10*1024*1024;
export function mergeSupportMessages(...groups:api.SupportMessage[][]){const bySequence=new Map<number,api.SupportMessage>();for(const group of groups)for(const message of group)bySequence.set(message.sequence,message);return [...bySequence.values()].sort((a,b)=>a.sequence-b.sequence);}
export type SupportAdapter={load:(signal?:AbortSignal)=>Promise<api.SupportResult>;history:(before:number,signal?:AbortSignal)=>Promise<api.SupportResult>;send:(text:string,file:File|undefined,key:string,signal?:AbortSignal)=>Promise<api.SupportMessage>;read:(sequence:number,signal?:AbortSignal)=>Promise<void>;state:(status:'open'|'closed',signal?:AbortSignal)=>Promise<void>;attachment:(id:string)=>string;download?:(id:string,signal?:AbortSignal)=>Promise<Blob>;ban?:(banned:boolean,reason:string,signal?:AbortSignal)=>Promise<void>;retry?:(delivery:string,reason:string,key:string,signal?:AbortSignal)=>Promise<api.SupportTelegramDelivery>};

export function SupportThread({lang,adapter,viewer,onForbidden}:{lang:Lang;adapter:SupportAdapter;viewer:'customer'|'operator';onForbidden?:()=>void}){
 const t=text(lang);const[conversation,setConversation]=useState<api.SupportConversation|null>(null);const[history,setHistory]=useState<{messages:api.SupportMessage[];loaded:Set<number>;oldest:number|null;hasMore:boolean}>({messages:[],loaded:new Set(),oldest:null,hasMore:false});const{messages,oldest,hasMore}=history;const[draft,setDraft]=useState('');const[file,setFile]=useState<File>();const[attempt,setAttempt]=useState<{key:string;text:string;file?:File}>();const[banReason,setBanReason]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[ready,setReady]=useState(false);const poll=useRef<AbortController|undefined>(undefined);const mutation=useRef<AbortController|undefined>(undefined);const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);const fileInput=useRef<HTMLInputElement>(null);
 const[retry,setRetry]=useState<{message:string;delivery:string;reason:string;confirmed:boolean;key?:string}>();const retryTrigger=useRef<HTMLButtonElement|null>(null);
 const handle=(reason:unknown)=>{if(reason instanceof api.ApiError&&(reason.status===401||reason.status===403)){onForbidden?.();return;}setError(errorText(reason,lang));};
 useEffect(()=>{let active=true,inFlight=false;const visible=()=>document.visibilityState!=='hidden';const stop=()=>{if(timer.current)clearTimeout(timer.current);timer.current=undefined;poll.current?.abort();poll.current=undefined;};const refresh=async()=>{if(!active||inFlight||!visible())return;inFlight=true;const current=new AbortController();poll.current=current;try{const result=await adapter.load(current.signal);if(!active||current.signal.aborted)return;setConversation(result.conversation);setHistory(previous=>{const overlap=result.messages.some(message=>previous.loaded.has(message.sequence));const gap=previous.loaded.size>0&&result.messages.length>0&&!overlap&&result.has_more;return {messages:mergeSupportMessages(previous.messages,result.messages),loaded:new Set([...previous.loaded,...result.messages.map(message=>message.sequence)]),oldest:gap||previous.oldest===null?result.oldest_sequence:previous.oldest,hasMore:gap||previous.oldest===null?result.has_more:previous.hasMore};});setError('');setReady(true);}catch(reason){if(!current.signal.aborted){handle(reason);setReady(true);}}finally{inFlight=false;if(poll.current===current)poll.current=undefined;if(active&&visible())timer.current=setTimeout(refresh,5000);}};const visibility=()=>{if(visible())void refresh();else stop();};document.addEventListener('visibilitychange',visibility);void refresh();return()=>{active=false;document.removeEventListener('visibilitychange',visibility);stop();mutation.current?.abort();};},[adapter,lang]);
 useEffect(()=>{const sender=viewer==='customer'?'operator':'customer';const received=messages.filter(message=>message.sender===sender);if(!conversation||received.length===0)return;const highest=Math.max(...received.map(message=>message.sequence));const current=viewer==='customer'?conversation.customer_received_sequence:conversation.operator_received_sequence;if(highest<=current)return;const controller=new AbortController();void adapter.read(highest,controller.signal).then(()=>setConversation(value=>value?viewer==='customer'?{...value,customer_received_sequence:Math.max(value.customer_received_sequence,highest)}:{...value,operator_received_sequence:Math.max(value.operator_received_sequence,highest)}:value)).catch(reason=>{if(!controller.signal.aborted)handle(reason);});return()=>controller.abort();},[adapter,messages,viewer,conversation?.id,conversation?.customer_received_sequence,conversation?.operator_received_sequence]);
 const download=(message:api.SupportMessage)=>void run(signal=>adapter.download!(message.id,signal),blob=>{const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=message.attachment!.name;anchor.click();URL.revokeObjectURL(url);});
 const changeDraft=(value:string)=>{setDraft(value);setAttempt(undefined);setError('');};const changeFile=(value:File|undefined)=>{setFile(value);setAttempt(undefined);setError('');};
 async function run<T>(operation:(signal:AbortSignal)=>Promise<T>,success:(value:T)=>void){if(busy)return;const controller=new AbortController();mutation.current=controller;setBusy(true);setError('');try{const value=await operation(controller.signal);if(!controller.signal.aborted)success(value);}catch(reason){if(!controller.signal.aborted)handle(reason);}finally{if(mutation.current===controller)mutation.current=undefined;setBusy(false);}}
 function send(event:FormEvent){event.preventDefault();if(Array.from(draft).length>4000){setError(t.supportTextTooLong);return;}if(file&&file.size>maxFile){setError(t.supportFileTooLarge);return;}if(!draft.trim()&&(!file||file.size===0)){setError(t.supportMessageRequired);return;}const current=attempt??{key:crypto.randomUUID(),text:draft,file};setAttempt(current);void run(signal=>adapter.send(current.text,current.file,current.key,signal),created=>{setHistory(previous=>({...previous,messages:mergeSupportMessages(previous.messages,[created])}));setConversation(value=>value?{...value,status:'open'}:value);setDraft('');setFile(undefined);setAttempt(undefined);if(fileInput.current)fileInput.current.value='';});}
 function retryDelivery(event:FormEvent){
  event.preventDefault();if(!retry||!adapter.retry)return;
  if(!retry.confirmed||!retry.reason.trim()||Array.from(retry.reason).length>1000){setError(t.telegramRetryRequired);return;}
  const currentMessage=messages.find(message=>message.id===retry.message);
  if(currentMessage?.telegram_delivery?.id!==retry.delivery||!currentMessage.telegram_delivery.retry_capability){setRetry(undefined);setError(t.telegramRetryChanged);return;}
  const current={...retry,key:retry.key??crypto.randomUUID()};setRetry(current);
  void run(signal=>adapter.retry!(current.delivery,current.reason,current.key,signal),delivery=>{
   setHistory(previous=>({...previous,messages:previous.messages.map(message=>message.id===current.message?{...message,telegram_delivery:delivery}:message)}));setRetry(undefined);
   document.getElementById('support-message-'+current.message)?.focus();
  });
 }
 function telegramDelivery(message:api.SupportMessage){
  const delivery=message.telegram_delivery;if(!delivery)return null;
  const label={queued:t.telegramQueued,sending:t.telegramSending,sent:t.telegramSent,failed:t.telegramFailed,unknown:t.telegramUnknown,skipped:t.telegramSkipped}[delivery.status];
  const current=retry?.message===message.id?retry:undefined;const warning='telegram-retry-warning-'+message.id;const reason='telegram-retry-reason-'+message.id;const confirmation='telegram-retry-confirmation-'+message.id;
  return <div className="telegram-delivery" role="group" aria-label={t.telegramDelivery}><p role="status">{label}</p>{delivery.media_availability==='telegram_only'?<p>{t.telegramOnlyMedia}</p>:null}
   {viewer==='operator'&&adapter.retry&&delivery.retry_capability?<button type="button" disabled={busy} onClick={event=>{retryTrigger.current=event.currentTarget;setRetry({message:message.id,delivery:delivery.id,reason:'',confirmed:false});setError('');}}>{t.telegramRetry}</button>:null}
   {current?<form onSubmit={retryDelivery} aria-describedby={warning} aria-busy={busy}>
    <p id={warning} className="warning">{t.telegramRetryWarning}</p>
    <label htmlFor={reason}>{t.telegramRetryReason}</label><textarea id={reason} rows={2} required autoFocus disabled={busy} value={current.reason} onChange={event=>{const value=event.target.value;setRetry(previous=>previous?{...previous,reason:value,key:undefined}:previous);setError('');}}/>
    <label htmlFor={confirmation}><input id={confirmation} type="checkbox" required disabled={busy} aria-describedby={warning} checked={current.confirmed} onChange={event=>{const checked=event.target.checked;setRetry(previous=>previous?{...previous,confirmed:checked}:previous);}}/>{t.telegramRetryCheck}</label>
    <button type="submit" disabled={busy}>{t.telegramRetryConfirm}</button><button type="button" disabled={busy} onClick={()=>{setRetry(undefined);setError('');retryTrigger.current?.focus();}}>{t.telegramRetryCancel}</button>
   </form>:null}
  </div>;
 }
 const changeState=(status:'open'|'closed')=>void run(signal=>adapter.state(status,signal),()=>setConversation(value=>value?{...value,status}:value));
 const loadOlder=()=>{if(oldest===null)return;const before=oldest;void run(signal=>adapter.history(before,signal),result=>{setHistory(previous=>({messages:mergeSupportMessages(result.messages,previous.messages),loaded:new Set([...previous.loaded,...result.messages.map(message=>message.sequence)]),oldest:previous.oldest===before?result.oldest_sequence:previous.oldest,hasMore:previous.oldest===before?result.has_more:previous.hasMore}));});};
 const changeBan=()=>{if(!adapter.ban)return;if(!banReason.trim()||Array.from(banReason).length>1000){setError(t.reasonRequired);return;}const banned=!conversation?.support_banned;void run(signal=>adapter.ban!(banned,banReason,signal),()=>{setConversation(value=>value?{...value,support_banned:banned}:value);setBanReason('');});};
 const date=(value:string)=>new Date(value).toLocaleString(lang==='ru'?'ru-RU':'en-US');const size=(value:number)=>value<1024?value+' B':new Intl.NumberFormat(lang,{maximumFractionDigits:1}).format(value/1024)+' KiB';const closed=conversation?.status==='closed';const blocked=viewer==='customer'&&conversation?.support_banned;const prefix=viewer==='operator'?'operator-':'support-';
 return <div className="support-thread">{error?<p className="error" role="alert">{error}</p>:null}{blocked?<p className="warning" role="alert">{t.supportBlocked}</p>:null}{!ready?<p role="status">{t.loading}</p>:null}{hasMore?<button onClick={loadOlder} disabled={busy}>{t.loadOlder}</button>:null}{ready&&messages.length===0?<p className="notice">{t.noSupportMessages}</p>:<ol className="support-list" aria-label={t.supportHistory}>{messages.map(message=><li key={message.id} id={'support-message-'+message.id} tabIndex={-1} data-sequence={message.sequence} className={'support-message '+message.sender}><div className="message-meta"><strong>{message.sender===viewer?t.you:viewer==='operator'?t.customer:t.supportAgent}</strong><time dateTime={message.created_at}>{date(message.created_at)}</time></div>{message.text?<p>{message.text}</p>:null}{message.attachment?adapter.download?<button className="attachment" disabled={busy} onClick={()=>download(message)}>{t.downloadAttachment.replace('{name}',message.attachment.name)} · {size(message.attachment.size_bytes)}</button>:<a className="attachment" href={adapter.attachment(message.id)} download={message.attachment.name}>{t.downloadAttachment.replace('{name}',message.attachment.name)} · {size(message.attachment.size_bytes)}</a>:null}<p className="delivery">{message.delivery==='stored'?t.storedSupport:t.deliveredCabinet}</p>{telegramDelivery(message)}</li>)}</ol>}
  {conversation?<div className="support-state"><p role="status">{closed?t.conversationClosed:t.conversationOpen}</p>{closed?!blocked?<button onClick={()=>changeState('open')} disabled={busy}>{t.reopenConversation}</button>:null:<button onClick={()=>changeState('closed')} disabled={busy}>{t.closeConversation}</button>}</div>:null}
  {!blocked?<form className="support-form" onSubmit={send} aria-busy={busy}><label htmlFor={prefix+'message'}>{viewer==='operator'?t.operatorSupportReply:t.supportMessage}<textarea id={prefix+'message'} rows={5} value={draft} onChange={event=>changeDraft(event.target.value)} aria-describedby={prefix+'message-help'} disabled={busy}/></label><p id={prefix+'message-help'} className="help">{t.supportMessageHelp}</p><label htmlFor={prefix+'file'}>{viewer==='operator'?t.operatorSupportFile:t.supportFile}<input ref={fileInput} id={prefix+'file'} type="file" onChange={event=>changeFile(event.target.files?.[0])} disabled={busy}/></label><p className="help">{t.supportFileHelp}</p><button className="primary" disabled={busy}>{busy?t.sending:viewer==='operator'?t.sendOperatorReply:closed?t.reopenSend:t.sendSupport}</button></form>:null}
  {viewer==='operator'&&adapter.ban&&conversation?<div className="support-ban"><label htmlFor="support-ban-reason">{t.supportBanReason}<textarea id="support-ban-reason" rows={2} value={banReason} onChange={event=>{setBanReason(event.target.value);setError('');}}/></label><button onClick={changeBan} disabled={busy}>{conversation.support_banned?t.unblockSupport:t.blockSupport}</button></div>:null}</div>;
}

const customerAdapter:SupportAdapter={load:api.getSupport,history:api.getSupportHistory,send:api.createSupportMessage,read:api.acknowledgeSupport,state:api.setSupportState,attachment:api.supportAttachmentURL,...(isMiniApp()?{download:api.downloadSupportAttachment}:{})};
export function Support({lang}:{lang:Lang}){const t=text(lang);const[sessionReady,setSessionReady]=useState(false);const[supportDenied,setSupportDenied]=useState(false);const[loggingOut,setLoggingOut]=useState(false);const[error,setError]=useState('');useEffect(()=>{const controller=new AbortController();void api.getAccount(controller.signal).then(()=>setSessionReady(true)).catch(reason=>{if(controller.signal.aborted)return;if(reason instanceof api.ApiError&&reason.status===401)loginRedirect(lang);else setError(errorText(reason,lang));});return()=>controller.abort();},[lang]);async function logout(){setLoggingOut(true);try{await api.logoutAccount();loginRedirect(lang);}catch(reason){setError(errorText(reason,lang));setLoggingOut(false);}}return <section className="card support-view"><div className="cabinet-head"><div><p className="eyebrow">{t.cabinet}</p><h1>{t.supportMessages}</h1></div><button onClick={logout} disabled={!sessionReady||loggingOut}>{t.logout}</button></div><nav className="account-links" aria-label={t.accountNavigation}><a href={link('/cabinet',lang)}>{t.backAccount}</a>{!isMiniApp()?<a href={link('/cabinet/security',lang)}>{t.security}</a>:null}</nav><p>{t.supportIntro}</p>{error?<p className="error" role="alert">{error}</p>:null}{!sessionReady&&!error?<p role="status">{t.loading}</p>:null}{sessionReady&&!loggingOut&&!supportDenied?<SupportThread lang={lang} adapter={customerAdapter} viewer="customer" onForbidden={()=>{setSupportDenied(true);setError(t.restricted);}}/>:null}</section>;}
