import {useEffect,useRef,useState,type FormEvent} from 'react';
import * as api from './api/client';
import {text,link,errorText,type Lang} from './i18n';

const maxFile=10*1024*1024;
export function mergeSupportMessages(...groups:api.SupportMessage[][]){const bySequence=new Map<number,api.SupportMessage>();for(const group of groups)for(const message of group)bySequence.set(message.sequence,message);return [...bySequence.values()].sort((a,b)=>a.sequence-b.sequence);}

export function Support({lang}:{lang:Lang}){
 const t=text(lang);const[conversation,setConversation]=useState<api.SupportConversation|null>(null);const[messages,setMessages]=useState<api.SupportMessage[]>([]);const[hasMore,setHasMore]=useState(false);const[oldest,setOldest]=useState<number|null>(null);const[textValue,setTextValue]=useState('');const[file,setFile]=useState<File>();const[attempt,setAttempt]=useState<{key:string;text:string;file?:File}>();const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[sessionReady,setSessionReady]=useState(false);const[ready,setReady]=useState(false);const request=useRef<AbortController|undefined>(undefined);const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);const fileInput=useRef<HTMLInputElement>(null);const exhausted=useRef(false);
 useEffect(()=>{let active=true,accountReady=false,inFlight=false;
  const pageVisible=()=>document.visibilityState!=='hidden';
  const stop=()=>{if(timer.current)clearTimeout(timer.current);timer.current=undefined;request.current?.abort();request.current=undefined;};
  const refresh=async()=>{if(!active||inFlight||!pageVisible())return;inFlight=true;const current=new AbortController();request.current=current;try{if(!accountReady){await api.getAccount(current.signal);accountReady=true;setSessionReady(true);}const result=await api.getSupport(current.signal);if(!active||current.signal.aborted)return;setConversation(result.conversation);setMessages(previous=>mergeSupportMessages(previous,result.messages));setHasMore(!exhausted.current&&result.has_more);setOldest(previous=>previous===null?result.oldest_sequence:result.oldest_sequence===null?previous:Math.min(previous,result.oldest_sequence));setError('');setReady(true);}catch(reason){if(current.signal.aborted)return;if(reason instanceof api.ApiError&&reason.status===401){location.replace(link('/login',lang));return;}setError(errorText(reason,lang));setReady(accountReady);}finally{inFlight=false;if(request.current===current)request.current=undefined;if(active&&pageVisible())timer.current=setTimeout(refresh,5000);}};
  const visibility=()=>{if(document.visibilityState==='hidden')stop();else void refresh();};document.addEventListener('visibilitychange',visibility);void refresh();return()=>{active=false;document.removeEventListener('visibilitychange',visibility);stop();};
 },[lang]);
 useEffect(()=>{const operator=messages.filter(message=>message.sender==='operator');if(!conversation||operator.length===0)return;const highestOperator=Math.max(...operator.map(message=>message.sequence));if(highestOperator<=conversation.customer_received_sequence)return;const controller=new AbortController();void api.acknowledgeSupport(highestOperator,controller.signal).then(()=>setConversation(current=>current?{...current,customer_received_sequence:Math.max(current.customer_received_sequence,highestOperator)}:current)).catch(()=>{});return()=>controller.abort();},[messages,conversation?.id,conversation?.customer_received_sequence]);
 const changeText=(value:string)=>{setTextValue(value);setAttempt(undefined);setError('');};
 const changeFile=(next:File|undefined)=>{setFile(next);setAttempt(undefined);setError('');};
 async function send(event:FormEvent){event.preventDefault();if(busy||conversation?.support_banned)return;if(Array.from(textValue).length>4000){setError(t.supportTextTooLong);return;}if(file&&file.size>maxFile){setError(t.supportFileTooLarge);return;}if(!textValue.trim()&&(!file||file.size===0)){setError(t.supportMessageRequired);return;}const current=attempt??{key:crypto.randomUUID(),text:textValue,file};setAttempt(current);setBusy(true);setError('');try{const created=await api.createSupportMessage(current.text,current.file,current.key);setMessages(previous=>mergeSupportMessages(previous,[created]));setConversation(value=>value?{...value,status:'open'}:value);setTextValue('');setFile(undefined);setAttempt(undefined);if(fileInput.current)fileInput.current.value='';}catch(reason){setError(errorText(reason,lang));}finally{setBusy(false);}}
 async function changeState(status:'open'|'closed'){if(busy||status==='open'&&conversation?.support_banned)return;setBusy(true);setError('');try{await api.setSupportState(status);setConversation(value=>value?{...value,status}:value);}catch(reason){setError(errorText(reason,lang));}finally{setBusy(false);}}
 async function loadOlder(){if(busy||oldest===null)return;setBusy(true);setError('');try{const result=await api.getSupportHistory(oldest);setMessages(previous=>mergeSupportMessages(result.messages,previous));setConversation(result.conversation);setOldest(result.oldest_sequence);setHasMore(result.has_more);if(!result.has_more)exhausted.current=true;}catch(reason){setError(errorText(reason,lang));}finally{setBusy(false);}}
 async function logout(){request.current?.abort();if(timer.current)clearTimeout(timer.current);setBusy(true);try{await api.logoutAccount();location.replace(link('/login',lang));}catch(reason){setError(errorText(reason,lang));setBusy(false);}}
 const date=(value:string)=>new Date(value).toLocaleString(lang==='ru'?'ru-RU':'en-US');const size=(value:number)=>new Intl.NumberFormat(lang,{maximumFractionDigits:1}).format(value/1024)+' KiB';const closed=conversation?.status==='closed';const banned=conversation?.support_banned;
 return <section className="card support-view"><div className="cabinet-head"><div><p className="eyebrow">{t.cabinet}</p><h1>{t.supportMessages}</h1></div><button onClick={logout} disabled={!sessionReady||busy}>{t.logout}</button></div>
  <nav className="account-links" aria-label={t.accountNavigation}><a href={link('/cabinet',lang)}>{t.backAccount}</a><a href={link('/cabinet/security',lang)}>{t.security}</a></nav><p>{t.supportIntro}</p>
  {error?<p className="error" role="alert">{error}</p>:null}{banned?<p className="warning" role="alert">{t.supportBlocked}</p>:null}{!ready?<p role="status">{t.loading}</p>:null}
  {hasMore?<button onClick={loadOlder} disabled={busy}>{t.loadOlder}</button>:null}
  {ready&&messages.length===0?<p className="notice">{t.noSupportMessages}</p>:<ol className="support-list" aria-label={t.supportHistory}>{messages.map(message=><li key={message.id} data-sequence={message.sequence} className={'support-message '+message.sender}><div className="message-meta"><strong>{message.sender==='customer'?t.you:t.supportAgent}</strong><time dateTime={message.created_at}>{date(message.created_at)}</time></div>{message.text?<p>{message.text}</p>:null}{message.attachment?<a className="attachment" href={api.supportAttachmentURL(message.id)} download={message.attachment.name}>{t.downloadAttachment.replace('{name}',message.attachment.name)} · {size(message.attachment.size_bytes)}</a>:null}<p className="delivery">{message.delivery==='stored'?t.storedSupport:t.deliveredCabinet}</p></li>)}</ol>}
  {conversation?<div className="support-state"><p role="status">{closed?t.conversationClosed:t.conversationOpen}</p>{closed?!banned?<button onClick={()=>changeState('open')} disabled={busy}>{t.reopenConversation}</button>:null:<button onClick={()=>changeState('closed')} disabled={busy}>{t.closeConversation}</button>}</div>:null}
  {sessionReady&&!banned?<form className="support-form" onSubmit={send} aria-busy={busy}><label htmlFor="support-message">{t.supportMessage}<textarea id="support-message" rows={5} value={textValue} onChange={event=>changeText(event.target.value)} aria-describedby="support-message-help"/></label><p id="support-message-help" className="help">{t.supportMessageHelp}</p><label htmlFor="support-file">{t.supportFile}<input ref={fileInput} id="support-file" type="file" onChange={event=>changeFile(event.target.files?.[0])}/></label><p className="help">{t.supportFileHelp}</p><button className="primary" disabled={busy}>{busy?t.sending:closed?t.reopenSend:t.sendSupport}</button></form>:null}
 </section>;
}
